### ISSUE TITLE
Automatic Refresh All tools when linking 3rd party tokens

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1000]
### Desired behaviour
When linking a third party token (Quay.io), Dockstore should trigger an automatic refresh all right after.

**Comment by denis-yuen** [comment]
Observations today:
* 500 when refreshing workflows with no tokens (tools seems ok)
* message should say to link at least one source control for tools, same with workflows
* see how difficult it would be to have a convenience "link and refresh immediately" button if you have no content and no tokens in My Tools and My Workflows

**Comment by garyluu** [comment]
A previous discussion determined that automatically 'refresh all' after linking a Quay.io token is really annoying and time consuming for the user.

**Comment by agduncan94** [comment]
@denis-yuen  Seems like this has not been implemented. Is it still what we want?

**Comment by agduncan94** [comment]
@denis-yuen  Should this issue be closed?

**Comment by agduncan94** [comment]
When I delete my quay token and refresh I get the error:
[HTTP 404] Not Found: unable to establish connection to registry, check that you have linked your accounts

When I delete my github token and refresh workflows, I get the error:
[HTTP 403] Forbidden: No GitHub token found. Please link a GitHub token to your account.

@garyluu is this correct?

**Comment by garyluu** [comment]
I believe so

**Comment by agduncan94** [comment]
Confirmed to work on staging 1.4.0-beta.3
