### ISSUE TITLE
Docker pull command does not take into account latest tag

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1006]
### Expected behaviour

The Docker pull command should use the version of the default tag

### Actual behaviour

The version is ignored and so Docker attempts to use latest which may not exist.

**Comment by denis-yuen** [comment]
This is from https://dockstore.org/containers/quay.io/wtsicgp/dockstore-biobambam2/bamtofastq#comment-3529594216 which doesn't exist due to the migration to Discource

**Comment by keiranmraine** [comment]
This [link](https://disqus.com/home/discussion/dockstoreorg/dockstore_503/?utm_source=reply&utm_medium=email&utm_content=read_more#comment-3529594216) does show the original thread.

**Comment by denis-yuen** [comment]
Looks good on staging.dockstore.org
