### ISSUE TITLE
Test Parameter Files dialogs need to be reworked

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1012]
## Bug Report
Adding test parameter files not intuitive.  Due to form validation, there were changes from UI1 to UI2.
UI2 form validates the 'add test parameter field', but the file is only added once the '+' symbol is clicked.

### Expected behaviour
All test parameter files to be added should have form validation.  All test parameter files edited should have form validation too.  Adding test parameter files should be intuitive.  Possible solutions:
- Use the UI1's layout but use reactive forms to apply form validation for every test parameter file path.
- Warn the user when they typed in the test parameter file path but didn't click '+'
- Disable the save changes button if there is content in the test parameter file path
- Always add the test parameter file in the field regardless of whether '+' has been clicked (my personal favorite solution)

### Actual behaviour
People often type in the test parameter file in the field path but do not click the '+' sign to add the file.  There is no indication that the file will not be added.

### Steps to reproduce the behaviour 
Try adding a test parameter file

**Comment by denis-yuen** [comment]
I agree, I think the current "+" is confusing, the dialog box should be reworked. 

Implementor should deal with  #962 , #834, #774 at the same time.

**Comment by briandoconnor** [comment]
+1 for fixing this... having to hit "+" to get the test file to save is not intuitive at all.

**Comment by denis-yuen** [comment]
Staging.dockstore.org hotfix looks a lot better, only one comment for now
Pressing enter is intuitive when editing the default "first" path, but it doesn't work
