### ISSUE TITLE
Improve testing docs in Dockstore primer

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1013]
### Desired behaviour

Testing section is dated September 2016 at https://wiki.oicr.on.ca/display/SEQWARE/Dockstore+Primer#DockstorePrimer-UnitTestingandEndtoEnd(E2E)TestingforDockstore-UI 
and contains a large number of paths and observations that seem out of date. 

Let's get this in shape for potential external developers.

**Comment by denis-yuen** [comment]
Moving this out for tracking, mainly need help with the ui testing portions

**Comment by agduncan94** [comment]
What do we do with stuff from UI1. I'm guessing we don't want to delete it. Maybe some sort of section at the end to put it, since I doubt any new people will be working on it.

**Comment by denis-yuen** [comment]
I think deleting it is fine, without maintenance, ui1 will quickly become unusable anyway.
At least the workflow section is likely broken already

**Comment by denis-yuen** [comment]
Thanks, looks better and more up-to-date
