### ISSUE TITLE
Standardize comments

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1014]
It would be nice if we had a standard way to do commenting, especially for functions. Keeping track of inputs, outputs, assumptions, etc would be helpful for reusing existing functions and updating/fixing functions.

**Comment by denis-yuen** [comment]
Agreed, I think @garyluu  looked at this for ui1, but I can't currently find a link to the relevant PR.
Gary, can you take a look and see what we decided on re: jsdocs or similar and if your older recommendations are still relevant?

**Comment by garyluu** [comment]
https://github.com/ga4gh/dockstore-ui/pull/136 was to build the ngdocs site.  Not entirely sure what was the required convention to generate the docs.

**Comment by garyluu** [comment]
Looks like it is probably using jsdocs for commenting, https://compodoc.github.io/website/ would replace ngdoc documentation generation.

**Comment by denis-yuen** [comment]
Linking to #1731
