### ISSUE TITLE
Tool descriptor doesn't match ga4gh swagger.yaml

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1027]
### Expected behaviour
According to https://github.com/ga4gh/tool-registry-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml, https://dockstore.org:8443/api/ga4gh/v1/tools/registry.hub.docker.com%2Fsequenza%2Fsequenza/versions/latest/CWL/descriptor/%2Fsequenza.cwl should return a type that is either "CWL" or "WDL".

### Actual behaviour
It returns DOCKSTORE_CWL

### Steps to reproduce the behaviour 
Go to https://dockstore.org:8443/api/ga4gh/v1/tools/registry.hub.docker.com%2Fsequenza%2Fsequenza/versions/latest/CWL/descriptor/%2Fsequenza.cwl

**Comment by denis-yuen** [comment]
Good catch

**Comment by denis-yuen** [comment]
Looks good
