### ISSUE TITLE
Deletion of tool (or workflow) should not reset organization that is open

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1029]
### Expected behaviour

Deregister deletes the tool and removes it from the left side organizational boxes immediately. 

### Actual behaviour

The tool remains until you browse away and return or refresh the page. 
Might be worth tackling in a group with 
#70 , #624 , and #655

**Comment by agduncan94** [comment]
This occurs in staging and prod, but not in develop.

**Comment by denis-yuen** [comment]
@agduncan94 hmm, is this a code change or something caused/revealed by the `--prod` mode of npm/ng build?

**Comment by agduncan94** [comment]
I think it is probably a code change, I remember Gary was working on something related to ensuring the tool was properly updated on changes, so maybe that fixed this.

**Comment by garyluu** [comment]
I think I remember this, it fixed with a webservice update.

**Comment by agduncan94** [comment]
Regarding the issues #624 and #655 , these will not be dealt with until we figure out what to do with workflow deletion. But the tool deletion seems to be working properly now.

**Comment by agduncan94** [comment]
I am closing this issue and moving it to ready for testing.

**Comment by denis-yuen** [comment]
Looks a lot better. 
However, this does that thing where deletion closes the organization and resets the page. 
Is it possible to keep the selected organization open? Would be easier to use for deleting more than one tool

**Comment by denis-yuen** [comment]
Deletion reset still a thing

**Comment by denis-yuen** [comment]
Working on staging
```
DockstoreAPI - 1.5.0-beta.4
DockstoreUI - 2.2.0-beta.3
```
