### ISSUE TITLE
Restructuring of adding/editing version tags

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1033]
Currently we have separate html/ts for adding and editing version tags for tools, even though there is a lot of overlap. We should be able to reuse a lot of code here.

We could also probably do some code sharing between the editing version tags for both tools and workflows.

**Comment by denis-yuen** [comment]
See also #1036 
Not sure if this is complete, maybe a 1.6.0 refactoring issue for the GUI if not
