### ISSUE TITLE
Optional POST/GET to REST endpoints at stages of flow

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1037]
## Feature Request 

Ability to have the dockstore wrapper post/get to a user defined endpoint when milestones reached, e.g.

1. Provisioning input files
2. Starting workflow
3. Provisioning output files
4. Completed

The user would need to provide a UUID for the current flow but this would make it very easy to provide progress info to any system using dockstore (language agnostic).

**Comment by keiranmraine** [comment]
@denis-yuen, currently doing some planning, how likely is this to be implemented?  Item 4 is the key item. Thanks

**Comment by denis-yuen** [comment]
It sounds pretty reasonable, we would like to use something similar for sending notifications to Slack.

**Comment by keiranmraine** [comment]
Would you be looking to accept an array of requests, I can see slack + another being a popular option.

**Comment by denis-yuen** [comment]
Yeah, I think that would make sense.

**Comment by denis-yuen** [comment]
@keiranmraine  For the UUID, is this generated by the user launching the workflow or is this something we generate ourselves when running a workflow?

@garyluu  for testing, you could sent notifications to Slack at #test_channel see this document for how webhooks work https://api.slack.com/incoming-webhooks

**Comment by keiranmraine** [comment]
@denis-yuen the user would provide the "UUID", doesn't really have to be a UUID just something they can use to identify their data when telling the server about it.

**Comment by garyluu** [comment]
@keiranmraine Would you like the user to provide the "UUID" via the config file or as a command line argument?

**Comment by denis-yuen** [comment]
@garyluu don't want to put words in Keiran's mouth, but I suspect command-line argument. 
A question I would add though is where they have any other preferences for the payload to be sent to a configurable URL or whether it is up to us

**Comment by keiranmraine** [comment]
@denis-yuen @garyluu, I think the id/uuid should be via the command line, but the endpoint may want to be in the config file, but cli is fine.

Some additional thoughts about payload, and extension could allow each step could to send a message if it fails, perhaps prefixing with 'failed-'?

* failed-provision-in
* failed-workflow-start
* failed-provision-out

**Comment by agduncan94** [comment]
Confirmed to work on staging 1.4.0-beta.3

**Comment by denis-yuen** [comment]
For records, this was done in #1112

**Comment by keiranmraine** [comment]
@denis-yuen, can I get a link to docs (if exposed yet)?
