### ISSUE TITLE
Update GA4GH endpoint for test parameters to return raw file given a path

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1038]
Currently with the GA4GH endpoint for test parameter files, either an array of the files are returned or the json representation of a file. These should instead behave like descriptor files, where you can pass a filepath and get the raw test json back.

**Comment by agduncan94** [comment]
Note: We need to change the TRS endpoint

**Comment by denis-yuen** [comment]
This is now obsolete. Test parameter files are now returned via the relative paths endpoint.
