### ISSUE TITLE
Disambiguate organizations for workflows (now testing for ga4gh compatibility)

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1044]
### Desired behaviour

Something to work on while redesigning workflows.
Right now, workflows are "first one wins" when two workflows have the same name and organization, but different registries. We have a bit of a window to fix this to be more like tools.

**Comment by denis-yuen** [comment]
While reviewing endpoints, we also noticed that Docker registries are returned, which implies that the UI will automatically adjust to new Docker registries. But we're probably not doing the same with source control

**Comment by denis-yuen** [comment]
Migration plan: 
Add an issue for how to review affected workflows before migration and create a redirect when SC is not specified (probably github.com) 
Note that we can either wipe out the existing workflow threads on Discourse or use the API to fix them to the new URLs

**Comment by agduncan94** [comment]
The webservice portion has been implemented and merged. The UI has been mostly completed.

**Comment by agduncan94** [comment]
This is done, I think you mentioned to Gary to write a test.

**Comment by denis-yuen** [comment]
This seems functional. Follow-up with smaller issues if needed, noticed #1245
