### ISSUE TITLE
Documentation: Broken link

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1052]
The [workflows documentation](https://dockstore.org/docs/workflows) has a broken link:

https://dockstore.org/workflows/denis-yuen/dockstore-whalesay

Not sure which it should point to but there are 2 similar ones:

https://dockstore.org/workflows/vrockai%2Fdockstore-whalesay

and 

https://dockstore.org/workflows/DockstoreTestUser%2Fdockstore-whalesay%2Fdockstore-whalesay-wdl

**Comment by denis-yuen** [comment]
Thanks for the heads-up, I probably forgot that workflow was referenced by docs.
