### ISSUE TITLE
include CWL visualizations using the view.commonwl.org API

### ISSUE THREAD

**Issue by mr-c** [ga4gh/dockstore#1058]
https://view.commonwl.org/apidocs

Sample:

![Sample workflow graph](https://view.commonwl.org/graph/png/github.com/common-workflow-language/workflows/blob/lobstr-v1/workflows/lobSTR/lobSTR-workflow.cwl)

From https://view.commonwl.org/workflows/github.com/common-workflow-language/workflows/blob/lobstr-v1/workflows/lobSTR/lobSTR-workflow.cwl

┆Issue Number: DOCK-6

**Comment by SolomonShorser-OICR** [comment]
:+1:

**Comment by SolomonShorser-OICR** [comment]
Hey you know what would be cool? If view.commonwl.org had a way to embed a diagram, based on a URL. The goal would be to embed a little bit of code into a README on github and then when someone views the repo, the diagram would be rendered for them automatically for them. Is there an API way to do this already?

**Comment by mr-c** [comment]
@SolomonShorser-OICR  I agree, however

> Note: Due to `cwltool` run times, the creation of workflows is done asynchronously and an intermediate queue resource is used

https://view.commonwl.org/apidocs#addWorkflow

**Comment by mr-c** [comment]
@SolomonShorser-OICR I've opened a ticket at the CWL viewer repository with an outline of how this could work: https://github.com/common-workflow-language/cwlviewer/issues/185
Contributions to the CWL viewer Java codebase are welcome!

**Comment by coverbeck** [comment]
1. The `POST /workflows` operation is not CORS enabled, so we cannot create a visualization directly from the browser. We could make the call server-side, but that is a bit of a hack and tends to introduce security issues. 
2. The [API doc](https://view.commonwl.org/apidocs) has a warning at the top of the page that `Disclaimer: The API is still under heavy development and breaking changes to endpoints or parameters may be made`. Even if the CORS issue gets addressed, it seems a little premature to support this.

@mr-c Do you have any more info or thoughts on either of the above points?

**Comment by mr-c** [comment]
Hello @coverbeck and thank you for looking into this. I am not a core developer of the CWL visualizer but I'll do my best.

Here's a PR that might fix the CORS issue, but I haven't tested it: https://github.com/common-workflow-language/cwlviewer/pull/187

I think your usage of the API will help the project firm it up, so please don't let that warning stop you. I'd really appreciate any feedback you have on it!

@stain Any comments?

**Comment by denis-yuen** [comment]
@coverbeck  I think it would be reasonable for the DAG tab to retain the existing visualization as an alternative when and/or if cwlviewer breaks. Keep in mind that the existing visualization would need to be retained for WDL in any case

**Comment by coverbeck** [comment]
@denis-yuen , sorry, what is the DAG tab? I was envisioning this being on the Info tab of a workflow or tool. Is that the wrong place?

**Comment by coverbeck** [comment]
@mr-c , thanks for quick response. I didn't know if the lack of CORS support was intentional or not, and wanted to check first before trying to figure out a PR for that repo.

**Comment by denis-yuen** [comment]
@coverbeck  for example, the sixth tab of https://dockstore.org/workflows/ICGC-TCGA-PanCancer%2FOxoG-Dockstore-Tools%2Fpcawg-oxog-full-workflow

**Comment by coverbeck** [comment]
@denis-yuen , thanks, I was looking at a Tool instead of a Workflow.

**Comment by stain** [comment]
I've merged common-workflow-language/cwlviewer#187 - thanks @mr-c - will try to spin up an updated dev instance later that @coverbeck can test with.

**Comment by denis-yuen** [comment]
@coverbeck  can you verify that you're awaiting this CORS change in production?

**Comment by coverbeck** [comment]
@denis-yuen Verified that we are still awaiting the change. Pinged them to see when they expect to deploy it.

**Comment by denis-yuen** [comment]
https://gitter.im/common-workflow-language/common-workflow-language?at=5b18376bedd06f7d1515acdd
Will give this a shot in staging on the next hotfix release

**Comment by denis-yuen** [comment]
This seems somewhat functional on staging.dockstore.org https://staging.dockstore.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/pcawg-oxog-full-workflow:master?tab=dag

@coverbeck to verify whether it is as functional as expected

**Comment by coverbeck** [comment]
This looks good to me in my tests. I did find and log #1487 in verifying this, but I don't think that is a blocker.
