### ISSUE TITLE
Updates needed for "launch with" section

### ISSUE THREAD

**Issue by mr-c** [ga4gh/dockstore#1061]
- [x] Third section should reference `cwl-runner` and not `cwltool` as it works with any CWL implementation that provides that interface: the reference CWL runner, `toil-cwl-runner`, `arvados-cwl-runner` and the Rabix CWL runner
- [x] Insert a new section using the [built in dockstore.org support](https://github.com/common-workflow-language/cwltool#use-with-ga4gh-tool-registry-api) in `cwltool`:

Example using https://dockstore.org/containers/quay.io%2Fbriandoconnor%2Fdockstore-tool-bamstats

> Alternatively, cwltool can run a workflow off of dockstore.org when all inputs and outputs are available on the local filesystem or via HTTP(S):
`cwltool --non-strict quay.io/briandoconnor/dockstore-tool-bamstats:1.25-11  Dockstore.json`
`cwltool` can also be used to create the input template:
`cwltool --make-template quay.io/briandoconnor/dockstore-tool-bamstats:1.25-11 > input.yaml`

**Comment by garyluu** [comment]
@mr-c Now that the third section references cwl-runner, should the example you provided also be cwl-runner or cwltool?

**Comment by mr-c** [comment]
@garyluu The `--make-template` option is not required by all `cwl-runner`s to implement, so that is why I used `cwltool` there.

**Comment by mr-c** [comment]
Thank you @garyluu  :-)

**Comment by denis-yuen** [comment]
Looks like it is working in staging.dockstore.org
