### ISSUE TITLE
Workflowname both null and sometimes empty string

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1075]
## Bug Report
Workflow contains workflowname that may be empty string or null inside the database

### Expected behaviour
Workflow names should not be empty string in the current database and should not create a new workflowname with empty string

### Actual behaviour
Workflow contains workflowname that may be empty string or null inside the database and can create empty string workflowname in workflows

### Steps to reproduce the behaviour 
Take production or staging database, look at the workflowname in workflow table.

**Comment by denis-yuen** [comment]
Confirmed fixed (production database standardized on null)
