### ISSUE TITLE
Cannot sort by verified, sorting by valid seems to break route navigation and display of versions

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1083]
### Expected behaviour
Be able to sort by verified (verified first, by alpha order) and valid (valid ones first)

### Actual behaviour
Cannot sort by verified, sorting by valid seems to break route navigation and display of versions

### Steps to reproduce the behaviour 

Go to https://dockstore.org/containers/quay.io%2Fpancancer%2Fpcawg-sanger-cgp-workflow and click on sort by valid on Versions page. Happens both in public and in my tools/my workflows

**Comment by agduncan94** [comment]
Sorting workflow versions doesn't seem to work on staging or production.

**Comment by denis-yuen** [comment]
Looks functional on staging.dockstore.org
