### ISSUE TITLE
Add tag and save, click add tag again, test parameter files input not reset

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1086]
### Expected behaviour
After adding a new test parameter file to a tag and saving, then adding tag again, the box for adding new test parameter files should be cleared.
### Actual behaviour
The box isn't cleared

**Comment by agduncan94** [comment]
#728 Charles posted a useful screenshot for this issue.

**Comment by denis-yuen** [comment]
Fixed on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
