### ISSUE TITLE
Dockstore entry URL without '/' being encoded

### ISSUE THREAD

**Issue by junjun-zhang** [ga4gh/dockstore#1097]
## Feature Request 
Currently both of the following two URL forms for a dockstore entry work:
```
https://dockstore.org/containers/quay.io%2Fpancancer%2Fpcawg-muse
```
and
```
https://dockstore.org/containers/quay.io/pancancer/pcawg-muse
```

### Desired behaviour
The latter (without url encoding of '/') is more preferable due to clarity to the users.

**Comment by denis-yuen** [comment]
There is probably less implementation than testing for this request. 
It looks like the UI2 already handles this in general, but we want to make sure that we're not missing any edge cases in links from browsing or searching

**Comment by denis-yuen** [comment]
@garyluu 
1) legal?
2) test the cases including edge cases
(with or without toolname for workflows, with or without workflow for workflows)
3) if no edge cases are found, let's link to these non-escaped versions from tools, workflows, search,

**Comment by denis-yuen** [comment]
Looks functional for tools, workflows, but not for links from search

**Comment by denis-yuen** [comment]
Seems broken on staging.dockstore.org for workflows.

**Comment by denis-yuen** [comment]
https://staging.dockstore.org/workflows/github.com/smc-rna-challenge/beccyl-7238196 as an example should be  https://staging.dockstore.org/workflows/github.com/smc-rna-challenge/beccyl-7238196/beccyl-7238196

**Comment by garyluu** [comment]
Looks like the workflow path change has broken a few things

**Comment by denis-yuen** [comment]
Looks better now
