### ISSUE TITLE
Request Access Button Missing for Private Tools in UI2

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1099]
## Bug Report

The `Request Access` button is not present on the private tools page of the new UI.

### Steps to reproduce the behaviour 

Note how on [https://dockstore.org:9000/containers/registry.hub.docker.com/broadinstitute/pcawg_broad_wgs_variant_callers/pcawg-broad-wgs-variant-caller](https://dockstore.org:9000/containers/registry.hub.docker.com/broadinstitute/pcawg_broad_wgs_variant_callers/pcawg-broad-wgs-variant-caller) in the old UI, there is a `Request Access on Docker Hub` button at the top right of the page.

If you navigate to the same tool [https://dockstore.org/containers/registry.hub.docker.com%2Fbroadinstitute%2Fpcawg_broad_wgs_variant_callers%2Fpcawg-broad-wgs-variant-caller](https://dockstore.org/containers/registry.hub.docker.com%2Fbroadinstitute%2Fpcawg_broad_wgs_variant_callers%2Fpcawg-broad-wgs-variant-caller) in the new UI, there is no `Request Access on Docker Hub` button.

**Comment by denis-yuen** [comment]
Back on staging.dockstore.org
