### ISSUE TITLE
Clean up CLI, make more consistent

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#110]
The CLI can be cleaned up a bit:
- consistent error handling (error codes)
- consistent help output and general output
- don't rely on order of input for commands
- possibly more ways

**Comment by denis-yuen** [comment]
:+1:

**Comment by agduncan94** [comment]
Another idea to make the CLI more consistent is for multi word sub-commands to always separate by underscore, instead of a mix of underscore and camelcase.
