### ISSUE TITLE
Setting default does not automatically refresh description

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1100]
### Expected behaviour

Setting a new default should automatically refresh and set the new description

### Actual behaviour

The UI seems to show a refresh, but it doesn't work

### Steps to reproduce the behaviour 

For example, if you have a tool and you switch from 1.3 to 1.4 of it, it will refresh. But it will use the description from 1.3 until you hit refresh again

Please check for tools and workflows

**Comment by agduncan94** [comment]
Confirmed to work on staging 1.4.0-beta.3
