### ISSUE TITLE
Investigate use of logstash and kibana to process weblogs

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1111]
### Desired behaviour

Currently, we use Google Analytics to measure overall site visits. However, we don't have much of a way of checking what endpoints are hit on the webservice. This would be useful to hint how long we need to keep around deprecated endpoints and which endpoints need to be optimized. 

Some potentially useful content for this task:
https://www.elastic.co/blog/found-analyzing-weblogs-with-elasticsearch
https://www.elastic.co/blog/found-analyzing-weblogs-with-elasticsearch-part-2
https://www.elastic.co/guide/en/beats/filebeat/current/configuring-ssl-logstash.html
https://github.com/reactome/elk-setup

**Comment by garyluu** [comment]
After PR, TODO: 


- Add to Primer about Kibana (literally the defaults)
- Find a way to selectively disable logstash in compose_setup (instead of selectively enabling everything with docker-compose up <everything-except-logstash>)

**Comment by denis-yuen** [comment]
When we set this up, we should aggregate by endpoints
Another useful report would be to aggregate the endpoints and parameters on which people encountered 500 errors and their stack traces if possible
