### ISSUE TITLE
Comment in WDL Causes Rest of File to be Shown as Commented

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1117]
## Bug Report
When viewing a WDL on the Files tab of a Workflow, if the WDL contains a comment, the rest of the file will show up as commented.

### Expected behaviour

Only comments should be displayed as comments

### Actual behaviour

All lines after a comment are displayed as comments.

### Steps to reproduce the behaviour 

1. Go to https://dockstore.org/workflows/ICGC-TCGA-PanCancer%2Fwdl-pcawg-sanger-cgp-workflow
2. Click on Files (wdl file will be selected by default)
3. Scroll down in the contents of the WDL file. Line 151 contains a comment, and all lines from there forwards are displayed as comments.

<img width="843" alt="screen shot 2018-01-18 at 12 49 43 pm" src="https://user-images.githubusercontent.com/1049340/35120778-16dba99e-fc4e-11e7-886c-ec33dc371014.png">

**Comment by denis-yuen** [comment]
Duplicates #1132
