### ISSUE TITLE
GitHub scope tweak

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1126]
### Desired behaviour

We currently ask for `read:org,user,user:email` https://github.com/dockstore/dockstore-ui2/blob/master/src/app/shared/dockstore.model.ts#L36 but it seems that `read:org,user:email` should be sufficient and safer.  May need 'read:user,read:org,user:email'

Try out refresh operations and sync account, if successful change the scope in ui2 and docker_compose

Can be grouped with #1127

**Comment by garyluu** [comment]
Removing `user` seems to work.

On a fresh database, Accounts page manages to grab sync up the GitHub info.  New workflows are automatically added using refresh all, new tools are automatically added using refresh all with a quay.io token.

**Comment by denis-yuen** [comment]
Looks good on staging.dockstore.org
