### ISSUE TITLE
Reorganize logos

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1128]
### Desired behaviour

Expand affliates for Dockstore
- UCSC should be added alongside OICR and GA4GH
Contributor section should be added as a prominent link below our affliates and include:
- CWL moved here, WDL, DNAstack with colour highlighting and links to their projects

[wdlLogo_black.eps.zip](https://github.com/ga4gh/dockstore/files/1665456/wdlLogo_black.eps.zip)
[wdlLogo_white.eps.zip](https://github.com/ga4gh/dockstore/files/1665457/wdlLogo_white.eps.zip)

 like the existing ones

**Comment by denis-yuen** [comment]
Also add status.dockstore.org somewhere

**Comment by denis-yuen** [comment]
Remove "Back to classic Dockstore website" link for 1.4.0

**Comment by denis-yuen** [comment]
Clarification:
```
At the next iteration of the Dockstore web site, can we add in the logos for Broad, UCSC, NIH, open-WDL, Genome Canada, and Ontario? We should also have (in fine print) an acknowledgement of funding from Genome Canada, the NIH, and Province of Ontario:

Support for Dockstore is provided by grants from Genome Canada, the National Institutes of Health, and the Province of Ontario.
```

**Comment by agduncan94** [comment]
Remove the logos from every page, they should only be displayed on the front page.

In affiliation with
-remove cwl, replace with UCSC

-add a second level with CWL, WDL, DNAStack, Broad
-only show second level on the home page

Add the funding to the bottom of every footer, should link to a page with descriptions/logos of funding partners.

**Comment by denis-yuen** [comment]
(Made a few edits up above for clarity)

**Comment by denis-yuen** [comment]
Looking good
