### ISSUE TITLE
Change SourceControl and Registry from enum to strings

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1129]
Currently we store the SourceControl for workflows and the Registry for tools as enums in the database. It probably makes more sense to just store the docker registry path and source control path. Then from the path we can figure out the associated Docker Registry or Source Control. Either it would be a predefined location (ex. hub.docker.com) or an "other" location like amazon-3231.com.

**Comment by agduncan94** [comment]
After a discussion, we have decided that for now we shall convert the registry/source control to a path. We will not store the name of the registry or source control, like github. Instead we will determine the source control from the path, since they are in most cases the same. For Amazon ECR, need to confirm that all amazon registries have the same prefix.

**Comment by denis-yuen** [comment]
Effectively tested as a part of other work
