### ISSUE TITLE
CWL syntax highlighting

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1131]
### Desired behaviour

CWL aware highlighting 

Looks like GitHub syntax highlighting went live for CWL. @mr-c helpfully pointed me toward https://github.com/github/linguist/pull/3902/files which seems to rely on https://github.com/manabuishii/language-cwl . See if there is a way to upgrade highlightjs to use this or perhaps switch to a different syntax highlighter that can use atom plugin information

**Comment by mr-c** [comment]
FYI, for syntax highlighting in gitlab, they use https://github.com/jneen/rouge so if a ruby backed is acceptable then porting the [atom grammar](http://flight-manual.atom.io/hacking-atom/sections/creating-a-grammar/) to rouge would be useful elsewhere.

**Comment by agduncan94** [comment]
I have made a fork which added the ace editor garmmar for CWL highlighting, which can be found here https://github.com/agduncan94/language-cwl/tree/feature/textmate-and-ace-support. A PR will be made soon.

**Comment by denis-yuen** [comment]
Functional and looks good on staging.dockstore.org. 

Amusingly, we both (the original grammar and our ace editor export) have the same problem with the apostrophe in https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:develop?tab=files or https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker/blob/develop/Dockstore.cwl

@agduncan94 reminder for the PR just in case anyone else finds the exports useful

**Comment by agduncan94** [comment]
I have created the PR here https://github.com/manabuishii/language-cwl/pull/11
