### ISSUE TITLE
WDL syntax highlighting

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1132]
### Desired behaviour

WDL syntax highlighting, re-use https://github.com/github/linguist/pull/3858 if possible. 
https://github.com/broadinstitute/wdl-sublime-syntax-highlighter seems to be the underlying grammar. Implement at the same time as #1131

**Comment by agduncan94** [comment]
I have made a fork which added the ace editor garmmar for WDL highlighting, which can be found here https://github.com/agduncan94/wdl-sublime-syntax-highlighter/tree/feature/ace-editor-support. A PR will be made soon.

**Comment by denis-yuen** [comment]
Same deal, looks good. 
Close with PR to original repo

**Comment by agduncan94** [comment]
I have created the PR here https://github.com/broadinstitute/wdl-sublime-syntax-highlighter/pull/14.
