### ISSUE TITLE
Modify search facet not possible

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1134]
### Expected behaviour
1. Go to https://dockstore.org/search?tags.verified=1&searchMode=files
2. Uncheck tag, expect to see all tools/workflows and be back at https://dockstore.org/searchsearchMode=files
### Actual behaviour
1. Go to https://dockstore.org/search?tags.verified=1&searchMode=files
2. Uncheck tag, you are back at https://dockstore.org/search?tags.verified=1&searchMode=files and only see verified tools

**Comment by denis-yuen** [comment]
Should probably be a hotfix depending on scope of the change

**Comment by denis-yuen** [comment]
Looks like this is functional on staging.dockstore.org
