### ISSUE TITLE
Dockstore CLI Should Let User Specify Cromwell Version

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1137]
## Feature Request 

Dockstore CLI always runs the version of Cromwell specified at `io.dockstore.client.cli.nested.AbstractEntryClient#CROMWELL_LOCATION`

Dockstore should use that value as the default, but should optionally allow the user to specify a different version. Using the latest or an earlier version of Cromwell would then no longer require a new Dockstore CLI build.

While Dockstore CLI has no compile time dependencies on Cromwell, there is still the risk a different version of Cromwell may not work from Dockstore, as, for example, the command-line arguments might change between versions. However, the users could use this feature at their own risk.

**Comment by denis-yuen** [comment]
The same strategy can be used for Bunny

**Comment by denis-yuen** [comment]
Configurable in config
```
$ cat ~/.dockstore/config
token: <censored>
#server-url: http://10.11.8.80:8080
server-url: https://dockstore.org:8443
use-cache = true
cwlrunner = cwl-runner
bunny-version = 1.0.4-4
cromwell-version = 30.2
$ dockstore tool launch --local-entry Dockstore.wdl --json test.wdl.json
Running with Cromwell 30.2 , Dockstore tests with 29
Creating directories for run of Dockstore launcher in current working directory: /home/dyuen/dockstore_tools/dockstore-tool-md5sum
Provisioning your input files to your local machine
Downloading: ga4ghMd5.inputFile from md5sum.input to: /home/dyuen/dockstore_tools/dockstore-tool-md5sum/cromwell-input/2ffde7e9-98e6-4a17-b19c-0878e6b45025/md5sum.input
Caching file /home/dyuen/dockstore_tools/dockstore-tool-md5sum/cromwell-input/2ffde7e9-98e6-4a17-b19c-0878e6b45025/md5sum.input in cache, hard-linking
Calling out to Cromwell to run your workflow
java -jar /home/dyuen/.dockstore/libraries/cromwell-30.2.jar run /home/dyuen/dockstore_tools/dockstore-tool-md5sum/Dockstore.wdl --inputs /tmp/foo8514513664046447635json
```

**Comment by agduncan94** [comment]
Confirmed to work on staging 1.4.0-beta.3

**Comment by agduncan94** [comment]
Confirmed to work on staging 1.4.0-beta.3
