### ISSUE TITLE
Refresh of source files should record last modification date

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1140]
### Desired behaviour

Source files should pull down modification dates, these are files for tools, workflows, dockerfiles, etc.

**Comment by denis-yuen** [comment]
Partial implementation with https://github.com/ga4gh/dockstore/commit/bfafa8ed777ca9c2ca57759fe60b9bd67bfa9bab 
This includes dates with workflows and versions of workflows, but not individual sourcefiles.

**Comment by garyluu** [comment]
Refreshing with version/sourcefile seems to modify the date in the db workflowversion
