### ISSUE TITLE
Issue with workflow path constraint

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1141]
Looking at migrations.test.xml, we insert 3 workflows with the same path. I have updated it so that two of the workflows have a unique workflow path.

We should check to ensure that all of our table constraints are behaving how we expect them to.

**Comment by agduncan94** [comment]
Seems like this was an issue with the org and repo named the same, but the source control were different. The partial_workflow_name constraint doesn't make sense, and shouldn't exist.

**Comment by denis-yuen** [comment]
If I recall correctly, there are two constraints in order to enforce when the workflow name is null (partial_workflow_name) and when the workflow is not null.

**Comment by agduncan94** [comment]
Ya and I'm pretty sure we overwrote them for when I added source control.

**Comment by agduncan94** [comment]
This is no issue since the database migration for tests has been fixed.
