### ISSUE TITLE
We are not consistent with how we show workflow names and tool names in the search results

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1143]
We are displaying tool names with /, but displaying workflows names with ().

Examples
Tool: dockstore-biobambam2/bamtofastq
Workflow: hello-dockstore-workflow (hello-world)

**Comment by garyluu** [comment]
Still present in /tools, /workflows, and /search

**Comment by denis-yuen** [comment]
Looks consistent now, issue with links though, see #1097
