### ISSUE TITLE
Synchronization of TRS v2 implementation to match style changes and checker tool

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1145]
### Desired behaviour

Implementation of TRS style changes to match https://github.com/ga4gh/tool-registry-service-schemas/pull/26 and https://github.com/ga4gh/tool-registry-service-schemas/pull/29 after release of initial tool registry schema v2

**Comment by denis-yuen** [comment]
Completed with #1208

**Comment by agduncan94** [comment]
As per the discussion it seems that we are missing the checker id.

**Comment by denis-yuen** [comment]
@garyluu  as discussed, test_tool_url is not hooked up in our implementation of TRS

**Comment by denis-yuen** [comment]
Passing validator, closing this for now
