### ISSUE TITLE
Add process for auto-port of swagger.yaml to openapi.yaml

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1146]
### Desired behaviour
Investigate upgrading all of Dockstore or just the TRS implementation to OpenAPI v3. 

Open questions:
1) Does this break swagger-codegen instantly since it does not claim OpenAPI V3 compatibility or does this just mean that swagger codegen will not take advantage of new OpenAPI V3 features?
2) Do we need to upgrade TRS as well?
3) How does this affect existing CLI clients?
4) How does this affect the GUI?
5) Is it possible for the swagger annotations we are using currently to output both a V2 and V3 OpenApi?

**Comment by garyluu** [comment]
Last I heard about v3 codegen: https://github.com/swagger-api/swagger-codegen/issues/6598#issuecomment-352205669

**Comment by denis-yuen** [comment]
One option to consider, serving up an automatically converted description? 
https://github.com/ga4gh/data-object-service-schemas/pull/40/files

**Comment by garyluu** [comment]
1. Ran an openapi 3.0 swagger.yaml with the swagger codegen both 2.3.1 and 3.0.0 snapshot and it encounters errors.
2. Might as well
3. Not sure, will need to use new annotations and core
4. Would completely break trying to swagger codegen an openapi 3.0 spec unless we keep the old one.
5. Doesn't look like it https://github.com/swagger-api/swagger-core/wiki/Annotations-2.X vs https://github.com/swagger-api/swagger-core/wiki/Annotations-1.5.X

Notes:
- Our TRS swagger 2.0 yaml can be easily converted to openapi 3.0 using swagger2openapi.  That can probably be placed on smart api without issues.

**Comment by denis-yuen** [comment]
I think I'd like to see a deeper, more granular look at our options here. 
Use the oicr wiki for this report, thanks!

**Comment by garyluu** [comment]
Investigation done.  Remaining tasks:
- Auto-generate TRS openapi.yaml via npm openapi2swagger within Travis
- Auto-generate Dockstore openapi.yaml using maven

**Comment by denis-yuen** [comment]
Could you also link the document you presented in the demo here?

**Comment by garyluu** [comment]
https://docs.google.com/document/d/1V1Y7aSa1D_e5l7ON4AFR4Y7AdOWuJClNmpVwYafaa8A/edit?usp=sharing

**Comment by david4096** [comment]
Thanks for this @denis-yuen! I think switching the v3 might be premature, the tooling is still catching up. That being said, the v2 -> v3 conversion is painless and automatable as you've shown. As a developer, I would prefer to have swagger v2 available based on current tooling. What are the benefits of going v3 versus v2 at this point?

**Comment by denis-yuen** [comment]
@david4096 we were mostly investigating from a "how difficult would it be to upgrade to OpenAPI 3" to directly support SmartAPI POV. It looks like it would be pretty difficult and breaks a lot of tooling, so we're going with the "provide a swagger v2 directly and a converted v3 description" strategy

We didn't actually investigate whether there are new exciting features of OpenAPI v3 that would make the conversion more compelling (but we probably should have, given more time)

**Comment by denis-yuen** [comment]
Automated conversion from swagger.yaml to openapi.yaml now exists for Dockstore as part of the maven build 
Working with a deploy key running in Travis TRS in that repo
