### ISSUE TITLE
search documentation?

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1148]
## Feature Request 

Be able to search the documentation via the same search area that tools/workflows are searched from?

I'm aware there is a big overhaul of documentation so it may be easier after that's released.

### Desired behaviour

Find documentation easier

**Comment by garyluu** [comment]
Wouldn't be the same search bar, but there's https://learn.cloudcannon.com/jekyll/jekyll-search-using-lunr-js/ for the new site.

**Comment by keiranmraine** [comment]
That works for me too, happy to nav into the docs area.

**Comment by denis-yuen** [comment]
A separate search would be fine, I wonder if there is a particularly gh-pages friendly solution

**Comment by denis-yuen** [comment]
Solution seems to work well :+1:
