### ISSUE TITLE
exec of cwl with $include fails

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1151]
## Bug Report

Looks like there is a failure to resolve the path of includes when pulling in linked files to CWL definition.

Project stucture:

```
dockstore-cgpmap
  - cwls
    - includes
        doc.yml
    - mixins
        hints.yml
        requirements.yml
    cgpmap-bamOut.cwl
    cgpmap-bamOut.cwl
```

cwl snippet

```cwl
...
doc:
  $include: includes/doc.yml
...
```

### Expected behaviour

Should build a local structure to mirror above pulling down the relates files before executing cwltool.

### Actual behaviour

```
dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap/cgpmap-bamOut:3.0.0-rc7 --json fastq_gz_input.json 
Error writing to File
java.io.FileNotFoundException: /tmp/1518013364741-0/cwlsincludes/doc.yml (No such file or directory)
```

Looks like missing `/` in `cwlsincludes`.  Note that no erroneously named folder was created either.

```
$ tree /tmp/1518013364741-0
/tmp/1518013364741-0
└── cwls
    └── cgpmap-bamOut.cwl
```

### Steps to reproduce the behaviour 

As above

### Environment (Browser or OS and Dockstore version)

```
$ dockstore --version
Dockstore version 1.3.3
```

**Comment by denis-yuen** [comment]
Investigate along with #1149

**Comment by keiranmraine** [comment]
Also confirm that a git symlink is resolved.  I've had to use one to maintain compatibility after adding multiple tool definitions, e.g.

https://github.com/cancerit/dockstore-cgpmap/blob/74a443c5694b87be43a7846b0e40ecdd50ec43ca/Dockstore.cwl

**Comment by denis-yuen** [comment]
@keiranmraine  FYI, looks like symbolic links work in production in some cases. For example a direct symbolic link to a file often works, symbolic links to folders do not. 
I'm adding in some handling for folders to see how it goes.

**Comment by keiranmraine** [comment]
I can run a cwl which has mixin/include against staging with 1.3.4 fine, but if the base cwl is a symlink (for legacy support) then the mixin/include files are not found.

For example in the dockstore-cgpmap repo on staging (3.0.0-rc8) the structure is as follows:

```
├── cwls
│   ├── cgpmap-bamOut.cwl
│   ├── cgpmap-cramOut.cwl
│   ├── includes
│   │   └── doc.yml
│   └── mixins
│       ├── hints.yml
│       └── requirements.yml
├── Dockstore.cwl -> cwls/cgpmap-bamOut.cwl
```

This execution works:

```
dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap/cgpmap-bamOut:3.0.0-rc8 --json examples/cgpmap/bamOut/fastq_gz_input.json
```

but this one pointing to the base `Dockstore.cwl` link doesn't:

```
dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap:3.0.0-rc8 --json examples/cgpmap/bamOut/fastq_gz_input.json
```

It's clear that it doesn' convert the path of the link before trying to pul in the include/mixins.

```
$ dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap:3.0.0-rc8 --json fastq_gz_input.json 
problems running command: cwltool --non-strict --print-pre /tmp/1519033443555-0/Dockstore.cwl
stderr for command:
	/usr/local/bin/cwltool 1.0.20170828135420
	Resolved '/tmp/1519033443555-0/Dockstore.cwl' to 'file:///tmp/1519033443555-0/Dockstore.cwl'
	Tool definition failed initialization:
	../../tmp/1519033443555-0/Dockstore.cwl:12:3: [Errno 2] No such file or directory: '/tmp/1519033443555-0/includes/doc.yml'
```

**Comment by denis-yuen** [comment]
Hmmm, I think this case might be tricky because this is what cwltool would do on its own. 
```
$ cat .git/config 
[core]
	repositoryformatversion = 0
	filemode = true
	bare = false
	logallrefupdates = true
[remote "origin"]
	url = https://github.com/cancerit/dockstore-cgpmap.git
	fetch = +refs/heads/*:refs/remotes/origin/*
[branch "develop"]
	remote = origin
	merge = refs/heads/develop
$ git checkout 3.0.0-rc8
HEAD is now at 7464263... Looks like mixin/include is functional, test server side
$ cwltool --non-strict --print-pre Dockstore.cwl 
/usr/local/bin/cwltool 1.0.20170828135420
Resolved 'Dockstore.cwl' to 'file:///home/dyuen/dockstore_tools/dockstore-cgpmap/Dockstore.cwl'
Tool definition failed initialization:
Dockstore.cwl:12:3: [Errno 2] No such file or directory: '/home/dyuen/dockstore_tools/dockstore-cgpmap/includes/doc.yml'
```
In other words, I think it would normally be more intuitive that Dockstore would use the same working directory (the directory Dockstore.cwl is in) as cwltool does rather than using the directory of `cwls` as the working directory by detecting the symbolic link as a special case to override the working directory.

**Comment by keiranmraine** [comment]
I can work around the symlink so it's not a problem just wanted to highlight that isn't possible.

**Comment by garyluu** [comment]
Seems to launch fine alongside https://github.com/ga4gh/dockstore/issues/1149 cgpmap with 3.0.0-rc8
