### ISSUE TITLE
Tool registration UI for multi-cwl tools

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1152]
## Bug Report

When defining a tool where more than 1 cwl will be attached you provide:

Source code repo: GitHub cancerit/dockstore-cgpmap
CWL descriptor path: /cwls/cgpmap-cramOut.cwl
Image registry: Quay.io wtsicgp/dockstore-cgpmap
Tool name: cgpmap-bamOut

When you continue to the `Versions` tab and pop open edit the `docker pull` entry gives an invalid pull path.  Correcting this does not seem to take.

### Expected behaviour

```
docker pull quay.io/wtsicgp/dockstore-cgpmap:3.0.0-rc8
```

### Actual behaviour

Seems to be populated with the value used by `dockstore tool --entry`

```
docker pull quay.io/wtsicgp/dockstore-cgpmap/cgpmap-cramOut:3.0.0-rc8
```

### Steps to reproduce the behaviour 

As above

### Environment (Browser or OS and Dockstore version)

UI 2.0.3

**Comment by denis-yuen** [comment]
This looks like it is working properly on staging.dockstore.org
