### ISSUE TITLE
Angular 4 issues

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1153]
## Feature Request 
UI2 Handlebars dependency needs to be upgraded to ^4.0.0.
Typescript mismatch needs to be resolved.
ssri needs to be upgraded from 5.2.1

```
@angular/compiler-cli@4.4.6 requires typescript@'>=2.1.0 <2.4.0' but 2.4.0 was found instead.
Using this version can result in undefined behaviour and difficult to debug problems.

Please run the following command to install a compatible version of TypeScript.

   npm install typescript@'>=2.1.0 <2.4.0'
```

Notes:
- `@angular/cli` is what currently leads to the handlebars version being below 4.0.0 and ssri being 5.2.1.
- All version of @angular/cli above our current one is intended to be used for Angular 5+
- New CLI also seems somewhat compatible with Angular 4 but newly generated projects and possibly files will be made for Angular 5.
- Angular 6 beta is already out, actual release is arriving around April 2018.
- The typescript mismatch doesn't appear to be affecting anything since we've apparently had it for a real long time. 

### Desired behaviour
UI2 Handlebars dependency ^4.0.0.
No Typescript mismatch warning

**Comment by garyluu** [comment]
Changing to Angular 4 issues, putting the typescript mismatch issue in here too.

**Comment by garyluu** [comment]
Recommended solution is to upgrade to Angular 5+ at some point.  This would solve both the Typescript mismatch and the Handlebars issues.

**Comment by denis-yuen** [comment]
Redundant via https://github.com/dockstore/dockstore-ui2/pull/272
