### ISSUE TITLE
Ensure that cwltool can launch multiple file CWL tools/workflows from TRS v2 endpoints

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1156]
### Desired behaviour

See https://github.com/ga4gh/tool-registry-service-schemas/issues/20 
This ticket tracks the creation of 
1) A test for Dockstore that launches a tool/workflow with multiple files from Dockstore implementation of the V2 TRS endpoints
2) A comment or some other way of documenting that relative paths are not encoded (and thus breaking CWL)

**Comment by garyluu** [comment]
Is there an example of a tool that launches with multiple files from Dockstore?  I think we only store the descriptor file and test parameter file in a ga4gh endpoint.  And that would be 1 descriptor file and 1 test parameter file for each launch command.

**Comment by denis-yuen** [comment]
https://github.com/DockstoreTestUser2/dockstore-whalesay-imports has a few examples in its branches

**Comment by agduncan94** [comment]
Ran with https://staging.dockstore.org/workflows/github.com/dockstore-testing/md5sum-checker/_cwl_checker and it works on DockstoreAPI - 1.4.0-rc.1

I ran the command 
cwl-runner https://staging.dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fdockstore-testing%2Fmd5sum-checker%2F_cwl_checker/versions/develop/plain-CWL/descriptor/%2Fchecker-workflow-wrapping-workflow.cwl Dockstore.json
