### ISSUE TITLE
Dockstore how to publish a workflow document (checker workflows for driver projects)

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1163]
Aimed at testbed participants. Could prep this ahead of time before Dockstore has support for testing workflows in March. Can pull this out of the RFC or just make it a section.

**Comment by denis-yuen** [comment]
https://github.com/ga4gh/dockstore/wiki/GA4GH-Driver-Project-Workflow-Registration---Mini-Tutorial

**Comment by denis-yuen** [comment]
Revisit with a new ticket when 1.4.0 is ready

**Comment by agduncan94** [comment]
Changes made if you want to review again. For the first point I ended up dealing with it in the [Quick overview of structure section](https://github.com/ga4gh/dockstore/wiki/WIP-Checker-Workflow-Support-Tutorial#quick-overview-of-structure), let me know if it is ok.

**Comment by denis-yuen** [comment]
Looks well underway at https://docs.dockstore.org/docs/publisher-tutorials/checker-workflows/
I think the image needs an update for point 1 above.

As discussed, the TRS curl examples should probably be in a new document. Not advanced features which needs some breaking out

**Comment by agduncan94** [comment]
Oops I misunderstood, didn't realize you meant the first image. I'll fix that today.

**Comment by denis-yuen** [comment]
Deployed on docs.dockstore.org
