### ISSUE TITLE
Create a few more example checker workflows to work with

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1165]
### Desired behaviour
 Based on https://github.com/denis-yuen/pcawg-bwa-mem-aligner-unified and https://github.com/denis-yuen/dockstore-workflow-md5sum-unified

In particular, we need a subworkflow version to ensure that our approach works. 
There are possible approaches, take a GA4GH-DREAM workflow and checker tool, effectively neuter it, and use it as a example for testing. Second possibility, create one of your own. Remember SubWorkflowRequirement.

**Comment by agduncan94** [comment]
https://github.com/dockstore-testing/md5sum-checker
https://github.com/dockstore-testing/dockstore-workflow-md5sum-unified

These two repos are a good start for having different variations of checker workflows with the following combinations:
-entry is tool, entry and checker share test json
-entry is tool, entry and checker don't share test json
-entry is workflow, entry and checker share test json
-entry is workflow, entry and don't checker share test json

**Comment by denis-yuen** [comment]
:+1:
