### ISSUE TITLE
UI2 Changes to browse checker workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1170]
### Desired behaviour

Initially, allows users to view and debug checker workflows. 
Also launch with commands to run a checker workflow.
Follows #1168

**Comment by agduncan94** [comment]
In launch with
* No convert exists for the checker command, need to use workflow
* checker launch should reference the parent tool/workflow entry and not the checker

**Comment by agduncan94** [comment]
As per the discussion:
Parent workflow
* Typical workflow commands
* How to create param file and launch checker
Checker workflow
* Typical workflow commands

**Comment by agduncan94** [comment]
Checked on UI2 2.1.0-rc.0.
