### ISSUE TITLE
Check if the Webservice for newer releases is backwards compatible with older CLI

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1176]

**Comment by denis-yuen** [comment]
This can be a test actually (pull down an older client jar from artifactory and run a few commands that people are likely to rely on like listing workflows/tools, and running one workflow and one tool)

**Comment by denis-yuen** [comment]
As discussed, use `ApiClient.setUserAgent` to track new versions of Dockstore, set it to the current version (I think there's a way to set this from the maven property) 

Additionally, it looks like `dockstore --server-metadata` was broken at some point, not sure if related to the changes we've been making

**Comment by garyluu** [comment]
For the `dockstore --server-metadata` issue, it occurs when the webservice is older than the client (webservice doesn't have V2 ga4gh endpoint, client uses it by default).  Generally, the dockstore.org webservice should be just as new or newer than the dockstore client
