### ISSUE TITLE
Tools can be published with neither a CWL or WDL path

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1187]
## Bug Report
In the my-tools' info tab

### Expected behaviour
Can manually clear "WDL Path" or "CWL Path" and then save or cancel.

### Actual behaviour
Clearing "WDL Path" or "CWL Path" without saving or canceling removes the entire textfield and label.

### Steps to reproduce the behaviour 
- Go to my-tools
- Go to the info tab
- Click "Edit" for the "WDL path"
- Clear its text

Now the entire text field and label is gone

### Environment (Browser or OS and Dockstore version)

UI2 2.0.4

**Comment by denis-yuen** [comment]
FYI, the immediate problem is solved. 
A user can now blank either the cwl or wdl path. 
However, this means that both could potentially be blank, putting the tool into an odd state.

**Comment by denis-yuen** [comment]
Working on staging.dockstore.org
