### ISSUE TITLE
Should add tests that test the order of migration

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1189]
Ex. 
1.3.0 generated -> conf test 1 -> 1.4.0
1.3.0 generated -> conf test 2 -> 1.4.0
1.3.0 generated -> test migration -> 1.4.0

**Comment by garyluu** [comment]
Looks like CommonTestUtilities and dropAndCreateWithTestData, cleanStatePrivate1, and cleanStatePrivate2 does this
