### ISSUE TITLE
clicking on labels for workflows and tools should bring up a search for that label

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1197]
### Desired behaviour

As it says, should apply to Tools, Workflows, and Search

**Comment by denis-yuen** [comment]
@agduncan94 FYI, was reviewing tickets for gantt, I think you might be done or mostly done this already

**Comment by agduncan94** [comment]
This is done

**Comment by denis-yuen** [comment]
Functional on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3

**Comment by denis-yuen** [comment]
Scratch that, think there was a miscommunication. 
Clicking on a label brings the user to a text search for that label.  
Rather, I think it would make more sense to bring them to a label search for that label. 
(i.e. https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:develop?tab=info clicking on pcawg goes to https://staging.dockstore.org/search?search=pcawg when it should go to https://staging.dockstore.org/search?labels.value.keyword=pcawg&searchMode=files )

**Comment by denis-yuen** [comment]
Working with staging
DockstoreAPI - 1.5.0-alpha.6
DockstoreUI - 2.2.0-alpha.4
