### ISSUE TITLE
Forward links from old workflows to new path

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1198]
### Desired behaviour

https://dockstore.org/workflows/vrockai%2Fdockstore-whalesay on production does not work on staging since it is now https://staging.dockstore.org/workflows/github.com%2Fvrockai%2Fdockstore-whalesay

For cases like this, where the source control is not recorded, forward to the new location

**Comment by agduncan94** [comment]
Say page not found. Workflow paths have been migrated to include the git registry.

For the recommendations, can do github, gitlab or bitbucket and provide links. Do not auto redirect though.

**Comment by denis-yuen** [comment]
You could also say something like "in most cases, you would probably be looking for <gihub.com/org/name/workflowname" based on the assumption that in the majority of cases it will be github.
