### ISSUE TITLE
Ability to run unpublished tools if developer token is set

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#1202]
## Feature Request 

A developer should be able to run an unpublished tool as a final test before making generally available.

### Desired behaviour

If the developer API token is defined in `.dockstore/config` it should be possible to run tools that are unpublished.

**Comment by garyluu** [comment]
Launch works for user-owned unpublished workflows and tools 
Launch doesn't work for non-user-owned unpublished workflows and tools
