### ISSUE TITLE
Edit own tools/workflows from public page

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1204]
## Feature Request 
Own repository not editable from /tools or /workflows page

### Desired behaviour
For GitHub, any user is able to go to https://github.com/ga4gh/dockstore and see the dockstore repository.  The users who have the necessary permissions are able to perform modifications as needed.  The users without the permissions can view it but not make modifications.

Currently in Dockstore, I can go to my own  https://dockstore.org/containers/quay.io%2Fgaryluu%2Fdockstore-tool-md5sum%2Fdockstore-tool-md5sum71 which I own but suddenly realize I cannot perform any modifications to it.  A link will be added to mytools and myworkflows for this, but the segregation seems unnecessary.

**Comment by denis-yuen** [comment]
To discuss at stand-up
