### ISSUE TITLE
Example Extra Tags outdir Parameter in Docs Doesn't Work

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1206]
## Bug Report

The example for `Running CWL-runner with extra tags` on the [the docs page](https://dockstore.org/docs/advanced-features) has an example setting `--outdir`

If you add that as an extra setting, the cwltool command executed by Dockstore will have two `--outdir`'s generated.

Dockstore should either remove that example from the doc, or should determine if there is an `--outdir` extra parameter, and if there is, honor it.

If the plan is not to support the parameter, then ideally, although not crucial, Dockstore would generate an error that the option is not supported instead of just generating the option twice.

**Comment by garyluu** [comment]
docs.dockstore.org still shows 

> As an example, adding the following line to your config file will stop cwl-runner from cleaning up, make it run in debug mode, and set the outdir to /new/outputdir

**Comment by denis-yuen** [comment]
Good catch

**Comment by garyluu** [comment]
Looks fine on http://docs.dockstore.org/docs/publisher-tutorials/advanced-features/#running-cwl-runner-with-extra-tags
