### ISSUE TITLE
Documentation for cromwell versioning, cwl-runner interface, and compare workflow languages

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1213]
### Desired behaviour

For 1.4.0, document how users can use cwl-runner, toil, version cromwell, version bunny. 
Also compare the state of CWL support, WDL support, and our nascent Nextflow work

**Comment by agduncan94** [comment]
Document TRS updating procedure.

**Comment by denis-yuen** [comment]
Well underway and split by team members
