### ISSUE TITLE
tool version editor add test parameter error

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1215]
### Expected behaviour
Test parameter file to be added

### Actual behaviour
Encounters an error when adding test parameter file
"Required parameter descriptorType was null or undefined when calling addTestParameterFiles."

### Steps to reproduce the behaviour 
- Have manual tool
- Have a version tag
- edit version tag and put new test parameter file
- save
There is now a console error and stuck with the refresh alert as "Adding tag"

### Environment (Browser or OS and Dockstore version)
UI2 develop

**Comment by denis-yuen** [comment]
This seems functional on staging
