### ISSUE TITLE
Inconsistency with toolname and workflowname

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1218]
In the database, toolnames cannot be null, so we set them to empty string if no toolname is present. 

For workflownames, they are nullable, so we don't have to set them to empty string and instead can set them to null if no workflowname is given.

We should make these consistent. It probably makes most sense to allow toolname to be null.

**Comment by denis-yuen** [comment]
Migrations have been successfully been applied to staging.dockstore.org
