### ISSUE TITLE
WDL yaml

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1240]
### Expected behaviour
Dockstore CLI mentions `--yaml` as one of the valid input types for `dockstore workflow launch` with WDL.  As a result, Dockstore should allow a yaml file.  If --yaml is not allowed for WDL, it should be specified in the CLI help.

### Actual behaviour
Using --yaml with WDL results in a null pointer exception in https://github.com/ga4gh/dockstore/blob/1.4.0-beta.2/dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java#L125
.  Also https://github.com/ga4gh/dockstore/blob/1.4.0-beta.2/dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java#L123 doesn't do anything.

### Steps to reproduce the behaviour 
Get a known working WDL descriptor with any yaml file
```
./dockstore workflow launch --local-entry Dockstore.wdl --yaml test.yaml
```
There is now a null pointer exception

### Environment (Browser or OS and Dockstore version)
1.4.0-beta.2

**Comment by denis-yuen** [comment]
For 1.4.0, specify that yaml cannot be used for WDL. 
For post 1.4.0, let's experiment with auto-conversion

**Comment by garyluu** [comment]
First step merged into develop.  2nd step (auto-conversion) for after 1.4.0

**Comment by agduncan94** [comment]
Works.
