### ISSUE TITLE
GA4GH ToolVersions missing image_name and registry_url

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1248]
### Expected behaviour
GA4GH V2 endpoints should not have any null values

### Actual behaviour
The /tools endpoint returns ToolVersions with null image_name and registry_url:
```
body: At '/268/versions/0/image_name' Invalid type: null (expected string)
body: At '/268/versions/0/registry_url' Invalid type: null (expected string)
body: At '/269/versions/0/image_name' Invalid type: null (expected string)
body: At '/269/versions/0/registry_url' Invalid type: null (expected string)
body: At '/269/versions/1/image_name' Invalid type: null (expected string)
```

### Steps to reproduce the behaviour 
- Use staging's swagger-ui and hit the /api/ga4gh/v2/tools endpoint

**Comment by agduncan94** [comment]
Works on webservice 1.4.0
