### ISSUE TITLE
Restub should not create a new workflow, it should just change the mode and delete the versions

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1250]
The problem with creating a new workflow is that the ID will change, which the GUI isn't too happy about. It is better just to fix the issue in the backend.

**Comment by agduncan94** [comment]
Restubing a workflow does not seem the clear the launch or description information. This is on UI 2.1.0-rc.0 and webservice 1.4.0-rc.1. Besides that it works.

**Comment by denis-yuen** [comment]
This seems better now on staging
