### ISSUE TITLE
Registering GitHub + Quay.io Tool Not automatic mode

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1254]
### Expected behaviour
When registering a new tool that uses GitHub and Quay.io (with build triggers set up), the newly registered tool should be in automatic mode (since GitHub + Quay.io is supported).

### Actual behaviour
The tool ends up being in manual mode

### Steps to reproduce the behaviour 
- Checkout UI2
- Import its db from the travis folder
- Login and register a tool that uses GitHub and Quay.io (I used garyluu/dockstore-tool-md5sum)

**Comment by denis-yuen** [comment]
@garyluu ran into this while testing out https://docs.dockstore.org/docs/publisher-tutorials/getting-started-with-dockstore/#quick-registration-of-alternate-tools

**Comment by agduncan94** [comment]
NOTE: This comment will be a WIP

This comment is a discussion on how tools get converted to auto.

**Current Method**
Currently a manual tool will only be converted to auto in the following situation:
* There exists an auto tool with the same path, quay.io registry, and git url

**Considerations**
1) Stick with current implementation, just make documentation more obvious
2) Allow users to switch a manual tool to auto if possible (only should be considered if there are a lot of manual published quay tools)
3) Update the refresh code for manual tools that are from Quay to check if they should be updated.

**How many manually published Quay.io tools are there?**

**Comment by denis-yuen** [comment]
Might not be necessary, I think the existing code might just leave them alone (if they refer to a valid git tag) and add new versions. This would be beneficial if they've been customized at all.

**Comment by garyluu** [comment]
Appears to be working
