### ISSUE TITLE
Cromwell Launch Exit Code

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1259]
### Expected behaviour
Dockstore CLI launch should return the same exit code as its Cromwell execution

### Actual behaviour
Exit code 0 is always returned no matter what 

### Steps to reproduce the behaviour 
Launch a WDL workflow that is known to fail.

**Comment by garyluu** [comment]
dockstore now returns a non-zero exit code when cromwell returns a non-zero exit code.  However, cromwell exit code was 1, but dockstore returned 3.  Not sure if that's what's intended.

**Comment by denis-yuen** [comment]
Probably our mappings don't match their's. A `1` for us would be a generic error. IO error probably isn't better, we probably need a code for workflow failure
