### ISSUE TITLE
Dockstore with ~/.dockstore/config

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1264]
### Expected behaviour
If a config file is specified, dockstore should not be asking for token and server-url

### Actual behaviour
Even though --config configFile is specified, dockstore asks for everything

### Steps to reproduce the behaviour 
- Move your ~/.dockstore/config file to ~/.dockstore/config2
- Run `./dockstore --config ~/.dockstore/config2 --version`

**Comment by denis-yuen** [comment]
Functional on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
