### ISSUE TITLE
1 Checker associated with 2 workflows

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1268]
### Expected behaviour
Can create 2 workflows (garyluu/example_cwl_workflow and garyluu/example_cwl_worklow/1) where garyluu/example_cwl_workflow has a checker workflow and garyluu/example_cwl_workflow/1 does not have a checker workflow

### Actual behaviour
Both of them end up with the same checker workflow

### Steps to reproduce the behaviour 
- start with empty database
- log in, add 2 workflows (garyluu/example_cwl_workflow and garyluu/example_cwl_workflow/1)
- add checker to garyluu/example_cwl_workflow
- refresh both (garyluu/example_cwl_workflow and garyluu/example_cwl_workflow/1)
Now both workflows have the same checker

**Comment by agduncan94** [comment]
Have you tested this with tools too?

**Comment by garyluu** [comment]
Steps performed, looks fine now.  Only 1 workflow with checker now.
