### ISSUE TITLE
WDL DAG seems to have some issues

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1283]
Doesn't show for https://staging.dockstore.org/workflows/github.com/vrockai/dockstore-whalesay:master even though it is valid.

**Comment by agduncan94** [comment]
I can recreate this in staging using the same descriptor file. However this seems to be fixed in a newer version of develop. @garyluu @denis-yuen Have either of you changed the WDL parsing code in the last few days?

**Comment by garyluu** [comment]
not by me

**Comment by denis-yuen** [comment]
@agduncan94 
Not to my knowledge. 
To be clear, are you running develop via IDE or via a compiled jar?

**Comment by agduncan94** [comment]
I'm using an IDE

**Comment by agduncan94** [comment]
Can confirm the error doesn't occur when running from IDE, but does from the jar.

**Comment by agduncan94** [comment]
Weird I didn't close this issue.

**Comment by agduncan94** [comment]
Oops

**Comment by garyluu** [comment]
https://help.github.com/articles/closing-issues-using-keywords/

**Comment by agduncan94** [comment]
That explains it.

**Comment by denis-yuen** [comment]
This particular workflow seems better now on staging
