### ISSUE TITLE
CWL DAG seems to be broken sometimes

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1284]
For some workflows the CWL DAG displays that the DAG only works for CWL V1.0, even though a workflow is cwl V1.0.

Another issue if there is only a high level docker requirement defined, and not per tool, then the tools page isn't properly populated.
https://staging.dockstore.org/workflows/github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/pcawg-oxog-full-workflow

**Comment by agduncan94** [comment]
Seems like for the second mentioned issue that tool isn't a good example, as the primary descriptor doesn't actually have a docker requirement. If I add a docker requirement to the primary descriptor, then it will be properly used as the default for subtools. However it is not used for subworkflows.

**Comment by agduncan94** [comment]
Just some comments for testing:
* A workflow with a high level docker requirement (hint or requirement) should propagate to any of its tools or subworkflows that don't define their own docker requirements
* Hints should now be properly parsed for CWL

**Comment by denis-yuen** [comment]
Seems a lot more robust on staging.dockstore.org
