### ISSUE TITLE
ui2 embed code needs to aggregate link to discourse

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1290]
### Desired behaviour

As it says, we auto-populate our forum via RSS but we're getting threads for different versions of workflows (and later, for different tabs of workflows).

**Comment by agduncan94** [comment]
Need to deal with
* Versions
* Tab
* Encoding
* Tools VS containers

**Comment by agduncan94** [comment]
@denis-yuen I tested for dealing with versions and tabs and your changes seem to support both of them. Since you already split by the 2nd colon (version), and the tab params always come after the version, it already worked.

This was in the develop branch.

**Comment by agduncan94** [comment]
@denis-yuen Is the encoding and tools v containers something I should look into now or later?

**Comment by denis-yuen** [comment]
I think now would be fine now that 1.4.0 is deployed and its fresh.

**Comment by denis-yuen** [comment]
Looks better except for the issue which is only partially related #1816
