### ISSUE TITLE
GA4GH invalid /tools/{id} endpoint handling

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1295]
### Expected behaviour
`curl -X GET "https://dockstore.org:8443/api/ga4gh/v1/tools/potato" -H  "accept: application/json"`
should result in a useful error message

### Actual behaviour
Message returned is 
{
  "code": 500,
  "message": "There was an error processing your request. It has been logged (ID fb156a32b3295403)."
}
### Steps to reproduce the behaviour 
`curl -X GET "https://dockstore.org:8443/api/ga4gh/v1/tools/potato" -H  "accept: application/json"`

**Comment by denis-yuen** [comment]
:+1:
