### ISSUE TITLE
Discourse thread should be displayed below tab container

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1305]
Currently we embed the discourse discussion for an entry at the bottom of the info tab. I think it may make more sense to have the embed exist below the tab holder, that way no matter the tab you are on you can see the discussion.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-325)
┆Issue Type: Story
┆Issue Number: DOCK-325

**Comment by denis-yuen** [comment]
Let's chat about getting discourse working on staging

**Comment by agduncan94** [comment]
On staging it looks like it is within all tabs, not just info tabs.

**Comment by agduncan94** [comment]
Fixed on:
DockstoreAPI - 1.6.0-rc.4
DockstoreUI - 2.3.0-rc.4
