### ISSUE TITLE
UI2 dependency upgrades

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1310]
## Feature Request 
A list of dependencies and tools we may wish to upgrade in the UI2 for 1.5.0

### Desired behaviour
- Completely replace ngx-bootstrap with Angular Materials (officially bundled with Angular 6) because less 3rd party dependencies, let Angular handle versions bundled.
- Upgrade our Angular 4 to Angular 6 (and all its suggested deps which include Typescript 2.6+).  For those whose auto-import depend on Typescript 2.6+, also ngxs and ngrx requires Angular 6.
- Upgrade Angular CLI to the latest version that matches Angular 6
- Upgrade npm to 5.7.1+ to avoid the EINTEGRITY error (latest nodejs LTS is still tied to npm 5.6.0 though.  even nodejs 9.x is also tied to npm 5.6.0 )
- Bootstrap 4 (4 is now stable but first glance appears to be a real pain for not much benefit)

**Comment by garyluu** [comment]
Results from the discussion:
- Upgrade to Angular 6 with matching Angular CLI
- Upgrade Cypress
- Experiment on NPM 5.7.1
- Don't upgrade to Bootstrap 4
- Slowly phase in Angular Material
- Hold off on NGXS

**Comment by denis-yuen** [comment]
Mostly in flight, follow-up with individual tickets as appropriate
