### ISSUE TITLE
Star/Unstar endpoint return object

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1314]
### Desired behaviour
Star/unstar endpoints should return something non-void to indicate success or failure.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-134)
┆Issue Number: DOCK-134

**Comment by denis-yuen** [comment]
usual caveat, should be idempotent

**Comment by denis-yuen** [comment]
@NatalieEO maybe a 500 as well if something really does go wrong server side vs client side. 
I defer to Charles and Gary if it would actually be useful/more efficient

**Comment by garyluu** [comment]
If it's already returning different status codes, then it's fine by me but would like the UI to better handle failure.
