### ISSUE TITLE
compose setup

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1324]
### Desired behaviour

Avoid use of --no-cache by breaking the ui2 cache in the Dockerfile before git clone

**Comment by garyluu** [comment]
Hack to not use cache:
`ADD https://api.github.com/repos/ga4gh/tool-registry-validator/compare/feature/flask...HEAD /dev/null`

**Comment by agduncan94** [comment]
@garyluu Do you have a link to where you read about this fix?

**Comment by garyluu** [comment]
long time ago

**Comment by garyluu** [comment]
probably similar to https://stackoverflow.com/a/39278224/4484759

**Comment by agduncan94** [comment]
Does the branch it is looking at matter? Can I just set it to develop?

**Comment by garyluu** [comment]
presumably, u want to use the cache when the branch of the repo doesn't change, but you do not want the cache when the repo changes.  so it'd be branch-specific

**Comment by agduncan94** [comment]
Hm that might be too much work. Might try what Denis was thinking about in the morning. Have `RUN echo {{ DOCKSTORE_UI2_VERSION }}` before the git clone, which will only change when the branch changes.

**Comment by garyluu** [comment]
I suppose that'd work for most cases.
