### ISSUE TITLE
Distinguish workflows from different organizations

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1338]
### Desired behaviour

Display organizations for workflows (possibly only when there are duplicates, not sure)  akin to how https://github.com/search?utf8=%E2%9C%93&q=swift&type= shows apple/swift and openstack/swift

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-332)
┆Issue Type: Story
┆Issue Number: DOCK-332

**Comment by NatalieEO** [comment]
Seems to be working on staging.dockstore.org DockstoreUI - 2.3.0-beta.2
