### ISSUE TITLE
Registering Tool does not change url

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1344]
### Expected behaviour
Registering a new tool will show the new tool.  It will also change the url to represent the new tool's url

### Actual behaviour
Registering a new tool will show the new tool.  However, it will keep the same url as what it was before.

### Steps to reproduce the behaviour 
Run the mytools.js cypress test, near the end of the test, look at the url.

**Comment by denis-yuen** [comment]
Functional on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
