### ISSUE TITLE
Embed expected webservice version in ui2

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1346]
### Desired behaviour

Somehow generate or template the expected (what you pointed at for swagger codegen) webservice version in the UI2 generated classes and then use that to trigger a warning banner in staging.

**Comment by agduncan94** [comment]
When I try this locally I get that the version is undefined.

**Comment by garyluu** [comment]
have to export to env variable.  Travis does it, but there's no script for dev

**Comment by agduncan94** [comment]
Works.
