### ISSUE TITLE
UI Not Showing Full Content of WDL

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1357]
## Bug Report

UI is only showing first 256 lines of a WDL.

### Expected behaviour

Should show all the WDL.

### Actual behaviour

Shows first 256 lines.

### Steps to reproduce the behaviour 

1. In browser, goto https://dockstore.org/workflows/github.com/BD2KGenomics/topmed_freeze3_calling/TopMed_Variant_Caller
2. Click on Files
3. There is only one file for that workflow; scroll to the bottom of the file in the UI. You can see the last line is number 256.
4. Scroll back to the top of the file and click the Copy to Clipboard icon
5. Paste the contents into your favorite editor.
6. In your editor, you'll see that the contents are 415 lines long.

**Comment by coverbeck** [comment]
This seems to be related to the content itself  and not the size of it -- an escaping/encoding issue.

Right where it gets truncated in the UI, the WDL is:

```
python <<CODE
```

Displayed HTML is

```
command {
 python <
```

**Comment by coverbeck** [comment]
See https://stackoverflow.com/questions/1273145/what-do-i-need-to-escape-inside-the-html-pre-tag

**Comment by denis-yuen** [comment]
Thanks for the lead, this probably affects both CWL and WDL so I'm linking to this #1132 and #1131 to be done at the same time those are handled.

**Comment by denis-yuen** [comment]
Seems better https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/Functional_Equivalence:1.7.0?tab=files

Tested on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
