### ISSUE TITLE
Implement branch and tag recording for Gitlab

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1364]
### Desired behaviour

Bitbucket and GitHub interfaces now record which versions are from tags and which are from branches. Follow up with implementation for GitLab

**Comment by denis-yuen** [comment]
Followed by #1364
This ticket mutates into GUI support for the above after #1362

**Comment by agduncan94** [comment]
@denis-yuen The related too is itself. Did you mean https://github.com/ga4gh/dockstore/issues/1336?

**Comment by denis-yuen** [comment]
yup

**Comment by garyluu** [comment]
Appears to work with gitlab:

![image](https://user-images.githubusercontent.com/24548904/43415110-b23089fe-9402-11e8-96b7-9f81e3152e85.png)
