### ISSUE TITLE
Launch with FireCloud Link Version Incorrect for Checker Workflow

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1371]
## Bug Report

When viewing a checker workflow, the version in the link to Launch with FireCloud does match the version of the checker workflow displayed (at least in this case).

### Expected behaviour

The link should be the same version as the currently selected version.

### Actual behaviour

The link has a different version.

### Steps to reproduce the behaviour 

1. Goto https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/Functional_Equivalence_wdl_checker
2. Hover the mouse cursor over the Launch with FireCloud button, and you will see the link at the bottom left of the browser.

See the attached screenshot and note the following:

1. The url is `https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/Functional_Equivalence_wdl_checker` (no version).
2. The page title is `github.com/DataBiosphere/topmed-workflows/Functional_Equivalence_wdl_checker:develop`, with `develop` as the version.
3. The status bar link is `https://portal.firecloud.org/#import/dockstore/github.com/DataBiosphere/topmed-workflows/Functional_Equivalence_wdl_checker:1.0.0` (version 1.0.0).

Note that if you click on a version in the `Recent Versions` box, e.g., on develop, then all 3 items come into sync.

![screen shot 2018-04-25 at 4 50 58 pm](https://user-images.githubusercontent.com/1049340/39278628-194b3788-48a9-11e8-94c9-7feaec9f36eb.png)

┆Issue is synchronized with this [JIRA Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-3)
┆Issue Number: DOCK-3

**Comment by denis-yuen** [comment]
Strange, having trouble re-producing. I just get sent to "feature/checker-fix" the default branch. The URL is https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/Functional_Equivalence_wdl_checker but I get the checker-fix version in the title and and launch with. 

This might be a specific set of conditions.
