### ISSUE TITLE
Be Able to Search for Workflows that Have Checker Workflows

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1374]
## Feature Request 

On the Search page, It would be nice if you could search for workflows that have checker workflows, so that you could see examples of implementations.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-53)
┆Issue Number: DOCK-53

**Comment by denis-yuen** [comment]
This should be implemented both via TRS and in Dockstore search

**Comment by denis-yuen** [comment]
Done in https://github.com/dockstore/dockstore-ui2/pull/309

**Comment by coverbeck** [comment]
LGTM on staging
