### ISSUE TITLE
Link to swagger UI in footer or docs

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1375]
It would be useful to have a link to the swagger UI for dockstore, either in the docs or footer.

**Comment by agduncan94** [comment]
Will likely add this to the ga4gh metadata endpoints

**Comment by denis-yuen** [comment]
While at this, in the footer the Status button looks kinda funny and the About Dockstore link goes to a  redirect

**Comment by denis-yuen** [comment]
- "About Dockstore" seems different but is still a redirect via https://staging.dockstore.org/docs/about (should be https://docs.dockstore.org/docs/ )
- Swagger UI link is a bit big and takes up its own line, thinking we could copy the layout for GitHub Repository + Follow Us, use two icons for Status and Swagger UI, move the gitter link a bit to the left and then insert Status and Swagger UI there.

**Comment by agduncan94** [comment]
@denis-yuen for the second point, you mean having 4 columns instead of the current 3?

**Comment by denis-yuen** [comment]
Specific issue with the status button, but overall the footer is much improved 
```
DockstoreAPI - 1.5.0-beta.5
DockstoreUI - 2.2.0-beta.4
```
