### ISSUE TITLE
Implement and test dates for hosted workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1378]
### Desired behaviour

Editing workflows on Dockstore for hosted workflows should update modification times akin to #1194 

Edit to add: Record who edited a workflow

**Comment by denis-yuen** [comment]
First part done via #1382

**Comment by garyluu** [comment]
new workflow versions appears to have the correct date for lastupdated in develop branch

**Comment by garyluu** [comment]
first part checked already

**Comment by denis-yuen** [comment]
@garyluu can you note what remains for this ticket?
