### ISSUE TITLE
cwltool update

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1381]
### Desired behaviour

Pick a newer version of cwltool (update UI, CLI, and test verified workflows on Dockstore with tooltester). Be aware of https://github.com/common-workflow-language/cwltool/pull/721

**Comment by garyluu** [comment]
All recently successful tools work with cwltool 1.0.20180403145700 on tooltester

**Comment by denis-yuen** [comment]
@garyluu  could you link to the appropriate updates for the UI and webservice, thanks.

**Comment by denis-yuen** [comment]
Part 4 of the setup wizard is out of date

**Comment by denis-yuen** [comment]
:+1:
