### ISSUE TITLE
Use SAM for Authorization

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1384]
## Feature Request 

Use FireCloud SAM for authorization for sharing workflows.

This means authorization will only work for users who have linked Google accounts.

* Stand up an instance for local development and CI. Will need to worry about certs.
* Add permissions UI
   - Permissions UI should initially only be present if user has a linked Google account, as SAM will currently only work with Google users.
   - If user has a linked Google account, also need to check if user can share; either user is the owner or has permission to share, if we introduce that permission.
* UI to show shared with workflows
* Invoke SAM to share
* Invoke SAM to verify if a user is authorized on the appropriate method calls.
* Call SAM to get a list of shared workflows with the user.
* New Dockstore Webservice endpoints
   - Get Shared With workflows
   - Checks for permissions, e.g., is a workflow shareable?
   - Set permissions on a workflow
* Create PR for SAM adding new resource type and roles.

┆Issue is synchronized with this [JIRA Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-10)
┆Issue Number: DOCK-10

**Comment by denis-yuen** [comment]
In the case that SAM is difficult to standup in the way we standup postgres, elastic search. It may be worthwhile deciding on some endpoints and mocking-out the return (and/or creating a few tests that demonstrate how the UI will interact with them). Then we can implement the GUI ahead of properly integrating with SAM

**Comment by denis-yuen** [comment]
This issue is complete enough to be closed in favour of more specific issues for sam related work.
