### ISSUE TITLE
Kibana issues

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1389]
## Bugs

- Test out whether new CLI works and shows up in Kibana with a proper version 
- path bug in generalized path and latency

### Desired behaviour

- logstash should also retain regular logging 
- either documentation to remake dashboard or export/import configuration files for restoring in case recreating for production later and/or backup

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-339)
┆Issue Number: DOCK-339

**Comment by garyluu** [comment]
- Primer updated to show how to import/export entire dashboard.  
- Generalized path fixed (at least for some, we'll see if more pop up)
- CLI shows up with proper version when using new CLI.

**Comment by denis-yuen** [comment]
Live feedback on 401 (failed authentication) to Slack would be nice to keep an eye on things security-wise

**Comment by denis-yuen** [comment]
Alerting should deal with the last #1811

**Comment by denis-yuen** [comment]
Think this is sufficiently complete to be followed with more specific tickets. 
Not strictly dependent on a release, so closing
