### ISSUE TITLE
Competition for 3 possible material design themes

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1390]
### Desired behaviour

As a part of this migration, come up with two or three demo-able themes. Convert one or two representative pages to use material widgets (my tools, accounts) as a demonstration.  

As a part of this, create one theme based on Dockstore's current colours and two can be more creative.

**Comment by agduncan94** [comment]
Seems cool, only on Mac OSX for some reason.
https://material.io/tools/theme-editor/

**Comment by agduncan94** [comment]
https://material.io/tools/color/#!/?view.left=0&view.right=0&primary.color=21335b&secondary.color=487980

**Comment by agduncan94** [comment]
I think this is done for now. I'll create another issue to create a style guide for Dockstore developers for the Wiki.

**Comment by denis-yuen** [comment]
Complete, looks good
