### ISSUE TITLE
Nextflow highlighting

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1396]
### Desired behaviour

Follows #1041, #1131, and #1132 
Try to find an existing highlight schema for Nextflow (nextflow.config and main.nf) to use for ACE probably based on Groovy syntax.

**Comment by denis-yuen** [comment]
https://github.com/github/linguist/issues/4080

**Comment by garyluu** [comment]
Partially implemented

**Comment by denis-yuen** [comment]
Functional on staging with API 1.5.0-alpha.4, UI 2.2.0-alpha.3
