### ISSUE TITLE
Implement Permissions UI

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1413]
Need a Permissions UI on My Workflows that lets users share their workflow.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-11)
┆Issue Number: DOCK-11
┆Epic: SAM for Authorization

**Comment by coverbeck** [comment]
Moving to ready for testing with @agduncan94 's merge of dockstore/dockstore-ui2#331

**Comment by denis-yuen** [comment]
Think this is functional enough to be split out into smaller follow-up tickets.
