### ISSUE TITLE
Doc and dct:creator fields not pulled from valid CWL file

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1419]
https://github.com/bogdang989/sbg_dockstore_tools/blob/master/pcawg/bwa/icgc_pcawg_seqware_bwa_sbg.cwl

User created a DockerHub tool using this CWL file. The Doc and dct:creator fields were not parsed from the CWL and therefore not displayed on the info tab. Using another DockerHub account the user was able to get it working.

I also tried registering the tool in dockstore and it was properly parsed.

Edit: The tool is on dockstore at https://dockstore.org/containers/registry.hub.docker.com/sevenbridges/pcawg_bwa_sbg_modified

**Comment by bogdang989** [comment]
Update: now it can't get parsed from the other account either

**Comment by agduncan94** [comment]
No luck recreating the issue yet. I was able to register the same tool on production and it properly parsed the author information. I also tried creating a repo with the same CWL/dockerfile and then altering the author after it was successfully parsed on the site, but that also worked.

@bogdang989 Just a heads up I am going to try refreshing your tool to see if I see anything strange happening.

**Comment by garyluu** [comment]
Can reproduce similar problem on production, seems fixed with staging.  Using tag 1.0 and git reference v1.0.0 and then with tag 1.0 and git reference v1.0.1
