### ISSUE TITLE
Missing Descriptor Type

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1434]
## Bug Report
1.5.0-alpha.0 removed descriptorType from /published endpoint due to descriptorType being resolved using sourcefiles. it is removed with https://github.com/ga4gh/dockstore/blob/1.5.0-alpha.0/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/DockerRepoResource.java#L590

### Expected behaviour
https://staging.dockstore.org/tools to have content in the Format column

### Actual behaviour
The format column is empty

### Steps to reproduce the behaviour 
Go to https://staging.dockstore.org/tools 

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.5.0-alpha.0
DockstoreUI - 2.2.0-alpha.1

**Comment by agduncan94** [comment]
@garyluu The links you have are for staging, but this is actually for the current develop version right?

**Comment by garyluu** [comment]
The version is specified

**Comment by agduncan94** [comment]
Ok I figured it out, it was just that the links you provided were for staging.

**Comment by garyluu** [comment]
because staging had that version...

**Comment by denis-yuen** [comment]
Post 1.5.0-alpha.4

**Comment by denis-yuen** [comment]
Obsolete with new pagination implementation and fix to lazy loading
