### ISSUE TITLE
Glitch with constructing the raw github url for specific workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1440]
## Bug Report

URL for 
https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fbriandoconnor%2Fdockstore-workflow-md5sum-tester/versions/develop/CWL/descriptor is messed up
https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fbriandoconnor%2Fdockstore-workflow-md5sum-tester%2F_cwl_checker/versions/develop/CWL/descriptor seems ok

https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FTopMed_Variant_Caller_wdl_checker/versions/1.11.0/WDL/descriptor is messed up
https://dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FDataBiosphere%2Ftopmed-workflows%2FTopMed_Variant_Caller/versions/1.11.0/WDL/descriptor is messed up

**Comment by agduncan94** [comment]
I think I am blind but where in the URLs is messed up? @denis-yuen

**Comment by garyluu** [comment]
possibly the url inside the json when u go to the link

**Comment by denis-yuen** [comment]
yeah, copy and paste the url in the json or click through on firefox

**Comment by agduncan94** [comment]
Fixed on webservice 1.4.4.
