### ISSUE TITLE
Recursive import support

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1446]
### Expected behaviour

Imports of imports should function

### Actual behaviour

Looks like imports of imports are an issue for the HCA checker workflow

**Comment by garyluu** [comment]
Also check if the CLI can launch local entries this way.

**Comment by denis-yuen** [comment]
Tested refresh and display for recursive imports , that aspect seems to work for me.

**Comment by garyluu** [comment]
Seems to be fine, UI2 is fine.  TRS returns all the files
