### ISSUE TITLE
Files endpoint is not returning relative paths for test json 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1448]
### Expected behaviour

Paths should all be relative paths as per documentation
https://github.com/ga4gh/tool-registry-service-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L324
### Actual behaviour

Seeing absolute paths which are inappropriate for the relative paths endpoint

**Comment by agduncan94** [comment]
Tested on webservice 1.4.4 and it is working as expected.
