### ISSUE TITLE
checker launch require authentication

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1449]
### Expected behaviour
The GET /workflows/path/entry/{repository}/published
Get an entry by path 
endpoint should be optionally authenticated.

### Actual behaviour
The endpoint has mandatory authentication.  Trying to launch a checker without a token will result in "entry not found".

### Steps to reproduce the behaviour 
$ dockstore checker launch --entry github.com/garyluu/skylab:master checkparam.json

**Comment by denis-yuen** [comment]
A published endpoint should have security at all, so this seems like an oversight

**Comment by denis-yuen** [comment]
There's something not quite right here.
Reviewing https://github.com/ga4gh/dockstore/pull/1227/files#diff-ec6e0cbc48d79e219cd04155bd31dcdfR158 

The published endpoint shouldn't have security, we check an entirely different endpoint to get workflows in the case that a workflow is not published. 
So it seems like there's two issues
1) The published endpoint should not have mandatory (or optional) security. 
2) Checker launch is not re-using that code to hit a different endpoint

**Comment by agduncan94** [comment]
The checker launch tries to get the checker workflow given the entry. This calls the /workflows/{workflowId} which requires authentication. This means that all of the checker workflow client calls will only work if you are authorized.

**Comment by denis-yuen** [comment]
I think this can just re-use code like https://github.com/ga4gh/dockstore/pull/1227/files#diff-d41787d11cad82b6d81a241f117fa3cbR294 
(i.e. try to get the checker workflow publicly first, then try it in an authenticated way)

**Comment by garyluu** [comment]
`dockstore checker launch --entry github.com/dockstore-testing/md5sum-checker:master --json checker-input-cwl.json` on develop branch with prod db

swagger-ui shows endpoint no longer require authentication
