### ISSUE TITLE
Further break out  integration tests

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1457]
### Desired behaviour

1. Identify good groupings for tests in dockstore-integration-tests
2. Use current build stages + Maven profiles setup for inspiration as to how to split up tests (or if a better solution is possible, do that)

**Comment by agduncan94** [comment]
I did this with https://github.com/ga4gh/dockstore/pull/1465. Now splits up ITs into 5 jobs.

**Comment by denis-yuen** [comment]
Seems to be working well
