### ISSUE TITLE
Provide non-published entries via TRS-like endpoints

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1469]
### Desired behaviour
Dockstore should be able to use TRS endpoints to grab the file contents of unpublished entries.
In particular, the /files endpoint or /descriptor/{relative-path} endpoint.

Pretty much utilize only the TRS endpoints in the entire UI2 files tab

**Comment by denis-yuen** [comment]
Spitballing, we can either use some undocumented behaviour (when logged in, TRS endpoints also return non-public workflows) or create new endpoints that are very similar under the tag https://dockstore.org:8443/static/swagger-ui/index.html#/extendedGA4GH

**Comment by denis-yuen** [comment]
Can we declare TRS endpoints to have optional authentication but still show this properly in the swagger-ui as an optional thing

**Comment by denis-yuen** [comment]
Options: newer swaggerui? hacking swagger ui? use completely new endpoints in extendedGA4GH

**Comment by denis-yuen** [comment]
use completely new endpoints in extendedGA4GH

**Comment by denis-yuen** [comment]
Done in #1614

**Comment by agduncan94** [comment]
I tried using the /api/ga4gh/v2/tools/{id}/versions/{version_id}/{type}/descriptor endpoint for this. When the workflow is not published, I get a not found error. When I publish it, it works.

**Comment by denis-yuen** [comment]
Hmm, were you authenticated as a user who would have access to it otherwise?

**Comment by agduncan94** [comment]
Yes I was using the same user who owned the workflow.

**Comment by denis-yuen** [comment]
Actually, this seems to be functional already due to https://github.com/ga4gh/dockstore/pull/1614#pullrequestreview-138741404
If you look at a non-published workflow and go to the files tab you should be able to see requests go through v2 endpoints

**Comment by agduncan94** [comment]
@denis-yuen Weird that it works in that case but not when I go through the swagger ui.

**Comment by garyluu** [comment]
I think that might be intended.  Officially, the endpoints do not require authentication (the swagger.yaml remains the same).  Swagger-ui thinks it's not authenticated, so it doesn't use the bearer token even if there is one linked.

**Comment by agduncan94** [comment]
Based on what Gary said, I am marking this as closed because it does work as expected. I'll just make a note that it will not work with swagger-ui because it thinks it is not authenticated.
