### ISSUE TITLE
Terms of service

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1471]
### Desired behaviour

Will probably have to get in-house legal to look through this, but we might need a privacy policy ala 
https://github.com/common-workflow-language/cwlviewer/pull/194

Policy is slightly different since we do allow users to login to discussion forums and we retrieve some info like their avatar images to display when showing who has starred a tool/workflow..

**Comment by denis-yuen** [comment]
https://portal.firecloud.org/#policy might be useful too

**Comment by coverbeck** [comment]
To register with [Smart API](http://smart-api.info/add_api), a `termsofservice` is required. Looks like, although I'm not a lawyer, that terms and conditions includes the privacy page. See the [GA4GH](https://www.ga4gh.org/policies/termsandconditions.html) for an example.

**Comment by denis-yuen** [comment]
Another example https://codecov.io/site/gdpr

**Comment by denis-yuen** [comment]
Created a rough draft https://gist.github.com/denis-yuen/53d4811e5963ac0c15bbc8556e1f7c7b 
Currently winding its way through legal (they're also considering other oicr sites at the same time)

**Comment by denis-yuen** [comment]
Still pending, add link to Swagger as per #1200 when we get a final draft

**Comment by denis-yuen** [comment]
Received a terms of service. 
Need to upload and link to UI

**Comment by denis-yuen** [comment]
[Dockstore Terms of Service.pdf](https://github.com/ga4gh/dockstore/files/2558950/Dockstore.Terms.of.Service.pdf)
