### ISSUE TITLE
/api/ga4gh/v2/tools/{id}/versions/{version_id}/{type}/files returns paths

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1472]
### Expected behaviour

ToolTests objects should return a URL to the underlying file

### Actual behaviour

ToolTests objects actually return a relative path as if they were part of the files listing

See also https://github.com/ga4gh/tool-registry-service-schemas/issues/40

**Comment by garyluu** [comment]
appears functional with `curl -X GET "https://staging.dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fgaryluu%2Fskylab%2F_wdl_checker/versions/feature%2FupperThingy/WDL/tests" -H  "accept: application/json"` resulting in `https://raw.githubusercontent.com/garyluu/skylab/feature/upperThingy/test/smartseq2_single_sample/pr/dockstore_test_inputs.json` and `curl -X GET "https://staging.dockstore.org:8443/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fgaryluu%2Fskylab%2F_wdl_checker/versions/master/WDL/tests" -H  "accept: application/json"` resulting in `https://raw.githubusercontent.com/garyluu/skylab/master/test/smartseq2_single_sample/pr/dockstore_test_inputs.json`
