### ISSUE TITLE
wdl4s getInputFiles causes null pointer exception

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1474]
## Bug Report
Dockstore is not able to launch the [HCA workflow](https://github.com/garyluu/skylab) using `launch --entry`, `launch --local-entry` still works.  This appears to be due to https://github.com/ga4gh/dockstore/blob/1.4.3/dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java#L152 causing a null pointer exception.  This should be investigated further.

Test was done using the master branch of the workflow.
Problem is actually with the checker workflow, not the workflow itself
```
Workflow Path: /test/smartseq2_single_sample/pr/test_smartseq2_single_sample_PR.wdl
Test File Path: /test/smartseq2_single_sample/pr/dockstore_test_inputs.json
```

### Expected behaviour
Dockstore should be able to launch the workflows with imports within imported files (like the HCA workflow).  

### Actual behaviour
Dockstore gets to https://github.com/ga4gh/dockstore/blob/1.4.3/dockstore-client/src/main/java/io/github/collaboratory/wdl/WDLClient.java#L152, all the files are downloaded to the tmp location and arranged properly but that line causes and error preventing launch from going further.   Note: dockstore can `launch --local-entry` in that temporary location just fine.

**Comment by denis-yuen** [comment]
Pending investigation of #1549 
I was unable to launch on develop, also noticed the linked issue.

**Comment by agduncan94** [comment]
The reason for this is that we are not actually downloading and provisioning any imports after the first level of imports. (See resolveImportsForDescriptor() in the WDLClient.java)

**Comment by denis-yuen** [comment]
Hmmm, 
reminds me of https://github.com/ga4gh/dockstore/commit/28e148176e810d8b6f1243c0f420ef11d838e5bc#diff-b488be7f020c4443b9e24ee31d934d6c

**Comment by garyluu** [comment]
Dockstore Staging
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6

Works:
dockstore workflow convert entry2json --entry github.com/garyluu/skylab:master > Dockstore.json
wget --header='Accept: text/plain' https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fgaryluu%2Fskylab/versions/master/PLAIN_WDL/tests -O Dockstore.json
dockstore workflow launch --entry github.com/garyluu/skylab:master --json Dockstore.json
dockstore checker launch --entry github.com/garyluu/skylab:master --json checkparam.json
dockstore workflow convert entry2json --entry github.com/garyluu/skylab/_wdl_checker > Dockstore.json
