### ISSUE TITLE
DOS File Provisioner Plugin Should Handle new DOS URI scheme

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1480]
## Feature Request 

The first implementation of the DOS File Provisioner Plugin is handling DOS URIs with the scheme `dos://<hostname>/UUID`.

DOS is being changed to the scheme `dos://prefix/UUID` where we will need to call a known resolver to do the resolution.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-12)
┆Issue Number: DOCK-12
┆Epic: DOS File Provisioner

**Comment by coverbeck** [comment]
See https://github.com/broadinstitute/martha/commit/3fa0703c7ad49e461b136c4a4f8d04f95bef8099

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

[~wshands] , this is the ticket I was talking about.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

OK,
Is there documentation on how to setup to work with this?

On Mon, Jul 9, 2018 at 2:45 PM, Charles Overbeck (Jira) <

-- 
Walt Shands
831-419-9148
UCSC Genomics Institute

**Comment by denis-yuen** [comment]
Was able to run a general workflow under 1.5.0-beta.4-SNAPSHOT matched with a corresponding staging.
