### ISSUE TITLE
DOS File Provisioning Plugin Should Have Configurable Preferences

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1482]
## Feature Request 

The DOS File Provisioning plugin should have a configuration option to specify what its preference is if the data object has more than one url. Currently, the plugin just takes the first url that a Dockstore file provisioning plugin supports.

The simplest option would be to specify protocols in order of preference, e.g., prefer s3 over gcs, or vice-versa.

More complex options could try to specify a regional preference, assuming we could determine a region from the URLs, e.g., prefer us-west over us-east.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-14)
┆Issue Number: DOCK-14
┆Epic: Improve DOS File Provisioner

**Comment by cricketsloan** [comment]
➤ Ryan Bautista commented:

Note to self:

PRs to Dockstore will not be reviewed until Denis comes back from vacation. Cannot move forward with new PR to official DOS plugin repo due to code changes in Dockstore that need to be reviewed first.
