### ISSUE TITLE
Can get to a null Dockerfile being displayed

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1485]
### Expected behaviour

A warning message like "No Dockerfile found" 

### Actual behaviour

When registering an example of a seven bridges tool with no Dockerfile (not the best example admittedly), I got into the following situation. 

![screenshot from 2018-06-11 15-42-20](https://user-images.githubusercontent.com/1730679/41253410-3a24917a-6d8e-11e8-9f12-40b9e1690a3b.png)

### Settings
![screenshot from 2018-06-11 15-42-25](https://user-images.githubusercontent.com/1730679/41253391-2d428124-6d8e-11e8-98d9-442c992685ce.png)
![screenshot from 2018-06-11 15-42-30](https://user-images.githubusercontent.com/1730679/41253375-20a31456-6d8e-11e8-81c1-47b75d1eb00f.png)

**Comment by agduncan94** [comment]
This is for the hotfix right?

**Comment by denis-yuen** [comment]
Yep, I wouldn't consider it blocking because it really didn't have a Dockerfile.

**Comment by denis-yuen** [comment]
Seems to no longer occur
