### ISSUE TITLE
TRS /tools filters

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1486]
### Expected behaviour
All filters available should be functional

### Actual behaviour
Filtering by ID does not work.  Returns empty array.  Same ID can be applied to /tools/{id} and still work

**Comment by denis-yuen** [comment]
Filtering needs a revamp. See also https://github.com/ga4gh/tool-registry-service-schemas/issues/38
and I should be able to search for checkers

**Comment by denis-yuen** [comment]
Note to implementer, may want to keep an eye on https://github.com/ga4gh/workflow-execution-service-schemas/pull/33#discussion_r195622300 as it evolves and take inspiration

**Comment by agduncan94** [comment]
This works in develop.
