### ISSUE TITLE
CWL Viewer DAG Blocked if Dockstore DAG Can't Render

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1487]
## Bug Report

In staging, if you are in `My workflows`, if there is an error, you can end up in  a state when the Dag tab is showing a CWL Viewer DAG for the previous workflow.

1. Go to staging.dockstore.org, logging in with an account that belongs to BD2KGenomics organization.
2. Navigate to https://staging.dockstore.org/my-workflows/github.com/BD2KGenomics/dockstore_workflow_cnv
3. Click on DAG tab, then click on `Common Workflow Language Viewer` radio button. You see a DAG for that workflow.
4. In the left panel in the BD2KGenomics org, while still on DAG for the previous workflow, click on `dockstore_workflow_snps`. You will see error messages, but you will also see a DAG (screenshot below). Also note the `Classic`/`Common Workflow Language Viewer` radio buttons are missing.
5. If you navigate directly in the browser to https://staging.dockstore.org/my-workflows/github.com/BD2KGenomics/dockstore_workflow_snps, click on DAG tab, you'll only see the error messages.

This probably means that:

1. Because we were on the CWL Viewer DAG in step 3, we were able to see the DAG in step 4.
2. But if you go directly, then it looks like if there is an error rendering the classic DAG, it doesn't even try to render the CWL Viewer DAG.

I would also be worth investigating in a separate issue why the classic DAG cannot render something for this workflow, but the CWL Viewer  can.

![screen shot 2018-06-11 at 3 05 40 pm](https://user-images.githubusercontent.com/1049340/41259584-fb7bb0fc-6d88-11e8-8d2d-15b93a8c7214.png)

┆Issue is synchronized with this [JIRA Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-18)
┆Issue Number: DOCK-18

**Comment by denis-yuen** [comment]
Seems more robust, also the classic DAG display seems more robust 
Thanks @agduncan94  
The only CWL example I could find the external viewer working and the classic not working was https://staging.dockstore.org/workflows/github.com/BD2KGenomics/dockstore_workflow_snps:master?tab=dag so I'm going to assume that this worked
