### ISSUE TITLE
Convenience link to github

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1489]
### Desired behaviour

Links out to GitHub can be versioned based on the current version selected. 
i.e. rather than link to https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker we can link to https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker/tree/2.0.4 if we're looking at 2.0.4 of that tool/workflow

**Comment by denis-yuen** [comment]
While we're at it, we need a more prominent place to display links to the TRS version of a tool/workflow for use by integrators

**Comment by agduncan94** [comment]
@denis-yuen Where do we want the TRS links? Would this be in the info tab?

**Comment by denis-yuen** [comment]
I think that would be reasonable if we have the room.

**Comment by agduncan94** [comment]
We use this link https://dockstore.org:8443/static/swagger-ui/index.html#/GA4GH/toolsIdGet1 ?

**Comment by agduncan94** [comment]
Would we just be displaying the link, or displaying text which links to the TRS endpoint (and opens in a new tab)

Like
TRS: #workflow/workflow_path

or 

TRS: https://dockstore.org...{version_id}/descriptor

**Comment by denis-yuen** [comment]
I think displaying text which links to the endpoint, full URL is likely to be long and unwieldy

**Comment by denis-yuen** [comment]
Working on staging with
DockstoreAPI - 1.5.0-alpha.6
DockstoreUI - 2.2.0-alpha.4

**Comment by garyluu** [comment]
Breaks everything that requires providerUrl: commitID and cwl viewer DAG.  I'll work on this

**Comment by denis-yuen** [comment]
Links look functional on
 DockstoreAPI - 1.5.0-alpha.7
DockstoreUI - 2.2.0-alpha.5
