### ISSUE TITLE
Hook up WDL metadata display to GUI

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1490]
### Desired behaviour

Display WDL description, email, author ala CWL

**Comment by denis-yuen** [comment]
This might be more testing than anything. 
If things go well, this should just work.

**Comment by garyluu** [comment]
seems to work for workflows:

![image](https://user-images.githubusercontent.com/24548904/41625482-f7bbc01a-73e6-11e8-8272-ac5b433bab8c.png)

and for tool:

![image](https://user-images.githubusercontent.com/24548904/41664525-ecf4f6fa-7473-11e8-98d6-c4bb23465072.png)

**Comment by denis-yuen** [comment]
Changing this to a documentation ticket

**Comment by denis-yuen** [comment]
Ah, didn't realize this was done already (which is good) 

Some improvements: 
* Headers on the left are messed up, WDL instructions are nested under https://docs.dockstore.org/docs/publisher-tutorials/best-practices/#recommended-cwl-fields
* let's get some screen shots and description along the lines of "if you want this info to show up for tool/workflow details, then you need to do 'this'' to motivate things
* also mention how this all ties into search

**Comment by denis-yuen** [comment]
I think this is sufficiently done on the documentation branch
