### ISSUE TITLE
Last modified not being set for entries

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1492]
For non-hosted entries it is set during refresh.

**Comment by denis-yuen** [comment]
Post 1.5.0-alpha.4

**Comment by denis-yuen** [comment]
Doesn't seem to be working with 

Working on staging with
DockstoreAPI - 1.5.0-alpha.6
DockstoreUI - 2.2.0-alpha.4

**Comment by denis-yuen** [comment]
Actually, probably needs clarification. 
I can see that lastUpdated is being returned. But last_modified and last_modified_date are null with both hosted workflows and workflows from gitlab/bitbucket.

Need to determine which value is being used in the UI and why lastUpdated is being populated without the rest (and does that make sense)

**Comment by garyluu** [comment]
For GitLab, HostedWorkflow, and Bitbucket...lastUpdated and last_modified_date have a sane date.  last_modified has a really strange date (sometimes negative) but is not used in UI2.

Hosted workflows initially has null for last_modified and last_modified_date until a file is added.

**Comment by denis-yuen** [comment]
I'm ok with the first sentence. 
We need a patch to set the dates for last_modified_date for creating workflows.

**Comment by agduncan94** [comment]
Works on staging.
