### ISSUE TITLE
License on the Swagger UI page is LGPL

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1494]
## Bug Report

The license on the [Dockstore Swagger UI](https://dockstore.org:8443/static/swagger-ui/index.html) is LGPL. The license in the [source code](https://github.com/ga4gh/dockstore/blob/develop/LICENSE) is Apache 2.

Note the that license displayed in Swagger UI comes from dockstore-webservice/src/main/java/io/dockstore/webservice/resources/Description.java

Shouldn't they be the same, or is there some reason for them to be different?

**Comment by denis-yuen** [comment]
We used to use LGPL, this is just out of date and should be fixed to display Apache 2.
