### ISSUE TITLE
Display platform verification information

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1495]
### Desired behaviour

Create a mockup for evaluation and then an implementation of how to display information coming from the GA4GH testbed. See #1476

**Comment by denis-yuen** [comment]
Note: should end with a tutorial and a PR to https://github.com/Sage-Bionetworks/synapse-orchestrator

**Comment by agduncan94** [comment]
Where can I find the tutorial for verification?

**Comment by garyluu** [comment]
https://github.com/Sage-Bionetworks/synapse-orchestrator/pull/29

**Comment by agduncan94** [comment]
It works, created this as a related issue though https://github.com/ga4gh/dockstore/issues/1665.
