### ISSUE TITLE
UI tests should not depend on other test sets

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1497]
Currently some tests between files depend on each other. For example some tests expect a checker workflow to be added by another test before they are run in order to pass. We should really make it so that the only tests that depend on each other are in the same describe block/file.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-359)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-359

**Comment by denis-yuen** [comment]
Also look into tests that take a long time and fail locally (mostly for redirects)

**Comment by denis-yuen** [comment]
See also https://github.com/cypress-io/cypress/issues/390#issuecomment-404491057

**Comment by denis-yuen** [comment]
Not really a reviewable ticket
