### ISSUE TITLE
TRS catch-up

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1501]
### Desired behaviour
There are a few TRS issues that are falling through the cracks. 
Evaluate and/or implement 
- https://github.com/ga4gh/tool-registry-service-schemas/issues/39
- https://github.com/ga4gh/tool-registry-service-schemas/issues/38
- https://github.com/ga4gh/tool-registry-service-schemas/issues/37

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-360)
┆Issue Number: DOCK-360

**Comment by denis-yuen** [comment]
See also https://github.com/ga4gh/dockstore/issues/1395

**Comment by agduncan94** [comment]
ToolDescriptor of a language doesn't seem to be implemented for issue 39 @garyluu

**Comment by cricketsloan** [comment]
We now have the TRS tickets in Jira, do you still want this ticket [~denis.yuen]
