### ISSUE TITLE
Evaluate remaining migration steps for Angular 6

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1505]
### Desired behaviour

As discussed, spend a couple of hours seeing how much of the Angular 5 compatibility layer can be removed and what progress can be made before reassessing.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-361)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-361

**Comment by garyluu** [comment]
Remaining items to update are ngx-sharebutton, ng2-ui-auth, swagger codegen.

**Comment by denis-yuen** [comment]
Not really testable by an end-user
