### ISSUE TITLE
Takeout option for hosted workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1510]
### Desired behaviour

We will need a few options to get hosted workflows out of Dockstore and into git. 
The first low hanging fruit will be an option to download a version of a workflow as a zip file.

**Comment by denis-yuen** [comment]
Should be versions, if the code is general enough (which it can be)
Just made this available for all.

**Comment by agduncan94** [comment]
Should this include test jsons too?

**Comment by denis-yuen** [comment]
Yup

**Comment by denis-yuen** [comment]
Some thoughts:

### Option using only client code
https://stackoverflow.com/a/43133108/6669573
(might be worth looking into first before a more sophisticated solution)

### Some reading on signed URLs on AWS
https://docs.aws.amazon.com/AmazonCloudFront/latest/DeveloperGuide/PrivateContent.html
(overkill due to workflow size probably)

### Google Drive
https://security.stackexchange.com/questions/29449/how-unlikely-is-it-that-a-google-doc-link-is-guessed

### From gist.github.com
1) gist.github.com is relying on the security by obscurity approach
2) Obscurity is on two levels, version and entry (i.e. the entry string doesn't change, the version string does, both are 
3) URLS do not seem to expire

**Comment by kghosesbg** [comment]
The old ways are the best! Frankly I would be happy if Dockstore was basically an ftp server that yielded tar/zip files that unarchived into the desired directory structure with a README. For me Dockstore's great value is in:

1. Being a durable store for versions
    - Easy to get a particular version
    - Easy to see a progression of versions and authors
2. Being self-contained
    - A workflow uploaded here (barring the Docker image) is self sufficient
    - A good (but expensive) value add would be to have an image server too
3. Having some commentary around the workflows
    - Howtos
    - notes
    - parameter sets for particular use cases
    - nice visualization of the DAG

For 3. Dockstore could be a thin webserver + database layer on top of the basic ftp service.

**Comment by denis-yuen** [comment]
Resulting zip structure looks a bit weird with nested files.
For example for, I'd expect test.zip but instead I get the y0wldioB.zip (the name could probably be better too).  Unzips properly though, so this is low priority. 
 
![screenshot from 2018-07-20 16-02-08](https://user-images.githubusercontent.com/1730679/43022772-5ca53c4c-8c36-11e8-9630-b54add144e70.png)

**Comment by denis-yuen** [comment]
Punting it back to track the paths issue from above

**Comment by denis-yuen** [comment]
Paths are fixed as of 
```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```
