### ISSUE TITLE
Back-button seems broken in odd ways

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1514]
### Expected behaviour

While viewing a tool or workflow, a single back-click brings you to the Tools or Workflows listing. 

### Actual behaviour
 
I need two or three to go back from the auto-selected tab to the listing. 

DockstoreAPI - 1.4.4
DockstoreUI - 2.1.4

**Comment by agduncan94** [comment]
This seems to be the solution https://angular.io/api/common/Location#replacestate

**Comment by denis-yuen** [comment]
This is working on staging as of 
DockstoreAPI - 1.4.5
DockstoreUI - 2.1.5
