### ISSUE TITLE
Common Workflow Language Viewer repeated calls

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1518]
### Expected behaviour
If the Common Workflow Language Viewer is not selected, there shouldn't even be any POST or GET view.common.cwl calls.  It fails to get the image (because the cwl tool version is not supported), stop calling the GET method.  Additionally, possibly stop the GET calls when the page changes.

### Actual behaviour
going to https://staging.dockstore.org/workflows/github.com/h3abionet/h3agatk:1.0.1?tab=dag (2.2.0-alpha.3) results in the maximum calls even though the response is 

```
cwltoolStatus | ERROR
-- | --
message | Tool  definition failed initialization: Tool definition  file:///data/git/e9cccbaa54f2e73180bf13e2ae02cf2af4df51f7/tools/picard-CreateSequenceDictionary.cwl  failed validation:   The CWL reference runner no longer supports pre CWL v1.0 documents.  Supported versions are:    v1.0   v1.1.0-dev1 (with --enable-dev flag only)
```

┆Issue is synchronized with this [JIRA Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-20)
┆Issue Number: DOCK-20

**Comment by coverbeck** [comment]
Initial notes:

See https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/workflow/dag/cwl-viewer/cwl-viewer.service.ts#L105

1. I wasn't expecting it to return a 200 (success) with an error message inside it.
2. I did want to eagerly request the image so that there was no delay when you clicked on the radio button, but maybe we shouldn't be doing that.

**Comment by denis-yuen** [comment]
I think the eager request is fine, my understanding is that they have a queue for requests, so eventually everything on Dockstore should be known to their their system. The odd part was the frequency of the requests (so maybe it should be turned down to once per second, say) and I think we noticed persisting when browsing away to a different workflow (or tool even).

**Comment by garyluu** [comment]
Looks fine to me, minimal calls every time we look at the DAG
