### ISSUE TITLE
Quieter openapi conversion script with Mac compatibility

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1529]
### Desired behaviour

As encountered in #1526, I'd like a swagger to openapi conversion script that is compatible with Mac OS but is quiet.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-26)
┆Issue Number: DOCK-26

**Comment by denis-yuen** [comment]
(not sure if @cricketsloan is really on the ball or the bot somehow detected this is related to something even through the linked issue doesn't seem to be?)

**Comment by coverbeck** [comment]
It's a bot that syncs everything that is assigned to me with our JIRA. :)

**Comment by denis-yuen** [comment]
I feel like this opens up some avenues for abuse of your JIRA ;)

**Comment by denis-yuen** [comment]
Going to assume this is working since I don't see a lot of output in Travis and @coverbeck has been working on Mac
