### ISSUE TITLE
The sharedflows endpoint should return a map

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1532]
## Feature Request 

The new `workflows/shared` endpoint returns an array of workflows that have been shared with the user.

It should instead return a map of workflows, where each key is a role, and the value is a list of workflows that have been shared for that particular role.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-28)
┆Sprint: Lighthouse Sprint 29 Cabrillo
┆Issue Number: DOCK-28

**Comment by denis-yuen** [comment]
One related ticket. When getting on specific workflow, we should also return the role you have in relation to it.

**Comment by coverbeck** [comment]
After further discussion, will instead add a synthetic field to the workflow that indicates the requester's role. This field will also be surfaced when fetching a single workflow.

**Comment by cricketsloan** [comment]
➤ Cricket Sloan commented:

This ticket is done on the UCSC side, but still in testing in the Dockstore side

**Comment by denis-yuen** [comment]
This seems functional on staging with 
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
