### ISSUE TITLE
Better error messages for invalid vs. nonexistent method versions

### ISSUE THREAD

**Issue by ansingh7115** [ga4gh/dockstore#1533]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

### Expected behaviour
When trying to hit the GET WDL descriptor endpoint, if we get a 404 we want error messages to be specific to the cause of the of the 404. We want the user to know if the 404 was the result of the method version is invalid or doesn't exist at all.

### Actual behaviour
Currently, the user can't tell why they're getting a 404.

### Steps to reproduce the behavior 
This is a method version that is invalid: https://dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2Fgithub.com%2FHumanCellAtlas%2Fskylab%2FHCA_SmartSeq2_wdl_checker/versions/10x_v0.1.0/WDL/descriptor
This is a method version that doesn't exist:
https://dockstore.org:8443/api/ga4gh/v1/tools/%23workflow%2Fgithub.com%2FHumanCellAtlas%2Fskylab%2FHCA_SmartSeq2_wdl_checker/versions/doesnt_exist/WDL/descriptor
Both error pages look the same.

**Comment by garyluu** [comment]
https://staging.dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FHumanCellAtlas%2Fskylab%2FHCA_SmartSeq2/versions/10x_v0.1.0/plain-WDL/descriptor//pipelines/smartseq2_single_sample/ss2_single_sample.wdl  not found.
https://staging.dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2FHumanCellAtlas%2Fskylab%2FHCA_SmartSeq2/versions/potato/plain-WDL/descriptor//pipelines/smartseq2_single_sample/ss2_single_sample.wdl also not found

Don't see a linked PR. wrong column?

**Comment by garyluu** [comment]
shows `Not Found : version found, but file not found (bad filename, invalid file, etc.)`
and 
`Not Found : version not found` now
