### ISSUE TITLE
Add Launch with DNAnexus button

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1537]
## Feature Request 

Add a `Launch with DNAnexus` button, similar to `Launch with FireCloud/DNAstack` buttons.

Should only be present for WDL.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-29)
┆Sprint: Lighthouse Sprint 30 Danns
┆Issue Number: DOCK-29
┆Epic: Aim 2: Cloud Execution Integration

**Comment by denis-yuen** [comment]
@coverbeck can you confirm that this is for WDL? 
I noticed that the precision FDA tools (note tools, not workflows) that were exported to Dockstore are in CWL. 
https://dockstore.org/search?namespace=pfda2dockstore&searchMode=files

Do they have the ability to convert from arbitrary WDL to CWL?

**Comment by coverbeck** [comment]
@denis-yuen Confirmed that it is for WDL. I asked them on the call yesterday. They have their own infrastructure for compiling and running WDL.

The Precision FDA work is a separate effort.

**Comment by denis-yuen** [comment]
@coverbeck do you have more clarity on their relationship? Feel free to bring this to Slack

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

DNANexus currently supports file-path import statements, but does not yet support http(s) imports. But http(s) support is coming soon.

**Comment by denis-yuen** [comment]
Weird, that's like the reverse of Firecloud
ex:  https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info

Maybe we need symbols for the n choose 2 combinations

**Comment by coverbeck** [comment]
Update: DNANexus now supports both file-path and http(s) imports.

**Comment by coverbeck** [comment]
It's also possible they may not work with our staging environment. At one point they said that they would only work with whitelisted domains, and they had only whitelisted dockstore.org.

On the other hand, I think I saw it working with my local build, so that may not apply any more, but I will investigate.

**Comment by coverbeck** [comment]
I think #1023 might be part of problem; the link is now: `https://platform.dnanexus.com/panx/tools/import-workflow?source=https://staging.dockstore.org:443/api/api/ga4gh/v2/tools/%23workflow%2F%2Fhaplotypecaller-gvcf-gatk4.wdl/versions/1.0.1`

Notice how `api` is there twice.

**Comment by garyluu** [comment]
In the dockstore-ui2/src/app/shared/constants.ts file, there's a '/api/ga4gh/v2' , yet the API_URI also has it

**Comment by denis-yuen** [comment]
The repeated api is unfortunately legit (but can be changed). 
Initially we had https://dockstore.org:8443/api/ga4gh/v2/metadata but in #1023 it turned out places were blocking 8443, so I added 
https://staging.dockstore.org/api/api/ga4gh/v2/metadata (no port)

**Comment by coverbeck** [comment]
This means the TRS link on the info tab is incorrect as well (has two api).

**Comment by denis-yuen** [comment]
(The info tab link it actually correct)
Consider https://staging.dockstore.org/api/containers/published?limit=100&sortCol=stars&sortOrder=desc for example, our endpoints are under `api`. What I didn't notice till after it was working was that the GA4GH api is namespaced using `api` so it looks doubled for those URLs

**Comment by denis-yuen** [comment]
URL generated seems legit with
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
