### ISSUE TITLE
Authorization delegation

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1539]
Clients should be able to provide keys for the store to be used.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-30)
┆Issue Number: DOCK-30
┆Epic: Improve DOS File Provisioner

**Comment by denis-yuen** [comment]
Note to self: I think this is for the use of Google tokens with Dockstore, when users lack a Dockstore account

**Comment by coverbeck** [comment]
This is for the DOS File Provisioner plugin, which only supports non-authenticated calls.

**Comment by cricketsloan** [comment]
This may come back if DRS takes off.
