### ISSUE TITLE
Nullpointer Exception for sourceCodeRepoInterface during refresh all tool

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1541]
## Bug Report
https://github.com/ga4gh/dockstore/blob/f45af28f5666a43278aa4f007bceac1cadb5ef89/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/AbstractImageRegistry.java#L325

causes a null pointer exception when sourceCodeRepoInterface is null

### Expected behaviour
Refreshing all tools should simply refresh all tools

### Actual behaviour
500 error due to null pointer exception

### Steps to reproduce the behaviour
Check out develop branch, clean db, create mode, refresh all tools

**Comment by agduncan94** [comment]
Fixed.
