### ISSUE TITLE
Convert command for HCA 

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1549]
### Expected behaviour

Should generate a proper input json in both cases

### Actual behaviour

```
$ ./dockstore workflow convert entry2json --entry github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore
dockstore needs to be on PATH for certain commands to work (like --upgrade)
null
null
$ ./dockstore workflow convert entry2json --entry github.com/HumanCellAtlas/skylab/HCA_SmartSeq2_wdl_checker:dockstore
dockstore needs to be on PATH for certain commands to work (like --upgrade)
null
null

```

**Comment by denis-yuen** [comment]
In my experiments with a version of this fix cherry-picked to develop, I encountered this problem with the checker workflow, but not the underlying workflow. 

Please check that this is functional for both, first in the hotfix and then in develop.

**Comment by denis-yuen** [comment]
Before I forget, one of the tests was in your personal account rather than the dockstore-testing account.

**Comment by denis-yuen** [comment]
Touching base with @garyluu 
This works with the hotfix for the underlying workflow, but not the checker workflow. 
In my experiments on develop, I had the same results.

**Comment by agduncan94** [comment]
Working on API 1.5.0-alpha.7 and UI 2.2.0-alpha.5
