### ISSUE TITLE
Missing versions for Nextflow workflow

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1551]
### Expected behaviour

Drop-down versions match the versions in the versions table. 

### Actual behaviour
Drop-down seems to display a different listing than the versions table (a subset including only the numerical versions).

![screenshot from 2018-06-27 15-26-10](https://user-images.githubusercontent.com/1730679/41995088-82815f7e-7a1e-11e8-97e9-bd59ad80f4fe.png)

ui2 version was commit 62c622bff2784ae1657364fb66b841c37ae8dcc3

**Comment by garyluu** [comment]
Also missing versions for https://staging.dockstore.org/my-workflows/github.com/garyluu/skylab

DockstoreAPI - 1.5.0-alpha.4
DockstoreUI - 2.2.0-alpha.3

WDL workflow

**Comment by denis-yuen** [comment]
Working with 
DockstoreAPI - 1.5.0-alpha.6
DockstoreUI - 2.2.0-alpha.4
