### ISSUE TITLE
Default version selected first in mytool/myworkflows

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1553]
### Expected behaviour
After refreshing, setting default version, or going somewhere else and coming back to your own workflow in mytools/myworkfows, etc, the default version should be the first one that's selected.
e.g. https://staging.dockstore.org/my-workflows/github.com/garyluu/example_cwl_workflow should go to my default version which is "master".  worst case it should stay on the previous branch selected.

### Actual behaviour
It goes to some other version (always the same version, not sure exactly why) instead

### Steps to reproduce the behaviour 
- Go to my workflows
- Have a workflow with many version
- select a version that's not currently selected
- set it as default version

The version is now swapped back to the initial version for some reason

**Comment by denis-yuen** [comment]
Seems functional on staging with 
 DockstoreAPI - 1.4.5
DockstoreUI - 2.1.5
