### ISSUE TITLE
epam pipeline builder

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1557]
### Desired behaviour

Consider the epam pipeline builder as another optional visualizer for WDL workflows
Along the lines of the common cwl viewer as an optional for how to visualize CWL   ( see https://dockstore.org/workflows/github.com/ICGC-TCGA-PanCancer/pcawg-minibam:1.0.0?tab=dag )

See the epam pipeline builder running at http://pb.opensource.epam.com/

Repo is at https://github.com/epam/pipeline-builder

See also #1545

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-90)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-90
┆Epic: Alternative Visualization WDL

**Comment by denis-yuen** [comment]
![screenshot from 2018-09-04 15-42-04](https://user-images.githubusercontent.com/1730679/45053839-31ddd680-b059-11e8-9b44-7e8f5fb44dce.png)

Similar to the above, I'd like to see a Classic option with our existing WDL visualization and an option for epam that displays the epam version plus a link out to fully see it on their site. Looks like a MIT license so we probably would have to add their license to a UI equivalent of https://github.com/ga4gh/dockstore/tree/develop/THIRD-PARTY-NOTICES

**Comment by agduncan94** [comment]
Working on:
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0

What is interesting is that some workflows we are able to parse and say are valid are not valid to the EPAM WDL. Perhaps this is due to use assuming draft-2 for parsing.
