### ISSUE TITLE
Test parameter files requested for every version

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1564]
### Expected behaviour
All test parameter files should not be pulled in for every version upon visiting a workflow/tool version.  Only the version that's currently being looked at should have test parameter files.

### Actual behaviour
All test parameter files are requested for every version when visiting any version of a tool/workflow.  Lots of network requests.  

42 test parameter files requests upon visiting https://dockstore.org/workflows/github.com/HumanCellAtlas/skylab/HCA_SmartSeq2:dockstore?tab=info

**Comment by denis-yuen** [comment]
Can confirm that only the current test parameter file is requested on 

DockstoreAPI - 1.5.0-alpha.7
DockstoreUI - 2.2.0-alpha.5
