### ISSUE TITLE
Hosted workflows + permissions feedback

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1572]
This is just a grab-bag of feedback for the in-memory implementation + gui2 for permissions as of 423bd67abc07141dbbf9817528adf034c8c27090

Overall looks good, some thoughts below (not necessarily constrained to permissions)
FYI @agduncan94 @coverbeck 

1. ~It isn't obvious what permissions I have on a workflow unless I'm an owner. A minimum fix might be to display the permissions tab but disabled. Better ideas welcomed~ broken out to #1608
2. Validation errors fail in a non-obvious way ('Save version failed"). Best to relax validation until we can pass useful feedback back to the user (made minimally better with https://github.com/dockstore/dockstore-ui2/pull/337)
3. ~PATCH method for editing workflows needs to be more robust (saw odd duplicate constraint issues). This might be after validation errors above when writing an incorrect WDL. 
  a) Investigation reveals that this was not a webservice issue. Instead, when creating a new hosted workflow while one is selected (using `+`), the current files are carried over and will be used in the new workflow. This can carry over WDL files into a new CWL hosted workflow as the most glaring and obvious case for testing~
4. ~Tab selection carries over when clicking between workflows (which is good), but gets into an odd state if I click from one workflow with permissions to one without~
5. ~Probably an issue with the in-memory implementation, but as a user with a workflow shared to me with owner permissions. I can casually change my permissions to writer or reader. This probably needs a warning. Second, I seem to still be able to edit permissions after giving away my owner permission but before a refresh, but this might be a in-memory glitch~
6. ~This might be an issue with the labels endpoint. I can edit labels for a workflow with only reader permission.~
7.  ~After creating a workflow, I don't see myself as an owner which is a bit odd but probably has to do with us having two concepts of ownership (ownership via sam and ownership via db users collection)~
8. ~Need to follow-up with idea of namespace obfuscation to avoid leaking email addresses via workflow names~ Broken out into #1645 
9. ~Past 9 revisions, hosted workflows do not auto select the 10,11th versions when they are created by editing files~
10. ~Files re-order while editing (might be a server thing and fixed server size). Found by editing test.cwl, test2.cwl, and Dockstore.cwl for 9~ addressed in web service
11.  ~Link outs to visualizers like cwlviewer will need to be disabled for hosted workflows~
12. ~Publish button for shared workflows can be pressed but doesn't update (actual workflow is published)~
13. ~What happens with nested folder names with hosted workflows? (this is a request to test out adding a workflow that uses folders to hosted workflows and then trying it out via launching or download)~

**Comment by agduncan94** [comment]
1. I like the idea of adding a tag of some sort (reader/writer/owner)
2. I think in general we need to clean up our error messages and regular messages to be more informative
3. Is the duplicate constraint for when the files have the same path?
4. I think we should just select the info tab on workflow change
5. This brings up the question, should an owner be able to change their permissions at all? I think yes, but am not completely sold on that.
6. Hm I think that is an oversight and should only be for people with write permission.
7. Ya we need a better word to distinguish being in the users array of an entry vs being given owner privileges.
8. No new thoughts on this yet.

**Comment by denis-yuen** [comment]
3. No, oddly enough it was a foreign key constraint. The failure might have left things in an odd state
4. That would work too
5. I don't feel strongly about this. If it takes time to work out the edge cases, I'm fine with making it that if you're the original owner, you can't ditch your own ownership (but then how do we tell who was the original owner, etc. etc.) 
8. I think the agreement in https://docs.google.com/document/d/1z70gH8_VVjEZ-2Z6xttuFtBxj6rHo10CL4dhLeV4Tik/edit?usp=sharing was just to obfuscate it. i.e. workflows would become `dockstore.org/mario@goo.gl/workflow` rather than `dockstore.org/mario@gmail.com/workflow` or comparable substitute for `goo.gl`

**Comment by coverbeck** [comment]
5. Currently the only test is to make sure you're not the last owner. Which now that I think about it is not an iron-proof test, especially since the test is in the UI. I agree that we shouldn't let the original owner ditch their ownership.
7. Agreed, there is some confusion especially with SAM. I'm avoiding creating an entry in SAM unless you explicitly start sharing. It's weird that your name only appears under permissions as a owner after you add somebody else.

**Comment by denis-yuen** [comment]
(FYI threw in a few comments due to numbering issues
https://meta.stackoverflow.com/questions/288910/how-do-i-override-the-numbering-in-lists)

**Comment by denis-yuen** [comment]
5. I agree, we shouldn't let the original owner (as distinct from the last owner) ditch ownership, at least for this phase. Don't want to run into odd situations where the namespace implies you own a workflow, but its not yours, accidentally giving away ownership so no one owns a workflow, conflicts between the Dockstore DB owner and the SAM owner, concurrency issues between SAM and the Dockstore DB, etc. 
7. Was there a reason for avoiding this? Possibly related, I didn't check, but how are we checking that a sole owner for a workflow doesn't see their own workflow in "Shared Workflows"?

**Comment by denis-yuen** [comment]
Reviewing:
3) Seems to be smaller, but still an issue. Ghost files can occur when adding and deleting files, causing 500s

![screenshot from 2018-07-25 14-40-58](https://user-images.githubusercontent.com/1730679/43220793-ee575ab8-9018-11e8-8fc6-537267760823.png)

**Comment by denis-yuen** [comment]
3) still a thing on 
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6

**Comment by denis-yuen** [comment]
Assigning 3, 4, 13 for now

**Comment by denis-yuen** [comment]
Also check on 11

**Comment by agduncan94** [comment]
Links to CWLviewer for hosted workflows is not disabled.

**Comment by coverbeck** [comment]
>>Links to CWLviewer for hosted workflows is not disabled.<<

This made me realize belatedly that CWLviewer should only be enabled for GitHub workflows (no BitBucket, etc.)

I'd overlooked this item; I'll submit a PR today.

**Comment by denis-yuen** [comment]
#2 is taken over by #1729 
I think everything else is clear so I'm closing this out
