### ISSUE TITLE
typescript code style

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1573]
### Desired behaviour

Need a solution similar to codestyle formatting file for Java, except for the ui2. 
Intellij can export/import https://www.jetbrains.com/help/idea/copying-code-style-settings.html for Typescript. Can this be imported/exported from other IDEs via a plugin or similar?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-368)
┆Issue Number: DOCK-368

**Comment by garyluu** [comment]
codestyle and checkstyle combined is the equivalent to tslint.json.  sadly, the most basic feature does not appear to be working right now: https://github.com/palantir/tslint/issues/2814

**Comment by denis-yuen** [comment]
Merge with #2130
