### ISSUE TITLE
Register Workflow Dialog  -- Minor Issues

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1576]
## Bug Report

1. On develop branch, if you click Register Workflow button, the first page of the dialog has a radiobutton that says `Create and Save CWL or WDL on Dockstore.org`.  If you select that radiobutton and click Next, the next page gives you an option to save the workflow as cwl, wdl, or nextflow. Either the first page should also mention nextflow, or the second page should remove Nextflow as an option.
2. Also, for the second page, since CWL and WDL are acronyms, I believe the dropdown should should list them in caps. And have `Nextflow` instead of `nextflow`.
3. After registering the workflow, I would expect that workflow to be selected (it is not).

**Comment by denis-yuen** [comment]
1. Mention nextflow
2. Tentative agree. To be clear the dropdown for "Descriptor Type" yes, the dropdown for "Workflow Path" in the other route, not so much
3. Seems reasonable

**Comment by denis-yuen** [comment]
Functional on 
```
DockstoreAPI - 1.5.0-alpha.7
DockstoreUI - 2.2.0-alpha.5
```
