### ISSUE TITLE
Retrieve CWL/WDL for a particular version of an image

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#158]
It seems like the Dockstore command line doesn't support retrieving a particular CWL/WDL version.  For example, I might likes to do the following:

    dockstore cwl --entry quay.io/collaboratory/seqware-bwa-workflow:2.6.7

And I would expect the CWL for that particular version to be returned.  Instead I get:

    No cwl file found

If I leave off the ':2.6.7' the latest is returned.

This might be a duplicate issue, I thought I submitted this before.

This was tested on hotfix/refresh_aging branch

**Comment by agduncan94** [comment]
What version of the CLI do you have listed at the top of your dockstore binary file?(probably in /usr/bin/dockstore). I have it at 0.3-beta.0, I think if you download through the dockstore UI it may be 0.3-alpha.0.  See if changing the version helps.

I am trying with on the same branch and it is working for me.

**Comment by agduncan94** [comment]
I was not able to reproduce this error.  Below is information regarding the version of dockstore I had.
dockstore - https://github.com/ga4gh/dockstore/compare/hotfix/refresh_aging
dockstore CLI - 0.3-beta.0
