### ISSUE TITLE
Make a button for DNANexus

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1581]
Dockstore will need a Launch with button for DNANexus

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-34)
┆Issue Number: DOCK-34

**Comment by coverbeck** [comment]
It's a duplicate of #1537

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Closed as a dupe of DOCK-29.
