### ISSUE TITLE
Permissions API Cleanup

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1582]
Flowing out of  #1572 as well as some additional discussion:

1. We only create an "entry", either in SAM or "InMemory" once a user starts to share a workflow. If you query the permissions for a workflow that you own/created but has not been shared, nothing comes back. This leads to a confusing UI (and API). In that case, the API should indicate that you are the owner.
2. The original owner should not be able to remove himself/herself as an owner from the workflow.
3. Need to ensure that the`/workflows/shared` endpoint only returns workflows that have been shared with you, and not workflows that you are also the original owner of.
4. Make sure inmemory authorizer behaves the same way as SAM, e.g., don't allow a call to get permissions unless requester is an owner.

This might get trickier for non-hosted workflows, as ownership is determined, I believe, by whomever belongs to the GitHub organization, and so knowing the original owner might not be possible. As opposed to a hosted workflow, where we know who created it.

So the solution for this in the first iteration may only address hosted workflows, which is where we are only enabling sharing to begin with.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-35)
┆Sprint: Lighthouse Sprint 30 Danns
┆Issue Number: DOCK-35
┆Epic: SAM for Authorization

**Comment by denis-yuen** [comment]
For non-hosted workflows, I think we would treat everyone in the GitHub organization as un-removable owners. (i.e. its silly to block them from sharing in Dockstore if they can edit and see the underlying content in GitHub anyway) But I'm happy to leave that to a second iteration. 

For 3, a simplification might be that the `/workflows/shared` endpoint only returns workflows that are not visible in `my workflows` already which is the content from `/users/7/workflows` in other words

**Comment by denis-yuen** [comment]
Seems functional 

1. Owner initially seems to have permissions
2.  Cannot remove self


```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```
