### ISSUE TITLE
My Workflows Page Displays No Workflows if Shared Endpoint Fails

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1588]
## Bug Report

On develop branch, if the call to get shared workflows fails, then no workflows are displayed. The call to get the user's workflows is cancelled.

The call to get the shared workflows was failing for me locally because the webservice was incorrectly making a call to SAM when the user wasn't registered with Google. I will fix that as part of ga4gh/dockstore#1582.

But still logging this because I think `combineLatest` [here](https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/myworkflows/my-workflow/my-workflow.component.ts#L113) and/or [here](https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/myworkflows/my-workflow/my-workflow.component.ts#L127) might need to be updated to handle error cases.

Also might want to consider displaying error messages for failing Ajax calls.

Just wanted to capture this in case this isn't already in progress and deemed necessary.

**Comment by coverbeck** [comment]
I intended it to be separate, but I don't know if it's worth addressing. If the shared workflows endpoint fails for some  reason, the UI won't display any workflows. I guess it depends on the likelihood of the shared endpoints failing but the "regular" endpoint working.

**Comment by denis-yuen** [comment]
I think its worth addressing, with priority based on how serious the problem is 
i.e. does this affect users that are not registered in FireCloud at all or does this only affect users that are registered?

**Comment by coverbeck** [comment]
Right now it will only happen for unexpected errors, e.g., SAM is down or we can't connect to it at all for some other reason, like a firewall rule, or they make a breaking change to their API.

If you get an authorization error with SAM, e.g., because you are not registered with FC, we will return an empty list.

In other words, for unlikely/unexpected events, that still end up occasionally happening.

**Comment by garyluu** [comment]
@coverbeck can you update the combineLatest line numbers?

**Comment by coverbeck** [comment]
@garyluu Updated the description

**Comment by denis-yuen** [comment]
Can confirm that this is working in the case that the sam path is set incorrectly, simulating SAM being down completely. Seeing indefinite waiting if SAM is blocked via AWS security groups, indicating that there might not be a timeout if SAM is up but non-responsive.

Will open a second lower-priority issue
