### ISSUE TITLE
Edit Files not Enabled when User Has Write Permission

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1589]
## Bug Report

With SAM authorizer enabled, if a user has write permissions to a workflow, the Edit Files button is not present.

Looking at the [UI code](https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/workflow/workflow.component.ts#L152), it's because UI is asking for the workflow's permissions on behalf of the user. The problem is that the user does not have permission to view permissions, which is legitimate -- you give a user permission to modify a workflow, but not to modify the sharing settings.

The intended way to figure out from the UI whether the user could edit a workflow is to make an OPTIONS call to `/workflows/hostedEntry/{entryId}` and look at the supported methods.

There is probably a bug with the InMemory authorizer that lets you make the call to get permissions, which is why it may not have come up. I will investigate as part of ga4gh/dockstore#1582.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-37)
┆Issue Number: DOCK-37

**Comment by denis-yuen** [comment]
@coverbeck  Seeing this still in staging.dockstore.org, please confirm

**Comment by coverbeck** [comment]
This works for me locally if I share with a user who has only logged in with Google, and not linked their account with GitHub. If I share with a user who first logged in with GitHub, then I can reproduce the problem. Investigating...

But also seeing 500's in Dev Tools on staging to get permissions that I don't see locally. Not sure what is going on there.

**Comment by denis-yuen** [comment]
This is working for me now on staging, either logged in as a GitHub user with a Google account linked or logged in with Google first.

DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
