### ISSUE TITLE
support for providing paths within git for Dockerfile, Dockstore.cwl, etc 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#16]
+1 this has been requested by UCSC and would allow direct support of tools organized like https://github.com/BD2KGenomics/cgl-docker-lib or https://github.com/common-workflow-language/workflows

**Comment by denis-yuen** [comment]
:+1:

**Comment by briandoconnor** [comment]
Also, you shouldn't require the CWL be named Dockstore.cwl.  Since we're allowing a user to specify a path you should allow anything (although enforcing it ends in .cwl seems reasonable).

**Comment by briandoconnor** [comment]
I think this is done now.  @victoroicr?

**Comment by oicr-vchung** [comment]
Finished in 0.2.1.
