### ISSUE TITLE
Change Permissions API

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1605]
## Feature Request 

1. Get rid of OPTIONS endpoints to indicate whether a user can perform actions
2. Change `/path/workflow/{repository}/permissions` endpoint to:
    1. Return all permissions for a workflow if the requester is the owner
    2. Return the only the requester's permission if the requester has a non-owner permission on the workflow (a non-owner should not be able to see other user's permissions on a workflow).
    3. Throw a 404 if the user has no permission on the workflow.

Also, see discussion in dockstore/dockstore-ui2#346

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-43)
┆Issue Number: DOCK-43

**Comment by coverbeck** [comment]
1. I will have to submit a new PR to SAM to enable writers being able to read permissions from SAM. For now, we'll have to go with my proposal until that PR gets approved, merged, and deployed.
2. I was going to do 404 as a security thing; returning a non-404 when you don't have permissions  indicates that it exists. Looking at the code in the hotfix branch, for example, for fetching a workflow, if you're not an owner, it returns a 403, so maybe we should do that here to be consistent.
3. Good point and memory; yes, will revert that.

**Comment by denis-yuen** [comment]
Looking good
1) No options endpoints
2) Permissions endpoints on other people's workflows seem to work when browsing "Shared With Me"

```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```
