### ISSUE TITLE
Better Handling of Overlapping Permissions of a User

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1609]
## Feature Request 

In the SAM API, you can add the same user to multiple policies on a resource. E.g., you could be both an owner and a writer. I don't believe there is a way to prevent this, but will double check.

1. ~~Dockstore should avoid creating such a scenario. Right now, if a user has read permissions and you give the user write permissions, the user ends up having both. Dockstore should avoid this, e.g., by removing the read permission after it has successfully set the write permission. (Although that could cause some problems if two machines or modifying a user's permissions on the same workflow at the same time).~~ Going to log this separately, as a change was committed to fix the next item, and the commit message refers to item 2 of this ticket, hence the strikethrough instead of just deleting this.
2. Even though Dockstore should (probably) try to avoid this scenario, it should handle it gracefully, as non-Dockstore users can hit the SAM API; right now if you are given both read and write permission to a workflow, the workflow shows up twice as shared workflow.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-46)
┆Issue Number: DOCK-46

**Comment by coverbeck** [comment]
Yes, in SAM a single resource can have multiple policies, and each policy can have multiple users.

The resource corresponds to the workflow, where we have defined 3 policies, Owner, Writer, and Reader. The same email can be added to multiple policies for the same resource.

What happens now is that if `jdoe@example.com` gets added to both the owner and writer policies of the same resource, let's say, and jdoe@example.com then GETs shared workflows, the workflow corresponding to that resource shows up twice.

**Comment by denis-yuen** [comment]
Seems cleaned up as of 
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
