### ISSUE TITLE
Download ZIP of an entry version on the CLI

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1615]
Currently we have a download option for checker workflows on the CLI (not sure if this downloads all files).

We should have a download option for all entries.

**Comment by denis-yuen** [comment]
Also, add download commands (both checker and normal to the ui)

**Comment by agduncan94** [comment]
@denis-yuen this works however when you download zip the filename is null.zip. This is only for workflows, and not for tools.

**Comment by garyluu** [comment]
Works for both tools and workflows.  Adding a few enhancments though...
