### ISSUE TITLE
Error Refreshing My Workflows if Only Logged in with Google

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1617]
## Bug Report

In develop branch, if you are only logged in with Google, refreshing your workflows causes an error to appear in UI.

1. Login with Google (only)
2. Go to My Workflows page. In case it's relevant, I had no workflows of my own, but I did have a workflow shared with me.
3. Click the refresh arrow, you get the following:

```
×
 The webservice encountered an error trying to create/modify.

[HTTP 400] Bad Request: No source control repository token found. Please link at least one source control repository token to your account.
```

Screenshot:

![screen shot 2018-07-17 at 2 53 39 pm](https://user-images.githubusercontent.com/1049340/42847685-a01f94d4-89d1-11e8-9060-339d26cdf965.png)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-75)
┆Issue Number: DOCK-75

**Comment by denis-yuen** [comment]
Hmmm, how did you manage to bypass https://github.com/ga4gh/dockstore/issues/1370#issuecomment-406726202 to test this out anyway?

**Comment by coverbeck** [comment]
I am able to log in with a Google account on both my local instance and on staging. I guess #1370 only happens in certain scenarios?

**Comment by denis-yuen** [comment]
@garyluu were you able to replicate the problem before your fix for it?

**Comment by garyluu** [comment]
Was not able to reproduce, my fix only updates the user profiles upon initial token creation.

**Comment by coverbeck** [comment]
It's still happening for me on staging. Is the fix deployed to staging yet?

**Comment by garyluu** [comment]
No, but you can manually update the user profile in the accounts page.  If the problem still persists, then there may be something else that needs to be done.

**Comment by coverbeck** [comment]
I went to the Account page, clicked `Sync with Google`, and now see my profile picture (I didn't before). Just making sure that's what you meant.

After I do that, I still get the error refreshing workflows.

**Comment by garyluu** [comment]
in that case, something else needs to be done.  I think the profile thing only fixes part of the permissions problem but not refresh all it seems.

**Comment by coverbeck** [comment]
I'll try to reproduce locally to see if I can catch it in the debugger

**Comment by coverbeck** [comment]
I can reproduce locally. I only have a Google token, which is not a source control token, per `io.dockstore.webservice.core.TokenType`.

1. Clicking on refresh invokes `io.dockstore.webservice.resources.UserResource#refreshWorkflows`
2. Which calls `io.dockstore.webservice.resources.WorkflowResource#refreshStubWorkflowsForUser`
3. Which then loops through all of the user's tokens, looking for a source control token.
4. Since my only token is not a source control token, it throws the exception at `io/dockstore/webservice/resources/WorkflowResource.java:239`.

Could fix by not throwing an exception, but I don't know if that would cause problems for other scenarios.

**Comment by denis-yuen** [comment]
To be clear, I was mostly curious how you got past the login issue. 
Setting that aside, I think the website could be more clear or helpful (disable refresh if the user has no sources for a refresh via token?) but the error message isn't the worst.

**Comment by agduncan94** [comment]
I think we should have a better error message, something along the lines of "error: link to a source control to get automatic workflows"

**Comment by coverbeck** [comment]
I still see the Refresh All button, and it is not disabled, when I am logged in with Google only. Clicking it causes the same error as in the description.

**Comment by garyluu** [comment]
are you on develop?

**Comment by coverbeck** [comment]
I'm on staging.dockstore.org. Looks like I incorrectly assumed it had been deployed there.

**Comment by denis-yuen** [comment]
Button disabled  on staging
```
DockstoreAPI - 1.5.0-beta.4
DockstoreUI - 2.2.0-beta.3
```
