### ISSUE TITLE
Listings pages should remember items per page setting

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1621]
## Feature Request 

It would be nice if the listings pages remembered your items per page setting.

### Example

1. Go to workflows page.
2. Set items per page to 20 (it defaults to 10).
3. Click on a workflow to look at it
4. Go back to workflows page. Items per page is back to 10. :(

### Possible Solutions

1. Simple -- store the setting in browser's local storage
2. Complex, that's probably overkill unless lots of other settings come up that are good candidates for this -- have a preferences endpoint(s), tied to the user, so that wherever a user logs in from, the setting is applied.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-377)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-377

**Comment by denis-yuen** [comment]
Note to implementor: this is not a regression, both 1.4 and the current 1.5 develop share this trait

**Comment by garyluu** [comment]
went with the first option, also saved pageIndex (current page number) because why not

**Comment by coverbeck** [comment]
Hmm, this doesn't seem to work for me. Doesn't work for for Search page, and we don't have the workflows and tools pages any more.

**Comment by garyluu** [comment]
It was implemented for workflows and tools page.  So I guess it's irrelevant now.

**Comment by denis-yuen** [comment]
We actually do have workflows and tools page, accessible via sitemap

**Comment by coverbeck** [comment]
@garyluu , for workflows and tools, it only remembers for the duration of the SPA, e.g., if you duplicate the workflows tab, the new tab goes back to the default number of items.

I assume this is the intent, but just making sure, since one of my proposals was to use local storage for the setting.

**Comment by garyluu** [comment]
That was the intent, the local storage seems...unnecessary

**Comment by denis-yuen** [comment]
It would be kinda nice for it to be tied to the user, but let's wait for someone to ask for it.

**Comment by coverbeck** [comment]
Agreed, a preferences API/service that could remember your settings across multiple machines would be ideal, although I don't think we have enough settings to make it worthwhile at this point.

The idea for local storage was somewhere in between persistent preferences and remembering longer than just your current tab/session.

Closing this, and will log one for the search page.

This was tested against 2.3.0-beta.0.
