### ISSUE TITLE
Token copy annoyance in Firefox

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1622]
### Desired behaviour

The Dockstore token always wraps on Firefox requiring three clicks to copy instead of two if using highlight copy (first world problems). Make it not wrap on a decent screen size.
(Does not occur in Chrome)

**Comment by denis-yuen** [comment]
More annoying, triple click introduces a whitespace at the end

**Comment by garyluu** [comment]
new profiles page redesign seems to have the same issue, but at least the triple-click still works

**Comment by garyluu** [comment]
Seems to be fine on production
