### ISSUE TITLE
Avoid leaving duplicate roles

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1625]
## Bug Report

Split off from #1609 

When invoking the SAM API to give a user access to a resource, we add the user to the appropriate policy, but we do not remove the user from any policies the user may already belong to. This will lead to a bug if you are trying to downgrade a user's permissions; if upgrading a user's permissions it will lead to unnecessary noise.

In the UI, with SAM as the authorizerType:

1. Add a a user as a Writer to a workflow, where the user does not yet have any permissions on the resource. In SAM, the user's email is added to the resource's Writer policy roles.
2. Now add the same user's email as a Reader. In SAM, the user's email is added to the resource's Reader policy roles. But the user is not removed from the resource's Writer policy roles, so now the user is both a Writer and Reader. Which means that the user still has write permissions -- the bug.
3. If you had gone the other way instead, first adding the user as a reader, then as a writer, the user would again belong to both policies, again having write permissions, which was intended in this case -- the unnecessary noise.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-50)
┆Sprint: Lighthouse Sprint 31 Eblis
┆Issue Number: DOCK-50
┆Epic: SAM for Authorization

**Comment by denis-yuen** [comment]
This seems functional on staging
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
