### ISSUE TITLE
Adding checker workflow does not update, needs refresh

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1626]
The descriptor type should be carried over from the workflow itself.

**Comment by denis-yuen** [comment]
Seems correct 
```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```

That said, adding a checker workflow doesn't seem to update immediately which can be confusing. 
I had to refresh for the Checker Workflow to show the correct button
Re-naming ticket

**Comment by garyluu** [comment]
Note: The current entry is no longer selected in the sidebar after adding checker workflow

**Comment by denis-yuen** [comment]
Well, one step forward, one step back. 
The button seems to update. But it doesn't actually seem to work until a refresh.

**Comment by denis-yuen** [comment]
Seems functional on 
```
DockstoreAPI - 1.5.0-beta.3
DockstoreUI - 2.2.0-beta.2
```
