### ISSUE TITLE
Console Error When Adding User on Permissions Tab

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1627]
## Bug Report

When adding a user in the permissions tab, there is an error message in the JavaScript console. The operation actually works, and if you didn't have developer tools open, you wouldn't notice the issue. But it's still not good.

### Steps to reproduce the behaviour 

1. SAM authorizer is enabled in Dockstore, although this probably will happen with the InMemory authorizer as well.
2. Go to a hosted workflow
3. Go to the permissions tab
4. Open Chrome Dev Tools (did not try this on another browser).
5. Add a user as a writer or reader (should be one that works, e.g., if using SAM, then the user you are adding should be registered with SAM).
6. User gets added, but you see this in console:

```
PermissionsComponent.html:35 ERROR Error: ExpressionChangedAfterItHasBeenCheckedError: Expression has changed after it was checked. Previous value: 'mat-form-field-should-float: true'. Current value: 'mat-form-field-should-float: false'.
    at viewDebugError (core.js:8445)
    at expressionChangedAfterItHasBeenCheckedError (core.js:8433)
    at checkBindingNoChanges (core.js:8535)
    at checkNoChangesNodeDynamic (core.js:11423)
    at checkNoChangesNode (core.js:11393)
    at debugCheckNoChangesNode (core.js:11997)
    at debugCheckRenderNodeFn (core.js:11951)
    at Object.eval [as updateRenderer] (PermissionsComponent.html:35)
    at Object.debugUpdateRenderer [as updateRenderer] (core.js:11940)
    at checkNoChangesView (core.js:11291)
```

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-51)
┆Sprint: Lighthouse Sprint 31 Eblis
┆Issue Number: DOCK-51
┆Epic: SAM for Authorization

**Comment by coverbeck** [comment]
Looks like: https://github.com/angular/material2/issues/10914

**Comment by garyluu** [comment]
I've seen these ExpressionChangedAfterItHasBeenCheckedError a lot, it's typically an indication that we didn't do something quite right rather than the library.

**Comment by denis-yuen** [comment]
Seems fixed for me  on staging 
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
