### ISSUE TITLE
For a Hosted Workflow, the TRS link's path is null

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1631]
## Bug Report

The actual href for the TRS link on a hosted workflow has the path `null`.

Depending on how you get there, it can also display the previous workflow's TRS link -- if I go to another workflow, hover over the TRS link, then come back to this workflow, and hover over the TRS link, it shows the previous TRS link.

![screen shot 2018-07-20 at 2 34 39 pm 2](https://user-images.githubusercontent.com/1049340/43026512-d92bfb36-8c2a-11e8-87ef-d7086cac6e26.png)

**Comment by denis-yuen** [comment]
Note to implementor: display this only when published rather than use optional auth

**Comment by denis-yuen** [comment]
This seems functional on staging
DockstoreAPI - 1.5.0-alpha.8
DockstoreUI - 2.2.0-alpha.6
