### ISSUE TITLE
docs.dockstore.org search glitches

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1639]
### Expected behaviour
Doesn't seem broken for most seaches, but some seem odd. 
The following searches https://docs.dockstore.org/search.html?query=dockstore.org https://docs.dockstore.org/search.html?query=8443 should at least return 
https://docs.dockstore.org/docs/publisher-tutorials/checker-workflow-trs/

### Actual behaviour

Empty results

**Comment by agduncan94** [comment]
It seems like matches will only occur if searching for a whole word that appears in the middle of a sentence. No substring matching is done.

For example the following will not have any results when you search 8443
test 8443
8443
test8443 test
test 8443test

But below will work
test 8443 test

**Comment by agduncan94** [comment]
Fixed in https://github.com/ga4gh/dockstore/pull/1786

**Comment by denis-yuen** [comment]
Looks functional with queries like 
http://127.0.0.1:4000/search.html?query=dockstore.org
