### ISSUE TITLE
Message for constraints on hosted workflows don't seem to quite work

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1644]
### Expected behaviour

Webservice should reject duplicates

### Actual behaviour

The add hosted workflow dialogue was hanging with no-end. Hit the register button a few times and ended up with duplicates. Verified that they have actual different ids

![screenshot from 2018-07-25 11-25-33](https://user-images.githubusercontent.com/1730679/43211271-257044ac-8fff-11e8-9a6b-1ef789320f66.png)

**Comment by garyluu** [comment]
Not entirely related but...in general, the button that was just hit should be disabled when it's still doing something.

**Comment by denis-yuen** [comment]
Agreed, should be a ui fix as well

**Comment by denis-yuen** [comment]
This seems to be constrained now but the message is not shown

**Comment by agduncan94** [comment]
I seem to still be able to register a tool with a duplicate name.

**Comment by denis-yuen** [comment]
@agduncan94 what do the two records in the database table look like?

**Comment by denis-yuen** [comment]
In discussion: this seems to be a mismatch between the production/staging database and a hibernate created one

**Comment by denis-yuen** [comment]
Constrained and message shown properly

```
DockstoreAPI - 1.5.0-beta.2
DockstoreUI - 2.2.0-beta.0
```
