### ISSUE TITLE
Update Launch nextflow cards

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1648]
### Desired behaviour

Update/replace commands in Launch tab to match Nextflow (aside from "Run with nextflow" which looks up-to-date) but needs testing. 
Is there a nextflow equivalent of a runtime json template?

**Comment by denis-yuen** [comment]
@agduncan94  FYI, if I'm reading https://github.com/nf-core/chipseq/blob/master/docs/usage.md#running-the-pipeline correctly. It looks like the config file https://github.com/nf-core/chipseq/blob/master/nextflow.config#L13 specifies parameters but only a subset are typically used. 

It's not clear to me which parameters should be emphasized when programmatically generating the launch command

**Comment by agduncan94** [comment]
So with Nextflow you can define parameters in the config or the descriptor file. You can set default values here too. You can also override these on the command line when you run the workflow from the command line. This makes it hard to generate some sort of inputs.

Instead I think we should just have ./nextflow run <workflow.nf> -c <nextflow.config>, and specify that users should check the nextflow.config and the workflow.nf file to figure out what inputs are needed. It is not ideal but I think it is good enough for now.

**Comment by agduncan94** [comment]
Actually, after looking through the Nextflow tab, I agree that the **run with Nextflow** looks good. We should remove the first section which talks about the **runtime JSON**. As for the **run locally with dockstore cli** section, do we support basic launch with for nextflow? If yes do we just support it without specifying a parameter file?

The only idea I can think of for a test parameter file for nextflow is having a nextflow.config file as a test parameter file. But that feels wrong. Perhaps there is just no equivalent for nextflow.

**Comment by denis-yuen** [comment]
I agree, it seems there is no parameter JSON equivalent and generating command-line parameters is too broad, so we might just have to explain how to find and set parameters in prose.

**Comment by agduncan94** [comment]
Ignore the above reference, accidentally put it in the wrong PR.

**Comment by denis-yuen** [comment]
![screenshot from 2018-08-14 13-25-02](https://user-images.githubusercontent.com/1730679/44107479-81171314-9fc5-11e8-8450-d803710d39db.png)

Bugged display of getting test json
Displays dockstore launch command and convert commands

```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```

May be dependent on ui2 PR in progress

**Comment by agduncan94** [comment]
This is most likely due to my ui2 PR not going into staging yet. I merged it into develop just after standup.

**Comment by denis-yuen** [comment]
Looks good on 
```
DockstoreAPI - 1.5.0-beta.2
DockstoreUI - 2.2.0-beta.0
```
