### ISSUE TITLE
Enable Automatic Installation of Data Object Service File Plugin

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1654]
1. Need to publish the plugin to the OICR repository
1. Need to add the plugin to plugins.json

I tried doing step 2, which is when I noticed that step 1 is not happening.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-57)
┆Sprint: Lighthouse Sprint 32 Falafel
┆Issue Number: DOCK-57
┆Epic: DOS File Provisioner

**Comment by coverbeck** [comment]
@denis-yuen, Is it documented on how to publish the plugin? I couldn't find anything. 

* Do I need to create a GitHub release in https://github.com/dockstore/data-object-service-plugin? 
* How do I push the plugin to the OICR repository? I haven't even tried, but are there credentials involved, and/or IP whitelisting? I've never published a Maven artifact before.

Thanks,

Charles

**Comment by denis-yuen** [comment]
@coverbeck  
Hmmm, it looks like you haven't had the opportunity to release anything to artifacts.oicr.on.ca yet. 
It looks like we have a couple of options

1) It looks like I have access to straight-up give you a login+password
2) We could publish it on GItHub, update the default plugin list, and potentially modify the plugin downloader to point at it, if it doesn't support that already. 
https://github.com/ga4gh/dockstore/blob/develop/dockstore-client/src/main/java/io/dockstore/common/FileProvisionUtil.java#L233

At this juncture, I think I actually prefer the latter to be more open and reliable.

**Comment by coverbeck** [comment]
Agreed, I like the second option. I'll look into that.

**Comment by denis-yuen** [comment]
Download seems to work, indeterminate progress too
```
DockstoreAPI - 1.5.0-beta.0
DockstoreUI - 2.2.0-alpha.8
```
