### ISSUE TITLE
Can get into weird state where the original owner cannot control sharing

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1657]
### Expected behaviour

The original owner should always be able to control sharing.

### Actual behaviour

Really getting into the weeds now ... 
DockstoreTestUser had `dockstore.org/DockstoreTestUser/test_cwl`, shared owner access to a second user. The second user removed the original owner. 

SAM seems to think that permissions are as follows

As DockstoreTestUser
https://sam.dsde-staging.broadinstitute.org/api/resources/v1/dockstore-tool
```
[
  {
    "resourceId": "%23workflow%2Fdockstore.org%2FDockstoreTestUser%2Ftest_wdl",
    "accessPolicyName": "owner"
  }
]
```

As second user 
https://sam.dsde-staging.broadinstitute.org/api/resources/v1/dockstore-tool
```
[
 {
    "resourceId": "%23workflow%2Fdockstore.org%2FDockstoreTestUser%2Ftest_cwl",
    "accessPolicyName": "writer"
  },
  {
    "resourceId": "%23workflow%2Fdockstore.org%2FDockstoreTestUser%2Ftest_cwl",
    "accessPolicyName": "reader"
  }
]
```

Further attempts to edit permissions via DockstoreTestUser give "Error initializing permissions"

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-59)
┆Issue Number: DOCK-59

**Comment by coverbeck** [comment]
Hmm, I thought I prevented the original owner from being removed, but I guess not.

**Comment by denis-yuen** [comment]
I see 
```
<username> is an original owner and their permissions cannot be modified
``` 

which is good.
