### ISSUE TITLE
Nextflow and hosted workflows?

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1658]
### Expected behaviour

Either we cannot create hosted nextflow workflows (which could make sense since the nextflow cli wouldn't be able to launch them) or we do and it should work. 

### Actual behaviour

ok?

![screenshot from 2018-07-27 15-43-47](https://user-images.githubusercontent.com/1730679/43343425-1d8f04a6-91b4-11e8-8834-ad45f6e1f859.png)

**Comment by denis-yuen** [comment]
See also #1649

**Comment by denis-yuen** [comment]
See also issues with https://staging.dockstore.org/workflows/bitbucket.org/denis_yuen/sarek:2.0.0?tab=files

(UI seems to be generating https://staging.dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fbitbucket.org%2Fdenis_yuen%2Fsarek/versions/2.0.0/nextflow/descriptor/bin%2FconvertAlleleCounts.r instead of https://staging.dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fbitbucket.org%2Fdenis_yuen%2Fsarek/versions/2.0.0/nfl/descriptor/bin%2FconvertAlleleCounts.r

**Comment by denis-yuen** [comment]
Ok, might as well lump in the general dialog box issue here. 

![screenshot from 2018-07-27 16-45-47](https://user-images.githubusercontent.com/1730679/43345719-9021a534-91bc-11e8-9360-b5c4fde76036.png)

I'd like it to display the message from the underlying response
{"code":500,"message":"org.hibernate.exception.ConstraintViolationException: could not execute statement could not execute statement ERROR: duplicate key value violates unique constraint \"partial_workflow_name\"\n  Detail: Key (sourcecontrol, organization, repository)=(dockstore.org, denis-yuen, test) already exists. "}

**Comment by agduncan94** [comment]
So I am in the process of adding hosted nextflow support for workflows and it seems to work. However based on previous discussions we don't want to rush something that might break, so for now we will block the nextflow option from the dropdown when registering hosted workflows.

**Comment by denis-yuen** [comment]
:+1:
