### ISSUE TITLE
Update to newer version of angular

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#166]
Currently Angular JS version 1.4.8 works.  Version 1.4.10 seems to break the code a bit.  The only example I have found so far is with trying to view container details from the containers page.  A tab will not be selected by default, and this will set the tab to be blank.  This is due to an issue with the containerDetail directive and not passing it active-tabs="activeTabs".

**Comment by denis-yuen** [comment]
Seems obsolete, currently running 1.5.7

Currently in test on staging.dockstore.org implemented in https://github.com/ga4gh/dockstore/releases/tag/0.4-beta.5
