### ISSUE TITLE
Clicking between shared workflows does not change selection

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1664]
## Bug Report

Clicking between shared workflows does not change the selection.

The address bar updates, but the content does not, nor does the selection on the left change.

In the screenshot, I clicked on test2, which shows on the address bar, but test6 is selected.

![screen shot 2018-07-30 at 10 36 20 am](https://user-images.githubusercontent.com/1049340/43413347-af32b164-93e4-11e8-963d-f686c00b6792.png)

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-68)
┆Issue Number: DOCK-68

**Comment by denis-yuen** [comment]
Problem seems to be getting worse. I see this on develop as well for normal workflows.

**Comment by denis-yuen** [comment]
FYI, this might have been worked on already

**Comment by denis-yuen** [comment]
Observed together with both shared and non-shared

**Comment by agduncan94** [comment]
Noting duplication with https://github.com/ga4gh/dockstore/issues/1572

**Comment by denis-yuen** [comment]
@agduncan94 
For my part, the mixing up of files between hosted workflows has been resolved on staging.dockstore.org. 
@coverbeck 
Is the address bar not-changing issue still reproducible for you? 
Please close if no longer present

**Comment by coverbeck** [comment]
This works for me in staging.
