### ISSUE TITLE
Platform verification of unpublished tools returns error unauthorized

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1665]
This is misleading, as the only issue is that the tool/workflow must be published. Should have a better error message.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-157)
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 4 Dory
┆Issue Number: DOCK-157

**Comment by Ldcabansay** [comment]
This seems to be already fixed and the error returned is actually 'Not Found', assuming the user has proper permissions (admin/curator) and is trying to verify an unpublished or non-existent workflow. If the user does not enter any token it returns error unauthorized, if the user enters a non-admin/curator token it returns error forbidden.
