### ISSUE TITLE
Tool with only Descriptor and no Dockerfile leads to UI issue

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1673]
### Expected behaviour

Add a Dockstore.cwl to a repo, no Dockerfile. 
Add as a Docker Hub tool with an arbitrary path on Docker hub leading to your legit repo. 
Refresh, should be able to see Dockstore.cwl, a warning due to no Dockerfile

### Actual behaviour

The Files tab displays no content at all.

**Comment by denis-yuen** [comment]
I think it makes sense to display a warning if you try to view the Dockerfile when there isn't. 
I don't think it makes sense to hide the Dockstore.cwl when the Dockerfile is absent. 
I could be convinced that a warning for both could be displayed saying that the version is invalid, but the existing file should be displayed regardless

**Comment by denis-yuen** [comment]
FYI, double check

**Comment by garyluu** [comment]
Looks like this nowadays:

![image](https://user-images.githubusercontent.com/24548904/44173402-cf269a00-a0ad-11e8-9a81-4ffbdd5ee31e.png)

File is displayed even though version is invalid.  Warning about invalid version is displayed too.

**Comment by denis-yuen** [comment]
Looks good on 

```
DockstoreAPI - 1.5.0-beta.2
DockstoreUI - 2.2.0-beta.0
```
