### ISSUE TITLE
Replace legacy refreshing alerts

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1680]
### Desired behaviour
Replace all refreshing alerts with the Angular material progress bar...but it would only be better for short refreshes where the user doesn't necessarily need to read anything for more info.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-388)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-388

**Comment by agduncan94** [comment]
Works on
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0
