### ISSUE TITLE
For API calls with Google tokens, should match against Profile email

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1684]
## Bug Report
In [SimpleAuthenticator](https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/SimpleAuthenticator.java#L71), when a call is made with a Google access token, we are looking for an existing user based on `User.username`. Because the username could be a GitHub username, depending on the order in which a user signed in/linked their accounts, we should instead be looking for in the User.Profile and comparing the email against that.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-61)
┆Sprint: Lighthouse Sprint 32 Falafel
┆Issue Number: DOCK-61
┆Epic: SAM for Authorization

**Comment by garyluu** [comment]
User Profiles are not unique, usernames are supposedly unique (though not checked)

**Comment by coverbeck** [comment]
Can there be multiple User Profiles, with the key `TokenType.GOOGLE_COM.toString()`, that have the same email? If so, would that be through this scenario:

1. User signs in for first time with GitHub username `iamgithub`
2. User logs out
3. User signs in for first time with Google
4. User logs out
5. User logs in again with `iamgithub` username
6. User links account to same Google account from step 3.
7. Now both Github and Google accounts have profiles with the same email.

If so, I think this is another reason to not allow step 6.

If we do decide to allow this, then when getting a webservice call with a Google token, we have to make some arbitrary decision as to which User the call should be associated with.

**Comment by denis-yuen** [comment]
As discussed as a group, we're going to have to head in the direction of unique user profiles (at least in terms of username) with database constraints for it. 

So we shouldn't allow 6, we should change the wizard to emphasize and encourage google linking as a 1.5 step.

**Comment by denis-yuen** [comment]
Was able to use a token gleaned from SAM and then use on Dockstore to get content
Was able to do this even if my token was cleared, seeming to indicate that this is matching against my profile as opposed to tokens

```
DockstoreAPI - 1.5.0-beta.3
DockstoreUI - 2.2.0-beta.1
```
