### ISSUE TITLE
Files do not show on iOS

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1687]
When viewing a tool/workflow on mobile, none of the file content are visible.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-389)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-389

**Comment by denis-yuen** [comment]
Seems obsolete, content is visible, squished, but visible

**Comment by denis-yuen** [comment]
Was able to duplicate on an iPad mini

**Comment by denis-yuen** [comment]
Works if slow-ish on an iPad mini
