### ISSUE TITLE
User Accounts Overhaul

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1691]
Notes from discussion in meeting (WIP)

UI changes: 
- on-boarding wizard should emphasize that once you've linked your accounts, you can use either github or google to sign into the same account @agduncan94 
  - email will be used for sharing 
  - strip down intro to be shorter
- self destruction option (take inspiration from GitHub, grey out when published repos, need to type out username to destroy) @garyluu 
-a) separate login and register options @garyluu  
- UI needs b), display option to change username if account setup is not complete @agduncan94 

WS change:
- b) user object needs a boolean to (account setup complete) - can share conditions with self-destruct ability @denis-yuen
- supports a) separate user-login and register endpoints (or use parameters to distinguish) @denis-yuen
- profile (needs username, needs constraints) @denis-yuen
- SAM permissions might break @coverbeck 
  - tokens from google need to figure out which user they came from 
  - sharing, needs to look at user profile (think Charles has this underway) 
- endpoint to check whether user exists, boolean, ~~unauthenticated~~ authenticated @agduncan94 
- endpoint to change username @denis-yuen
  - checks, [a-zA-Z][a-zA-Z0-9 -_()]
  - definitely no '@'  if we want to reserve admin or special usernames

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-62)
┆Issue Number: DOCK-62

**Comment by garyluu** [comment]
WS change:
  endpoint to delete account

**Comment by agduncan94** [comment]
Onboarding has been updated to let users change their username. It has also been updated to mention signing in to the same account with github/google and what email will be used for sharing.

**Comment by denis-yuen** [comment]
I can verify that this is functional from my POV. 
Assigning to @agduncan94 to verify any missing gaps

**Comment by garyluu** [comment]
functional as far as i can tell
