### ISSUE TITLE
Flesh out user deletion feature

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1697]
### Desired behaviour

Test/make sure user profiles and tokens are deleted when a user self destructs. 
Workflows and tools in their own workspace should be deleted (check that they are the only owner).
Identify any other relevant DB orphans

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-69)
┆Issue Number: DOCK-69

**Comment by denis-yuen** [comment]
Also handle https://github.com/ga4gh/dockstore/pull/1694#discussion_r209315754

**Comment by denis-yuen** [comment]
As discussed, to clear out workflows and tools when the last owner

**Comment by garyluu** [comment]
user profiles and tokens deleted, entries in own org deleted, orphaned entries also deleted
