### ISSUE TITLE
Flesh out user login/register testing

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1698]
### Desired behaviour

There is now testing for user login vs register in #1694 
However, it mostly tests register with google + link github or vice versa. 
We need better tests that test that 
1. once a user logins and has both google and github profiles, those accounts can not be linked to or register for new accounts
1. once a user self-destructs, their accounts can be reused
1. changing usernames does not change the first item
1. login with google or github after username changes still works
1. a security review as a part of #1401 

The mocking in https://github.com/ga4gh/dockstore/pull/1694/files#diff-b9d7334f2e2fc7ce79d5fa882e152126 will be of use since it demonstrates how to mock the GitHub and Google interactions

**Comment by agduncan94** [comment]
I have an account I first signed in with Github to. If I add a Google account, I can sign in with it. If I unlink the google account, logout, then login with Github, it shows me as not linked to the Google account.

However:
a) If I log back out and login with the same Google account as before, which should no longer be linked, it takes me to my Github user, and
B) I am also not able to register a Google account with the same Google account, getting the error that a user with that account already exists.

**Comment by denis-yuen** [comment]
As discussed, this is potentially confusing but by design. 
Basically, we don't want to "forget" which accounts are associated with which login methods. 
Right now, the username can be changed and if tokens are destroyed, we could end up with an account with no way to login (like with our censored database dumps). So the usernames for each login method are *uniquely* stored in profiles and can only kicked out with another login of the same type (google login overwriting google login) or by destroying the account. 

This could be viewed as an easier to understand improvement on the old design (previously login methods could be associated with multiple accounts and we needed complicated rules to define which one "wins".

**Comment by agduncan94** [comment]
It works!
