### ISSUE TITLE
Syntax highlighting for other file types

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1699]
Nextflow allows for importing of files, such as .r files. We should add support for some common files like this, it should be pretty straightforward.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-390)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-390

**Comment by garyluu** [comment]
checked r, python, looks sane
