### ISSUE TITLE
Use Material Tooltips in Launch Third Party Component

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1704]
## Feature Request 

launch-third-party.html should use Material tooltips, `matTooltip`, instead of the HTML `title` it is currently using.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-63)
┆Sprint: Lighthouse Sprint 33 Gibbs
┆Issue Number: DOCK-63

**Comment by denis-yuen** [comment]
Looks good
```
DockstoreAPI - 1.5.0-beta.3
DockstoreUI - 2.2.0-beta.1
```
