### ISSUE TITLE
Skip "Choose your username" page for returning users on login

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1711]
### Desired behaviour

Can key off of the `{"canChangeUsername":false}`  from https://staging.dockstore.org/api/users/user/extended

**Comment by agduncan94** [comment]
I have made this change, though I think a user logging in again who has already published a workflow should be linked to another page entirely. Maybe the accounts page.

**Comment by denis-yuen** [comment]
Agreed, I think that makes sense.

**Comment by denis-yuen** [comment]
Ah, my mistake. 
I think it should be the equivalent of  `(extendedUser).canChangeUsername && (user).setupComplete`
This still appears for me after changing a username if I'm still allows to change the username

**Comment by garyluu** [comment]
using develop, login for returning users that have already changed their username now goes to the onboarding wizard without the username change step.
