### ISSUE TITLE
Error initializing permissions again

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1713]
### Expected behaviour

Permissions should initialize correctly

### Actual behaviour

I did see `Error initializing permissions` and 
```
nginx_https_1    | 206.108.127.16 - - [14/Aug/2018:17:49:38 +0000] "PATCH /api/workflows/path/workflow/dockstore.org%2FDockstoreTestUser%2Ftest_cwl/permissions HTTP/2.0" 409 30 "https://staging.dockstore.org/my-workflows/dockstore.org/DockstoreTestUser/test_cwl" "Mozilla/5.0 (X11; Linux x86_64) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/68.0.3440.84 Safari/537.36" "-"
```

Follows #1657

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-65)
┆Sprint: Lighthouse Sprint 33 Gibbs
┆Issue Number: DOCK-65

**Comment by denis-yuen** [comment]
Note that this is distinct from an email that doesn't exist which gives 
`guest@foo.com not found`

**Comment by denis-yuen** [comment]
After some testing, I suspect that this is when the workflow in question was previously initialized and subsequently deleted. 
i.e. you can't initialize a workflow again

**Comment by coverbeck** [comment]
Was it owned by somebody else in SAM? I'm guessing that might cause it.

If that is the case, I don't think there is much we can do other than give a better message. It would probably require SAM admin access to delete the resource in SAM.

**Comment by denis-yuen** [comment]
@coverbeck 
Not exactly, its the same user `DockstoreTestUser` trying to give permissions to my other account for one of its own workflows. You might be able to re-create the situation by creating one of your workflows again (if you remember the name or its in your browser cache) and sharing it with me for example.

**Comment by denis-yuen** [comment]
Confirmed that this was due to a user re-creating a previously initialized workflow leaving SAM in a bit of an odd state. 

We might be able to direct users to avoid this situation

**Comment by denis-yuen** [comment]
I think this has been fixed since we didn't encounter this on the last reset
