### ISSUE TITLE
Swagger UI should indicate that TRS API v2 is not final

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1717]
## Feature Request 

The TRS API v2 is not finalized. There was a recent change in the API that may have broken at least one client's use of the API. Because the API could still change, the Swagger UI should have some indication that the API is beta and could still evolve, and clients should use at their own risk.

1. The easiest thing to do would be to update the description at https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/templates/io/dockstore/webservice/resources/Description.java#L55, which means that the description for the category of APIs can indicate beta.
2. Apparently you could also add a vendor extension as suggested at OAI/OpenAPI-Specification#132, but I don't know how that ends up getting surfaced in the UI.

Probably should just do 1, if anything.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-80)
┆Issue Number: DOCK-80

**Comment by denis-yuen** [comment]
See also #1375

**Comment by coverbeck** [comment]
Looks good on staging.
