### ISSUE TITLE
Register Workflow Inconsistent Error Object

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1718]
### Expected behaviour
Errors that occur when registering hosted workflows and non-hosted workflows should have the same error object structure

### Actual behaviour
Registering duplicate hosted workflows yields a different error object than normal workflows

Hosted:
![image](https://user-images.githubusercontent.com/24548904/44156801-d7cb2a1a-a07e-11e8-936b-12afc4e7f161.png)

Non-hosted:
![image](https://user-images.githubusercontent.com/24548904/44156894-07f588a2-a07f-11e8-93c0-dee6da6d62ff.png)

**Comment by denis-yuen** [comment]
Implementor should standardize on the 400

**Comment by agduncan94** [comment]
Fixed
