### ISSUE TITLE
Join the nf-core community and add the workflows there as high quality seed examples

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1721]
### Desired behaviour

Join https://github.com/nf-core and add the workflows to Dockstore (ask for permission of course) as high quality examples of nextflow workflows.

**Comment by denis-yuen** [comment]
Pending release to staging and/or adding as a script?

**Comment by denis-yuen** [comment]
In discussion: some of these workflows have a config structure that might break parsing and can be ignored 
https://github.com/nf-core/chipseq/blob/master/nextflow.config#L107

**Comment by agduncan94** [comment]
It seems like the issue is that these configs have some nextflow packages used in them (nextflow.util.MemoryUnit) which will fail parsing for the DAG because we do not have these packages loaded.

You are still able to register these tools and view their files, you just can't take advantage of the tool/dag tabs.

**Comment by agduncan94** [comment]
Looks like [this](https://github.com/nf-core/tools/blob/dev/nf_core/pipeline-template/%7B%7Bcookiecutter.name_noslash%7D%7D/nextflow.config) is how the nextflow.config files are generate.

Now that we have fixed the DAG endpoint to be authenticated this seems to be working.

**Comment by agduncan94** [comment]
I have been added as a member.

**Comment by denis-yuen** [comment]
I think it's worthwhile working with them to grant permission to our production and staging sites. 
Worst case, we can fork a few to experiment with on staging. But long term, I think we want to get things done on the up and up so that others can help maintain those entries too

**Comment by agduncan94** [comment]
They seem to have accepted staging, I can now fetch the nf-core workflows on staging.

**Comment by agduncan94** [comment]
All of the workflows fully work on staging, except for RNASeq and Eager. For those RNASeq tool and dag tab sort of work, but Eager doesn't seem to work.

**Comment by denis-yuen** [comment]
These already existed in production
