### ISSUE TITLE
Hosted workflows do not display authorship and email like regular workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1723]
### Expected behaviour

Add a workflow that works for WDL authorship and email as a regular workflow as a hosted workflow. 
See this information in the info tab

### Actual behaviour

A workflow like https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/test/resources/metadata_example0.wdl displays Chip as a github workflow. However, the authorship does not work for a hosted workflow.

**Comment by denis-yuen** [comment]
This might apply for both CWL, WDL, and (Nextflow)

**Comment by denis-yuen** [comment]
Addressed by https://github.com/ga4gh/dockstore/pull/1725
Should be on staging

**Comment by agduncan94** [comment]
Fixed
