### ISSUE TITLE
Hosted Workflows - Error Does Not Go Away After Correcting It

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1729]
## Bug Report

If you get a legitimate error trying to save a hosted workflow, then fix it, then save again, the error message does not go away.

1. Go to My Workflows
2. Register a hosted on Dockstore CWL workflow
3. Go to Files tab
4. Click Add Files
5. Enter the following content, which is the CWL for a tool, not a workflow
```
!/usr/bin/env cwl-runner

cwlVersion: v1.0
class: CommandLineTool
baseCommand: echo
inputs:
  message:
    type: string
    inputBinding:
      position: 1
outputs: []
```
6. Click Save as New Version
7. You get an error message `[HTTP 400] Bad Request: Your edited files are invalid. No new version was created. Please check your syntax and try again.`
8. Correct the CWL by changing `CommandLineTool` to `Workflow`
9. Click Save as New Version again.
10. It saves successfully, and you see a SnackBar message so indicating, but the big red box is still at the top of the page. See screenshot.

A couple of other notes, which maybe should be separated out into their own issues if there is agreement on doing any of them:

1. It would be nice if the validation/error message could give better feedback as to what is wrong.
2. Should we be using the SnackBar to display error messages instead of the current way? On the one hand, we've started doing it in some places. On the other hand, especially if we improve the feedback for a validation error, the SnackBar might not be the best place for that, both because of real estate and because the SnackBar disappears, although that time is configurable.
3. Also, IMO, the UI shouldn't be showing the HTTP status code. I don't think that's helpful to most end users.

![screen shot 2018-08-17 at 8 41 39 am 2](https://user-images.githubusercontent.com/1049340/44275733-613bb900-a1fa-11e8-9be2-57722e35021b.png)

**Comment by garyluu** [comment]
I think in general, SnackBar is used for short messages.  If it's longer messages, the bootstrap alert is used.

**Comment by agduncan94** [comment]
Do we want the alert to disappear? The alert currently must be closed manually. Do we want alerts to disappear when another action is performed?

**Comment by agduncan94** [comment]
We decided that any success message will clear any error state.

**Comment by denis-yuen** [comment]
Error message issue is fixed
Large issue of validation to be addresses in 1.6.0 
See #766
