### ISSUE TITLE
Create a style guide for Dockstore

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1731]
Now that we are switching over to Material, it is a good time to define a design language for Dockstore so that the site is consistent. This can go in the wiki.

**Comment by denis-yuen** [comment]
See the closed linked issues for ideas (code code style anyway)

**Comment by denis-yuen** [comment]
To sum up, running requirements for the style guide are: 
* document how IDs are used and assigned to material components for testing 
* how to use observables
* commenting format
* when to use types (and enforce with lint eventually)
* when to use the GA4GH (v2) endpoints as opposed to our proprietary

**Comment by agduncan94** [comment]
Github returns 404 errors for private repos instead of a 401. We should consider something like this for hosted entries or unpublished entries.

**Comment by agduncan94** [comment]
I've added a lot to the style guide, however it is a living document. I don't think we need to keep this issue open. @denis-yuen
