### ISSUE TITLE
After Registering with Google, Onboarding Wizard says its required to have a GitHub account

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1735]
## Feature Request 

If you are a new user and register for the first time with Google, the onboarding page says a GitHub account is required. It is not required -- what is required is either a Google or a GitHub account.

By chance, I had a small window when I did this, so it sort of stuck out due to its being in bold and was confusing.

![screen shot 2018-08-20 at 8 52 28 am](https://user-images.githubusercontent.com/1049340/44351460-c68be600-a456-11e8-9284-2f921840cf13.png)

**Comment by denis-yuen** [comment]
I think we might have outgrown the simple categorization of things as required/optional. 
We probably have to lengthen the descriptions to describe the login process better

**Comment by denis-yuen** [comment]
Working on staging
```
DockstoreAPI - 1.5.0-beta.4
DockstoreUI - 2.2.0-beta.3
```
