### ISSUE TITLE
Register hosted tool with toolname

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1738]
With non-hosted tools, you can specify a toolname to go along with the path to the docker image (ex. quay.io/test/test2). You cannot do this for hosted tools. This means that you cannot have two hosted tools with the same image provider path. You can also not have one non hosted tool with a given image provider path, and a hosted tool with the same path.

For example, say I have the quay.io image agduncan94/md5sum. I can only use that image for one hosted tool, even though I may use the same image for different tools.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-394)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-394

**Comment by denis-yuen** [comment]
Undecided as to whether we want to squeeze hosted tools into 1.5.0 or punt to 1.6.0

**Comment by david4096** [comment]
I was able to confirm that the dockstore name suffix is editable at creation time for hosted tools.

Testing against staging

DockstoreAPI - 1.6.0-beta.0DockstoreUI - 2.3.0-beta.0
