### ISSUE TITLE
Onboarding wizard stepper error

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1743]
### Expected behaviour
No errors

### Actual behaviour
![image](https://user-images.githubusercontent.com/24548904/44366562-12607e80-a49b-11e8-9860-cc49f91186ab.png)

**Comment by denis-yuen** [comment]
Working on staging
```
DockstoreAPI - 1.5.0-beta.4
DockstoreUI - 2.2.0-beta.3
```
