### ISSUE TITLE
Material indeterminate progress bar doesn't look too good

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1745]
## Bug Report

The Material indeterminate  progress bar used to look better; you could clearly see the bar going back and forth. 

Now you, or at least I, have to squint to see it changing.

To see the problem, to the workflows or tools page.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-71)
┆Issue Number: DOCK-71

**Comment by denis-yuen** [comment]
:+1:

**Comment by coverbeck** [comment]
Confirmed as well.
