### ISSUE TITLE
Confusing Feedback When Updating Username if Email Has Period

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1761]
## Bug Report

My email is of the format `<firstname>.<lastname>@<domain>`, e.g., `john.doe@example.com`.

When I register with Google, I get brought to a page warning me that I should probably change my username, because it's an email. Kudos on that page; it's really clear, except for what happens next.

As soon as I delete a character, e.g., the `m` in `.com`, the `Update Username` button gets disabled and the message `Username not available` appears. Except for deleting the period character, not matter what I do, it continues to say `Username not available`.

Once I delete the period, the button gets enabled.

Also, I at first found it a little confusing that the `Update Username` button was enabled, but the `Next` button was enabled. I can see now why it is so, but it wasn't clear to me that I could click `Next` while seeming to have an error condition.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-76)
┆Issue Number: DOCK-76

**Comment by denis-yuen** [comment]
1) Should probably show username invalid or similar in addition to not available for valid but taken usernames
2) Open to ideas

**Comment by coverbeck** [comment]
Verified on staging that the message now says `Invalid Username Pattern (Only alphanumeric characters and internal underscores and dashes allowed)` when going through my steps.

FWIW, I think the only capital in the message should be the the I in `Invalid`. Examples in [Material Design](https://material.io/design/components/text-fields.html#anatomy) seem to follow that pattern.
