### ISSUE TITLE
Workflows (possibly tools) cached through logout and login via google

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1764]
### Expected behaviour

Should see workflows for user 2 after logging out using user 1 and logging in via user 2

### Actual behaviour

After switching logins to user 2, see workflows for user 1, but I can't interact with them presumably because I have no rights.

### Steps to Reproduce

Basically as described, although note the need for step 3:

1. Logout and Reload, to start from a clean slate
2. Login as user 1
3. Click on My Workflows
4. Logout
5. Login as user 2
6. Open Chrome Dev Tools
7. Click on My Workflows. You'll see a 403 error for `https://staging.dockstore.org/api/users/{wrong user}/workflows`

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-77)
┆Issue Number: DOCK-77

**Comment by denis-yuen** [comment]
A bit of a smoking gun, the GUI calls `https://staging.dockstore.org/api/users/{wrong user}/workflows` but calls `https://staging.dockstore.org/api/users/{correct user}/workflows` after a hard refresh

**Comment by coverbeck** [comment]
Update: In https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/myworkflows/my-workflow/my-workflow.component.ts#L112, the subscription is receiving the previous user. Still trying to figure out why/how, so then it calls `https://staging.dockstore.org/api/users/{previous user}`.

In my tests, it sends the token of the new user, so I always see the call fail, and so no workflows show.

Will continue to investigate.

**Comment by garyluu** [comment]
I changed something with the user recently, branch off a recent develop and see if that still occurs

**Comment by coverbeck** [comment]
@garyluu Still happening with latest develop.

**Comment by garyluu** [comment]
:disappointed:

**Comment by coverbeck** [comment]
Update 2: More than one instance of `UserService` is being created, and that's what's leading to the problem; the code would work if `UserService` were a singleton. I believe this has to do something with modules and lazy loading. Investigating using `forRoot()`, but still coming up to speed on it.

**Comment by denis-yuen** [comment]
Looks good with 
```
DockstoreAPI - 1.5.0-beta.5
DockstoreUI - 2.2.0-beta.4
```
