### ISSUE TITLE
Starred tools and workflows links incorrect

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1765]
### Expected behaviour

Links on this page work

### Actual behaviour

Links to hosted workflows seem to point (incorrectly) to where a hosted tool would be. 
Test the vice versa too

![screenshot from 2018-08-24 17-04-46](https://user-images.githubusercontent.com/1730679/44607918-f3762b00-a7bf-11e8-8753-a7f7fde7d7cd.png)

**Comment by denis-yuen** [comment]
Getting better, most links work. 
However, it is possible to publish a hosted workflow, star it, unpublish it. 
The workflow still shows up but the link doesn't work and our guesses for redirection are incorrect. 

Best solution: link to unpublished tools and workflows via My Tools/My Workflows
Acceptable solution: do not show unpublished tools and workflows on the starring page

**Comment by agduncan94** [comment]
This works, the hosted workflow that is published, starred, then unpublished will not be visible on the starring page.
