### ISSUE TITLE
File dropdown for non hosted workflows should be a full path

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1769]
If you go to a non hosted workflow with a long filename, the whole path won't show.

![screenshot from 2018-08-27 15-46-01](https://user-images.githubusercontent.com/6331159/44682075-637af000-aa10-11e8-8428-0ab11a2bf1ff.png)

**Comment by denis-yuen** [comment]
Works with 
```
DockstoreAPI - 1.5.0-beta.6
DockstoreUI - 2.2.0-rc.0
```
