### ISSUE TITLE
dockstore workflow publish on CLI should only list full workflows, and not all workflows

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1773]
dockstore workflow publish on the CLI will list all of the workflows that the user has. Unfortunately most users will probably have a larger list of workflows with many being stubs, which are likely not important. By default the command should only show unpublished FULL workflows. There can be an optional parameter to also show the stubs.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-400)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-400

**Comment by david4096** [comment]
I can confirm that stubbed workflows do not appear in the CLI output. The original request was suggested an optional parameter for viewing the stubbed workflows.

This filtering is done by the CLI client so the API will still return stubbed workflows. This should make it possible to easily add a parameter for removing the filter. Added a separate issue to track that feature. https://github.com/ga4gh/dockstore/issues/2184

Tested against staging
Dockstore version 1.6.0-beta.0
