### ISSUE TITLE
Pagination Offset Re-ordered

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1777]
### Expected behaviour
The first 10 workflows listed should be different than the next 10 workflows

### Actual behaviour
The first 10 and next 10 workflows have common workflows

### Steps to reproduce the behaviour 
- Go to https://staging.dockstore.org/workflows
- Copy the workflows seen
- Click the next page button
- Look at the workflows and notice how some are still present

DockstoreAPI - 1.5.0-beta.3
DockstoreUI - 2.2.0-beta.2

**Comment by denis-yuen** [comment]
Huh, weird. We probably need more order

**Comment by garyluu** [comment]
appears to work
