### ISSUE TITLE
Refresh update files

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1778]
### Expected behaviour
Refresh should update the file contents

### Actual behaviour
Refresh does not update the file contents in the UI (once the file contents are gotten, refresh does not trigger it again)

### Steps to reproduce the behaviour 
- Have a workflow without metadata
- Go to the workflow in my-workflows page
- Go to git repo and add metadata
- Refresh
The workflow has metadata displayed but the file contents are still the same until page reload

**Comment by denis-yuen** [comment]
Seems functional in 
```
DockstoreAPI - 1.5.0-beta.6
DockstoreUI - 2.2.0-rc.0
```
