### ISSUE TITLE
Auto tools with invalid Quay.io images are breaking refresh

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1779]
If you somehow get into the state where the Quay.io repo associated with an auto tool no longer exists, it will break the refresh for the tool and for the org and for the refresh all.

Workaround is to refresh other tools individually.

**Comment by denis-yuen** [comment]
FYI, turns out we had a couple bugs that was affecting this. 
After the fix above, if quay.io legitimately responds and says a quay.io repo no longer exists, it will be deleted.

**Comment by agduncan94** [comment]
This is fixed!
