### ISSUE TITLE
Strip sourcefiles for operations like updating workflow paths

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1794]
### Desired behaviour

For scalability, need to not send source files back to the web service when calling endpoints that don't (shouldn't?) need them like https://dockstore.org:8443/static/swagger-ui/index.html#/workflows/updateWorkflow and https://dockstore.org:8443/static/swagger-ui/index.html#/containers/updateContainer

Will need UI changes and testing for the web service.

**Comment by denis-yuen** [comment]
Test obvious operations like editing workflow paths, default versions for now and then send back to backlog if successful (ly small)

**Comment by garyluu** [comment]
Tested editing fields like default workflow paths and default dockerfile paths for both tools and workflows.  WorkflowVersions and Tags are no longer sent, but the difference between production and staging was less than 100 bytes.

Default version was tested but it uses another endpoint that was small to begin with.
