### ISSUE TITLE
There should be a consistent message for endpoints that don't require authentication

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1795]
## Feature Request 

The Swagger doc, generated from the `notes` attribute of `@APIOperation` has different ways of saying the same thing:

* `Does not need authentication`
* `NO authentication`
* Sometimes nothing at all, although I suppose for some endpoints maybe it's redundant, and this is OK.

**Comment by denis-yuen** [comment]
Ended up in #1810
