### ISSUE TITLE
Double Refresh Workflow Version Edit

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1799]
### Desired behaviour
Should be one refresh that happens but...saving changes in workflow version edit results in a double refresh.  One refresh after workflow version is updated (workflow path, hidden, etc). Another refresh happens after test parameter files are added/removed.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-403)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-403

**Comment by denis-yuen** [comment]
Looks miss-classified, fix is to develop (as it should be)

**Comment by NatalieEO** [comment]
Only one refresh occurs now for DockstoreUI - 2.3.0-beta.0
