### ISSUE TITLE
unique, stable URL for each tool/version that can be used in publications 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#18]
think https://www.dockstore.org/image/quay.io/briandoconnor/dockstore-tool-bamstats not https://www.dockstore.org/search/25

**Comment by denis-yuen** [comment]
:+1:  I wonder if we could even submit something automatically to Zenodo, they have an API https://zenodo.org/dev

**Comment by oicr-vchung** [comment]
Implemented as: https://www.dockstore.org/{registry_name}/{namespace}/{name}/{toolname*}

* toolname is optional
