### ISSUE TITLE
.../descriptor/{relative_path} errors

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1800]
### Expected behaviour
There should be no .../descriptor/{relative_path} calls that result in error because the parameters are gotten from the /files endpoint.

### Actual behaviour
There sometimes appear to have a .../descriptor/{relative_path} error where the {relative_path} may be correct but the {id} is not  .

### Steps to reproduce the behaviour 
Have a bunch of workflows, go to my-workflows and randomly click through several of them on the sidebar.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-404)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-404

**Comment by wshands** [comment]
Tested the fix on staging DockstoreUI - 2.3.0-beta.0 and I do not see the incorrect calls that I did see in production.
