### ISSUE TITLE
Entry2Json CLI for WDL workflows/tools fails if the version is invalid

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1813]
I noticed this on staging when following the launch tab command for downloading the checker workflow JSON file.

```
dockstore workflow convert entry2json --entry github.com/dockstore-testing/dockstore-workflow-md5sum-unified/wdl_wdl_checker:1.2.0 > Dockstore.json
```

The above command fails because version 1.2.0 is invalid for the checker workflow.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-131)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-131

**Comment by NatalieEO** [comment]
Command no longer fails. Gives message saying version could not be found, and runs command using last modified version instead.
