### ISSUE TITLE
If not logged in, UI still sends Authorization header in Ajax requests

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1818]
## Bug Report

If you are not logged in, Ajax requests from the UI requiring authorization are sent with the Authorization header set to `Bearer null`.

See https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/loginComponents/token.service.ts#L39 and https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/loginComponents/user.service.ts#L46 

While the web service will correctly reject these calls with 401s, it could do so more efficiently if there was no auth header instead of a bogus one.

Discovered while investigating #1817 

###

### Steps to reproduce the behaviour 

1. Go to dockstore.org
2. If logged in, log out
3. Open Developer tools
4. Reload the page
5. Look at the failing AJAX calls returning 401, `/api/users/user` and `/api/users/user/extended`, and you'll see in the Request headers `Authorization: Bearer null`.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-83)
┆Issue Number: DOCK-83

**Comment by denis-yuen** [comment]
Seems fixed on the webservice log side of things (with non-logged in users)

**Comment by denis-yuen** [comment]
:+1:
