### ISSUE TITLE
Ownership is quirky for manual registration of alternate tool names for existing tools

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#182]
> [HTTP 400] Bad Request: User does not own the container quay.io/collaboratory/seqware-bwa-workflow. You can only add Quay repositories that you own or are part of the organization

When attempting to re-add seqware-bwa-workflow under an alternate name although I definitely own collaboratory

**Comment by denis-yuen** [comment]
Note: This occurs on production as well

**Comment by agduncan94** [comment]
I couldn't reproduce this error in staging. It seems to have been fixed.
