### ISSUE TITLE
Grab bag of small UI fixes needed for my tools/workflows page

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1820]
Workflow DAG
* While loading the DAG there is an alert that no descriptor file could be found, even if there is one
* Add workflow button visible in full screen (change z-index)

Hosted workflow
* Edit/View version tab, git reference is disabled but is blank, should have N/A

My Tools
* Refresh org button should actually be refresh namespace

**Comment by garyluu** [comment]
Workflow DAG
* ~While loading the DAG there is an alert that no descriptor file could be found, even if there is one~
It is now blank
* ~Add workflow button visible in full screen (change z-index)~
Can no longer see the button in full screen DAG

Hosted workflow
* ~Edit/View version tab, git reference is disabled but is blank, should have N/A~
Now is "n/a"

My Tools
* ~Refresh org button should actually be refresh namespace~
It now says "Refresh Namespace"
