### ISSUE TITLE
Published workflows page making unnecessary call to fetch actions

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1823]
## Bug Report

UI is making call to actions endpoint, unnecessarily, on the Published workflow endpoint.

### Steps to reproduce the behaviour 

1. Goto home page
2. Open Dev Tools
3. Logout if logged in (makes it easier to see the issue)
4. Click on Workflows
5. Click on a workflow
6. In Chrome dev tools Network tab, you'll see a 401 with a call to the actions endpoint. But we shouldn't be making this call at all, even if you were logged in and authorized for the particular workflow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-84)
┆Issue Number: DOCK-84

**Comment by garyluu** [comment]
A fix should not involve the order of subscriptions as there's no guarantee that the first subscription would yield something before the next one.
