### ISSUE TITLE
Published Workflows Not Showing Files

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1824]
## Bug Report

If you are not logged in and go to a published workflow, you do not see any of the workflow's files. There is also an error in the console `Cannot read property 'length' of null`.

This happens due to #1818 

### Steps to reproduce the behaviour 

1. If logged in, log out
2. Go to workflows page
3. Click on a workflow
4. Click on Files tab. Expect to see files; instead see an error saying there are no files. If you login, you do see the files.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-85)
┆Issue Number: DOCK-85

**Comment by denis-yuen** [comment]
:+1:
