### ISSUE TITLE
GUI consistency - failed publish still toggles publish button

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#183]
When a repo does not meet the requirements to publish, the Publish button still changes state to Unpublish. The tool is not actually published and if you change to a different page and come back, the button correctly still says Publish. 

Correct behaviour: The button should stay at Publish when publishing fails. 

![screenshot from 2016-04-01 11 27 52](https://cloud.githubusercontent.com/assets/1730679/14211630/1eee88e2-f7fd-11e5-8080-f14f111126bb.png)

**Comment by agduncan94** [comment]
One idea is to block the publish button (disable) if it is not valid.  This can be done for workflows by checking if the workflow has been refreshed, and if so are any of these valid.  For tools, disable the publish button if invalid.

**Comment by denis-yuen** [comment]
That would work too (and would be an improvement). I think making the button "bounce" back to publish if unable to publish would be maybe a minimum requirement. Disabling pre-emptively would be even better.

**Comment by agduncan94** [comment]
For workflows I have the check implemented.  So the button is disabled if the workflow is a STUB, and if the workflow is FULL it will check validity (by looking at each version tag)

**Comment by denis-yuen** [comment]
Sounds good. What's the current behaviour for tools?

**Comment by agduncan94** [comment]
I have not implemented it for tools yet, though it is very easy to do so.  I'm going to make a pull request where I am adding DAG support.  So I'll  make the change there.
