### ISSUE TITLE
Search facets show more has weird indent

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1832]
Seems like the class panel-container-label is being applied twice.

<img width="313" alt="screen shot 2018-09-17 at 3 40 10 pm" src="https://user-images.githubusercontent.com/6331159/45645931-fa771d00-ba8f-11e8-825f-ac5987d282ad.png">

**Comment by denis-yuen** [comment]
Weird indent is gone with 2.2.4 at staging.dockstore.org
