### ISSUE TITLE
Nextflow workflow with no description shows the wrong information

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1836]
If I have a nextflow workflow with no description, I get the following message:

> No description associated with this workflow. See Dockstore's Getting Started With CWL and commonwl.org for how to define a description for this tool.

This should be descriptor type specific. Not sure if the same issue with WDL.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-233)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.5.5
┆Issue Number: DOCK-233

**Comment by denis-yuen** [comment]
Also swap Nextflow logo to large logo with text

**Comment by agduncan94** [comment]
Note that nextflow logo is missing on the Docs site.

**Comment by denis-yuen** [comment]
Encountered this with WDL testing. 
might be nice to get into hotfix

**Comment by garyluu** [comment]
Now I see this on staging

![image](https://user-images.githubusercontent.com/24548904/54781474-c2919380-4bf2-11e9-8fca-5e4ae612d805.png)
