### ISSUE TITLE
Should not use $ at start of code sections, makes it harder to copy

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1838]
Could add a copy button beside the text too.
An example of this is in launch with.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-417)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-417

**Comment by wshands** [comment]
Tested it in staging.dockstore.org DockstoreUI - 2.3.0-beta.0. '$' is no longer present in the code examples on the Dockstore Launch tab
