### ISSUE TITLE
We should show the Dockstore CLI config file in the Accounts page

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1841]
After setup is no longer in the dropdown, the only way to access the CLI info is through the setup link on the homepage.

We should show the ~/.dockstore/config file in the accounts page for each access on new computers, along with a link back to the onboarding page with full install notes in case the user forgets.

**Comment by coverbeck** [comment]
I might be misunderstanding, and/or you probably know this already,  but for security reasons I don't think you can read the contents of an arbitrary local file and display them in the browser, unless the user selects the file with an `<input type="file">`.

**Comment by denis-yuen** [comment]
He's referring to the generated config file in the onboarding wizard under "Part 2 - Setup Dockstore CLI Config"

**Comment by coverbeck** [comment]
Got it, thanks for the explanation.

**Comment by denis-yuen** [comment]
Link added to "Dockstore Account" of Profiles, Accounts, and Controls
