### ISSUE TITLE
Join nf-core contributors page

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1843]
Make a PR to https://github.com/nf-core/nf-co.re/blob/master/nf-core-contributors.yaml

It will appear at http://nf-co.re/about

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-419)
┆Issue Type: Story
┆Issue Number: DOCK-419

**Comment by agduncan94** [comment]
Planning out the card here, feel free to edit.
Name: Dockstore
Description: Dockstore is an open platform for sharing Docker-based tools and workflows described with Common Workflow Language (CWL), the Workflow Description Language (WDL), and Nextflow (NFL).
Affiliation: OICR, UCSC, GA4GH, and Cancer Genome Collaboratory???
Image: Dockstore logo
Contact: Denis Yuen

**Comment by denis-yuen** [comment]
Joined
