### ISSUE TITLE
Footer links should open in new window/tab

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1844]
When redirected to another site, makes sense to open in a new tab or window.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-133)
┆Issue Number: DOCK-133

**Comment by coverbeck** [comment]
In case you didn't know (I just discovered this a couple of weeks ago), if you add `target="_blank"`, you should also add `rel=noopener noreferrer`. See [this article](https://www.pixelstech.net/article/1537002042-The-danger-of-target=_blank-and-opener).

**Comment by denis-yuen** [comment]
I think the lighthouse audit also shows this and can be used to test a fix
#1600
