### ISSUE TITLE
TRS V1 response objects should link to V1 responses, not v2 responses

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1849]
### Expected behaviour

Workflows with links to checker workflow should generate those links correctly. 

### Actual behaviour

See   https://groups.google.com/a/ga4gh.org/d/msg/ga4gh-cloud/B5mEHJnq144/h0zW87NxAAAJ
Looks like there's a missing "/api" caused by #1023 

Also double-check that the rest of the checker "plumbing" is correct while at it.

Note @jaeddy

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-191)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-191

**Comment by denis-yuen** [comment]
(worth tests)

**Comment by denis-yuen** [comment]
#1904

**Comment by agduncan94** [comment]
I noticed the v1 endpoints all link to the v2 endpoints in their responses. Is this intended? @denis-yuen @garyluu

**Comment by garyluu** [comment]
Not sure

**Comment by denis-yuen** [comment]
Nope

**Comment by denis-yuen** [comment]
FYI, look a quick look. I think this is ugly enough (or rather the surrounding code is) that I don't think we'll hold up the hotfix for this.

**Comment by NatalieEO** [comment]
Yes, this seems to be working on DockstoreAPI - 1.6.0-beta.0
