### ISSUE TITLE
Ability to run tools and workflows offline

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1854]
A user wanted to be able to run tools and workflows with no internet connection from the CLI.

Workaround:
1) Download descriptor files locally
2) Add the following to the config file:
`cwltool-extra-parameters: --disable-pull`
4) Follow steps here https://stackoverflow.com/a/48125632 to get a copy of the docker image loaded locally
5) Launch the tool
`dockstore tool launch --local-entry <local-file-path> --json <input-json-path>`

We should update the documentation to include this.

Note: The user had an issue getting the image working on a cluster. On the head node the image existed and was named with a tag, however on the compute nodes the repository and tag were missing. Will update here once a solution is found.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-422)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-422

**Comment by agduncan94** [comment]
**What they wanted:**
- to run a CWL tool on the cluster. The head node is connected to the public internet, but the compute nodes are not.

**Problem:**
- no internet connection means the compute node won't be able to download descriptor files or download a docker image

**Solution:**
- download the docker image on the head node (with internet access) and save it into a file (which the compute nodes have access to)
- load the image onto the compute node
- download the descriptor files to the compute node
- launch using --local-entry

**Situation explained by user:**
> was able to run the dockstore container just fine on the head node of our commodity cluster, which has internet access. Of course the point of having a cluster is to run software on compute nodes, which do not have public internet access. So when trying to execute the same command on a compute node it was complaining that it couldn't pull down the docker image
>
> So we saved the docker image with "docker save -o dockstore-cgpwgs_with_tags quay.io/wtsicgp/dockstore-cgpwgs:1.1.4" (executed on the head node to some cluster-globally-accessible directory), then added it to the compute node(s) with "docker load -i /path/to/image.tar" (executed on the compute node)
>
>What we had done before, which caused the lack of entries in the repo and tag column was "docker save -o dockstore-cgpwgs.tar 8f2d9de5ab9d", so just giving the tag id doesn't place nicely with dockstore
>
>After that, the command "dockstore tool launch --local-entry Dockstore.cwl --json example.json" worked just fine on our offline compute node

**Comment by wshands** [comment]
Doesn't seem to be fixed...
(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => echo $DOCKSTORE_VERSION 
1.6.0-beta.0-shaded
(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => docker images | grep 8c1d429312ea
quay.io/briandoconnor/dockstore-tool-md5sum      1.0.4               8c1d429312ea        19 months ago       120MB
(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => docker rmi 8c1d429312ea
Untagged: quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4
...

CWL file:
...
requirements:
- class: DockerRequirement
  #dockerPull: quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4
  dockerImageId: 8c1d429312ea
...

(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => docker load -i dockstore-tool-md5sum.tar 
e5d2f035d7a4: Loading layer [==================================================>]  123.5MB/123.5MB
...

(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => docker images | grep 8c1d429312ea
<none>                                           <none>              8c1d429312ea        19 months ago       120MB


dockstore workflow launch --local-entry ../md5sum.cwl --json ../md5sum.cwl.fixed.json
...

```(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => dockstore workflow launch --local-entry ../md5sum-docker-imageid.cwl --json ../md5sum.cwl.fixed.json
Downloading: file:///Users/waltershands/Documents/UCSC/dockstore_work/md5sum.cwl.fixed.json to file:///var/folders/vj/xky2f9pn64q6__y6w2kpjx4m0000gn/T/parameter822648685849186859json
[##################################################] 100%
Created temporary working directory at '/var/folders/vj/xky2f9pn64q6__y6w2kpjx4m0000gn/T/1551749145061-0'
Using local file '../md5sum-docker-imageid.cwl' as primary descriptor
Creating directories for run of Dockstore launcher at: /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac
Provisioning your input files to your local machine
Parsed file:///Users/waltershands/Documents/UCSC/dockstore_work/dockstore-tool-md5sum-dockerimage.cwl
Preparing download location for: #input_file from https://raw.githubusercontent.com/Sage-Bionetworks/workflow-interop/develop/tests/testdata/md5sum.input into directory: /Users/waltershands/Documents/UCSC/dockstore_work/beta_t
esting_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/inputs/654ed085-88af-4570-bd30-bab5b76acb90
Downloading: https://raw.githubusercontent.com/Sage-Bionetworks/workflow-interop/develop/tests/testdata/md5sum.input to file:///Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore/launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/inputs/654ed085-88af-4570-bd30-bab5b76acb90/md5sum.input
[##################################################] 100%
WARNING: Output location not found for "output_file" provisioning by default to working directory
Calling out to cwltool to run your workflow
########### WARNING ###########
You are using extra flags for your cwl runner which may not be supported. Use at your own risk.
--disable-pull
Executing: cwltool --disable-pull --enable-dev --non-strict --outdir /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/outputs/ --tmpdir-prefix /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/tmp/ --tmp-outdir-prefix /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/working/ /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/../md5sum-docker-imageid.cwl /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore/launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/workflow_params.json
/Users/waltershands/Documents/virtual_environments/gs_plugin_env/bin/cwltool 1.0.20180403145700
Resolved '/Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/../md5sum-docker-imageid.cwl' to 'file:///Users/waltershands/Documents/UCSC/dockstore_work/md5sum-docker-imageid.cwl'
[workflow md5sum-docker-imageid.cwl] start
[step md5sum] start
Workflow or tool uses unsupported feature:
Docker is required to run this tool: Docker image 8c1d429312ea not found
org.apache.commons.exec.ExecuteException: Process exited with an error: 33 (Exit value: 33)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:404)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        at java.lang.Thread.run(Thread.java:748)
17:25:50.532 [main] ERROR io.dockstore.client.cli.nested.BaseLanguageClient - Problem running launchercwltool: 
java.lang.RuntimeException: problems running command: cwltool --disable-pull --enable-dev --non-strict --outdir /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/outputs/ --tmpdir-prefix /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/tmp/ --tmp-outdir-prefix /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore//launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/working/ /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/../md5sum-docker-imageid.cwl /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/datastore/launcher-a76a4eb8-3a72-4712-9749-b7a46b68e9ac/workflow_params.json
        at io.dockstore.common.Utilities.executeCommand(Utilities.java:146)
        at io.dockstore.common.Utilities.executeCommand(Utilities.java:93)
        at io.dockstore.client.cli.nested.BaseLauncher.executeEntry(BaseLauncher.java:112)
        at io.dockstore.client.cli.nested.BaseLanguageClient.commonExecutionCode(BaseLanguageClient.java:322)
        at io.github.collaboratory.cwl.CWLClient.executeEntry(CWLClient.java:247)
        at io.dockstore.client.cli.nested.BaseLanguageClient.launchPipeline(BaseLanguageClient.java:173)
        at io.github.collaboratory.cwl.CWLClient.launch(CWLClient.java:281)
        at io.dockstore.client.cli.nested.WorkflowClient.checkEntryFile(WorkflowClient.java:497)
        at io.dockstore.client.cli.nested.WorkflowClient.launch(WorkflowClient.java:461)
        at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:236)
        at io.dockstore.client.cli.Client.run(Client.java:707)
        at io.dockstore.client.cli.Client.main(Client.java:609)
```

**Comment by garyluu** [comment]
Which docker-images directory did you specify in the dockstore config file?

**Comment by wshands** [comment]
OK thanks now it can find the docker image tar file and load the image (however if there are any other non image files in the directory the command fails; this should be noted in documentation):

I used this directory in the config:
docker-images = /Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/docker_images


...
(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => dockstore workflow launch --local-entry ../md5sum-docker-imageid.cwl --json ../md5sum.cwl.fixed.json
Loading docker images...
Loaded image ID: sha256:8c1d429312ea1224a511ed4f48518b2f8f14cb985107a10f64b20c4ae838c537
Downloading: file:///Users/waltershands/Documents/UCSC/dockstore_work/md5sum.cwl.fixed.json to file:///var/folders/vj/xky2f9pn64q6__y6w2kpjx4m0000gn/T/parameter8788004399500947643json
[##################################################] 100%
...

and the image is there:
(gs_plugin_env) ~/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0 => docker images | grep 8c1d429312ea
<none>                                           <none>              8c1d429312ea        19 months ago       120MB

but the workflow still doesn't run:
...
/Users/waltershands/Documents/virtual_environments/gs_plugin_env/bin/cwltool 1.0.20180403145700
Resolved '/Users/waltershands/Documents/UCSC/dockstore_work/beta_testing_for_1_6_0/../md5sum-docker-imageid.cwl' to 'file:///Users/waltershands/Documents/UCSC/dockstore_work/md5sum-docker-imageid.cwl'
[workflow md5sum-docker-imageid.cwl] start
[step md5sum] start
Workflow or tool uses unsupported feature:
Docker is required to run this tool: Docker image 8c1d429312ea not found
org.apache.commons.exec.ExecuteException: Process exited with an error: 33 (Exit value: 33)
...

**Comment by garyluu** [comment]
it doesn't run even if you've properly included only images in the docker-image directory?

**Comment by wshands** [comment]
Tested on staging and works, but image tar files need to be in their own directory with no other types of files. Also works if you specify dockerImageId instead of dockerPull in the requirements section of the CWL.
