### ISSUE TITLE
When viewing a workflow, UI is making unnecessary calls to fetch files

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1857]
## Bug Report

If you go to, for example, a CWL workflow, the UI is making calls to fetch the workflow's (non-existent) WDL and Nextflow files.

I think the UI should just be able to go off the workflow's descriptor type.

No harm is done, other than the unnecessary calls potentially slowing down the page's performance.

### Steps to reproduce the behaviour 

1. In Chrome, open Developer Tools
2. Go to https://dockstore.org/workflows/github.com/h3abionet/h3agatk:1.0.1?tab=info
3. In network tab, you'll see calls to `https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fh3abionet%2Fh3agatk/versions/1.0.1/CWL/files`, `https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fh3abionet%2Fh3agatk/versions/1.0.1/WDL/files`, and `https://dockstore.org/api/api/ga4gh/v2/tools/%23workflow%2Fgithub.com%2Fh3abionet%2Fh3agatk/versions/1.0.1/NFL/files`. Only the call to get the CWL files should be necessary.

This is happening because [files.component.ts](https://github.com/dockstore/dockstore-ui2/blob/81eeb7c917895982fc4faa4cd436156ad932a69e/src/app/workflow/files/files.component.ts#L45) is calling [GA4GHFiles.state.service.ts](https://github.com/dockstore/dockstore-ui2/blob/81eeb7c917895982fc4faa4cd436156ad932a69e/src/app/shared/entry/GA4GHFiles.state.service.ts#L76), which iterates through the different workflow types.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-425)
┆Issue Type: Story
┆Issue Number: DOCK-425

**Comment by rjbautis** [comment]
The bug report has already been addressed in [Feature/state #473](https://github.com/dockstore/dockstore-ui2/pull/473).

The UI is no longer fetching non-existent files after migrating to Akita state management. The ga4gh files service is passed the descriptor type of the current workflow when fetching files.

https://github.com/dockstore/dockstore-ui2/blob/7bb646371cd68450dcd24a915c4e3383aee3cb05/src/app/workflow/workflow.component.ts#L202-L205
