### ISSUE TITLE
GUI needs an easy way to check version

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#186]
The CLI and web service now have easy ways to check for versioning. 

```
$ dockstore --version
Dockstore version 0.3-beta.1
You are running the latest stable version...
$ dockstore --debug --server-metadata
Apr 01, 2016 2:32:08 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET https://www.dockstore.org:8443/tools/metadata
1 > Accept: application/json
1 > Authorization: Bearer 8f0139974c8572dd1ac156f94149885186a34d0abe913164b105ea5d0f9360f2
1 > User-Agent: Java-Swagger

Apr 01, 2016 2:32:08 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 200
1 < Content-Length: 99
1 < Content-Type: application/json
1 < Date: Fri, 01 Apr 2016 18:32:33 GMT

{
  "version": "0.3-beta.1",
  "country": "CAN",
  "friendlyName": "Your friendly neighbourhood docker store"
}
```

However, there is no equivalent for the GUI. Create one.

**Comment by jpatricia** [comment]
Ideas:
We want to avoid a procedure that would be easy to forget 
e.g. having a manually updated string in the docs or bower.json
Also avoid literally running any directly on the server at runtime (like git)

Ideally, we would have something that renders the current version number (or git commit) during the build process (grunt --force) into either the "about" page or the website footer.  

This might be useful `git rev-parse HEAD`

**Comment by jpatricia** [comment]
1. Found a module from npm : https://www.npmjs.com/package/git-rev that i might be able to use to get the tag. We will need to use "require" to import the module to the project, which is from CommonJS. However, I tried to use RequireJS to able to use "require", but apparently it's more complicated that it seems. The documentation and example for both RequireJS and git-rev are unclear. It does say that RequireJS should be able to load a Node module, but it has some restrictions, and plus it is asynchronous, which is not that nice.
2. Another thing that can be used is Browerify, but this one will require you to run it in the command line http://www.leanpanda.com/blog/2015/06/28/amd-requirejs-commonjs-browserify/ 
3. One thing that they also mentioned in the article is to use WebPack. However, this will not be so worth the effort cause it might complicate stuff for the whole project.

**Comment by denis-yuen** [comment]
Just to elaborate/emphasize, we want a solution that doesn't actually run git or similar on the server while the website is running. Ideally, the solution would hook into the build process (grunt) and render the git version into the static website, somewhere on the about page or the website footer,

So calling a shell command from the webservice would definitely not be a good solution (also the webservice does not necessarily even know where the website is running, it could even be on a different server)

**Comment by denis-yuen** [comment]
Currently in test on staging.dockstore.org implemented in https://github.com/ga4gh/dockstore/releases/tag/0.4-beta.5
