### ISSUE TITLE
If there is no description for a hosted WDL workflow, the hint refers to CWL

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1860]
## Bug Report

See screenshot of a hosted WDL workflow:

![screen shot 2018-10-11 at 3 23 35 pm](https://user-images.githubusercontent.com/1049340/46837335-d1356e00-cd69-11e8-8664-60156693d997.png)

**Comment by agduncan94** [comment]
I have fix this in one of my branches which has since been merged with develop (https://github.com/dockstore/dockstore-ui2/pull/467)

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/issues/1836
