### ISSUE TITLE
Expanded Facets on Search Page Show up as Indented

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1862]
## Bug Report

In the Search Page, if you expand a facet, e.g., Author, the newly revealed facets show up indented. At first glance, it looks like they are children or a subtree, but they are not.

### Steps to reproduce the behaviour 

1. Go to dockstore.org/search
2. Under Author (happens with others as well), click the `<n> more` link to show all authors.
3. Newly visible authors show up indented to the right.

![screen shot 2018-10-18 at 8 36 13 am](https://user-images.githubusercontent.com/1049340/47166389-eef65c00-d2b0-11e8-8e0b-7416cfefb781.png)

**Comment by garyluu** [comment]
https://github.com/ga4gh/dockstore/issues/1832

**Comment by coverbeck** [comment]
Closing as dupe of #1832
