### ISSUE TITLE
Cannot run dockstore CLI for SNAPSHOT

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1869]
Trying to run dockstore CLI from 1.6.0-alpha.0-SNAPSHOT but am getting the following issue.

```
Downloading Dockstore to /home/aduncan/.dockstore/self-installs/dockstore-client-1.6.0-alpha.0-SNAPSHOT.jar now...
file:////home/aduncan/.m2/repository/io/dockstore/dockstore-client/1.6.0-alpha.0-SNAPSHOT/dockstore-client-1.6.0-alpha.0-SNAPSHOT-shaded.jar
curl: (3) SMB shares are not supported in file: URLs.
```

**Comment by garyluu** [comment]
Works for me.  However, if ./dockstore/dockstore/config is pointed at a downed server (staging is down), it gets stuck indefinitely with no useful error message.

**Comment by denis-yuen** [comment]
Weird, the only reference to curl in the script is to something that we seem to have inherited from the original script involving proxy servers (which I assume you're not using)
Is this repeatable?

**Comment by agduncan94** [comment]
I can still produce it locally.

**Comment by agduncan94** [comment]
This happens for Denis and I on Ubuntu 18, but not to Gary on Ubuntu 16.

**Comment by denis-yuen** [comment]
Try in Docker container, make sure fix works in 18 and still works in Ubuntu 16

**Comment by agduncan94** [comment]
It works!
