### ISSUE TITLE
Dockstore CLI for Developers

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#187]
When using the Dockstore CLI it would be nice to be able to manually specify a local CWL for use with the launch feature:

'''
ubuntu@brian-pcawg-bwa-testing:~/gitroot/CGP-Somatic-Docker$ dockstore launch

Usage: dockstore launch --help
       dockstore launch

Description:
  Launch an entry locally.
Required parameters:
  --entry <entry>                Complete tool path in the Dockstore
Optional parameters:
  --json <json file>            Parameters to the entry in the dockstore, one map for one run, an array of maps for multiple runs
  --tsv <tsv file>             One row corresponds to parameters for one run in the dockstore
  --descriptor <descriptor type>             Descriptor type used to launch workflow. Defaults to cwl
'''

In addition to the --entry.  That way, a developer can work on a new CWL and locally built docker image without having to do a full round trip to Dockstore.

**Comment by agduncan94** [comment]
Added to #194
