### ISSUE TITLE
Replace custom nextflow parsing code with code from Nextflow project

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1872]
Now possible due to https://github.com/nextflow-io/nextflow/issues/788#issuecomment-432715342

## Feature Request 

Find my Groovy code coded without looking at Nextflow and replace with Nextflow code which should better understand the Nextflow language.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-210)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-210

**Comment by cricketsloan** [comment]
➤ Louise Cabansay commented:

To verify, use PR: https://github.com/ga4gh/dockstore/pull/2053 ( https://github.com/ga4gh/dockstore/pull/2053 )

**Comment by Ldcabansay** [comment]
The only thing that seems to be off is that on develop the generated [DAG](https://staging.dockstore.org/workflows/github.com/Ldcabansay/eager/nfl-parsing-test-eager:2.0.3?tab=dag) the message "DAG display is still experimental for Nextflow" pushes out the 'export to png', expand icon, etc out of the info box. This doesn't occur for [other descriptor DAGs](https://staging.dockstore.org/workflows/github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/PairedEndSingleSampleWf-Firecloud-B37:dev?tab=dag) on develop. This also doesn't occur to the [same nfl workflow on production](https://dockstore.org/workflows/github.com/nf-core/eager:2.0.3?tab=dag). The additional information nfl is populating to the description on the info tab is great though.

**Comment by denis-yuen** [comment]
I think this should be coincidental, the parsing code shouldn't really affect the DAG before it loads. 
So I'm opening https://github.com/ga4gh/dockstore/issues/2180
