### ISSUE TITLE
Update Default Cromwell Version for Dockstore CLI

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1875]
## Feature Request 

The default Cromwell version is currently 30.2, which is a getting a little outdated -- they are up to [release 36](https://github.com/broadinstitute/cromwell/releases).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-183)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-183

**Comment by agduncan94** [comment]
It might be worth learning how to use tool tester and run in the background, but unknown how many WDL workflows we have.

**Comment by coverbeck** [comment]
Verified with `DOCKSTORE_VERSION=1.6.0-beta.0` when running dockstore CLI.
