### ISSUE TITLE
When registering a new tool, users working on smaller screens should be able to scroll on the form to reach all textfields.

### ISSUE THREAD

**Issue by rjbautis** [ga4gh/dockstore#1877]
## Feature Request 

When registering a new tool, users working on smaller screens should be able to scroll on the form to reach all textfields.

The UI for registering a new tool should be scrollable, if user is working on a smaller screen, to reach all textfields and the 'Add Tool' button.

1. Go to My Tools page
2. Click 'Add Tool' or 'Register Tool' button
3. Navigate to Step 2 Create a Tool
4. Attempt to reach all textfields and 'Add Tool' at the bottom of the form.

### Environment (Browser or OS and Dockstore version)

Browser: Google Chrome Version 70.0.3538.77 (Official Build) (64-bit)
Workstation Screen Size: 13-inches
Dockstore version: Production site Version 1.5.1

**Comment by denis-yuen** [comment]
@garyluu did I see something like this in one of your recent PRs?

**Comment by garyluu** [comment]
https://github.com/dockstore/dockstore-ui2/pull/480

**Comment by denis-yuen** [comment]
Scroll exists in staging.dockstore.org at ui 2.2.4
