### ISSUE TITLE
Submit Document: Audit and accountability policies and procedures

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1879]
We must submit document, **Audit and Accountability Policies and Procedures**: 

https://drive.google.com/open?id=1uZ0gr9n_PxtJ6n0sT9wqih12AooYYJvvGZyTK10mW_8

ALL DISCUSSION SHOULD HAPPEN IN THE DOCUMENT ITSELF NOT THE TICKET

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SEAB-36)
┆Issue Number: SEAB-36
┆Epic: Dockstore Compliance

**Comment by denis-yuen** [comment]
@garyluu As detailed in document, improvements to logging would be a future improvement
