### ISSUE TITLE
Submit document: Incident response policies and procedures

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1880]
We must submit the document: **Incident Response Policies and Procedures**
  https://drive.google.com/open?id=1Z599BNa4H8RbTDLQ-BhkEOBZpm9EW-pNHMFtwc04poE
ALL DISCUSSION SHOULD HAPPEN IN THE DOCUMENT ITSELF NOT THE TICKET

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SEAB-35)
┆Issue Number: SEAB-35
┆Epic: Dockstore Compliance

**Comment by denis-yuen** [comment]
@cricketsloan FYI, think syncbot has gone rogue
