### ISSUE TITLE
Evaluate Cromwell for CLI integration

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1891]
### Desired behaviour

Use heterodon to simplify process of installing and configuring cwltool
Will need to test verified workflows via jenkins

See also #1734 for the webservice equivalent

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-162)
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 4 Dory
┆Issue Number: DOCK-162

**Comment by denis-yuen** [comment]
Alternatively, a version of cromwell that doesn't reply on system cwltool but includes cwltool (also packaged via heterodon?)

**Comment by agduncan94** [comment]
As discussed, we may just want to use Cromwell to run CWL files, without going into Heterodon or cwltool, and rely on Cromwell to bring in Heterodon on its own. One caveat, you may want to still use Heterodon for CWL avro.

https://github.com/ga4gh/dockstore/pull/1831
-this uses CWL Avro in the webservice, we just want to use in the CLI for now

Need to then use tooltester to run all of the CWL tools and workflows.

With Cromwell 36, need to specify how to deal with the imports (look at current dir like cwltool).
Cromwell can also only look at a ZIP file for imports (don't unzip, look in zip file for imports). For local set of files, would need to zip.

**Comment by agduncan94** [comment]
Was able to get our CWL workflows properly working with Cromwell 36.

However, when passing a zip dir as imports that has files that Cromwell thinks are invalid, even if not referenced, will cause the workflow to fail input file processing.

This became evident when we tried zipping the directory of the primary descriptor for different tests that we had.

One idea that we had to get around this was to try using the cwltool pack command to pack imports into one file and run Cromwell with no imports specified. Doing this on a simple workflow with two imports ended up with some token parsing issues.

We don't want to have the option for the user to specify the zip themselves, as this is more work than it used to be with cwltool.

**Comment by denis-yuen** [comment]
Going to take a look at running CWL workflows with Heterodon bypassing Cromwell and the import behaviour.

**Comment by agduncan94** [comment]
Just an update:
We have decided to allow the users to define in their config that they are using either cwltool or cromwell. Cromwell will not work out of the box with all workflows (mainly due to importing differences), so we will have it included but in 'alpha' mode. We will list in both the CLI help and documentation that Cromwell is in alpha and makes some assumptions.

**Comment by denis-yuen** [comment]
(our integration with Cromwell is in beta, not Cromwell is in alpha)
