### ISSUE TITLE
Fetching a Workflow can cause a huge number of SQL statements to be executed

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1895]
Fetching a single workflow can cause thousands of SQL statements to be executed. On a local install, if I do GET /workflows/\<id\>, where in this case the id is for the  `github.com/BD2KGenomics/dockstore_workflow_cnv` workflow), I see in the terminal where the web service is running:

```
INFO  [2018-11-07 19:19:49,743] org.hibernate.engine.internal.StatisticalLoggingSessionEventListener: Session Metrics {
    66715 nanoseconds spent acquiring 2 JDBC connections;
    68248 nanoseconds spent releasing 2 JDBC connections;
    80103319 nanoseconds spent preparing 6601 JDBC statements;
    4314709128 nanoseconds spent executing 6601 JDBC statements;
    0 nanoseconds spent executing 0 JDBC batches;
    0 nanoseconds spent performing 0 L2C puts;
    0 nanoseconds spent performing 0 L2C hits;
    0 nanoseconds spent performing 0 L2C misses;
    112638278 nanoseconds spent executing 1 flushes (flushing a total of 3751 entities and 6748 collections);
    0 nanoseconds spent executing 0 partial-flushes (flushing a total of 0 entities and 0 collections)
}
```

When you add a file to a hosted workflow, it first fetches the workflow to make sure it exists and you have permission, then after the file is added, it fetches it again to return to the client, so that would be ~13K SQL statements to add a file to a hosted hosted workflow that was similar to the above workflow.

Looked into this a little, and there are lots of tables that need to be queried (not a complete list):
* workflow
* workflow_workflowversion
* version_sourcefile
* users
* sourcefile
* etc.

All of the data is obviously needed, but we should investigate if there is a way to optimize the SQL queries Hibernate is issuing.

To help debug, you can do one of the following:

1. Set `hibernate.show_sql: true` in dockstore.yml
2. Turn on Hibernate loggers (overlaps with previous step, but the second one actually prints out the values that are passed to the SQL statement:
```
loggers:
    org.hibernate.SQL: DEBUG
    org.hibernate.type: TRACE
```
3. Set up the p6spy driver, which will show the actual SQL statements going to the DB

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-137)
┆Issue Number: DOCK-137

**Comment by denis-yuen** [comment]
Sounds like an eager fetch gone awry.

**Comment by denis-yuen** [comment]
Can verify that performance is improved on staging.dockstore.org

**Comment by coverbeck** [comment]
I informally verified this by observing the behavior of fetching tools and workflows and comparing between staging and prod.
