### ISSUE TITLE
Forward Client IP

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1898]
### Expected behaviour
Client IP should be forwarded by nginx to the dockstore webservice

### Actual behaviour
Client IP is always 172.18.0.2

Possible solution:
https://calvin.me/forward-ip-addresses-when-using-nginx-proxy/

**Comment by denis-yuen** [comment]
Create at https://github.com/dockstore/compose_setup/tree/hotfix/1.5.2

**Comment by denis-yuen** [comment]
Correct ip seems to show in Kibana
