### ISSUE TITLE
allow users to register quay.io images without associated automated builds (will need to manually point at github CWL) 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#19]
* requested by UCSC to support the likes of https://quay.io/repository/ucsc_cgl/samtools

**Comment by agduncan94** [comment]
You can manually add quay repos with no automated builds as long as they have quay tags.  
However, if the builds were found automatically (quick registered), the qit url will always be blank as the refresh grabs the git url from build info, which won't include any git url.
