### ISSUE TITLE
File Provisioning Code Not Passing Metadata to Plugins

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1907]
## Bug Report

The [documentation](https://docs.dockstore.org/docs/publisher-tutorials/for-developers/#file-provisioning-plugins) for the file provisioning plugins describes how attach metadata to files.

However, [this code](https://github.com/ga4gh/dockstore/blob/1eb0a393a8c68badfb620b1bdf28d9e7b21fc16f/dockstore-client/src/main/java/io/dockstore/common/FileProvisioning.java#L183) leads to the plugins' `uploadTo` method always being called with an empty Optional.

Also see [this line](https://github.com/ga4gh/dockstore/blob/1eb0a393a8c68badfb620b1bdf28d9e7b21fc16f/dockstore-client/src/main/java/io/dockstore/common/FileProvisioning.java#L424), where `metadata` is present but not passed on.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-161)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-161

**Comment by denis-yuen** [comment]
1907 also happens to be the date of the discovery of the Diamond Sutra. 
The "the earliest complete survival of a dated printed book" and "the first creative work with an explicit public domain dedication". https://en.wikipedia.org/wiki/Diamond_Sutra

**Comment by garyluu** [comment]
I see 
```
"Uploading" from /home/gluu/testDir/datastore/launcher-502517b2-7088-48ff-93c3-313d30628f60/outputs/Hello.class to noop://nowhere.output.something with really cool metadata
```
When running with a json that has metadata
