### ISSUE TITLE
Upgrade TRS repo with latest auto-build ideas from WES (and now DRS)

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1912]
### Desired behaviour

Upgrade TRS to match DRS repo in terms of auto-generate and hosting of swagger-ui, auto-generate and hosting of documentation pages, and verification of schema validity
See https://github.com/ga4gh/workflow-execution-service-schemas#api-definition
Also last paragraph of https://github.com/ga4gh/workflow-execution-service-schemas/releases/tag/1.0.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-434)
┆Sprint: Seabright Sprint 4 Dory
┆Issue Number: DOCK-434

**Comment by denis-yuen** [comment]
https://ga4gh.github.io/workflow-execution-service-schemas/docs/pdf/index.pdf
https://ga4gh.github.io/workflow-execution-service-schemas/docs/html5/

**Comment by cricketsloan** [comment]
I think this is a duplcate to https://github.com/ga4gh/tool-registry-service-schemas/issues/60

Should we close this one and use that one?

**Comment by denis-yuen** [comment]
It's a little different, the part 2 part addresses an investigation into OpenAPI3 which I think should be split into a second ticket
