### ISSUE TITLE
Verification Version

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1918]
### Desired behaviour
Verification currently has no required version parameter (e.g. version 1.5.2 of Dockstore CLI).  Would be nice if that was a required parameter for clarity to users who see the verification information.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-437)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-437

**Comment by denis-yuen** [comment]
@garyluu link and request for review

**Comment by agduncan94** [comment]
It works!
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0
