### ISSUE TITLE
Logging improvements

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1921]
### Desired behaviour
Refer to security compliance documents. 
This ticket is to investigate potential options, choose and integrate software for system-level logging of events and hopefully send it to logstash,

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-201)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-201

**Comment by garyluu** [comment]
It'd probably be simplest to just tighten the IAM and use Amazon Cloudwatch combined with https://www.elastic.co/guide/en/logstash/current/plugins-inputs-cloudwatch.html
