### ISSUE TITLE
Normal workflow and tool search case sensitive

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1922]
### Desired behaviour
Searching BWA and bwa in https://dockstore.org/workflows returns different results.  Might be better if it was case insensitive and returns both set of results.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-438)
┆Issue Type: Story
┆Issue Number: DOCK-438

**Comment by coverbeck** [comment]
+1

I always have a hard time finding the HCA workflows because I forget the exact case.

**Comment by denis-yuen** [comment]
Reviewed and seems functional as expected on staging.dockstore.org
