### ISSUE TITLE
TRS affected by sort of result with null verification source

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1923]
### Expected behaviour

TRS should return list of workflows

### Actual behaviour

500 dependent on what content is being returned
```
ERROR [2018-11-30 15:25:10,366] io.dropwizard.jersey.errors.LoggingExceptionMapper: Error handling a request: d9235bea42cab02b
! java.lang.NullPointerException: null
! at java.util.ComparableTimSort.countRunAndMakeAscending(ComparableTimSort.java:320)
! at java.util.ComparableTimSort.sort(ComparableTimSort.java:188)
! at java.util.Arrays.sort(Arrays.java:1312)
! at java.util.Arrays.sort(Arrays.java:1506)
! at java.util.ArrayList.sort(ArrayList.java:1462)
! at java.util.Collections.sort(Collections.java:141)
! at io.swagger.api.impl.ToolsImplCommon.setVerified(ToolsImplCommon.java:261)
! at io.swagger.api.impl.ToolsImplCommon.convertEntryToTool(ToolsImplCommon.java:137)
! at io.swagger.api.impl.ToolsApiServiceImpl.toolsGet(ToolsApiServiceImpl.java:362)
```
 on server

### Steps to reproduce the behaviour 

Use censored DB dump, hit up https://dockstore.org/api/api/ga4gh/v2/tools?checker=false&limit=1000
compare with 
https://dockstore.org/api/api/ga4gh/v2/tools?checker=true&limit=1000
 which does work

### Environment (Browser or OS and Dockstore version)

DockstoreAPI - 1.5.1

**Comment by denis-yuen** [comment]
Note: not present in current staging DB

**Comment by denis-yuen** [comment]
Should probably also rummage around the other TRS endpoints, V1 and V2

**Comment by garyluu** [comment]
Both endpoints seem to work with staging.  staging passes the TRS validator (which tests most v2 with the first tool it finds),  tested a v2 endpoints with a workflow manually, tested some random v1 endpoints
