### ISSUE TITLE
Establish a location for all policies and procedures

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1926]
We will need to have a formal location for policies and procedures and onboarding documentation needs to point to this area. 

We will need a calendar reminder of some sort to indicate that it is review time for policies and procedures. This task likely needs to be OICR and UCSC.

I would assign this to Denis, but I cannot from Jira

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-138)
┆Issue Number: DOCK-138
┆Epic: Dockstore Compliance

**Comment by denis-yuen** [comment]
@cricketsloan think there's a gremlin in the system

**Comment by denis-yuen** [comment]
Arbitrarily, I created a repeating calendar alarm on the wiki for April 12 
I think it makes sense for the formal location to continue to be https://wiki.oicr.on.ca/display/DOC/SOPs where the primer is currently.
