### ISSUE TITLE
Dockstore Entry Validation

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#193]
As we add Workflow entry types to the Dockstore, validation becomes even more important.  Users may be confused as to what constitutes a workflow and what constitutes a tool.  This becomes even more challenging for the user when you throw in different kinds of descriptor languages (CWL and WDL).

We need to set some solid definitions for Workflows and Tools for CWL and WDL, and we need to make these obvious to the user.  This can be done in part by updating documentation #190 .  

We can also add validation, so that when a user is adding/updating a workflow/tool, we can let them know if it is valid.  For example, if a user is refreshing a workflow Stub, we should check that it is a valid workflow of type CWL or WDL, and only then will we make it valid to publish.  Validation must be implemented in both the GUI and CLI.

**Comment by denis-yuen** [comment]
This one is a bit more involved than the previous assigned tasks, but should also be more satisfying and will introduce you more heavily into CWL and WDL.
