### ISSUE TITLE
Files included by Nextflow config are not indexed

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1932]
## Bug Report

If a Nextflow workflow's config file includes other config files, those other config files are not indexed, meaning that they will not be visible in the Files tab nor if you download the workflow as a zip.

### Steps to reproduce the behaviour 

1. Goto https://dockstore.org/workflows/github.com/nf-core/rnaseq:1.0?tab=files
2. Note how there is only one config file in the dropdown of files, nextflow.config
3. Note how the nextflow.config file has several lines like `includeConfig 'conf/base.config'`
4. If you go to the corresponding GitHub repo/branch, you'll see a conf directory with several config files that you would expect to be visible in the files dropdown: https://github.com/nf-core/rnaseq/tree/1.0/conf

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-217)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-217

**Comment by denis-yuen** [comment]
Warning to implementer, I think "includeConfig" is a custom Nextflow keyword. 
So our current code probably ignores it. See also #1872

**Comment by denis-yuen** [comment]
Test this after #1979

**Comment by garyluu** [comment]
Works locally with develop webservice and develop ui:
![image](https://user-images.githubusercontent.com/24548904/53762065-18490a80-3e95-11e9-90d8-2138839330a3.png)

**Comment by garyluu** [comment]
But doesn't work with staging...hmm.

**Comment by garyluu** [comment]
https://github.com/ga4gh/dockstore/issues/2181  .  Closing because it does work on develop and will likely work on staging once that issue is fixed.
