### ISSUE TITLE
Have Checker workflows default to hidden

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1933]
## Feature Request 

When Browsing the workflows, the checker workflows clutter the interface.  There is a facet to filter to only non-checker workflows, but for a new user this is counter intuitive.  The checker workflows only mean something in context of the workflow it is checking so by default I would want these hidden.

### Desired behaviour
When I am browsing the checker workflows are hidden with the facet ability to show them

### Environment (Browser or OS and Dockstore version)

Dockstore 1.5.2 and UI 2.2.2

**Comment by denis-yuen** [comment]
@cricketsloan FYI, edited out the redundant template components

**Comment by agduncan94** [comment]
I would go even further than just hiding by default, I don't think that the checker workflows should ever show up in search. No one would ever search for a checker workflow specifically. It is mostly useful for confirming that a tool/workflow works on some environment, which the average user wouldn't use. I think simply having a link to the checker workflow on the info tab is enough.

**Comment by garyluu** [comment]
Implementation wise, hiding it by default would be much simpler.  Revert https://github.com/dockstore/dockstore-ui2/pull/500 (the current elasticsearch index is broken for it anyways).  And just don't put the checkers into the index.

**Comment by denis-yuen** [comment]
Obsolete with #2006
