### ISSUE TITLE
phase out tools and workflows browsing in favour of search

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1934]
### Desired behaviour

Link to custom search for tools and workflows for the tools and workflow views
Phase out the current tools and workflows views (redirect current URL to the appropriate search view)
Looks like the only thing we're missing now is the default sort by stars

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-440)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-440

**Comment by agduncan94** [comment]
Based on discussion, no longer do the redirect of /tools or /workflows to /search, instead they will still exist, but only linked to in the sitemap.

**Comment by denis-yuen** [comment]
Sitemap link location is awkward (below "Support for Dockstore is provided by grants from Genome Canada, the National Institutes of Health, and the Province of Ontario.") Will fix separately
