### ISSUE TITLE
Establishing a Boundary: Ideas for SSH

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1936]
We are considering that the production system on AWS is our boundary.  So what tools/policies need to be in place for ssh access?

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/SEAB-39)
┆Issue Number: SEAB-39
┆Epic: Dockstore Compliance

**Comment by denis-yuen** [comment]
@cricketsloan  This particular discussion is probably better handled in private

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

One option: https://www.digitalocean.com/community/tutorials/how-to-set-up-multi-factor-authentication-for-ssh-on-ubuntu-16-04

and

https://aws.amazon.com/blogs/startups/securing-ssh-to-amazon-ec2-linux-hosts/
