### ISSUE TITLE
Better Handling for Multiple Users when Load Testing

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1938]
## Feature Request 

In order to simulate a large number of unique users, hitting Dockstore, we need to have a large number of unique users with tokens.

Since users are normally created by individual users using OAuth with GitHub and/or Google, we should probably have a SQL script that generates users with Dockstore tokens.

┆Issue is synchronized with this [JIRA Story](https://ucsc-cgl.atlassian.net/browse/DOCK-142)
┆Sprint: Seabright Sprint 1 Argo
┆Issue Number: DOCK-142
┆Epic: Dockstore Performance Testing

**Comment by denis-yuen** [comment]
https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/java/io/dockstore/client/cli/AdvancedIndexingBenchmarkIT.java#L141 might be useful.
