### ISSUE TITLE
Dockstore test yaml create -> validate

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1939]
### Desired behaviour
Change create in https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/resources/dockstore.yml#L57 to validate

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-246)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-246

**Comment by denis-yuen** [comment]
(done and not testable)
