### ISSUE TITLE
Odd table when no search results

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1947]
### Desired behaviour
No search results should not look like:

![image](https://user-images.githubusercontent.com/24548904/49534976-fb4e6c80-f890-11e8-8138-1572687f79aa.png)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-190)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-190

**Comment by NatalieEO** [comment]
Steps to reproduce

1. Select workflow as entry type
2. Search for term like "lololol"

**Comment by denis-yuen** [comment]
Looks solved on staging.dockstore.org
