### ISSUE TITLE
Document how to add descriptions to wdl workflows

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#1957]
Currently wdl workflows are confined to a one line description, taken as a 'string' from the meta parameter. A process needs to be created to either link to cwl readme or have markdown syntax support be added to either the wdl or dockstore end.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-148)
┆Issue Number: DOCK-148
┆Epic: Workflow Curation Tooling

**Comment by coverbeck** [comment]
You actually can enter a full blown markdown in the description, as long as it is on one line. You can use `\n` for the cases where the markdown needs newlines. It's a pain, but it works.

There is an OpenWDL [issue](https://github.com/openwdl/wdl/issues/221) to make multi-line easier, but until then we need to do something like [this](https://github.com/coverbeck/expeditions/blob/b515d9ffc7e9ffc7ef3cd3e44defc5bbf01f734c/u_of_michigan_aligner.wdl#L6)

**Comment by denis-yuen** [comment]
@cricketsloan I think that glitch with your migration tool is back (assigning everyone)

@Ldcabansay might be good to get documentation on this, touch-base with @agduncan94 or @coverbeck to get an orientation on the gh-pages based docs.dockstore.org (may want to update dockstore primer if it is insufficient)
