### ISSUE TITLE
uptime robot-able search health check

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1963]
### Desired behaviour

Need a health-check for elastic search (unhealthy both  when the index is not populated and/or down).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-284)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-284

**Comment by agduncan94** [comment]
Note to self:
Endpoint should check to see if the elastic search is up by checking things like size of index.

**Comment by denis-yuen** [comment]
Seems working on staging, hooked up to uptime robot with success
