### ISSUE TITLE
UI should indicate if you are a curator and/or admin

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1965]
## Feature Request 
The UI should have some visual indication when the current user is an admin and/or curator.

Some ideas:

1. On the Account page
1. Some icon/indicator next to the username in the dropdown in the top right of toolbar.
1. Both 1 and 2.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-156)
┆Issue Number: DOCK-156
┆Epic: Workflow Curation Tooling

**Comment by agduncan94** [comment]
Looks like we do say on the profiles page whether or not you are admin. We could also add the curator there.

It definitely is a bit hidden though.

**Comment by agduncan94** [comment]
Use the user.curator field in the same way the user.isAdmin in the accounts.component.html file.

**Comment by denis-yuen** [comment]
Could also investigate changing an icon or adding an icon in the accounts drop-down

**Comment by agduncan94** [comment]
I think both the icon and information on the profile page would be sufficient.

**Comment by NatalieEO** [comment]
> https://github.com/ga4gh/dockstore/issues/1990#issuecomment-455671403
![image](https://user-images.githubusercontent.com/16004905/51563778-2d685d80-1e42-11e9-90c7-4e9b573c7242.png)
And for the curator, it should be a clipboard or pen
![image](https://user-images.githubusercontent.com/16004905/51563795-39ecb600-1e42-11e9-8857-77cceb2e53ea.png)
