### ISSUE TITLE
My Workflows page says "You have not registered any workflows", then shows your workflows

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#1966]
## Feature Request 

When you navigate to the My Workflows page, it displays "You have not registered any workflows", and then, after a brief delay, shows your registered workflows.

If the delay is too long, this is a bit jolting.

Similar to #1937, but this is in different part of the code, so creating a separate issue for it.

### Desired Behavior

The page should initially display a progress bar, and then once the Ajax calls to fetch your workflows have completed, should remove the progress bar and either display your workflows, or if you don't have any, only then display the "You have not registered any workflows" message.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-283)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-283

**Comment by denis-yuen** [comment]
Note to self: might be worth putting into "ready for testing - develop"

**Comment by denis-yuen** [comment]
This comment seems misplaced
