### ISSUE TITLE
By default no tools are shown in search

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1973]
Since we always add the filter "Search: the Checker workflows is non-checker workflows" to the search page, it seems like it is only showing workflows and not tools. If you deselect the non-checker workflows then all the tools show.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-245)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-245

**Comment by garyluu** [comment]
It seems the is_checker property in the elasticsearch index is not set to '0' for tools

**Comment by denis-yuen** [comment]
Not applicable anymore, 
"Search: the Checker workflows is non-checker workflow" doesn't exist
