### ISSUE TITLE
Chrome tab crashes when using search

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#1987]
### Expected behaviour
Typing query into search should re-populate results as each character is typed. 

### Actual behaviour
Chrome tab crashes while typing query for the unpublished workflow 'expeditions' after first five characters ('exped'). Upon refresh, search works as normal query can be completed. 

### Steps to reproduce the behaviour 
Type 'expeditions' into search. On staging, we were able to reproduce this error on different machines on Chrome, but the reproducibility results were mixed on production. Bug could not be reproduced on safari or firefox.

### Environment (Browser or OS and Dockstore version)
Mac: Mojave 10.14.2
Chrome: 71.0.3578.98 (Official Build) (64-bit)
Dockstore (Staging): DockstoreAPI - 1.5.4 DockstoreUI - 2.2.5
Dockstore (Production): DockstoreAPI - 1.5.1 DockstoreUI - 2.2.2

**Comment by denis-yuen** [comment]
Interesting, was unable to reproduce on a Mac with Chrome 70. 
But it gave me the option of updating to Chrome 71 which does crash

**Comment by coverbeck** [comment]
We also saw this fail on an Ubuntu 16 box with Chrome 71, no Oh Snap page, but the page stopped responding.

But it didn't fail on an Ubuntu 18 with Chrome 71.

**Comment by garyluu** [comment]
Failing on my Ubuntu 18 with Chrome 71 and Chromium 71

**Comment by garyluu** [comment]
Possibly the autocomplete portion is the problem

**Comment by denis-yuen** [comment]
In the narrow, it seems to work on my Mac with Chrome 71

**Comment by Ldcabansay** [comment]
Working on my mac with chrome 71 on DockstoreUI - 2.2.6

**Comment by coverbeck** [comment]
Works for me too on Mac. 👍
