### ISSUE TITLE
Edit tool GUI and workflow GUI

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#199]
Tool: Edit things like the name, default path from the web UI
Workflow: Edit the same for workflows

**Comment by jpatricia** [comment]
To elaborate, it would be nice to:

1. Be able to see the default cwl path, the default wdl path, and the default dockerfile path in the GUI
2. To be able to edit and change them via the GUI 

@denis-yuen need to see if we want to automatically change the paths for all versions as well, or just keep the current behaviour
