### ISSUE TITLE
Add title tag to pages

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#1990]
Currently no matter what page on dockstore you are on, the page always has the title Dockstore.
![tabs](https://user-images.githubusercontent.com/6331159/50903967-2165b000-13ed-11e9-8868-6ed80c89da16.png)

We should have it a bit more specific, ex. My Tools, My Workflows, Account.

Replace all title with DOCKSTORE | route page name

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-200)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-200

**Comment by agduncan94** [comment]
https://angular.io/guide/set-document-title

**Comment by agduncan94** [comment]
Not sure if we want to use the format 'Dockstore | My Workflows' or Simply 'My Workflows'. I prefer the first.

**Comment by garyluu** [comment]
I prefer the first too

**Comment by cricketsloan** [comment]
![image](https://user-images.githubusercontent.com/3299651/51410415-70ac8e80-1b19-11e9-8fec-86c70084abf3.png)

**Comment by cricketsloan** [comment]
And for the curator, it should be a clipboard or pen

**Comment by cricketsloan** [comment]
![image](https://user-images.githubusercontent.com/3299651/51410489-9f2a6980-1b19-11e9-8160-f6b584571b6f.png)

**Comment by denis-yuen** [comment]
Reviewed and seems functional as expected on staging.dockstore.org
