### ISSUE TITLE
More Organizations Endpoints

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#1992]
## Feature Request 
A few endpoints that would be useful.

### Desired behaviour
- Some way to retrieve the members of an organization and possibly their role too.  Another option is to have the organizations object have members.
- Some way to search organization by name.  Either as a new endpoint or alter the current one to have a id query parameter and name query parameter.
- Some way to retrieve organization-specific events

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-276)
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-276

**Comment by agduncan94** [comment]
For the second point, I think you only need one parameter since we always know if a parameter is an id or a name based on its composition.

**Comment by denis-yuen** [comment]
Not really the kind of thing that is reviewed independently
