### ISSUE TITLE
Implement topic vs (lengthy) description for organizations

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#1999]
### Desired behaviour

User should be able to specify a short topic that shows up in searches, listings, etc. 
A longer description would be for when you are viewing the actual organization page, similar to a readme on github

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-272)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-272

**Comment by garyluu** [comment]
Topic is visible in organizations page, searchable in organizations page, visible in organization page.
Description is visible in organization page
