### ISSUE TITLE
Implement markdown rendering of description fields for orgs and collections

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2000]
### Desired behaviour

n/t

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-230)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-230

**Comment by denis-yuen** [comment]
@agduncan94 you're well on the way for this

**Comment by agduncan94** [comment]
Gary has done this for orgs, still needs to be added for collections.

**Comment by agduncan94** [comment]
Are we expecting something similar to organisations with the short topic and longer description (markdown)?

**Comment by NatalieEO** [comment]
Markdown seems to be working for collection and organization descriptions on staging.dockstore.org DockstoreUI - 2.3.0-beta.2
