### ISSUE TITLE
Events for organizations

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2002]
### Desired behaviour

Display events for organizations. May need to flesh-out and make wireframe more attractive

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-229)
┆Issue Number: DOCK-229

**Comment by agduncan94** [comment]
The basics of this have been done. Planning to add the following:
* Pagination (webservice) and maybe 
* Add timestamp in UI on hover

**Comment by denis-yuen** [comment]
FYI, there's pagination code that can be copied/re-used from tools/workflows

**Comment by cricketsloan** [comment]
REPLACED BY DOCK‌-519
