### ISSUE TITLE
Change organisation to organization

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2005]
Use the American spelling of organisation.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-242)
┆Issue Number: DOCK-242

**Comment by denis-yuen** [comment]
In case you're curious for Canada https://g.co/trends/Uww2P

> In America, there is only one choice for the spelling of this word. In Britain, both see common use.
> 
> While some British editors and publishers might write off organization as an Americanism, the spelling does seem to be gaining ground in British English.
> 
> In other words, you should be safe using organization wherever you find yourself writing. If you write in Great Britain and your workplace has a preference towards organisation, you should obviously follow that.
> 
> You can remember that organisation is used with more frequency in the U.K. relative to that of the U.S. since it shares an S with the towns Salisbury, Sandwich, and Sheffield, all of which are located in the U.K. By thinking about all the U.K. cities with names that start with S, you can remember to always use organisation in the U.K.
> 
https://writingexplained.org/organisation-vs-organization-difference
