### ISSUE TITLE
Initial demo for organizations

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2020]
### Desired behaviour

demo for the biweekly

#### Needed
- user can request org, edit org (topic and name), and add collections (edit description and name)
- curator can approve or reject orgs
- other users can see organizations (bare-bones with just collections)
- organizations page

#### Not minimum, but needed soon after
- other user can join org

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-228)
┆Issue Number: DOCK-228

**Comment by cricketsloan** [comment]
This seems done to me
