### ISSUE TITLE
Organizations - usability review

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2021]
## Definition of Done
At least 2 people have reviewed all aspects of the organizations pages and usability.

There are a list of tickets files and linked to this ticket.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-189)
┆Sprint: Seabright Sprint 3 Coble
┆Issue Number: DOCK-189
┆Epic: Organizations for Dockstore

**Comment by cricketsloan** [comment]
https://docs.google.com/document/d/1JglBnwQYUK9ZQx4h4UUP2P8aR8sAt7_RFzC1dYc0Tjk/edit?ts=5c58b0b7 ( https://docs.google.com/document/d/1JglBnwQYUK9ZQx4h4UUP2P8aR8sAt7_RFzC1dYc0Tjk/edit?ts=5c58b0b7 )
