### ISSUE TITLE
Documentation required for docker_compose logging

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2024]
### Desired behaviour

- [x] https renewal
  * `/home/ubuntu/certbot-auto renew &> /home/ubuntu/logs/certbot-auto.log`
- [x] password generation 
  * `htpasswd -c ./nginx/kibana.htpasswd user1`
- [x] backup restore from zip commands
  * starting from a zip, how do I get the backup into elastic search?
- [x] permissions issue
  * sudo chown -R ubuntu:ubuntu  essnapshot
  * sudo chmod -R 775 essnapshot
- [x] version of elastic search curator
- [x] change essnapshot_backup.sh to absolute aws bin path to get previous file size
- [x] change buffer time for elastalert
- [x] quieter backups (aws and zip)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-268)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-268

**Comment by denis-yuen** [comment]
Tune CPU usage via https://www.elastic.co/guide/en/elasticsearch/reference/current/tune-for-indexing-speed.html#_increase_the_refresh_interval

Also set the default refresh for new indices

**Comment by denis-yuen** [comment]
This one might be tricky due to https, try to run locally without https. 
Might treat this as a way to learn docker compose as opposed to totally reviewing this with https
@garyluu  please link docs for how you did this recently

**Comment by garyluu** [comment]
https://github.com/dockstore/compose_setup/blob/develop/DEV-README.md#self-signed-certificate

**Comment by NatalieEO** [comment]
Was able to run locally without https.
