### ISSUE TITLE
Logs missing client IP

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2046]
### Expected behaviour
`server-url: https://dockstore.org:8443` in the config: have proper client ip
`server-url: https://dockstore.org:443/api` in the config: have proper client ip

### Actual behaviour
`server-url: https://dockstore.org:8443` in the config: missing proper client ip
`server-url: https://dockstore.org:443/api` in the config: have proper client ip

### Steps to reproduce the behaviour 
`./dockstore --server-metadata` with any recent Dockstore CLI

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-207)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-207

**Comment by coverbeck** [comment]
Confirmed that I can see my IP address in the logs using both `https://staging.dockstore.org/api` and `https://staging.dockstore.org/api`, for version  1.6.0-beta.0
