### ISSUE TITLE
Should be able to display secondary files

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#205]
We need the GUI to be able to show dependent descriptor files reached via import statements or similar
This will entail the creation of a new dropdown in the Descriptor tab for both Workflows and Tools

**Comment by jpatricia** [comment]
Will need an example workflow/tool registered in the staging dockstore.org

**Comment by denis-yuen** [comment]
@jpatricia 

Examples:
On staging, I've created an example that you can retrieve from the web service at 
https://staging.dockstore.org:8443/workflows/published/155

Note that you can get the "primary" CWL (the current descriptor) file either by comparing paths or by hitting the following URL 
https://staging.dockstore.org:8443/workflows/155/cwl?tag=master
You can get the "secondary" CWL files via 
https://staging.dockstore.org:8443/workflows/155/secondaryCwl?tag=master

**Comment by denis-yuen** [comment]
Implemented and deployed in production
