### ISSUE TITLE
Export as ZIP fails in develop branchfor unpublished workflows

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2050]
## Bug Report

Clicking on the Export as Zip button on the Info tab of an unpublished workflow fails.

It fails because [this line](https://github.com/dockstore/dockstore-ui2/blob/f8cbba25b2eec99b7ce58f8eda79157299fc108f/src/app/shared/extended-workflows.service.ts#L54) is using `this.basePath` instead of `this.configuration.basePath` like the WorkflowsService class that it extends does. Since `this.basePath` is set to `http://localhost` instead of `http://localhost:8080` the call fails.

This works in production/staging and the master branch.

### Steps to reproduce the behaviour 

1. Log in to a local instance of the UI, `http://localhost:4200`
1. Go to My Workflows
1. Go to an unpublished workflow (create a hosted workflow if you don't have an unpublished workflow)
1. Open Chrome Dev Tools
1. Click the Export as Zip button
1. Nothing happens on the page; in dev tools, you'll see an OPTIONS call to `http://localhost` failed, which failed because the web service is running on `http://localhost:8080`.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-208)
┆Issue Number: DOCK-208

**Comment by denis-yuen** [comment]
Random thought, is this due to a different web.yml used in compose setup vs what you have locally?
https://github.com/dockstore/compose_setup/blob/1.5.3/templates/dockstore.model.ts.template#L12

**Comment by coverbeck** [comment]
Further info -- dev build works if run in production mode.
