### ISSUE TITLE
Use gravatar or URL for organisation logo

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2052]
This would require:
* adding a column to the organisation.java along with migration
* webservice should auto populate with gravatar photo if an email is given
* in UI, should be able to use custom url, gravatar, or none

Note we use gravatar for populating the images for users, so this could be used as a starting point.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-220)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-220
┆Epic: Organization for Dockstore

**Comment by denis-yuen** [comment]
Hmmm, I think there are potential risks with a custom URL. 
Let's start with a gravatar for the associated email, a default placeholder when a gravatar is not provided

**Comment by agduncan94** [comment]
I think gravatar should be an option, I don't think we should use it as default. There is a high chance that the gravatar is not relevant to the organisation, but instead more relevant to the user. Note we should also update the organisation creation form to mention the email is used for gravatar.

**Comment by denis-yuen** [comment]
Long term, we should also allow image upload, but for the scope of this ticket, I think allowing for choosing between a gravatar and default placeholder would work for now

**Comment by NatalieEO** [comment]
For the gravatar associated with the email, do you guys mean the email of the account that created the organization or the email field that's on the create org form? And if it's the latter, do you have permissions/would you know where to grab their gravatar?

**Comment by coverbeck** [comment]
What about if we whitelist only urls starting with `https://avatars\d+/githubusercontent.com` to start with?

**Comment by garyluu** [comment]
I'd assume it'd be its own separate field in the organization create form.

**Comment by denis-yuen** [comment]
For gravatar, you would generally not need permissions. There's a write-up here https://en.gravatar.com/site/implement/images/ but there should be code in the UI already for profiles. You would probably want to use the email that's on the create org form. 
 
I also like the toggle option with a whitelist for URLs, start with just github avatars for now.

**Comment by david4096** [comment]
The original issue asked for gravatar emails to be used for the org. Instead, gravatar is being used to sanitize images added by URL. This works as expected.

![Screenshot from 2019-03-19 14-00-36](https://user-images.githubusercontent.com/3795586/54641453-735f2d80-4a4f-11e9-9751-7e061a735658.png)
