### ISSUE TITLE
CORS access-control-allow-origin header is incorrect for requests to port 443

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2056]
## Bug Report

The `access-control-allow-origin` header is set to two values when you hit `https://dockstore.org/api` and `https://staging.dockstore.org`. It's set to the client's host plus `*`.
It should only be set to one value, per [MDN](https://developer.mozilla.org/en-US/docs/Web/HTTP/Headers/Access-Control-Allow-Origin).

Interestingly, it correctly works if you hit the 8443 endpoint.

### Expected behaviour

This is working correctly when the port is 8443.
```
Request URL: https://staging.dockstore.org:8443/api/ga4gh/v2/metadata
Request Method: OPTIONS
...
access-control-allow-origin: http://localhost:4200
```

### Actual behaviour

When going against port 443, there are two values:
```
Request URL: https://staging.dockstore.org/api/users/user/extended
Request Method: OPTIONS
...
access-control-allow-origin: http://localhost:4200, *
```
### Steps to reproduce the behaviour 

1. Run a local instance of the UI, changing dockstore.model.ts to:
```
  static readonly HOSTNAME = 'https://staging.dockstore.org';
  static readonly API_PORT = '443';
```
2. Open Dev tools, navigate to localhost:4200, and see the response header for the OPTIONS call.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-265)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-265

**Comment by denis-yuen** [comment]
This is blocking update on the Firecloud side to use the more robust 443 port

**Comment by NatalieEO** [comment]
Yes this is working, no longer seeing "access-control-allow-origin: http://localhost:4200, *". Changed to "access-control-allow-origin: http://localhost:4200"
