### ISSUE TITLE
Selected filename in files tab should be wider

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2057]
## Feature Request 

If there is room, the control that shows the currently selected filename in the Files tab of a workflow should be wider.

Currently it unnecessarily truncates the filename, even if there is enough room to display it.

See the screenshots comparing the display when the dropdown has been clicked vs. when it has not been clicked. There is enough room to display the filename when the dropdown has not been clicked.

![screen shot 2019-01-30 at 12 45 16 pm](https://user-images.githubusercontent.com/1049340/52011568-2d450f00-248d-11e9-88cf-435cb0acb971.png)

![screen shot 2019-01-30 at 12 45 32 pm](https://user-images.githubusercontent.com/1049340/52011567-2d450f00-248d-11e9-88ab-dd864db29bc3.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-264)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-264

**Comment by david4096** [comment]
Confirming the Files pulldown is now wider and file names are easier to read without clicking the pulldown.

DockstoreAPI - 1.6.0-beta.3DockstoreUI - 2.3.0-beta.2
staging.dockstore.org
