### ISSUE TITLE
Cannot select text from Launch tab on develop branch

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2068]
## Bug Report

With a local build running off the develop branch, on the Launch tab of a tool or workflow, you cannot select text to copy it. Tried on Chrome and FireFox on a Mac.

This works in production and staging.

### Steps to reproduce

1. Goto [a tool](http://localhost:4200/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:develop?tab=launch) or [workflow](http://localhost:4200/workflows/github.com/DataBiosphere/topmed-workflows/TopMed_Variant_Caller:1.30.0?tab=launch) in your local UI
2. Try to select text; you can't.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-222)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-222

**Comment by garyluu** [comment]
Oops, I fixed this already.  (I also broke it btw)

**Comment by coverbeck** [comment]
This works on staging.dockstore.org, version 1.6.0-beta.0
