### ISSUE TITLE
Search on homepage does not perform requested search

### ISSUE THREAD

**Issue by NatalieEO** [ga4gh/dockstore#2069]
## Bug Report
When you try to enter a search from the home page, the search is not done. You are only redirected to the search page and must enter it again. One thing to note is that while you are ultimately taken to ```http://localhost:4200/search?searchMode=files``` ,  the url will very briefly include the search as a param  e.g. ```http://localhost:4200/search?search=topmed```. You can go back to it, but the right search doesn't show up on this page either.

### Steps to reproduce the behaviour 

1. Run Dockstore locally, ```http://localhost:4200```
2. Type any term into search bar of the homepage.
3. Enter, you'll be directed to the search page, but no search has been performed.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-259)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-259

**Comment by denis-yuen** [comment]
Reproduced by @coverbeck , not an issue with elastic search it seems

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified on +2.3.0-beta.2+ ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.3.0-beta.2 ) on staging.dockstore.org
