### ISSUE TITLE
Create document for GA4GH outlining the WES endpoint differences

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2070]
WES endpoints, including those used in the exercise at Basel, are often implemented differently and require some adjustments to the client request. These should be documented as much as possible.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-219)
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 4 Dory
┆Issue Number: DOCK-219
┆Epic: WES API support

**Comment by denis-yuen** [comment]
Should be much more readable version of https://github.com/ga4gh/cloud-interop-testing/blob/develop/docs/example_requests.md contributed to either that repo or the WES repo

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

I will be adding to the document https://docs.google.com/document/d/1bOiHEakZ03mGjFkhSHrUuHCg43OBFxr7hut8SEq1oOo/edit?usp=sharing ( https://docs.google.com/document/d/1bOiHEakZ03mGjFkhSHrUuHCg43OBFxr7hut8SEq1oOo/edit?usp=sharing ) that James Eddy has started.
