### ISSUE TITLE
On info tab, workflow version information should display the version

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2072]
## Feature Request 

The `Workflow Version Information` section when you're on the Info tab should explicitly display the version. While the user can still derive the version from elsewhere on the page, might as well have it with right there as well for clarity.

You need to run a local build off develop branch to see this.

![screen shot 2019-01-31 at 12 59 49 pm](https://user-images.githubusercontent.com/1049340/52085373-33a0bd00-2559-11e9-90b7-c4be7f4d37bf.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-258)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-258

**Comment by coverbeck** [comment]
When I typed 1.29.0, I was looking at the checkmark in `Recent Versions`, thinking that meant the currently selected version. Now I realize that means verified, right?

If so, that UI should probably be tweaked in that panel.

**Comment by agduncan94** [comment]
@coverbeck 
The issue with highlighting is that only a subset of the versions are shown. It could be the case that the currently selected version is not in the recent versions.

Would it still make sense to highlight? or is this inconsistent?

**Comment by coverbeck** [comment]
@agduncan94 I think it could still make sense to highlight if visible, but not sure. Another thought is that you could always ensure that the current version is displayed in the subset.

It was actually @garyluu 's suggestion to highlight, so he should opine as well.

Another or additional option is to have a different icon for verified, so that it more clearly indicates its function. That's beyond the scope of this issue though. Maybe the material verified_user material icon? Although that would have implications for other pages.

**Comment by garyluu** [comment]
if it's not in the recent versions, it's simply not highlighted.  If it's not highlighted in recent versions, all that means is your current version is not considered recent.  You should feel a need to highlight something all the time.

**Comment by garyluu** [comment]
Looks like it's working on staging after selected versions on the "Recent Versions" section as well as the version tab:

![image](https://user-images.githubusercontent.com/24548904/54766899-80585a00-4bd2-11e9-9a98-952314ab2c54.png)
