### ISSUE TITLE
Can import CWL files with or without an import

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#208]
https://github.com/common-workflow-language/workflows/blob/master/workflows/FestivalDemo/filtercount.cwl

In the above link the tool cwls are imported with just run: grep.cwl.
In other places the tool cwls are imported with run: {import: grep.cwl}.

We need to change the code to deal with both cases.

**Comment by agduncan94** [comment]
To fix this it is a matter of changing the way we parse the YAML to check if the content of run in the CWL file is a String or a map <String,Object>, and getting the name of the file accordingly.  I didn't have time to implement this, but if you checkout the workflow_dag_resource branch and search all files for CHECKIFIMPORTMAP you can find where to make the changes.

**Comment by jpatricia** [comment]
Related to #205

**Comment by denis-yuen** [comment]
Also needs to work for Tools

**Comment by denis-yuen** [comment]
Implemented and deployed, see https://www.dockstore.org/workflows/denis-yuen/dockstore-whalesay
