### ISSUE TITLE
Account controls displays warning when it doesn't need to

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2084]
## Feature Request 

If you go to the Dockstore Account Controls tab under Accounts, you get a warning about using extreme caution when changing controls (see screenshot).

This warning makes sense when you can perform actions on the page, but, as in my screenshot, if you can't do any of the actions, it's slightly disconcerting to see a big red warning -- when you first tab through there, it looks like you're in some sort of error state.

![screen shot 2019-02-05 at 9 48 27 am](https://user-images.githubusercontent.com/1049340/52293351-72ed5600-292b-11e9-8730-dddda712cc14.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-255)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-255

**Comment by denis-yuen** [comment]
If changing is disabled, remove the warning

**Comment by denis-yuen** [comment]
@rshreya

**Comment by denis-yuen** [comment]
Properly hidden when user name cannot be changed
(shown when it can)
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
