### ISSUE TITLE
Improvement to dockstore CLI when Docker daemon is down

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2088]
Vincent Carey- "Hi -- I had the misfortune of attempting to use the CLI when my docker
desktop had died.  The error messages were not particularly helpful and only
when I tried to use cromwell manually did I come to an understanding
of the situation.  Perhaps the CLI could check for running docker and
fail with a clear message if such is not found?"

!Screen Shot 2019-02-05 at 12.35.56 PM.png|thumbnail!

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-238)
┆Issue Number: DOCK-238
┆Attachments: <a href="https:&#x2F;&#x2F;ucsc-cgl.atlassian.net&#x2F;secure&#x2F;attachment&#x2F;10125&#x2F;Screen+Shot+2019-02-05+at+12.35.56+PM.png">Screen Shot 2019-02-05 at 12.35.56 PM.png</a>

**Comment by denis-yuen** [comment]
Replacement for #2068

**Comment by denis-yuen** [comment]
Actually, duplicates #2082
