### ISSUE TITLE
Organization and collection names should be case insensitive

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2089]
Need to add case constraints to the DB.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-241)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-241

**Comment by denis-yuen** [comment]
To break this down
1) webservice should return the same organization whether we look for for OICR, oicr, or OiCR. 
2) a new database constraint should enforce that there is only one entry for the above three
3) tests (obviously)

**Comment by agduncan94** [comment]
This works for organisations but not for collections. @denis-yuen 
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0

**Comment by denis-yuen** [comment]
Come to think of it, I didn't see that index, so I'm not sure its working properly 
Although I'm puzzled why the test is passing

**Comment by denis-yuen** [comment]
hmmm https://liquibase.jira.com/browse/CORE-3369 @coverbeck

**Comment by denis-yuen** [comment]
Damnit 
https://liquibase.jira.com/browse/CORE-2895

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Verified in DockstoreAPI \- 1.6.0-beta.4DockstoreUI \- 2.3.0-rc.0Swagger
