### ISSUE TITLE
More granular and configurable limits on hosted workflows

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2092]
## Feature Request 

Currently the number of hosted workflows and hosted workflow versions per user is limited. The limits are start-up parameters, and apply to each user.

With the upcoming implementation of #1768, we expect some users might run into the existing limits -- the limits may need to be increased. A few ideas are:

1. Just increase the limits for everybody
2. Implement a configurable limit on a per-user basis, and admins can increase the limits for selected users.
3. Make the limits more adaptive or time-based, e.g., rather than having a hard limit of n workflows, make it a limit of n workflows per month.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-253)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-253

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

New commit pushed with fix; you’ll have to wait until it is deployed.

**Comment by Ldcabansay** [comment]
Verified that version limit is now honored when posting zip on DockstoreAPI - 1.6.0-rc.0
