### ISSUE TITLE
Refresh all tools/workflows in an organization

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#210]
Might be a useful idea to allow users to be able to refresh organizations/groupings of entries instead of just an individual entry or all entries.  For example the UI could have refresh buttons beside the name of all the organizations on the lefthand side of my tools and my workflows which would refresh a grouping of entries.

**Comment by agduncan94** [comment]
This would also require adding a new API call for both tools and workflows which refreshes all the tools/workflows in the given org.

**Comment by denis-yuen** [comment]
The refresh message has a partial name for tools which can be ambiguous. 
For example refreshing "quay.io/cancercollaboratory" will say "Refreshing cancercollaboratory..."

**Comment by denis-yuen** [comment]
If a message appears during fresh, dismissing it, browsing to a different page and then coming back, the message may return.

**Comment by denis-yuen** [comment]
The refresh for workflows is worse and just displays a generic message "Refreshing Organization ..."

**Comment by garyluu** [comment]
Not sure what message is being dismissed.  The bootstrap alert is currently set to not be dismiss-able.

**Comment by denis-yuen** [comment]
An error message like a 500 or a gateway timeout

**Comment by denis-yuen** [comment]
Ran into #977 and #975 , splitting those guys out. Otherwise this works in general.
