### ISSUE TITLE
When a user initially signs up we should refresh workflows

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#211]
When a user signs up they now have there github account linked, which is likely where they store workflows.  We should refresh this right away, like we do for tools.

**Comment by agduncan94** [comment]
Should we also do this when we link Bitbucket and Gitlab accounts?

**Comment by agduncan94** [comment]
How would we go about doing this?
For Bitbucket and GitLab we can do what we do with Quay and just call a refresh (maybe add refresh by git registry so that we don't refresh all?).
For GitHub, the account is linked on signup, so should we automatically grab workflows on initial signup? Or would this be confusing to the user and we should not automatically grab github workflows.

**Comment by agduncan94** [comment]
@denis-yuen do you think this is a good idea? or should we not do the auto refresh because it might be confusing to users.

**Comment by agduncan94** [comment]
I feel like this is no longer relevant. Especially if we end up changing how users register on dockstore. I think it can be closed. @denis-yuen

**Comment by denis-yuen** [comment]
Interesting, this might be a case for improved documentation.

**Comment by denis-yuen** [comment]
Obsolete if we move toward a webhook approach
