### ISSUE TITLE
Alternative Visualization for WDL in Dockstore

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2112]
Using the [EPAM Pipeline Builder](https://github.com/epam/pipeline-builder), provide an alternative visualization of WDL workflows in Dockstore. On the DAG tab of WDL workflows, a radiobutton will let the user select whether she wants to see the current Dockstore-generated visualization, or a visualization done with the Pipeline Builder.

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-159)
┆Issue Type: Epic
┆Issue Number: DOCK-159

**Comment by denis-yuen** [comment]
Duplicates #1557
