### ISSUE TITLE
Allow Zip to Published to Dockstore

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2114]
At lot of detail is in already in DOCK-154, but here is another summary:

Dockstore currently recognizes two kinds of workflows:

1. Workflows in source control, e.g., GitHub
1. Workflows hosted by Dockstore itself

We need a 3rd category of workflows, workflows that are built. The layout in the source control repo may not match what the user will need -- some build steps may need to be performed.

Dockstore would have an API that lets a tarball be published.

Additionally, this provides a way for workflow developers to do CICD with their workflows; when they make a change to the workflow, they can have a CI server run tests and the publish the version if the tests pass.

Probably need the following stories:

* More detailed use cases
* A design document
* Maybe split this up into workflows and tools
* Split up UI and backend

┆Issue is synchronized with this [Jira Epic](https://ucsc-cgl.atlassian.net/browse/DOCK-175)
┆Issue Type: Epic
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-175

**Comment by denis-yuen** [comment]
This has already been deployed to staging
