### ISSUE TITLE
Unpublished checker workflows still appear in search results on production

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2118]
### Expected behaviour
Unpublished checker workflows should not appear in search after hotfix.

### Actual behaviour
Unpublished parent workflows were removed from search in  #1941 #1956, but the unpublished checker workflows are still appearing. 
### Steps to reproduce the behaviour 
When querrying ['topmed'](https://dockstore.org/search?search=topmed) in search, the [CRAM_no_header_md5sum_CWL](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/CRAM_no_header_md5sum_CWL_cwl_checker) and [CRAM_no_header_md5sum_wdl_checker](https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/CRAM_no_header_md5sum_wdl_checker) still appear in search results even though both checker workflows are unpublished. Note: the checker workflows were automatically unpublished when parent workflows were unpublished manually by user. 

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.5.4
DockstoreUI - 2.2.6
Chrome  72.0.3626.96 
Mac 10.14.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-515)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.5.5
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-515

**Comment by garyluu** [comment]
1. Unpublished entries should not be indexed
2. Checker workflows should not be indexed (this fix likely hasn't made it to production yet)

**Comment by david4096** [comment]
Checking in to confirm that when a workflow is added with a checker workflow, if that checker workflow is `Unpublished` it will still appear in search.

**Comment by david4096** [comment]
I have a fix for this working locally that updates the ES index during unpublishing events of the parent workflow. Working on an integration test to demonstrate it.
