### ISSUE TITLE
Editable display name for organizations and collections

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2119]
### Desired behaviour
Organizations and Collections would have an editable display name that is separate from the UUID and url. This display name should be unique (given on a first come, first served basis), and allow for special characters and spaces. The display name should be editable on the user interface for organization/collections maintainers.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-516)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-516
┆Epic: Organization for Dockstore

**Comment by agduncan94** [comment]
Just to clarify, will the display name ever be used to link directly to an organisation?

**Comment by agduncan94** [comment]
Also, this was what I had in mind for displaying the display name alongside the main name
![jbrowse](https://user-images.githubusercontent.com/6331159/52882045-71463e00-3134-11e9-973d-ff8461ad2533.png)

**Comment by denis-yuen** [comment]
Ah Twitter. That's actually a good example. Twitter handles don't change, but you do the see the display change in lists, replies, and the like.

**Comment by agduncan94** [comment]
What should we allow? alphanumeric, spaces, and punctuation (\p{Punct})

**Comment by denis-yuen** [comment]
During review, one issue:
1. Expected the non-display names (just called "names") to be used in the URLs when browsing around normally (currently using database ids)
2. Expected display name to be used when browsing (seems working)

**Comment by Ldcabansay** [comment]
> What should we allow? alphanumeric, spaces, and punctuation (\p{Punct})

Was this either specified? I'm finding that only some special characters and punctuation are accepted. Good news: consistent between organizations and collections, and also consistent between UI and swagger.

Accepted: &(),'-_
Rejected:`~!@#$%^*+={}[]\|.?<>;:"

**Comment by agduncan94** [comment]
@Ldcabansay Denis and I decided on the accepted &(),'-_ and not all punctuation. The logic was that it is better to be more restrictive at first and slowly relax constraints than to go the other way. I had updated the constraints in the code but I forgot to update them here in this issue, thanks for looking into it.

**Comment by Ldcabansay** [comment]
Verified that this works on 1.6.0-beta.3
