### ISSUE TITLE
Users should be able to star repositories

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#212]
This is a feature that seems to have been thought of before but not implemented.  I think it would be nice to have as it would help get more users of tools/workflows to add accounts, and not just publishers.

**Comment by denis-yuen** [comment]
This probably requires a bit of thought. However, I do like starring vs rating. 
A star is a way of registering interest or nebulous support whereas giving a rating (say between 1 and 5) could lead to trolling or friction.

**Comment by denis-yuen** [comment]
Let's elaborate on this one, this may need a full fledged-specification if this grows too much. 

Required components:

1. web service database changes (Java models with new relationship between end-user and entries, and company+bio+location+avatar_url for each user)
2. database migration script (to create new relationship and store information needed for end-users)
3. migration program that will populate the company+bio+location for existing users given a github access token
4. UI will need a button to star/unstar tools ala GitHub
5. Clicking on the number of stars should show the users that starred a particular repo

**Comment by denis-yuen** [comment]
https://wiki.oicr.on.ca/display/SOFTENG/Dockstore+Starred+Entries+Specification

**Comment by denis-yuen** [comment]
Thanks @agduncan94 and @garyluu 
This is functional on staging.dockstore.org to the extent that I think new issues should be created for specific problems.
