### ISSUE TITLE
Add Pagination to Events API

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2122]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-519)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-519

**Comment by agduncan94** [comment]
Works, tried on 
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0
