### ISSUE TITLE
Error message does not disappear when navigating away from page

### ISSUE THREAD

**Issue by NatalieEO** [ga4gh/dockstore#2124]
## Bug Report
When an error surfaces at the top of the page, it will not go away when you navigate to another page. It will go away if you refresh the page. 

### Steps to reproduce the behaviour 
1. Go to staging.dockstore.org
2. Do something to create an error message. Ex: Open the same workflow/tool in 2 tabs. Star it in one tab. Then go to second tab and attempt to star it again. You will get an error message at the top of the page.
3. Navigate away from page by clicking another link on the site.
4. You'll still see error from previous page.
![image](https://user-images.githubusercontent.com/16004905/52881895-d5f49f00-311a-11e9-8e12-1b23737a350f.png)

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-521)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-521

**Comment by garyluu** [comment]
Works for the current pages that we have

**Comment by garyluu** [comment]
Oops, managed to reproduce it.  Go to my-workflows, try to add a git repo asdf/asdf workflow to cause error, go to home page, to to setup account

**Comment by NatalieEO** [comment]
Ahh, same deal when navigating to starred page after getting an error somewhere else on the site. More widespread than I thought...

**Comment by coverbeck** [comment]
Now I wonder if we shouldn't just go with the other proposed fix, that each page cleans up after itself.

Might be risky this close to release though.

**Comment by denis-yuen** [comment]
> Might be risky this close to release though.

I agree, maybe we actually use a hubflow release branch this time

**Comment by NatalieEO** [comment]
yeah I'm wondering about that too. Could add the quick fix line to these two page components for this release and maybe do the more thorough fix after the release? But the con with that is that we could be missing more on another pages/components.

**Comment by garyluu** [comment]
I think the easiest way is to have subscription in the app component which clears the alert every time it detects router change

**Comment by denis-yuen** [comment]
Looks fixed on 
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
