### ISSUE TITLE
PUT and POST are reversed in OrganizationResource

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2128]
## Bug Report

The endpoint to create an organization has the [@PUT](https://github.com/ga4gh/dockstore/blob/0e9b4e169b7d6dc681b22e4cedab7db27257e2d3/dockstore-webservice/src/main/java/io/dockstore/webservice/resources/OrganizationResource.java#L324) annotation. It should be POST.

Conversely, the code to update an organization is annotated with `@POST`; it should be annotated with `@PUT`.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-523)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-523
┆Epic: Organization for Dockstore

**Comment by david4096** [comment]
Should close with https://github.com/ga4gh/dockstore/pull/2176 after review in staging.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified in +2.3.0-beta.2+ ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.3.0-beta.2 ) UI and +1.6.0-beta.3+ ( https://github.com/ga4gh/dockstore/releases/tag/1.6.0-beta.3 ) API.
