### ISSUE TITLE
CWL Viewer broken in develop branch

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2129]
## Bug Report

The CWL Viewer is not working on develop branch. Clicking on the CWL viewer radio button leads to this error (note `url=undefined` in the url):

```
The Common Workflow Language Viewer was unable to process the CWL. It returned the following error:
Http failure response for https://view.commonwl.org/workflows?url=undefined%2Fblob%2Fmaster%2Fmetaphlan_wfl.cwl: 400 OK
```

### Steps to reproduce

Go to http://localhost:4200/workflows/github.com/dockstore-testing/Metaphlan-ISBCGC:master?tab=dag

Per @garyluu , problem is that the cwl-viewer.component.ts is expecting an `ExtendedWorkflow` but getting a `Workflow`.

Fix will most likely be needed in fullscreen mode as well.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-525)
┆Issue Type: Bug
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-525

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified in +2.3.0-beta.2+ ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.3.0-beta.2 ) on staging.dockstore.org
