### ISSUE TITLE
Hook up parent DAG and child WDL Viewer component to a shared service

### ISSUE THREAD

**Issue by rjbautis** [ga4gh/dockstore#2141]
## Feature Request 
EPAM WDL visualizer component currently handles the creation of a workflow visualization with an observable. Move the observable that creates the pipeline builder visualization to a plain service and hook up the parent and child components to it.

### Actual behaviour
The parent DAG component relies on an `EventEmitter` to determine the success of the pipeline builder visualization for a workflow. Putting the observable into a service that both parent and child components use removes the need for `EvenEmitter`s and async callbacks

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-535)
┆Issue Type: Story
┆Issue Number: DOCK-535

**Comment by coverbeck** [comment]
Closing as an internal implementation detail.
