### ISSUE TITLE
Can't encode certain symbols

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2162]
### Expected behaviour
Docs should be able to encode the >= sign properly shown here:
https://github.com/CancerCollaboratory/dockstore-tool-samtools-view/blob/1.0/Dockstore.cwl#L276

and should be able to view it properly here:
https://staging.dockstore.org/containers/quay.io/cancercollaboratory/dockstore-tool-samtools-view:1.0?tab=info

and here: 
https://staging.dockstore.org/api/api/ga4gh/v2/tools/quay.io%2Fcancercollaboratory%2Fdockstore-tool-samtools-view

### Actual behaviour
Those show  ��� instead

### Steps to reproduce the behaviour 
See above

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-alpha.6
DockstoreUI - 2.3.0-alpha.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-548)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-548

**Comment by denis-yuen** [comment]
Wacky, will need to refresh after above fix is deployed

**Comment by david4096** [comment]
I can confirm that after adding a workflow with the protected character, dockstore will properly show it. As noted by Denis, repos that have broken characters may have to be refreshed.

DockstoreAPI - 1.6.0-beta.4 DockstoreUI - 2.3.0-rc.0
staging.dockstore.org
