### ISSUE TITLE
Organization change case issue

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2163]
### Expected behaviour

Can change case of org

### Actual behaviour

I guess as a consequence of making the organizations case insensitive, you now get an error if you try to change the casing of your organization. 

https://lh5.googleusercontent.com/5el_VLDPQIaCRwxQ9XJUKPDXQiKvXPW_y-Unay2WwgGzssvbkc10gNBUOghWmu_-J3hRXw5ligks2r-wyWRvqG74lhjMeg3CiJdY4Ctg=s1230

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-551)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-551

**Comment by david4096** [comment]
I can confirm that changing the case of the `Name` of the organization will be reflected in the display and path. Further, the routes themselves are not sensitive to case:

https://staging.dockstore.org/organizations/MoNkeY
https://staging.dockstore.org/organizations/monkey
