### ISSUE TITLE
HostedEntry API should not create a new version if contents are identical to previous version

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2164]
## Feature Request 

When submitting files to create a new version of a hosted entry, a new version is always created, even if the contents are identical to the previous version.

Instead, when the webservice detects that no files have changed, it should not create a new version.

When fixing this, note the integration test code in [LimitedCRUDClientIT.java](https://github.com/ga4gh/dockstore/blob/develop/dockstore-integration-testing/src/test/java/io/dockstore/client/cli/LimitedCRUDClientIT.java) is relying on the current behavior of a new version being created every time, and so will need to be updated as part of this fix.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-550)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-550

**Comment by garyluu** [comment]
So the database no longer has an extra version but the UI expects a workflow object and doesn't handle it quite well when there's isn't one (because 204 no content).

**Comment by denis-yuen** [comment]
Probably worth upgrading the GUI to say something like "No changes detected, update rejected"
How horribly does the UI crash?

**Comment by coverbeck** [comment]
Confirmed that a new version is not saved. API call returns 204, no content, and the UI displays a snackbar message that the version did not change.

Tested on staging.dockstore.org with:
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
