### ISSUE TITLE
Organizations rollup issue

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2165]
## Bug Report
A grab-bag of a few remaining bugs that I want to track from "Organizations Review 2"
FYI @Ldcabansay 

- ~In the members page, if the member’s email/username is too long, it will appear outside of its card.~
- ~On collections page, if tool/workflow name is too long, it will appear outside its card.~
- ~The URL seems to be case sensitive!~
- ~You can still delete yourself as a user even if you’ve created an organization. You can also update your username, not sure if that really matters, but you’re not allowed to do these actions after publishing a workflow~
- ~Don’t surface http status codes in error message to user~ We like the code, as long as additional information is available this is fine for now

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-549)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-549

**Comment by agduncan94** [comment]
* Should be a confirmation box for deleting a member of an org
* Recent events should have timestamp and fix spacing

**Comment by Ldcabansay** [comment]
Also the url and email string on webservice #2179

**Comment by Ldcabansay** [comment]
> * Should be a confirmation box for deleting a member of an org
> * Recent events should have timestamp and fix spacing

@agduncan94 are we no longer doing recent event timestamps?

**Comment by denis-yuen** [comment]
Some indication of time makes sense to me, not mandatory for this release if difficult

**Comment by agduncan94** [comment]
@Ldcabansay Instead we have recent event timestamp on hover.

**Comment by Ldcabansay** [comment]
verified on DockstoreAPI - 1.6.0-beta.3 DockstoreUI - 2.3.0-beta.2
