### ISSUE TITLE
UI set event pagination API limit

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2166]
The default limit for org events is 100.

The ui should set the limit to a lower value (10), as it will not display that many events.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-552)
┆Issue Type: Story
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-552

**Comment by agduncan94** [comment]
We only show a subset of events in the UI, since some have more importance than others. @denis-yuen suggested being able to pass a list of event types to the endpoint and return only events that meet that filter.

**Comment by NatalieEO** [comment]
Seems to be working on staging DockstoreUI - 2.3.0-beta.2
