### ISSUE TITLE
Repos on My Workflows page sometimes are not visible

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2167]
## Bug Report

Sometimes unpublished hosted workflows panel doesn't show your list of unpublished workflows.

In the screenshot note the blank space under `Unpublished` on the left hand-side. There should be two workflows displayed t here.

If you click on Published, then click on Unpublished, you can briefly see the workflows, then they disappear.

I am unable to consistently or reliably reproduce this, but others on the team have seen the issue as well, so there is definitely something here.

This problem probably isn't limited to just unpublished hosted workflows, but it's the only place I've seen it for sure.

![screenshot from 2019-03-01 13-34-41](https://user-images.githubusercontent.com/1049340/53668219-1dede880-3c28-11e9-9097-ea7f7a5cd472.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-553)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-553

**Comment by NatalieEO** [comment]
Just when I thought I could close this...
Steps to reproduce:
1. Go to My Workflows
2. Have at least one published and unpublished hosted workflow
3. Click on an unpublished hosted workflow
4. Refresh page

**Comment by coverbeck** [comment]
Verified this works on staging with version 2.3.0-rc.1
