### ISSUE TITLE
when creating an organization, swagger API accepts strings that are considered invalid on UI 

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2179]
### Expected behaviour
Behavior should be consistent whether registering an organization through UI or the swagger API.
### Actual behaviour
When registering an organization through the UI, a user cannot submit an invalid url or improperly formatted email, however the swagger API will accept almost any specified string for these fields.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-559)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-559

**Comment by denis-yuen** [comment]
Looks like https://github.com/ga4gh/dockstore/pull/2195 was done for this

**Comment by agduncan94** [comment]
@denis-yuen I've updated to have some basic checking for URLs and emails, though Gary pointed out some edge cases that these don't cover.

**Comment by denis-yuen** [comment]
Ok, I think we'll close for now and re-open or create new for specific cases as needed

**Comment by denis-yuen** [comment]
(re-opening for testing, I think testing can confirm that some invalid URLs are blocked as opposed to all edge cases)

**Comment by garyluu** [comment]
Webservice handles all this correctly:

```
    expect(regexp.test('https://www.google.ca')).toBeTruthy();
    expect(regexp.test('http://www.google.ca')).toBeTruthy();
    expect(regexp.test('https://google.ca')).toBeTruthy();
    expect(regexp.test('http://google.ca')).toBeTruthy();
    expect(regexp.test('http://google.com')).toBeTruthy();
    expect(regexp.test('http://google.ca/potato')).toBeTruthy();
    expect(regexp.test('http://numb3r5.ca')).toBeTruthy();
    expect(regexp.test('httpz://google.ca')).toBeFalsy();
    expect(regexp.test('httpsz://google.ca')).toBeFalsy();
    expect(regexp.test('HTTP://www.google.ca')).toBeTruthy();
    expect(regexp.test('www.google.ca')).toBeFalsy();
```
It does not handle
```
    expect(regexp.test('https://google.superLongTLDThatStillWorksForSomeReason')).toBeTruthy();
```

Good enough for now I guess?

**Comment by denis-yuen** [comment]
:man_shrugging:
