### ISSUE TITLE
buttons for nextflow DAG display are misaligned

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2180]
### Expected behaviour

DAG should behave the same between staging and production

### Actual behaviour

Buttons are misaligned

### Steps to reproduce the behaviour 

@Ldcabansay The only thing that seems to be off on develop is the generated [DAG](https://staging.dockstore.org/workflows/github.com/Ldcabansay/eager/nfl-parsing-test-eager:2.0.3?tab=dag). The message "DAG display is still experimental for Nextflow" pushes out the 'export to png', expand icon, etc out of the info box. This doesn't occur for [other descriptor DAGs](https://staging.dockstore.org/workflows/github.com/gatk-workflows/broad-prod-wgs-germline-snps-indels/PairedEndSingleSampleWf-Firecloud-B37:dev?tab=dag) on develop. This also doesn't occur to the [same nfl workflow on production](https://dockstore.org/workflows/github.com/nf-core/eager:2.0.3?tab=dag).

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-561)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-561

**Comment by denis-yuen** [comment]
Looks fixed, albeit slower than expected (might be doing more work on webservice side than needed)
Open new issue

**Comment by agduncan94** [comment]
Works, looks better too.
