### ISSUE TITLE
nf-core rnaseq workflow is going from valid to invalid on refresh

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2181]
This is occurring on staging. For example, https://staging.dockstore.org/workflows/github.com/nf-core/rnaseq previously had all valid versions, now on refresh they are invalid.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-562)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-562

**Comment by garyluu** [comment]
Try running webservice inside container and outside container

**Comment by denis-yuen** [comment]
This seems to just affect rnaseq actually

**Comment by agduncan94** [comment]
Working on 1.6.0-beta.3 and 2.3.0-beta.2
