### ISSUE TITLE
recently visited collection will appear on all organizations pages

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2190]
### Expected behaviour
Collection should only show on its respective organization page (unless a duplicate has been manually made)
### Actual behaviour
Visiting a collection's page will cause the collection to appear as a collection on all registered organization pages. After a hard refresh, the collection will disappear and the organization page will display properly. I was able to reproduce on both chrome and safari
### Steps to reproduce the behaviour 
1. Visit a [collection page](https://staging.dockstore.org/organizations/7/collections/6)
2. Manually navigate from that collection page to another organization page (click through only)
3. Refresh the organization page and the phantom collection should disappear

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-beta.0
DockstoreUI - 2.3.0-beta.0
Chrome 72.0.3626.96
Safari 12.0.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-566)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-566

**Comment by agduncan94** [comment]
I think this is because we do not clear the active collection on organisation switch.

**Comment by garyluu** [comment]
should be clearing ALL collections on organization switch

**Comment by garyluu** [comment]
Hmm...apparently I fixed it in https://github.com/dockstore/dockstore-ui2/blame/develop/src/app/organizations/collections/collections.component.ts#L48

**Comment by Ldcabansay** [comment]
Verified that collections bug no longer persists on DockstoreAPI - 1.6.0-beta.3DockstoreUI - 2.3.0-beta.2
