### ISSUE TITLE
Speed up CI

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2194]
### Desired behaviour
Travis is taking quite some time to run on both webservice and UI2

Webservice is sometimes taking up to 5 hrs:
![image](https://user-images.githubusercontent.com/24548904/53917135-ddc8a480-4031-11e9-961a-75c68c9bb0ea.png)

UI2 is taking up to 1.5 hrs
![image](https://user-images.githubusercontent.com/24548904/53917204-fe90fa00-4031-11e9-872b-b7214b3bb28a.png)

Something should be done to speed this process up.  Some options:

1.  Move a portion of the tests to another CI
1.  Somehow disable the push build when a PR build is going on at the same time
1.  Fork the repo and run all the push builds on your own individual CI of choice and only do PR builds on the "real" Travis.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-568)
┆Issue Type: Story
┆Issue Number: DOCK-568

**Comment by garyluu** [comment]
I'm currently doing 3 personally, 1 would be preferable too imo.

**Comment by denis-yuen** [comment]
I like 1 with CircleCI because everyone will benefit immediately. 
To roughly divide the tests in half for the webservice, we should move coverage testing since its less critical and takes half the time. 
Downside, we need a way of encrypting the confidential data on CircleCI too

**Comment by denis-yuen** [comment]
Initial moves that can be moved to circle ci without confidential data:
1. openjdk10 unit tests 
2. automated review (database check)

(removes one stage, but 15 minutes or so)

**Comment by denis-yuen** [comment]
Duplicates #2215
