### ISSUE TITLE
show a sample command from parsing the CWL

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#22]
Help to put together command to run tool with cwltool or potentially the dockstore CLI wrapping the dockstore-descriptor-launcher

**Comment by briandoconnor** [comment]
carrot would be better searching... e.g. search for tools that take unaligned BAM as inputs as designated by EDAM ontology term

**Comment by briandoconnor** [comment]
Also, this feature could generate a sample JSON for parameterizing the call to this docker-based tool via the cwl command line tool

**Comment by briandoconnor** [comment]
Might not need the sample command... more of a tool to help prepare running via the launcher... need to think about this more.

**Comment by denis-yuen** [comment]
Redundant from #345 I think
