### ISSUE TITLE
Rename organization_alias table

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2200]
Typo, currently `organzation_alias`, should be `organization_alias`

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-570)
┆Issue Type: Story
┆Issue Number: DOCK-570

**Comment by denis-yuen** [comment]
(for review, must have been missed because its on 1.6.x)

**Comment by agduncan94** [comment]
Migrations look good, and haven't noticed any issues with migrations locally.
