### ISSUE TITLE
Provide CLI help warnings that WES CLI is Beta quality

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2203]
From Denis:
I think we can merge to develop, but with ample warnings that this is a beta-quality feature (due to the difficulty having it properly submit to WES implementations) both in the CLI help and on docs.dockstore.org.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-575)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-575

**Comment by NatalieEO** [comment]
Using command `dockstore workflow wes launch` or `dockstore workflow wes launch --help`
Returns
```
Usage: dockstore wes workflow launch --help
       dockstore wes workflow launch [parameters]
```

wes and workflow need to be swapped. The other help messages seem to be okay though.

**Comment by NatalieEO** [comment]
Working on Dockstore version 1.6.0-rc.0
