### ISSUE TITLE
Rename swagger-java-wes-client to openapi-java-wes-client

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2204]
rename swagger-java-wes-client to openapi-java-wes-client since this actually using openapi 3 already

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-574)
┆Issue Type: Story
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-574

**Comment by denis-yuen** [comment]
Already in develop
