### ISSUE TITLE
Provide instructions on how WES swagger was converted to OpenAPI 3.0

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2205]
please provide instructions on how this was converted from https://github.com/ga4gh/workflow-execution-service-schemas/blob/master/openapi/workflow_execution_service.swagger.yaml to OpenAPI 3.0 swagger-java-wes-client/src/main/resources/workflow-execution_service-1.0.0-oas3-swagger.yaml

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-573)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-573

**Comment by wshands** [comment]
See the instructions at dockstore/openapi-java-wes-client/src/main/resources/OPENAPI_CREATION.md

**Comment by garyluu** [comment]
https://github.com/ga4gh/dockstore/blob/develop/openapi-java-wes-client/src/main/resources/OPENAPI_CREATION.md

**Comment by denis-yuen** [comment]
@wshands 
Oh I see. Files in `src/main/resources` actually make it into the classpath. Convention is normally that readmes and the like just go into the root. ( https://maven.apache.org/guides/introduction/introduction-to-the-standard-directory-layout.html )
Not a big deal, I'll close this for now and this can be moved later when you're in the area.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

See the instructions at dockstore/openapi-java-wes-client/src/main/resources/OPENAPI_CREATION.md
