### ISSUE TITLE
Tools Tab retains previous workflow's tools

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2216]
### Expected behaviour
Each workflow displays their own tools only

### Actual behaviour
The tools from the workflow before currently shows sometimes

### Steps to reproduce the behaviour 
Go to the search page, navigate to the nf-core/vipr workflow
Go back to the search page, navigate to the DataBiosphere/topmed-workflows/TopMed_Variant_Caller workflow.  The tools page is full of nextflow tools.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-578)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-578

**Comment by denis-yuen** [comment]
Seems fixed 
DockstoreAPI - 1.6.0-beta.3DockstoreUI - 2.3.0-beta.2
