### ISSUE TITLE
Provide docs.dockstore.org warnings that WES CLI is Beta quality

### ISSUE THREAD

**Issue by cricketsloan** [ga4gh/dockstore#2219]
┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-580)
┆Issue Type: Story
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-580
┆Epic: WES API support

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

From Denis:
I think we can merge to develop, but with ample warnings that this is a beta-quality feature (due to the difficulty having it properly submit to WES implementations) both in the CLI help and on docs.dockstore.org ( http://docs.dockstore.org ).

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Please update ticket with commit

**Comment by david4096** [comment]
https://github.com/ga4gh/dockstore/commit/74b69a9f063e4910139e25659e36b6463696aca7

I can confirm this message appears for the Dockstore client currently in `develop`.

`NOTE: WES SUPPORT IS IN BETA AT THIS TIME. RESULTS MAY BE UNPREDICTABLE.`

**Comment by david4096** [comment]
@coverbeck can also confirm it works using the `dockstore --upgrade-unstable` and will therefore work against staging.

The docs for it appear here https://docs.dockstore.org/docs/publisher-tutorials/advanced-features/
