### ISSUE TITLE
Display of newly created workflows seems glitchy

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#222]
When new workflows are visible in the list after doing a `dockstore workflow refresh` via the GUI, some glitches can occur including:
- the newly created workflow stubs cannot be published, but can after a browser refresh
- a newly published workflow has no descriptors loaded, but can after a browser refresh

**Comment by denis-yuen** [comment]
@garyluu  after refresh all tools, doesn't return set of all tools

**Comment by denis-yuen** [comment]
Can be done/tested at the same time you're working on #977

**Comment by agduncan94** [comment]
This is from UI1. I tested out some cases like the ones listed in the initial comment and I can't recreate any issues.
