### ISSUE TITLE
POST and PUT are reversed in CollectionResource

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2223]
## Bug Report

`CollectionResource.createCollection` is annotated with `@PUT`.

`CollectionResource.updateCollection` is annotated with `@POST`.

They work as is, but this is technically not RESTful.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-582)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-582

**Comment by denis-yuen** [comment]
Implementer, see #2128

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified with DockstoreUI \- 2.3.0-rc.0 ( https://github.com/dockstore/dockstore-ui2/releases/tag/2.3.0-rc.0 ) and DockstoreAPI \- 1.6.0-beta.4 ( https://github.com/ga4gh/dockstore/releases/tag/1.6.0-beta.4 )

staging.dockstore.org
