### ISSUE TITLE
Organization Logo Should not be a Circle

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2227]
## Feature Request 

I think most logos will be be rectangular. Trying to squish the TOPMed logo into a circle doesn't quite look right, IMHO.

Or if we keep the circle, we should not change the aspect ratio of the source image.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-591)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-591

**Comment by denis-yuen** [comment]
Works on 
DockstoreAPI - 1.6.0-beta.4
DockstoreUI - 2.3.0-rc.0
