### ISSUE TITLE
CLI launch simplification

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#223]
#When launching a workflow, we require the user to specify whether they're launching a WDL or CWL workflow. This isn't strictly necessary since we could just look at the provided file to see what type of workflow we have 

i.e. 
```
dockstore workflow launch --entry wdl.wdl --local-entry --json wdl.json --descriptor wdl
```

becomes 

```
dockstore workflow launch --entry wdl.wdl --local-entry --json wdl.json
```

if we just examine wd.wdl. Don't only rely upon the extension, do take a look at the contents. 
If the contents and the extension seems to conflict, show a warning and pick the one that seems most likely. 

Related to #193 in that this might be a good stepping stone before taking a look at that one.

**Comment by jpatricia** [comment]
Still allow `--descriptor` to act as an override if we guess incorrectly while looking at a local cwl or wdl file.

If we're looking at a remote entry,  you will still need to specify since a particular Dockstore tool can have both a CWL and a WDL file, so you won't be able to make this simplification.

**Comment by jpatricia** [comment]
Algorithm: 

0. Check the extension and the contents
  0. If both agree and say that its CWL, launch as a CWL file without asking for `--descriptor`
  0. if both agree and say that its WDL, ""
0. If there is an extension, but the contents seem to disagree (i.e. you have a WDL file but it looks like a CWL file or vice versa), print an error message and abort
  0. the user can use `--descriptor` to force a choice, in this case don't print an error
0. if there is no extension, check the file contents only 
  0. If you can guess, go with your guess and warn the user that they should add a file extension
  0. if you can't figure it out, just print an error and abort

**Comment by denis-yuen** [comment]
Hi,
As discussed, I should probably elaborate. The above strategy of examining the descriptor content only applies to `--local-entry`. In other words, when working with a remote descriptor, a different strategy is needed.

**Comment by denis-yuen** [comment]
Implementation in progress at #243
