### ISSUE TITLE
Collection URL doesn't update when name is changed

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2232]
When you edit the collection name, the link doesn't change.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/DOCK-588)
┆Issue Type: Task
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-588

**Comment by denis-yuen** [comment]
Works 
DockstoreAPI - 1.6.0-beta.4
DockstoreUI - 2.3.0-rc.0
