### ISSUE TITLE
Swagger description for get organisation by alias is wrong

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2233]
It says collections, should say orgs.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/DOCK-587)
┆Issue Type: Task
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-587

**Comment by denis-yuen** [comment]
not worth reviewing
