### ISSUE TITLE
Prepare for hiding export to FireCloud

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2235]
## Feature Request 

Broad is transitioning from FireCloud to Terra; FireCloud is expected to shutdown on May 1st.

Make the appearance of the FireCloud button configurable, so that we can hide the button once FireCloud gets shutdown without doing a code change.

┆Issue is synchronized with this [Jira Task](https://ucsc-cgl.atlassian.net/browse/DOCK-586)
┆Issue Type: Task
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-586

**Comment by denis-yuen** [comment]
Note to self: try this out on next deploy to staging

**Comment by denis-yuen** [comment]
Seems to work
