### ISSUE TITLE
When refreshing tools with non-default paths, refresh uses the default paths rather than non-default for each version

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#224]
Refresh behaviour is not quite correct. When refreshing, even if a particular version uses a non-default path (say /delly_docker/Dockstore.cwl rather than /Dockstore.cwl), the grabbing of descriptors uses the default 
https://github.com/ga4gh/dockstore/blob/develop/dockstore-webservice/src/main/java/io/dockstore/webservice/helpers/Helper.java#L241

This causes descriptors to be not returned when reporting on CWL and Dockerfiles in the client.

Workaround: modify the default path to match the real paths in the source code repo
Accomplish this with the command `dockstore updateContainer --entry quay.io/pancancer/pcawg_delly_workflow --cwl-path /delly_docker/Dockstore.cwl --dockerfile-path /delly_docker/Dockerfile`
i.e. 
```
default_cwl_path": "/Dockstore.cwl",
"default_wdl_path": "/Dockstore.wdl",
```
should be 
```
default_cwl_path": "/delly_docker/Dockstore.cwl",
"default_wdl_path": "/delly_docker/Dockstore.wdl",
```

**Comment by briandoconnor** [comment]
Thanks Denis for the workaround

**Comment by briandoconnor** [comment]
Hi @denis-yuen, any idea why the same command for me causes a Forbidden error?  I double-checked my dockstore token in my .dockstore/config file and it looks OK.  And I'm using '0.3-beta.1':

ubuntu@brian-pcawg-bwa-testing:~/gitroot/pcawg_delly_workflow/delly_docker$ dockstore updateContainer --entry quay.io/pancancer/pcawg_delly_workflow --cwl-path /delly_docker/Dockstore.cwl --dockerfile-path /delly_docker/Dockerfile
io.swagger.client.ApiException: Forbidden: please check your credentials.
        at io.swagger.client.ApiClient.invokeAPI(ApiClient.java:532)
        at io.swagger.client.api.ContainersApi.getContainerByToolPath(ContainersApi.java:121)
        at io.dockstore.client.cli.Client.updateContainer(Client.java:1314)
        at io.dockstore.client.cli.Client.main(Client.java:1753)

**Comment by briandoconnor** [comment]
Actually, this is strange.  the pcawg_delly_workflow no longer shows up in my pancancer organization:

![image](https://cloud.githubusercontent.com/assets/1730584/15136982/6288dee8-163b-11e6-956e-aa4c887da99c.png)

**Comment by denis-yuen** [comment]
Hi,
Actually, this is expected behaviour, although it could be improved. 
While experimenting, I tried deleting and re-creating the tool. That means the tool would have lost your ownership of it (ownership being a property of a tool and not the organization currently), something that you re-claimed when refreshing.

**Comment by denis-yuen** [comment]
Properly handling of default paths and non-default on the backend. Follow up with #284 for ideas on how to make this easier to use on the GUI side
