### ISSUE TITLE
Rejected organization appears in add to collection and when visiting org url

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2244]
### Expected behaviour
Rejected organization should not appear as an option when adding a tool/workflow to a collection. 
### Actual behaviour
The rejected organization appears as an option when adding a tool/workflow to a collection. 
Related: The rejected organization can still be visited by url (by requesting user and curators, not public). This might be something we want by design until we decide what to do with rejected organizations.

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-beta.3
DockstoreUI - 2.3.0-beta.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-595)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-595

**Comment by agduncan94** [comment]
Filtering so only approved organisations show up.

**Comment by agduncan94** [comment]
Some thoughts about rejected organisations:
* They should show up on the requests tab of the accounts page with clear indication that they are rejected
* They should have a banner on the organisation page saying the org is rejected
* Users should either be able to delete a rejected org, or re-request a review, or both

**Comment by agduncan94** [comment]
@denis-yuen

**Comment by agduncan94** [comment]
Based on discussion, won't add delete, but will add ability to re-request review

**Comment by NatalieEO** [comment]
@agduncan94 
Confirmed only approved orgs show up as options when adding an entry to a collection through the UI. But, is it okay to that entries can be added through the API for rejected/pending orgs? 



DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1

**Comment by agduncan94** [comment]
I think you should be able to add entries to rejected/pending orgs, but we need to figure out how these are shown in the current collections section of an entry.

**Comment by agduncan94** [comment]
Based on discussion with @denis-yuen , will let users add entries to pending and rejected orgs. This will show up in the collections list for an entry even if the collection is from an approved/rejected org. This must be fixed at a later time.

**Comment by NatalieEO** [comment]
@agduncan94 
I don't see rejected or pending orgs as option when adding an entry to a collection DockstoreAPI - 1.6.0-rc.3DockstoreUI - 2.3.0-rc.2

**Comment by agduncan94** [comment]
@NatalieEO I think staging was on the wrong version, it looks like it works now.

**Comment by NatalieEO** [comment]
Thanks, working now
DockstoreAPI - 1.6.0-rc.3
DockstoreUI - 2.3.0-rc.3
