### ISSUE TITLE
Tooltester Backup

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2249]
### Desired behaviour
Back up tooltester logs on the first Jenkins Master before Jenkins Master V2 takes over

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-597)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Issue Number: DOCK-597

**Comment by denis-yuen** [comment]
Or to persist between release (shutdowns)

**Comment by denis-yuen** [comment]
@garyluu think this was mis-assigned, think you're well underway and can close this if appropriate
