### ISSUE TITLE
Compose_setup default webservice version

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2252]
### Desired behaviour
Compose setup: if webservice version is not specified, just use the webservice version in the UI's .travis.yml

This is another way of making sure that the webservice is compatible with the UI since the UI runs tests using a specific webservice version.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-598)
┆Issue Type: Story
┆Issue Number: DOCK-598

**Comment by denis-yuen** [comment]
I think the versions of dependencies should be explicit (i.e. like how we enforce Maven dependencies)
