### ISSUE TITLE
Missing Descriptor Types in Tool Files Tab

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2257]
### Expected behaviour
- Go to https://staging.dockstore.org/containers/quay.io/briandoconnor/dockstore-tool-bamstats:develop?tab=files  
- Click on "descriptor files"
The descriptor type should say CWL

### Actual behaviour
There is nothing there and no dropdown to be clicked

DockstoreAPI - 1.6.0-beta.3
DockstoreUI - 2.3.0-beta.2

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-602)
┆Issue Type: Story
┆Issue Number: DOCK-602

**Comment by denis-yuen** [comment]
Seems like a bug https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:develop?tab=files 
has both WDL and CWL for example

**Comment by garyluu** [comment]
Looks like the `includes=validation` isn't returning validation

**Comment by denis-yuen** [comment]
@garyluu is this comment for this ticket?

**Comment by garyluu** [comment]
Yes, it's getting the valid descriptor types to put into the dropdown menu.  The valid descriptor types is figured out by the selected version's validations array...which is currently empty.

**Comment by denis-yuen** [comment]
Oh I see, pinging @agduncan94

**Comment by garyluu** [comment]
One temporary workaround is just to not look at validation (not use `vaildDescriptors`) and just use `descriptors` instead

**Comment by agduncan94** [comment]
Good find. I think my logic was on public pages, only show valid descriptor types. On the my tools page, it should show all descriptor types.

**Comment by denis-yuen** [comment]
> One temporary workaround is just to not look at validation (not use `vaildDescriptors`) and just use `descriptors` instead

I'm thinking this is particularly helpful while we don't support WDL 1.0
Especially since we tell people why things don't validate now, I think I'm ok with just showing everything along with the validation messages that we show now.

**Comment by denis-yuen** [comment]
Can verify that we can toggle descriptor types now. 
Workflows with validation issues will display the validation warning along with the contents
