### ISSUE TITLE
Verify portless webservice url works with UI

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2260]
With the fix to #1594, the UI will be now be working with a webservice base url that no longer explicitly specifies the port, i.e, instead of  `https://dockstore.org:443/api` and `https://staging.dockstore.org:443/api`, the base will be `https://dockstore.org/api` and `https://staging.dockstore.org/api`. This has implications not only for API calls themselves, but for urls that the UI generates. 

At least the following should be verified:

- [x]  The UI can successfully execute API calls against the webservice
- [x]  Sign in with both Google and GitHub continues to work
- [x]  The generated TRS urls are correct and work on the info tab of containers and workflows
- [x]  Download as zip
- [x]  Downloading the CLI
- [x]  Launch with instructions for tools and workflows work
- [x] The link to Swagger and RSS at the bottom of the page work
- [x]  Launch with DNAnexus still works (Dockstore passes TRS url to them)
- [x]  Should also go through the onboarding tutorial again
- [x]  Verify [this PR](https://github.com/ga4gh/dockstore/pull/2251/files) is visible in the docs.
- [x] Possibly other things that I'm missing.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-604)
┆Issue Type: Story
┆Issue Number: DOCK-604

**Comment by denis-yuen** [comment]
Verified a bunch with 
DockstoreAPI - 1.6.0-beta.4
DockstoreUI - 2.3.0-rc.0
Waiting for collab

**Comment by garyluu** [comment]
When no server-url is specified in the config file, the default URL used no longer works

**Comment by denis-yuen** [comment]
@garyluu could you do a PR to modify the default URL?

**Comment by garyluu** [comment]
ok

**Comment by denis-yuen** [comment]
Launch with instructions for tools and workflows work
* working with CWL tools

**Comment by denis-yuen** [comment]
identified and split out https://github.com/ga4gh/dockstore/issues/2297

**Comment by denis-yuen** [comment]
Identified and split out #2300

**Comment by coverbeck** [comment]
Confirmed that I was able to import https://staging.dockstore.org/workflows/github.com/vrockai/dockstore-whalesay:dnastack?tab=info into into DNAnexus with: 

DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1

**Comment by denis-yuen** [comment]
Cool, I think we'll address "Possibly other things that I'm missing." separately as we think of them
