### ISSUE TITLE
Fun Tab Switching Bug

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2265]
### Expected behaviour
Switch tabs as fast as humanly possible without some infinite loops

### Actual behaviour
Switching tabs as fast as possible and the tabs start to bounce back and forth like crazy in an infinite loop

### Steps to reproduce the behaviour 
- Use chrome
- Set CPU performance to 6x slow down
- Go to https://staging.dockstore.org/containers/quay.io/pancancer/pcawg-sanger-cgp-workflow:feature_cross?tab=files
- Change tabs between files and versions a couple times really fast
- Get popcorn, watch the madness

### Environment (Browser or OS and Dockstore version)
Staging
DockstoreAPI - 1.6.0-beta.4DockstoreUI - 2.3.0-rc.0

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-607)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-607

**Comment by denis-yuen** [comment]
Is this network performance?

**Comment by garyluu** [comment]
CPU looks like

**Comment by garyluu** [comment]
I did first somehow manage to produce this without Chrome CPU slowdown...but can't reproduce without it anymore

**Comment by denis-yuen** [comment]
Seems fixed on DockstoreAPI - 1.6.0-rc.3
DockstoreUI - 2.3.0-rc.3
