### ISSUE TITLE
Tests may be hitting production

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2267]
There are a couple of test configuration files that are referencing the production server:

* dockstore-integration-testing/src/test/resources/pluginsTest1/configWithPlugins
* dockstore-integration-testing/src/test/resources/pluginsTest2/configWithPlugins

We should be hitting production server with any tests.

Note: maybe we're not; needs investigation if that particular setting is actually used.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-608)
┆Issue Type: Story
┆Issue Number: DOCK-608

**Comment by denis-yuen** [comment]
Duplicates #2048 , copied comment there
