### ISSUE TITLE
Unpublished entries still visible in collection

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2283]
## Bug Report

If you add a workflow to a collection, then unpublish the workflow, the workflow is still in the collection.

### Steps to Reproduce
1. Create an organization and a collection
2. Navigate to one of your public workflows
3. Add it to your collection
4. Go to My Workflows
5. Unpublish the workflow you just added
6. Go to your organization's collection

Expect: To no longer see the unpublished workflow
Actual: You see the unpublished workflow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-617)
┆Issue Type: Story
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-617

**Comment by coverbeck** [comment]
@agduncan94 This was fixed, wasn't it?

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/pull/2289

**Comment by agduncan94** [comment]
This should be fixed, needs to be tested.

**Comment by agduncan94** [comment]
Looks good to me, but someone else should try.

**Comment by denis-yuen** [comment]
Works for me
https://staging.dockstore.org/organizations/SHIELD/collections/Test
(when toggling bcbio)
