### ISSUE TITLE
Navigating to a non-existent/unpublished workflow shows a blank page

### ISSUE THREAD

**Issue by coverbeck** [ga4gh/dockstore#2286]
## Feature Enhancement

If you navigate to a non-existent or unpublished workflow, you get a blank page. Ideally this would display some sort of 404 page.

Note: there are some cases where you get redirected to the home page. I haven't quite figured out the pattern (presumably it's a non-existent route), but the fixer for this should look at those as well.

### Steps to reproduce

1. Go to [this url](https://staging.dockstore.org/workflows/dockstore.org/coverbeck/helloworld), which currently is unpublished.

Variants:

1. Goto https://staging.dockstore.org/workflows/github.com/nf-core/vipr:master?tab=info (works, as expected).
2. Change `vipr` to `bad-name1`: https://staging.dockstore.org/workflows/github.com/nf-core/bad-name:master?tab=info -- you go to home page
3. Change to a non-existent branch: https://staging.dockstore.org/workflows/github.com/nf-core/vipr:bad-name?tab=info -- you end up back on master branch -- it falls back on default version if the specified version doesn't exist. I can see how that's useful, although maybe we want to have a warning.
4. Put a typo in the repo namespace, e.g., make it github.org, https://staging.dockstore.org/workflows/github.org/nf-core/vipr:master?tab=info -- you have a blank page.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-618)
┆Issue Type: Story
┆Issue Number: DOCK-618

**Comment by denis-yuen** [comment]
Merging with duplicates #1019 #2038
