### ISSUE TITLE
Updating collection clears collection readme

### ISSUE THREAD

**Issue by Ldcabansay** [ga4gh/dockstore#2294]
### Expected behaviour
A user should be able to update a collection's name, display name, or topic.

### Actual behaviour
Updating the name, display name, or topic fields on a collection's page will clear the collection's readme on submission.

### Steps to reproduce the behaviour 
Navigate to a collection's page and edit any of the mentioned fields and the readme will be cleared when submitted.

### Environment (Browser or OS and Dockstore version)
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1
Chrome 72.0.3626.96

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-623)
┆Issue Type: Story
┆Issue Number: DOCK-623

**Comment by agduncan94** [comment]
Works on
DockstoreAPI - 1.6.0-rc.1
DockstoreUI - 2.3.0-rc.2
