### ISSUE TITLE
Can switch to NFL launch-with instructions for tools and they don't make sense

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2297]
### Expected behaviour

Should show only for NFL tools and they should make sense

### Actual behaviour

https://staging.dockstore.org/containers/quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4?tab=launch can choose NFL (despite the tool not having NFL descriptors), instructions shown look like messed up WDL instructions

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-626)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-626

**Comment by garyluu** [comment]
It's figuring out the current descriptors wrong: https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/container/launch/launch.component.ts#L69 . Not sure how long that's been there.

**Comment by NatalieEO** [comment]
ga4gh/dockstore#2280

**Comment by agduncan94** [comment]
Looks good at
DockstoreAPI - 1.6.0-rc.4
DockstoreUI - 2.3.0-rc.4
