### ISSUE TITLE
Workflow not being added on refresh organization

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2303]
I have a new GitHub repo that is not currently on the my workflows page, however I can't seem to add it by doing any refresh.

Refresh organisation - does not add
Refresh all workflows - fails due to https://github.com/ga4gh/dockstore/issues/2299

Tested on
DockstoreAPI - 1.6.0-rc.0
DockstoreUI - 2.3.0-rc.1

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-630)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-630

**Comment by denis-yuen** [comment]
@agduncan94 please take an initial look, give me a shout if it turns hairy

**Comment by agduncan94** [comment]
Not able to reproduce this locally, even with the staging database.

**Comment by denis-yuen** [comment]
What about your account? Can you replicate with a new account, might it be related to the side/tokens/something specific?

**Comment by agduncan94** [comment]
So the issue is that our library is grabbing all of our owned repositories and putting them in a mapping of repository name -> repository object. Originally we assumed this would only grab in my case, agduncan94/* repositories. We had another function to grab repositories from organisations you belong to.

Turns out "owned" repositories is not only those in your namespace (ex. agduncan94), but also include others. So if you had a repository agduncan94/foo and another one you "owned" called dockstore/foo, only one would show up in the mapping.

The function returns all repos according to the following:
> List repositories that are accessible to the authenticated user (public and private) using the specified page size.
>   
>      * This includes repositories owned by the authenticated user, repositories that belong to other user, where the authenticated user is a collaborator, and other organizations' repositories that the authenticateduser has access to through an organization membership.

What we actually want is is just the first point (repositories owned by the authenticated user)

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/issues/2311

**Comment by Ldcabansay** [comment]
Verified that refreshing github organizations now grabs repositories owned by the authenticated user even if repo has the same name or is forked from a github organization that the user also belongs to. For example, both Databiosphere/toolbox and Ldcabansay/toolbox show on refresh.

DockstoreAPI - 1.6.0-rc.1
DockstoreUI - 2.3.0-rc.2
