### ISSUE TITLE
Improve plugin documentation

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2306]
Documentation for using plugins should be more clear, feels like there are some missing steps.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-631)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-631

**Comment by coverbeck** [comment]
Agreed -- it's not clear to me when/if/how the plugins get automatically downloaded/upgraded.

**Comment by denis-yuen** [comment]
Consolidate documentation, appropriate from both developer POV and user POV
Look at dockstore readme for a few examples and bring over to docs.dockstore.org
