### ISSUE TITLE
Update to OpenJDK11

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2320]
### Desired behaviour

Switch to next LTS Java release for 
* travis-ci and circle-ci should switch tests against 8 to 11
* test with compose_setup

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-638)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.7
┆Sprint: Seabright Sprint 7 Gondola
┆Issue Number: DOCK-638

**Comment by david4096** [comment]
I took a quick look at this and saw that `jdeps` error. You can run two java installs next to each easily on Ubuntu using update-alternatives.

```
sudo apt install openjdk11-jdk
sudo apt install openjdk-8-jdk
sudo update-alternatives --config java
# select java 11
cd dockstore
mvn clean install
[ERROR] Failed to execute goal org.codefx.mvn:jdeps-maven-plugin:0.2:jdkinternals (default) on project dockstore: Executing 'jdeps -jdkinternals' failed.: Could not locate JDeps executable. -> [Help 1]
```

**Comment by garyluu** [comment]
So I've been using openjdk11 for quite some time now.  I've pretty much had to comment out:
```
-            <plugin>
-                <groupId>org.codefx.mvn</groupId>
-                <artifactId>jdeps-maven-plugin</artifactId>
-                <version>0.2</version>
-                <configuration>
-                    <defaultSeverity>FAIL</defaultSeverity>
-                </configuration>
-                <executions>
-                    <execution>
-                        <goals>
-                            <goal>jdkinternals</goal>
-                        </goals>
-                    </execution>
-                </executions>
-            </plugin>

```

**Comment by denis-yuen** [comment]
Haven't run into this (yet?) with unit tests.
But liquibase (for propose_migration.sh) and jacoco (for integration tests) seem to be having issues.
Pushing onwards
