### ISSUE TITLE
Better location for clear search filters

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#2327]
Currently to clear search filters, you need to scroll to the very bottom to see the 'reset filters' button. We should also have one at the top, beside the share button possibly.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-644)
┆Issue Type: Story
┆Issue Number: DOCK-644

**Comment by denis-yuen** [comment]
Merge with #2115
