### ISSUE TITLE
Instructions for Dockstore.yml settings for webapp don't cover items for Quay/GitHub/Bitbucket

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#233]
Need better docs on what these are.

**Comment by briandoconnor** [comment]
We also need directions for setting up postgres, it's never mentioned

**Comment by denis-yuen** [comment]
Postgres setup is documented via .travis.yml https://github.com/ga4gh/dockstore/blob/develop/.travis.yml#L17 

I'll add a link in the readme.md to explain this.
