### ISSUE TITLE
Tooltester Generate Models

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2331]
### Desired behaviour
Currently the blue ocean models are semi-manually created.  This is a pain because a new blue ocean api will cause the models to change.  Ideally these models should be created using https://github.com/jenkinsci/blueocean-plugin somehow.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-649)
┆Issue Type: Story
┆Issue Number: DOCK-649

**Comment by denis-yuen** [comment]
re-create in under seabright jira 
(this is too inside baseball)
