### ISSUE TITLE
Terra launch-with WDL tools

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#2355]
### Desired behaviour

Bring over launch-with from workflows like https://dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_variant_caller_wdl:1.32.0?tab=info 
to tools like
https://dockstore.org/containers/quay.io/mduran/generate-igv-session_2/GenerateIGVSession:dockstore?tab=info

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-666)
┆Issue Type: Story
┆Issue Number: DOCK-666

**Comment by coverbeck** [comment]
Is this a duplicate of #1705?

**Comment by denis-yuen** [comment]
Yup
