### ISSUE TITLE
Dockstore website seems to improperly cache information

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#236]
After a new release, the homepage of https://www.dockstore.org is bugged and requires a clear cache refresh. It will automatically go to https://www.dockstore.org/login whenever you tried to go to the homepage and also use the old version's UI, unless you signed in/logged in. After you log in, the UI changed into the new version and the homepage is accessible. It could be because we're not setting our cache or something correctly when redeploying.

**Comment by denis-yuen** [comment]
For future reference, something like https://www.npmjs.com/package/grunt-cache-control might be interesting

**Comment by denis-yuen** [comment]
busting the cache based on the git commit you compute in #186 would be nice

**Comment by denis-yuen** [comment]
Seems that Angular 2 made this better by default, at least in prod mode
