### ISSUE TITLE
Remove extra requirements from future requirements.txt files

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#2364]
### Desired behaviour
We have a lot of python packages specified in our requirements.txt files because historically installing just cwltool wasn't enough to run all our verified tools/workflows. ~Ideally cwltool should be responsible for determining which packages are needed and install them when installing cwltool.~  Perhaps many of the packages we specify are actually no longer needed.

Edit: making it clear that we cannot rely on this at this point in time

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-668)
┆Issue Type: Story
┆Issue Number: DOCK-668

**Comment by denis-yuen** [comment]
That probably won't work. 
The problem is that previously when installing a pinned version cwltool, we would find that transitive dependencies could still float and break, which is why we pinned transitive dependencies.

**Comment by garyluu** [comment]
Yes, the point is that if their transitive dependencies aren't correct (in other words their requirements.txt range has too wide of a gap), they should be modifying their requirements.txt and pinning it there instead of us having our own separate requirements.txt that does pin it

**Comment by denis-yuen** [comment]
That doesn't seem like an issue for this repo?

**Comment by garyluu** [comment]
Our issue because our requirements files overlap quite a bit:

schema-salad, ruamel.yaml and requests which is effectively half our requirements.txt file.  It's been a very long time since we checked if those pinned versions we have are necessary (compared to theirs).  It is very likely it isn't.  Considering Lincoln mentioned last time that it's annoying to use, we should do what we can about it.

**Comment by denis-yuen** [comment]
I don't think the complaint was about the length of the requirements file, its not like people are typing the requirements file out by hand. The complaint was more about having to use pip at all. 
Can discuss offline

**Comment by garyluu** [comment]
Re-opening as the title of this mentions this is for FUTURE requirements.txt files

**Comment by garyluu** [comment]
FYI, pip freeze output after install cwltool==1.0.20181217162649:
bagit==1.7.0
CacheControl==0.11.7
certifi==2019.3.9
chardet==3.0.4
cwltool==1.0.20181217162649
decorator==4.4.0
idna==2.8
isodate==0.6.0
lockfile==0.12.2
lxml==4.3.3
mistune==0.8.4
mypy-extensions==0.4.1
networkx==2.2
pathlib2==2.3.2
pkg-resources==0.0.0
prov==1.5.1
psutil==5.6.1
pyparsing==2.4.0
python-dateutil==2.8.0
rdflib==4.2.2
rdflib-jsonld==0.4.0
requests==2.21.0
ruamel.ordereddict==0.4.13
ruamel.yaml==0.15.77
scandir==1.10.0
schema-salad==3.0.20181206233650
shellescape==3.4.1
six==1.12.0
subprocess32==3.5.3
typing==3.6.6
typing-extensions==3.7.2
urllib3==1.24.1
