### ISSUE TITLE
Adding ICGC Storage and Synapse File Provisioning

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#244]
Storing large reference files on S3 is easy but incurs hosting and data transfer charges.  It also means important reference files are stored in private AWS accounts, which can be shutdown.

A better approach is to host large reference files on a service like Synapse or the ICGC Storage System.  Both of these are considered public repositories, can handle large files, and Synapse is a complete self-served model.

Both require user registration/tokens so it's not quite as nice as a free place to host HTTP-based files.  But the benefits of Synapse (free hosting/transfer) and general importance of the ICGC Storage System make it worthwhile to support these.

**Comment by briandoconnor** [comment]
@spacime I temporarily assigned you this.  If it's something you can work on it would be great.

**Comment by denis-yuen** [comment]
I think ICGC Storage is largely functional, I'll take a look Synapse file provisioning when I get a chance.

**Comment by denis-yuen** [comment]
ICGC Storage exists, Synapse is now implemented
