### ISSUE TITLE
Provide option to specify working directory for Dockstore launch

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#245]
The `dockstore tool launch` function will locally launch a tool which is super helpful (and how I'm telling people to use Dockstore today).

However, it's not super clear that this will automatically create a datastore directory in the `pwd` that will contain all input files.  These can be very large.  

I think you want to make the docs/help message clear this is happening and also give an option (such as --working-dir) that lets users override this location.  You can also provide an option in the .dockstore/config file as well.

**Comment by briandoconnor** [comment]
@denis-yuen 

On a related note, how would this scenario work with the cwltool runner:

* workflow input is a 22G reference.tar.gz file
* dockstore command line happily downloads from S3/HTTP to the `$cwd` which happens to be a large volume capable of storing it
* I can't really decompress and treat each one of the files as input because the tar.gz contains thousands of files
* so inside my container I'm going to call `tar zxf reference.tar.gz` and point my tool/workflow at that output
* the issues is, the 50GB of expanded data doesn't fit on the volume used for the root filesystem for this Docker container
* how can I:
    * pass in a directory of decompressed files to cwltools runner
    * or tell cwltools to use a particular working directory and ensure that, inside the container, I expand the file there

**Comment by denis-yuen** [comment]
Is there any significance to the 50GB number? Is it possible you actually ran out of space on the host machine?

Digging around, I haven't found any references to a maximum size for Docker volumes. In fact, I found an issue where people want actually restrict a volume from using up all the disk space available https://github.com/docker/docker/issues/16670

Alternatively, while specifying all input files inside the tar.gz individually would suck, I don't think that is actually necessary. I think CWL provides a couple options here that should work.
Out of the box, it looks like you can specify secondaryFiles using a pattern or even by expression if needed
https://github.com/common-workflow-language/common-workflow-language/issues/172#issuecomment-160703479

Alternatively, it looks like they're also working on supporting directories in issues linked to that thread, so you could lend a hand there.

**Comment by denis-yuen** [comment]
Re-open on clarification
