### ISSUE TITLE
Web UI should display easy command to run with cwl-runner

### ISSUE THREAD

**Issue by tetron** [ga4gh/dockstore#248]
`cwltool` and other CWL runners can run CWL files directly from URLs.  I'd like to see an easy cut-and-paste command for running tools similar to the existing "Docker Pull Command".  So in addition to:

```
Docker Pull Command
docker pull quay.io/briandoconnor/dockstore-tool-bamstats
```

We could also have:

```
CWL Runner Command
cwl-runner https://www.dockstore.org:8443/api/v1/tools/dockstore-tool-bamstats/version/latest/descriptor?format=CWL
```

**Comment by denis-yuen** [comment]
@tetron 
Hi, a couple questions about this idea. 
Question 1) The tool-registry specification so far indicates that it produces two formats, JSON and plain text ( https://github.com/ga4gh/tool-registry-schemas/blob/develop/src/main/resources/swagger/ga4gh-tool-discovery.yaml#L7 ). 

The intent was the the ToolDescriptor would output either our JSON object (so far just containing the content and a URL to the original file) or the actual CWL file depending on the content type. 

The cwl-runner implementation I have (cwltool 1.0.20160323212343)  seems to do a wildcard request so it gets back JSON which it doesn't understand. 

Would it make more sense to add/modify endpoints to the tool registry schema so it doesn't rely on content-type or change cwltool and other runners to send a specific content-type?

2) When using CWL files from URLs, how are imports handled?

**Comment by denis-yuen** [comment]
This is functional on staging.dockstore.org, for example https://staging.dockstore.org/containers/quay.io/collaboratory/dockstore-tool-bedtools-genomecov
