### ISSUE TITLE
Link to descriptor for easy copy-and-paste 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#249]
Link to the descriptor or do something like http://mvnrepository.com/artifact/commons-io/commons-io/2.5 where a simple one-click copies the descriptor into the clipboard 

Idea split out from #248 .
Should implement along with #201 at the same time

**Comment by tetron** [comment]
One click copy and paste is a good idea, but I would still want a download link.

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/105

**Comment by agduncan94** [comment]
As discussed, going to add a download file button similar to the copy button in the files tab, as well as a link to download the main descriptor in a box on the right.
