### ISSUE TITLE
Login issue with some installs of Google Chrome 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#250]
Difficult to describe this one. 
Login seems to work with Firefox across the board, also with Chromium across the board. 
There are, however, intermittent issues with Google Chrome. (Intermittent in the sense that not all users get the issue, but once they do, it doesn't go away)/ 

This bears further investigation.

**Comment by jpatricia** [comment]
Encountering the issue on desktop Chromium and Chrome. 
This has the following characteristics

1. On the affected machine, it affects Chrome and Chromium but not Firefox
2. On the affected browser, a different user can attempt to login but will fail
3. The version is `Version 50.0.2661.102 Ubuntu 14.04 (64-bit)`  but another machine has the same version
4. The error code in the web service is not always the same, it can be 400 or 409, but once login fails it seems to fail continuously. 
5. Reconstructing the call that the web service makes to  https://developer.github.com/v3/oauth/#3-use-the-access-token-to-access-the-api  we just get a message about https://developer.github.com/v3/oauth/#bad-verification-code with a status code of 200. 

Seems like other developers have also encountered a similar issue. Google "bad_verification_code" to see other apps with the same issue and see why it occurs.

**Comment by denis-yuen** [comment]
A thought, we should maybe rewrite the OAuth2 flow code with the help of a library, say https://github.com/google/google-oauth-java-client

**Comment by denis-yuen** [comment]
Work around: Affected Chrome/Chromium browsers will be able to login by either logging out of the affected user or clearing all browsing information, currently trying to narrow down the issue.
