### ISSUE TITLE
Invalid GitHub tokens can blank associated source files

### ISSUE THREAD

**Issue by nuwang** [ga4gh/dockstore#251]
Hi,

I'm new to dockstore and am trying to get it working for the first time with the following workflow: https://github.com/ICGC-TCGA-PanCancer/Seqware-BWA-Workflow

After setting up dockstore v0.4-beta1, I tried to fetch the cwl file as follows:
`dockstore tool cwl --entry quay.io/pancancer/pcawg-bwa-mem-workflow:2.6.8`

However, the fetch fails with 'No cwl file found.' However, running
`dockstore tool info  --entry quay.io/pancancer/pcawg-bwa-mem-workflow`
works as expected and shows the path to the cwl file.

Is my expectation of how this is supposed to work correct? Please see below for the full log.

cheers!
/Nuwan

```
(tmp)galaxy@server-dcdaa0b3-2b5b-488d-8bfa-f3e36ce2da83:/tmp$ dockstore tool cwl --entry quay.io/pancancer/pcawg-bwa-mem-workflow:2.6.8 --debug
13:06:36.993 [main] DEBUG o.a.c.c.ConfigurationUtils - ConfigurationUtils.locate(): base is null, name is /home/galaxy/.dockstore/config
13:06:36.997 [main] DEBUG o.a.c.c.DefaultFileSystem - Could not locate file /home/galaxy/.dockstore/config at null: no protocol: /home/galaxy/.dockstore/config
13:06:36.997 [main] DEBUG o.a.c.c.ConfigurationUtils - Loading configuration from the absolute path /home/galaxy/.dockstore/config
May 31, 2016 1:06:39 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Sending client request on thread main
1 > GET https://www.dockstore.org:8443/containers/path/tool/quay.io%2Fpancancer%2Fpcawg-bwa-mem-workflow/published
1 > Accept: application/json
1 > Authorization: Bearer REDACTED
1 > User-Agent: Java-Swagger

May 31, 2016 1:06:40 PM org.glassfish.jersey.filter.LoggingFilter log
INFO: 1 * Client response received on thread main
1 < 200
1 < Content-Length: 2257
1 < Content-Type: application/json
1 < Date: Tue, 31 May 2016 13:09:10 GMT
1 < Vary: Accept-Encoding

No cwl file found.
```

**Comment by denis-yuen** [comment]
Hi,
Your understanding is correct. The issue seemed to be that the tools in the collaboratory and pancancer organizations seem to have been blanked of content.

I'll have to investigate further to find an explanation, but in the meantime I've refreshed the information and it should be working now.

**Comment by nuwang** [comment]
@denis-yuen The token refresh seems to have done the trick - thanks!
