### ISSUE TITLE
Elaborate on validation errors

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#259]
i.e. what fields were missing
```
ubuntu@brian-pcawg-bwa-testing:~/gitroot/dkfz_dockered_workflows$ dockstore tool launch --entry /home/ubuntu/gitroot/dkfz_dockered_workflows/Dockstore.cwl --json /home/ubuntu/gitroot/dkfz_dockered_workflows/Dockstore.json  --local-entry  --descriptor cwl

Entry file is not a valid CWL file.
```

@briandoconnor  maybe just point Patricia toward the CWL files for this. I see https://github.com/ICGC-TCGA-PanCancer/dkfz_dockered_workflows but I don't see CWL checked in yet

**Comment by briandoconnor** [comment]
#260, this is now a duplicate so closing @denis-yuen
