### ISSUE TITLE
500 when trying to add a tool - better error message without quay.io account

### ISSUE THREAD

**Issue by philloooo** [ga4gh/dockstore#267]
Using the same repository as in #266, I got a 500, any idea what's causing it?
![screen shot 2016-06-09 at 8 10 49 pm](https://cloud.githubusercontent.com/assets/3324084/15951490/637b7b48-2e7e-11e6-9402-980684e1d12a.png)

**Comment by denis-yuen** [comment]
FYI, so that I don't leave you hanging. This should be correct, unlike with #266.
I was able to register my fork of this, so I'm currently investigating.

**Comment by denis-yuen** [comment]
Ok, the issue here is that your account has no quay.io account linked to it. Therefore, the refresh code isn't able to get information about `cdis/cwlutils`. Is it possible for you to try linking up quay.io at https://www.dockstore.org/accounts ?

**Comment by philloooo** [comment]
Got it, works now, thanks!
Could you add a more descriptive response for this scenario?

**Comment by denis-yuen** [comment]
Definitely :+1:

**Comment by denis-yuen** [comment]
Live in production
