### ISSUE TITLE
deleted repo from github is still on the workflow/tool list

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#268]
A repo is deleted on github, but that deleted repo is still available in the "My Workflows' list. This repo will still be on the list even after hitting the 'Refresh All Workflows' button. When the link to the workflow is clicked, and then hit the 'Refresh' button, it will output an error as the github repo link is invalid(not available anymore)
Same thing goes for "My Tools"

**Comment by denis-yuen** [comment]
That's true, we don't have delete functionality for many entities. This is related to #148

**Comment by SolomonShorser-OICR** [comment]
:+1: 

Also, there should be a "Delete" button for tools and workflows so that if one of them is created incorrectly or a user simply no longer wants it there, they should be able to do that (instead of unpublishing, which still leaves data in the database).

**Comment by denis-yuen** [comment]
Related to #655

**Comment by agduncan94** [comment]
This is still an issue, I think it could be annoying for users. Perhaps on refresh, if a tool/workflow no longer exists on github/bitbucket/gitlab then we can do the following (quick brainstorm):

For stub workflows, delete automatically.

For tools and full workflows we want to preserve the history in case it was accidental, the git registry is down forever, or whatever the case may be.

- Tag it with delete tag of some sort
- Can refresh, which checks if the repo exists again, if not simply skip over
- Give owner option to delete (doesn't currently exist)
- Owner can leave it as is if they want to keep the history

**Comment by denis-yuen** [comment]
related to #1995
