### ISSUE TITLE
Implement account-less new user flow

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#271]
- The documentation does not make it clear that a user must actually log in to obtain the Dockstore CLI client
- The instructions when setting up a new account are not clear. The Setup page says to
  1. download and execute a script and follow its instructions
  2.  THEN copy and past the token into `~/.dockstore/config`. When the script is run, it asks if I've set up an account. Since I'm in the _middle_ of the process, I answer "N" (because I haven't completed account setup, just half-way through - or at least that's what it looks like to me), and the script exits. I then proceed with step (ii) and re-run the script. When I re-run, it is **NOT** interactive like it was the first time (it prints its own help text and then simply exits) - but there is no explanation of this change in behaviour. 
- It is hard to find the link back to download the CLI tool again. "Setup" is not intuitive.

Maybe there should be a big ad/image on the front page that says "Get started today!!" with a direct link to download the dockstore CLI. Then they should be prompted for account creation if they don't have one - but is an account even really _necessary_ if they are just interested in playing with CWL/Dockstore capabilities locally on their workstation?

**Comment by denis-yuen** [comment]
@briandoconnor 
Relating to our conversation:
We should also make sure that certain operations (listing public tools, launching them) can work properly without a token

**Comment by briandoconnor** [comment]
+1 to token-less launch and listing

**Comment by denis-yuen** [comment]
For @garyluu 
1) Make sure that our site and CLI actually are user-friendly for account-less or guest users. This includes not having a config file or a minimal one without account information
2) Update documentation so that this makes sense  for the operations above

**Comment by denis-yuen** [comment]
As an update for who works on this ticket, many users just use a dummy token with success but this needs documentation

**Comment by denis-yuen** [comment]
There is now a path for this at https://staging.dockstore.org/quick-start
