### ISSUE TITLE
PUT will reset the value back to default

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#274]
When trying to change the value of these: default cwl path, default wdl path, default dockerfile path, toolname, gitUrl, the value will be reset to the default value assigned in the Java object. Currently, you need to update all information at once in order to change the value. However, if you just do one at a time(e.g change cwl path first, then change wdl path), the changes from cwl path will be gone, it will get reset to the default value as if no changes have ever been made. If the changes are made directly in Postgre using UPDATE, it works fine.

Options: 
1. Get rid of the default values, but this might require more changes on other parts of the code.
2. Change the implementation of PUT to check if there's any changes from the old value.

NOTE: For GUI part, for now it will submit all 5 fields everytime the default path is changed. When this issue is fixed, the GUI part will need to be changed so it can submit just one field instead of all 5 fields everytime when editing 1-3 fields(default cwl/wdl/dockerfile path)

**Comment by denis-yuen** [comment]
After doing some reading, it seems that we've entered a bit of a minefield. 
See articles such as https://soabits.blogspot.ca/2013/01/http-put-patch-or-post-partial-updates.html
http://www.apuchkov.com/choosing-the-best-approach-for-partial-updates-in-rest-api/
https://stormpath.com/blog/put-or-post

In short, it seems that there is a philosophical grey area in how to handle partial updates. For now, the "canonical" REST thing to do is to always send back the full representation in a PUT request, but there is a debate as to whether to use PATCH for partial updates.
