### ISSUE TITLE
Streamline selection of descriptor-type and workflow path

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#284]
When changing the descriptor-type and workflow-path, some changes could be streamlined. 
a) When toggling the descriptor-type, the workflow path should be automatically changed to match the new extension (e.g. choosing WDL should cause /Dockstore.cwl to change to /Dockstore.wdl)
b) When editing the workflow path, the change should cascade down to the versions of the workflow as well (this can be done either in the GUI or in the web service)

**Comment by jpatricia** [comment]
Notes: 
a). Users are allowed to put in anything in the workflow path when editing. However, should add warning if the extension is not cwl,wdl,yaml,yml. If the extension in workflos path is neither cwl/wdl, then dont change the descriptor type dropdown.
b). Changing the workflow path in 'Info' tab(default) should change the workflow path in 'Version' tab, but not the other way around. Changing path in 'Version' tab should not change the path in 'Info' tab(default)
