### ISSUE TITLE
Validation warning a bit too eager

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#290]
Validation warnings currently show up in both "My Tools" and "Tools". 
They should only really show up in "My Tools" (i.e. when looking at your own tools that you can change) and not when looking in "Tools" (everyone's published tools)

The same for Workflows/My Workflows if applicable

![screenshot from 2016-06-20 14 51 22](https://cloud.githubusercontent.com/assets/1730679/16206467/9cd23e38-36f6-11e6-9cc2-192ac3740990.png)

**Comment by jpatricia** [comment]
fixed by adding a line for the warning to show only when it's on edit mode

**Comment by denis-yuen** [comment]
Seems to still be an issue

![screenshot from 2016-06-24 14 46 38](https://cloud.githubusercontent.com/assets/1730679/16347395/7f658162-3a1a-11e6-9a3a-43fbbcc758a4.png)

**Comment by jpatricia** [comment]
Fixed: https://github.com/ga4gh/dockstore-ui/commit/1b2ed44d9268c5cb62f855214a661ae8d9045678
