### ISSUE TITLE
Fix JSHint issues

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#308]
[JSHint](http://jshint.com/docs/) flags a bunch of suspicious usages when compiling, fix these so that we can compile without using `--force`

```
Running "jshint:all" (jshint) task

app/scripts/controllers/containerdetails.js
  line 36   col 8    Missing semicolon.
  line 148  col 23   Expected '!==' and instead saw '!='.

app/scripts/controllers/containerfileviewer.js
  line 86   col 24   'result' is already defined.
  line 118  col 24   'i' is already defined.
  line 134  col 45   Missing semicolon.
  line 227  col 123  Expected '===' and instead saw '=='.
  line 227  col 142  Missing semicolon.
  line 227  col 144  Missing semicolon.

app/scripts/controllers/registerworkflow.js
  line 58   col 28   Expected '!==' and instead saw '!='.

app/scripts/controllers/workflowdagview.js
  line 45   col 39   Expected '===' and instead saw '=='.
  line 121  col 28   'cytoscape' is not defined.

app/scripts/controllers/workflowdetails.js
  line 118  col 53   Missing semicolon.
  line 130  col 23   Expected '!==' and instead saw '!='.
  line 337  col 84   Missing semicolon.

app/scripts/controllers/workflowfileviewer.js
  line 86   col 24   'result' is already defined.
  line 117  col 24   'i' is already defined.
  line 132  col 45   Missing semicolon.
  line 189  col 123  Expected '===' and instead saw '=='.
  line 189  col 142  Missing semicolon.
  line 189  col 144  Missing semicolon.

  ⚠  20 warnings

Warning: Task "jshint:all" failed. Use --force to continue.
```

**Comment by denis-yuen** [comment]
Also running into karma issues (unit testing) after a bower update
```
Running "karma:unit" (karma) task
29 06 2016 15:33:02.474:WARN [watcher]: Pattern "/home/ubuntu/workspace/dockstore-ui/test/mock/**/*.js" does not match any file.
29 06 2016 15:33:02.546:INFO [karma]: Karma v0.13.14 server started at http://localhost:8080/
29 06 2016 15:33:02.552:INFO [launcher]: Starting browser PhantomJS
29 06 2016 15:33:02.807:INFO [PhantomJS 1.9.8 (Linux 0.0.0)]: Connected on socket sLursRYaKjAPzLUJAAAA with id 9194385
PhantomJS 1.9.8 (Linux 0.0.0) ERROR
  TypeError: 'undefined' is not a function (evaluating 'math.makeBoundingBox.bind( math )')
  at /home/ubuntu/workspace/dockstore-ui/bower_components/cytoscape/dist/cytoscape.js:26444


Warning: Task "karma:unit" failed. Use --force to continue.
```

**Comment by jpatricia** [comment]
The issues are fixed (will be on a pull request soon), except for "line 121  col 28   'cytoscape' is not defined." and the karma issue
- Not sure about the karma issue, but it looks like it's from the original cytoscape.js itself, which I dont think it's fixable(?)
- For cytoscape issue, it's how they gave example on https://gist.github.com/maxkfranz/e52c2fbc0b09edd6ec46 , and i also think this one is not fixable, since it's how to use the cytoscape for dag

**Comment by denis-yuen** [comment]
Leaving this open until we can run without --force
(Will need a deeper look at Cytoscape, karma)

**Comment by jpatricia** [comment]
With the package.json and bower.json updated with newer versions of the modules, jshint issue might have been resolved. Locally, I dont have anymore jshint issue. Will need to test on staging and production about this

**Comment by jpatricia** [comment]
After checking karma.conf.js (can be found in test folder), in the 'files' field, it includes all bower components, all scripts with *.js extension inside app/scripts, and it includes all tests inside test/mock and test/spec
Looking into the test files inside test folder, it does not have any meaningful tests. It only does beforeEach to inject the function/module. After the beforeEach, there is a commented test, which in this case, should not lead to any issue of failing the test or give back JSHint issue. All of the test files in 'test' folder have the same format of beforeEach and a commented test.

**Comment by denis-yuen** [comment]
This looks fixed now
