### ISSUE TITLE
Hook up GUI testing to generate and display coverage

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#316]
Testing on the back-end is well developed. 
However, testing of the UI is much less well developed. 

Research needs to be done on how to properly test an AngularJS application 
https://docs.angularjs.org/guide/unit-testing

Note that the current source does have some setup to use Karma, Jasmine. 
However, it is not up to date with 0.4 (workflows, DAG, tools tab, etc.) and may or may not be broken.

Afterwards, hook up coverage information to coveralls.io so that we can track our progress. 
https://coveralls.zendesk.com/hc/en-us/articles/201769715-Javascript-Node

**Comment by denis-yuen** [comment]
Additional ideas:
https://github.com/angular/protractor
https://ghostinspector.com/

**Comment by jpatricia** [comment]
Great tutorial about setting up and using jasmine, karma, coveralls and travis: http://fatihacet.com/feci/
It also includes an explanation about using Istanbul, which is a code coverage tool, that can be used before Coveralls and travis

**Comment by jpatricia** [comment]
https://www.cypress.io/ This thing seems to be way easier to use and setup compare to protractor, seeing how we've had some problems with protractor, phantomjs and selenium when running the e2e tests.

**Comment by denis-yuen** [comment]
Currently running and visible at https://github.com/ga4gh/dockstore-ui
