### ISSUE TITLE
auto-conversion, if a user uploads a WDL auto-convert to CWL and vice versa(?)

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#32]
-  (Broad group may help with this)

**Comment by briandoconnor** [comment]
Can we get Jay or someone from the Broad to help?

**Comment by denis-yuen** [comment]
Keep an eye on the progress of https://github.com/common-workflow-language/wdl2cwl

**Comment by denis-yuen** [comment]
Blocked on outside dependencies, re-open when this is actionable
