### ISSUE TITLE
Update Dockstore GUI for CWL 1.0 changes

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#322]
Experiment with samples of CWL 1.0 and make sure we are compatible http://www.commonwl.org/

**Comment by jpatricia** [comment]
In particular, make sure that the DAG code works if there have been any changes to workflows in 1.0

**Comment by denis-yuen** [comment]
Looks like duplicate of #365

**Comment by jpatricia** [comment]
After reading into the documentation more, CWL 1.0 changes should not affect the current validation check because the 1.0 changes are for the inner part of 'steps', which in this case are not checked in the validation check code.
