### ISSUE TITLE
Display correct dates for creation and update of workflows (DB and github)

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#331]
It should be showing the last time/date of the version is built or modified
Note: only happens in Workflow

**Comment by jpatricia** [comment]
This issue is more to webservice side than gui. Observation from webservice side: One difference between Tools and Workflow is that Workflow will create a new workflow everytime refresh is hit. If the same workflow already exist, it will copy the workflow into that newly created workflow. Everytime a workflow is obtained from WorkflowDAO, that workflow somehow does not have workflow versions.
Whereas in Tools, after getting the user token, it will call helper to refresh container, which will check and update database if there is any changes. Everytime tool is obtained from ToolDAO, the tool will have complete information including the tags and its information.
It is a bit weird that the workflow somehow have a different information obtained compare to Tools.

**Comment by denis-yuen** [comment]
This still exists as of the 1.1 release

**Comment by agduncan94** [comment]
This is simply because on refresh we create new workflow versions, and if a matching one exists in the database, we simply copy the newly created version to the old one. In this copy, we are setting the last modified to be the same as the newly created workflow version, however we never set the last modified for the newly made workflow version. So to fix this we just need to update the workflow version initialization code to also set last modified.

**Comment by agduncan94** [comment]
It seems like we need to add code to check the git repository for the last update, it isn't possible to grab it from existing API calls that we use.

After a quick look it seems like it is possible for GitLab and Bitbucket, but the egit thing we use doesn't seem to have the option.

**Comment by denis-yuen** [comment]
Still exists in 1.2-alpha.3

**Comment by denis-yuen** [comment]
This is a more general task, we should make sure that we show creation and update times properly for workflows.

**Comment by denis-yuen** [comment]
Merged issue

## Feature Request 
Have user friendly last modified/updated dates.

### Desired behaviour
Instead of only using x days since last modified, use months and years too.

**Comment by denis-yuen** [comment]
@coverbeck looks like this duplicates/is related to #514 , review for new info

**Comment by denis-yuen** [comment]
#1147 does a partial implementation for workflows, github only

**Comment by denis-yuen** [comment]
Will need to follow up with tickets for other types of source control
