### ISSUE TITLE
blank descriptor path for tool returns Null pointer exception

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#332]
If Dockerfile and CWL path are not empty, but WDL path is empty, it should not return null pointer exception. Same thing for Dockerfile and WDL but CWL is empty.
Currently, if cwl path is empty, it will return null pointer exception without even checking wdl and dockerfile. Apparently, the webservice is set that the descriptor/dockerfile path cannot be empty/blank.
Note: there is no warning or null pointer exception returned if the path is not blank(e.g put random name in cwl path: /foobar.cwl when there is no foobar.cwl in the repo)

**Comment by denis-yuen** [comment]
:+1:

**Comment by agduncan94** [comment]
A tool should have at least one non-empty default descriptor path. But what about with tags, do these also need at least one non-empty descriptor?

**Comment by denis-yuen** [comment]
@agduncan94  I think this might be only partially complete, but please-double check.
The intent here was that if the default Dockerfile/WDL/CWL paths are set before tags/versions are created, all of the tags will get those default versions. If the default is set afterwards, it should cascade to all the tags and refresh them.  

Specifically for tags, a user could change them one-by-one afterwards, for example when only one version has an alternative path. That said, I don't see a user-case for a tag with no descriptors, so we should probably disallow that.
