### ISSUE TITLE
Dockstore pagination order could be better

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#336]
Currently, it goes (record numbers), previous, next. 
However, for google, it goes  previous, record numbers, next. 

I put the record number in quotes because we don't actually have click able page numbers which could be useful.

**Comment by denis-yuen** [comment]
Still needs clickable page numbers, which would probably require #368

**Comment by agduncan94** [comment]
See pull request https://github.com/ga4gh/dockstore-ui/pull/95
