### ISSUE TITLE
UI: look at linking to tools defined by other standards such as Galaxy Toolshed, Elixir and WDL from the Broad

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#34]
bulk import for galaxy toolshed registered tools, for each XML, convert to CWL and build docker image on top of galaxy docker image that calls galaxy toolshed

**Comment by briandoconnor** [comment]
Galaxy Toolshed might be a really good project for Sheldon

**Comment by denis-yuen** [comment]
Break this out into more specific issues later
