### ISSUE TITLE
Testing Dockstore-UI (Unit Testing and E2E Testing)

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#349]
## Feature Request 
Need to create unit tests for dockstore-ui. Currently, the coverage is very low because there are no meaningful unit tests created in the project. Follow the 'test/spec/**' folder to implement the unit tests for each files. After the unit testing, will need to do end to end testing to make sure everything is working properly.

Related issue: https://github.com/ga4gh/dockstore/issues/316

**Comment by jpatricia** [comment]
Testing services: http://nathanleclaire.com/blog/2014/04/12/unit-testing-services-in-angularjs-for-fun-and-for-profit/

**Comment by denis-yuen** [comment]
Related to #316
