### ISSUE TITLE
URL formatting issues in JSON response

### ISSUE THREAD

**Issue by tfmorris** [ga4gh/dockstore#352]
version: "0.4-beta.4",
https://staging.dockstore.org:8443/api/v1/tools

There are a few problems with the URLs returned in the JSON response:
- the `api/v1/` prefix is omitted
- `version` is used instead of `versions`
- slashes (/) are double encoded, coming out as `%252F` instead of `%2F` (they work like that, so presumably they're getting double decoded, but this will be confusing for client software which is encoding its own identifiers in URLs)

**Comment by denis-yuen** [comment]
Hi, thanks for the heads up!

**Comment by denis-yuen** [comment]
Currently in test on staging.dockstore.org implemented in https://github.com/ga4gh/dockstore/releases/tag/0.4-beta.5

Note that the path is now https://staging.dockstore.org:8443/api/ga4gh/v1/tools due to changes in the 1.0.0 pull request

**Comment by tfmorris** [comment]
Thanks! I only poked at it a little bit, but LGTM.
