### ISSUE TITLE
Migration and testing of sample Dockstore tools to CWL 1.0

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#354]
## Feature Request 

Sample SAB tools should be updated to CWL 1.0

### Desired behaviour

Each repo for the SAB tools (originally converted by Andy @ Collaboratory) needs to have a new tag with CWL 1.0 descriptors. The Dockstore CLI should be capable of launching these tools both in their draft-3 and 1.0 incarnations (which means that these repos will also need sample json parameter files).

**Comment by jpatricia** [comment]
Double check that our launcher code can correctly handle the new simplified syntax for inputs and output 
http://www.commonwl.org/v1.0/CommandLineTool.html#Introduction_to_v1.0

(This might work since we use avro)

**Comment by denis-yuen** [comment]
See the following for instructions and to co-ordinate tools which have been successfully upgraded https://github.com/ga4gh/dockstore/wiki/Upgrading-of-PCAWG-and-Sample-Tools-on-Dockstore

**Comment by denis-yuen** [comment]
Completed by @agduncan94
