### ISSUE TITLE
Build issues

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#359]
### Expected behaviour

1.  `grunt` in production does not require --force
2. gitVersion.htm should be created in the normal `grunt` lifecycle and the build should fail if unable to create it 

### Actual behaviour

1. `grunt` in production dies on the following error

```
Running "protractor:e2e" (protractor) task
[18:32:36] E/launcher - Process exited with error code 1
/home/ubuntu/workspace/dockstore-ui/node_modules/q/q.js:155
                throw e;
                ^

Error: No selenium server jar found at the specified location (/home/ubuntu/workspace/dockstore-ui/node_modules/grunt-protractor-runner/node_modules/protractor/selenium/selenium-server-standalone-2.52.0.jar). Check that the version number is up to date.
```
This is for unit testing (i.e. unit testing should not really have to run in production) 

2. gitVersion.htm is not created normally and thus the grunt insert task simply blanks the gitVersion without filling it in, with no error indicated.

**Comment by jpatricia** [comment]
1. when running `grunt`, it will go to 'default' in Gruntfile.js, which includes 'test', so it will automatically run `grunt test` --> will need to get rid of 'test' inside 'default'
2. gitVersion is added inside `serve:dist` --> will also need to edit this to run on regular grunt
