### ISSUE TITLE
API hyperlink, remove extra break between UI and API description

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#363]
### Desired behaviour

Currently, the two versions at the bottom of the UI look like 
```
DockstoreUI - 0.4-beta.8 - d750c51

DockstoreApi - 0.4-beta.5 
```

Ideally, they would look like 

```
DockstoreUI - 0.4-beta.8 - d750c51
DockstoreApi - 0.4-beta.5
```

where a link is added to both tags, linking to the appropriate release on GitHub
ex: https://github.com/ga4gh/dockstore/releases/tag/0.4-beta.5

**Comment by jpatricia** [comment]
can be fixed by adding 'style="line-height: 1em;"' into either or both DockstoreUI and DockstoreApi html tag
