### ISSUE TITLE
Update CWL validation check to CWL 1.0 syntax

### ISSUE THREAD

**Issue by jpatricia** [ga4gh/dockstore#365]
## Feature Request 
Need to update the cwl validation check on both cli and gui to also accept cwl 1.0 syntax
example: 'input'-> 'in', 'output'->'out'

**Comment by denis-yuen** [comment]
Related to #365

**Comment by jpatricia** [comment]
#322 will be the gui and this issue will be for cli

**Comment by jpatricia** [comment]
After reading into the documentation more, CWL 1.0 changes should not affect the current validation check because the 1.0 changes are for the inner part of 'steps', which in this case are not checked in the validation check code.

**Comment by denis-yuen** [comment]
Looks like no issues with current slate of CWL 1.0 tools on staging
