### ISSUE TITLE
Permalink for dockstore search results

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#368]
### Desired behaviour

It would be neat to have a permanent link to particular search results. Like https://staging.dockstore.org/search-containers?term=test or something similar

Notice for @briandoconnor

**Comment by denis-yuen** [comment]
This was echoed in the docker testing group meeting in 2016-09-14 to allow the ICGC portal to link to pre-populated searches for pcawg tools

**Comment by agduncan94** [comment]
This link would be useful
https://docs.angularjs.org/api/ng/service/$location

**Comment by agduncan94** [comment]
This is already sort of implemented in production.
https://dockstore.org/search-workflows/searchterm
Above will load "searchterm" into the search box and search automatically when you go to the page.

This is obviously not ideal, so I will implement using query params like mentioned above.

**Comment by agduncan94** [comment]
See pull request https://github.com/ga4gh/dockstore-ui/pull/95
