### ISSUE TITLE
"Tools" and "DAG" tabs not populated for workflow.

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#369]
The "Tools" and "DAG" tabs are not populated with a workflow that I just registered. 

Under "Tools" it says "Some tools associated with this workflow are missing from Github repo." even though all tools used by the workflow are in the same repo as the workflow, and when I click on the "Descriptor"  tab, I can *see* all of the tool files listed there (and I can see their contents when I select them)

Under "DAG", it says "A Descriptor associated with this workflow could not be found. " but the "Descriptor" tab correctly shows the workflow CWL file.

Workflow in question:

https://staging.dockstore.org/workflows/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/oxog-preprocessor

**Comment by jpatricia** [comment]
Error from webservice side: 
`java.lang.ClassCastException: java.util.LinkedHashMap cannot be cast to java.util.ArrayList`

**Comment by agduncan94** [comment]
Seems like this was fixed, so I am closing it.
