### ISSUE TITLE
Support for multiple primary logins

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#37]
Right now we require a Github account to login to the system.  We should provide more options including (in order of priority):
- google
- yahoo
- twitter
- facebook
- windows live

This is just to establish the user identity, if they login with any of the above it establishes their account (giving us a username/email to search on when modifying image permissions via Quay.io) but the user will need to link to GitHub (and/or Bitbucket) and Quay.io to complete onboarding.

┆Issue Number: DOCK-8

**Comment by briandoconnor** [comment]
See https://github.com/sahat/satellizer

**Comment by briandoconnor** [comment]
Would be great to at least have Google working as an alternative to Github

**Comment by denis-yuen** [comment]
Grouping this with #1040 since it looks like FireCloud login will be our first second login method

**Comment by denis-yuen** [comment]
Google functional as of at least #1437 (thanks @garyluu )
Please follow-up with new methods with specific tickets
