### ISSUE TITLE
Can't access plain-CWL through GA4GH API

### ISSUE THREAD

**Issue by tetron** [ga4gh/dockstore#375]
The URL 

https://www.dockstore.org:8443/api/v1/tools/quay.io%252Fcollaboratory%252Fdockstore-tool-bwa-aln/versions/master/plain-CWL/descriptor

returns a 404:

```
{"code":404,"message":"HTTP 404 Not Found"}
```

However as far as I can tell it appears to be correct according to the swagger API spec,

```
  /tools/{id}/versions/{version-id}/{type}/descriptor
```

Where `id = quay.io%252Fcollaboratory%252Fdockstore-tool-bwa-aln`, `version-id = master` and `type = plain-CWL`

**Comment by denis-yuen** [comment]
As per gitter, Give https://staging.dockstore.org:8443/api/ga4gh/v1/tools/quay.io%2Fcollaboratory%2Fdockstore-tool-bwa-aln/versions/master/plain-CWL/descriptor a shot instead 

Review again after release to production
