### ISSUE TITLE
Print GA4GH id as container page title

### ISSUE THREAD

**Issue by tetron** [ga4gh/dockstore#377]
The title line of the container page has an abbreviated version of the container name, for example `collaboratory/dockstore-tool-bwa-samse`

However, the GA4GH API paths looks like:

`/api/ga4gh/v1/tools/quay.io%252Fcollaboratory%252Fdockstore-tool-bwa-samse`

This means if a user copies and pastes `collaboratory/dockstore-tool-bwa-samse` from the page into a tool that integrates with the GA4GH API, it will looks try `/api/ga4gh/v1/tools/collaboratory%252Fdockstore-tool-bwa-samse` which is missing the `quay.io/` part.

The title line should provide the full identifier of the container to support user workflows that access Dockstore from other tools, such as `cwltool`.

**Comment by denis-yuen** [comment]
Makes sense. 

Note for the implementer, I think the relationship between the title, name, and path needs to be reviewed (and simplified). I think the three have become somewhat redundant after we switched to the structure of (docker registry, defaults to docker hub if not present)/docker organization/docker repo/toolname

**Comment by tetron** [comment]
Alternately, `quay.io` doesn't need to be part of the dockstore id, in which case the title text can stay the same and it's the identifier exposed by the GA4GH API that should change.

**Comment by denis-yuen** [comment]
I think the title is actually currently misleading, but I need to double check how it changes when we add a custom tool name. `quay.io` does currently need to be part of the dockstore id and the title text should probably reflect that. 

For simplicity, we should probably export the same id to the GA4GH id to make your use case simple

**Comment by denis-yuen** [comment]
Example for implementer:

We have two tools with ids of "quay.io/denis_yuen/dockstore-tool-imports/test3" and "quay.io/denis_yuen/dockstore-tool-imports/test4". Both use the same quay.io image (and thus both share ""quay.io/denis_yuen/dockstore-tool-imports." Where they differ is that they poing to different cwl documents, the latter pointing to `/funky/Dockstore.cwl `

The titles use brackets to distinguish one from another ` denis_yuen/dockstore-tool-imports (test4) `, which isn't all that useful in the context of GA4GH. We should instead, simply show the GA4GH ids ` denis_yuen/dockstore-tool-imports/test4/`.

The name is redundant and should be omitted. The path can stay, although we should probably add a tool tip or explain that it is the docker path. 


![screenshot from 2016-08-16 17 17 29](https://cloud.githubusercontent.com/assets/1730679/17716207/b62729be-63d5-11e6-843d-51022a0e639e.png)
![screenshot from 2016-08-16 17 17 45](https://cloud.githubusercontent.com/assets/1730679/17716209/b7579e5e-63d5-11e6-9965-0d7d3ca449d2.png)
