### ISSUE TITLE
"Tools" and "DAG" tabs seem to have problems if a workflow contains a subworkflow or if a tool reference is in a git submodule.

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#382]
## Bug Report

Problem with this workflow: https://staging.dockstore.org/workflows/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/OxoG-Variantbam-Annotation-WF

Based on this github repo: https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools
### Expected behaviour

The Tools tab should show tools within the CWL and the DAG tab should show a DAG.
### Actual behaviour

Tools tab displays message: "Some tools associated with this workflow are missing from Github repo."

DAG tab displays message: "A Descriptor associated with this workflow could not be found. "

I'm guessing that this is because the Variantbam tool was originally created on its own in a stand-alone repository, and was then included into the OxoG-Dockstore-Tools repo as a submodule so that the workflow could make use of it from a relative path.

But since this workflow _also_ contains a reference to a subworkflow (the preprocessing workflow 9https://staging.dockstore.org/workflows/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/oxog-preprocessor) is the subworkflow) maybe that's what caused this error?

**Comment by agduncan94** [comment]
Submodules are currently not supported and will need to be added.

**Comment by agduncan94** [comment]
https://git-scm.com/book/en/v2/Git-Tools-Submodules
It seems like submodules are supported by Git, and not just a GitHub specific thing, which is good. I could see this being important if workflows use submodules as tools, which I could see as being a recommended practice.

**Comment by agduncan94** [comment]
This seems more like a new feature instead of a bug.

**Comment by denis-yuen** [comment]
Merging this ticket with https://github.com/ga4gh/dockstore/issues/382
