### ISSUE TITLE
Email field is not properly pulled from dct metadata

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#383]
## Bug Report

The "E-mail" field is not populated.

### Expected behaviour

When the descriptor contains "foaf:mbox" with a value, that value should show up in the UI in the "E-mail" field.

### Actual behaviour

The "E-mail" field shows as "n/a".

**Comment by SolomonShorser-OICR** [comment]
This has been observed in staging and production, for tools and workflows.

**Comment by agduncan94** [comment]
The author field is also blank.

**Comment by agduncan94** [comment]
fixed in #395
