### ISSUE TITLE
Refreshing hits an incorrect path if different versions have a different descriptor path

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#390]
### Expected behaviour

Refreshing should pull up description, author, and email from the descriptor specified for each version, from the default, if not specified. 

### Actual behaviour

Refreshing always pulls up the descriptor specified as the default path.

**Comment by denis-yuen** [comment]
A good example is https://github.com/denis-yuen/dockstore-tool-imports which has Dockstore.cwl renamed to different files on each of its two branches.

**Comment by denis-yuen** [comment]
As discussed, this is grouped with your work on setting a default branch.

**Comment by agduncan94** [comment]
fixed in #395
