### ISSUE TITLE
Clean up/reorganizing of tool/workflow info tab

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#391]
I feel that we can better layout the info for the tools/workflows on the Info tab.

![screenshot from 2016-08-31 09 13 35](https://cloud.githubusercontent.com/assets/6331159/18130036/70c61a88-6f5b-11e6-9f99-c76dab2b4c2f.png)

As seen in the screenshot, we just display info line by line.  Perhaps grouping similar information within the info tab would be better for the user.

For example, Author and Email could be under Contact Info.
Dockerfile path, CWL path, WDL path, etc could be under Associated Files.

**Comment by agduncan94** [comment]
Also hovering over some of the information, like Build Mode, will display a tooltip with a brief explanation of what the attribute means.

**Comment by denis-yuen** [comment]
I definitely like the tooltip idea, especially for "Last Build", "Last Update".  
A different layout, I'd probably need to see example to have a strong opinion about that.
