### ISSUE TITLE
Expose extra cwltool parameters for debugging

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#396]
## Feature Request 

When debugging tools (and workflows), it would be useful to expose additional parameters from cwltool. In particular, `--leave-tmpdir` and `--leave-container`.  `--debug` might also be useful (might already be exposed by `dockstore --debug`)

### Desired behaviour

A new flag in the configuration file (defaults to blank) that allows one to set additional parameters to cwltool launch. 

```
ubuntu@dkfz-psuedo-mega-testing:~/dkfz_dockered_workflows$ cat ~/.dockstore/config 
token: <blah>
server-url: https://staging.dockstore.org:8443
use-cache = true
cwltool-extra-parameters = -- debug --leave-container
```

**Comment by agduncan94** [comment]
fixed in #397
