### ISSUE TITLE
Supporting tertiary, quaternary, etc cwl files

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#399]
## Feature Request

Currently Dockstore only supports CWL files with at most one level of dependent CWL files (secondary descriptors). It may be the case that a workflow contains another workflow as a step, and the second workflow would thus have it's own secondary descriptor files.  I am not sure if this will be a similar problem for WDL.
### Desired behaviour

Dockstore should grab all dependent descriptor files, and not just secondary descriptors.

**Comment by agduncan94** [comment]
http://www.commonwl.org/v1.0/Workflow.html#WorkflowStep
As seen here a workflow step can be either a tool or another workflow, so this is needed.

**Comment by agduncan94** [comment]
cwltool --dry-run and --print-deps might be useful

**Comment by agduncan94** [comment]
See [4.2WorkflowStep->Subworkflows](http://www.commonwl.org/v1.0/Workflow.html)

**Comment by agduncan94** [comment]
We would also need to support files in WDL. It is easier in WDL as you just have to grab the files required for each by looking at each files import. So you look at a file, find the imports, look at each import, check for imports, etc until a file has no imports. We would have to ensure that there are no cycles occurring (A imports B, B imports A)

**Comment by denis-yuen** [comment]
I think this was effectively done at some point before checker workflows since https://dockstore.org/workflows/github.com/dockstore-testing/dockstore-workflow-md5sum-unified/cwl_checker has a two level import. 

This was also done for WDL recently in #1446
