### ISSUE TITLE
Catch-up documentation for 1.0

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#405]
## Feature Request 

Documentation should be up-to-date to reflect new features and best practices SOP for creating Dockstore tools 

### Desired behaviour

In particular, documentation should cover:
* default branch selection
* extra cwl tool flags (MAC example)
* our support of GA4GH tool-registry-schema
* tips for bringing complicated tools into CWL 1.0 and Dockstore (also integrate tips from wiki https://github.com/ga4gh/dockstore/wiki/Dockstore-New-Developer-Tutorial#tips--tricks ) (this could be our FAQ #38 )
  * extra tip, deleted GitHub versions will need their corresponding quay.io version deleted to remove them from Dockstore

* Add a cumulative changelog from previous production (0.4-beta.4) to https://staging.dockstore.org/docs/blog 

* Add grant announcement to news events https://news.oicr.on.ca/2016/09/canadian-government-makes-big-investment-in-big-data-research/

* Add how to cite Dockstore 

[![DOI](https://zenodo.org/badge/DOI/10.5281/zenodo.154185.svg)](https://doi.org/10.5281/zenodo.154185)

**Comment by agduncan94** [comment]
Default branch selection and extra cwl tool flags have been added.

**Comment by denis-yuen** [comment]
Thanks https://github.com/ga4gh/dockstore-ui/pull/94/files
