### ISSUE TITLE
Search page and tool listing snippets

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#412]
### Desired behaviour

The listing of tools, whether by clicking "Tools" or by searching shows a list of available tools. However, there are no details on them. It would be nice to add a new column that displays snippets of the "doc" field from CWL in order to give some context (we may need to strip out elements like images).

**Comment by agduncan94** [comment]
I don't know how good a column would be for a description as the current columns for tools and workflows take up a lot of space. The doc column would be too cramped I think to show enough useful information.

I could see us using an [accordion or collapsible element](https://angular-ui.github.io/bootstrap/) to show extra information. This could include the doc snippet, as well as other information that would be useful to improve quickly searching through search results. This could be download count, last update, etc.

**Comment by denis-yuen** [comment]
Perhaps we could move away from a purely table design and do something like Google Search results with a snippet on a second line.

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/105
