### ISSUE TITLE
Getting CWL for oxog workflow with no tag set cannot find CWL file

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#414]
Workflow: ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools/oxog-preprocessor
I believe this is because if no tag/branch is set we look at master, but in the case of this workflow the master branch is not valid. We should find a better way to deal with get CWL and WDL when no branch/tag has been given.

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-450)
┆Issue Number: DOCK-450

**Comment by agduncan94** [comment]
Grab default branch instead (if exists), else try master.

**Comment by denis-yuen** [comment]
Related to #585

**Comment by agduncan94** [comment]
This is probably fixed, I cannot find the workflow on dockstore prod.

**Comment by denis-yuen** [comment]
@SolomonShorser-OICR
