### ISSUE TITLE
Tooltip expansion (and/or help links)

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#416]
### Desired behaviour

We need tooltips (or help links) for many more places in Dockstore to describe our functionality better. 
Particular places to document include:
- default branch selection
- launch with
- fields in Info Tab
- columns in Versions
- difference between running with dockstore CLI and directly using cwltool (which should work too)

**Comment by agduncan94** [comment]
[Popovers](https://angular-ui.github.io/bootstrap/) from angular UI might be a good option as you can format the content.

**Comment by agduncan94** [comment]
We should also use the angular UI tooltip (uib-tooltip) instead of the bootstrap tooltip (data-toggle:tooltip) that we were previously using as the bootstrap tooltip seems to be causing a few issues.

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/102
