### ISSUE TITLE
Better use of the Java logging

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#417]
Currently we use the [log4](http://logging.apache.org/log4j/1.2/manual.html)  logging library to log what happens in our webservice (though we aren't using it enough).  We seem to be using a mix of the debug and info tags, but there doesn't seem to be an exact way to how we decide which to use. I think we should better use these levels of logging in the webservice, which can be seen in the site linked above.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-451)
┆Issue Type: Story
┆Issue Number: DOCK-451

**Comment by agduncan94** [comment]
We should decide on standard situations in which we could use the logging levels (could look online for ideas) and then can update the dockstore dev wiki to include them.

**Comment by SolomonShorser-OICR** [comment]
You could use this as a guideline to decide what level to log things at: http://www.thejoyofcode.com/Logging_Levels_and_how_to_use_them.aspx

**Comment by denis-yuen** [comment]
Here we probably want a couple of things 
1) Decide on how we want to do logging both with our jars and shaded jars
2) Make sure that end-users can turn on and off logging from the command-line using --debug
3) The webservice should continue to display logging from INFO and above
4) Projects using our jars as a dependency like Consonance should not be affected (they shouldn't see multiple bindings)
5) Developer documentation, Dockstore primer or README.md

**Comment by denis-yuen** [comment]
Things seem to be generally working with logging.dockstore.org, cloudwatch, and whatnot. 
Re-open with more specifics if needed
