### ISSUE TITLE
Does the CLI support passing directories?

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#427]

**Comment by denis-yuen** [comment]
Yes, for these two cases
1) Input from a directory https://github.com/ga4gh/dockstore/blob/develop/dockstore-client/src/test/resources/dir6.cwl
2) Output to a directory https://github.com/ga4gh/dockstore/blob/develop/dockstore-client/src/test/resources/splitBlob.cwl https://github.com/ga4gh/dockstore/blob/develop/dockstore-client/src/test/resources/splitBlob.json 

Let's keep an eye out for more cases
