### ISSUE TITLE
Export feature for DAGs

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#430]
Not sure how useful this would be but with cytoscape you can export graphs to PNG or JPG
http://js.cytoscape.org/#core/export

**Comment by denis-yuen** [comment]
Oddly, the doc seems to say that the export is done at the current screen resolution, making it basically the same as taking a screenshot. I would say that it would probably be more useful if we can either get, preferably, a vector image format (e.g. svg) or a higher resolution screenshot.

**Comment by agduncan94** [comment]
http://stackoverflow.com/questions/32702006/how-to-determine-maximum-scale-for-cytoscape-js-png-output

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/100
