### ISSUE TITLE
Travis Protractor tests are failing with Chrome

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#448]
Travis and Protractor do not seem to work with the newest stable version of Chrome (54.0.2840). The last passing tests used Chrome 53.0.2785. The way we currently install Chrome we always download the latest stable build, perhaps there is a way to download a specific version (like 53.0.2785).

I've switched the tests to use Firefox, though in the future we should test on both Chrome and Firefox.

**Comment by agduncan94** [comment]
This won't be a problem once we switch to using cyprus, since we will no longer need protractor.

**Comment by thomcom** [comment]
I'm also having this problem with protractor ^2.2.0

**Comment by agduncan94** [comment]
We switched to Cypress, so this is no longer relevant.
