### ISSUE TITLE
Useless parameter for dockstore workflow convert

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#449]
For the command dockstore workflow convert, one of the required params is --descriptor (CWL or WDL). This is useful for the dockstore tool convert equivalent, however since workflows can only be of one type we should remove this parameter and just use the actual descriptor type for the workflow.

**Comment by agduncan94** [comment]
There may be other commands for workflows with this parameter where we should really just use the set descriptor type for the given workflow.

**Comment by denis-yuen** [comment]
Verified removed for at least 
`dockstore workflow convert entry2json` and
