### ISSUE TITLE
Support for Amazon docker registry

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#452]

**Comment by agduncan94** [comment]
Would have to be a private only registry (no public facing way to search/view). Owners of images can [share with other AWS users](http://docs.aws.amazon.com/AmazonECR/latest/userguide/RepositoryPolicyExamples.html#IAM_allow_other_accounts) using IAM by allowing them to pull

**Comment by denis-yuen** [comment]
Present in 1.2.0
