### ISSUE TITLE
Improve loading experience

### ISSUE THREAD

**Issue by btiernay** [ga4gh/dockstore#463]
There is a noticeable delay when the screen looks as follows:

![image](https://cloud.githubusercontent.com/assets/2717578/19951606/8c2bf89a-a135-11e6-8d82-d29ad6b8b0dc.png)

Adding a loading indicator or otherwise might be useful.

**Comment by denis-yuen** [comment]
There's probably a way of detecting a slow connection and adding a loading indicator in that case. 
The Google mobile interface for example loads a different set of options when on a slow connection.

**Comment by denis-yuen** [comment]
Same applies to the "my tool" and "my workflow" pages if the connection is slow

**Comment by denis-yuen** [comment]
A couple options here
1) Find out why there is a delay
2) Add a loading indicator or similar to avoid the half-rendered site/pop-in

**Comment by JWKaiqi** [comment]
Ideas from sprint meeting
* Currently, angular shows "loading ...." but this could be nicer
* bigger problem is that if you no workflows, it looks weird (probably for tools as well)
* make sure old warning message is migrated

**Comment by denis-yuen** [comment]
Closing in favour of the new issue (ugly loading screen-> better loading screen)
