### ISSUE TITLE
Populate Dockstore with tools/workflows

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#467]
To increase the number of tools/workflows on the site, and also to show prospective users some examples of what they can register on Dockstore, we should populate the site with some more tools.

For example, BioLinux is a platform that can be run through docker which includes over 250 bioinformatics related packages (according to the [website](http://environmentalomics.org/bio-linux/)).

It can be found on [Dockerhub](https://hub.docker.com/r/gawbul/docker-bio-linux8/), though we probably want it on Quay since Dockstore supports auto builds for quay.

It would be fairly easy to write some CWL/WDL tools and workflows which use this docker image and call one of the many [command line tools preinstalled](http://environmentalomics.org/bio-linux-software-list/)

**Comment by denis-yuen** [comment]
Re-open with specific collections of workflows when applicable
