### ISSUE TITLE
Add OpenJDK:8 as a docker dependency

### ISSUE THREAD

**Issue by brainstorm** [ga4gh/dockstore#469]
Right after onboarding into dockstore while deploying [CGP Sanger pipeline](https://github.com/ICGC-TCGA-PanCancer/CGP-Somatic-Docker), I've been greeted by this:

```
Dockstore requires Java version 1.8 and above.
```

On (legacy) HPC clusters this is bound to be a problem... would you accept a pullrequest that pulls [jre 8](https://hub.docker.com/r/library/openjdk/tags/8/) as a default runtime instead of relying on the host's (deprecated) preinstalled JAVA?

**Comment by brainstorm** [comment]
For the record, I'm trying to have something as unintrusive as the following docker commandline in the `dockstore` script:

```
+ docker run -it -v /home/rvalls/.dockstore:/root/.dockstore openjdk:8 java io.dockstore.client.cli.Client tool launch --entry Dockstore.cwl --local-entry --json test1.json
Error: Could not find or load main class io.dockstore.client.cli.Client
```

Still have to figure out the `CLASSPATH`-related issue, but I hope my intentions are clearer now.

**Comment by denis-yuen** [comment]
@brainstorm  Hi, I think there are two parts to this answer
1) Sounds good, an option to point at a version of Java not on the PATH makes sense to me. 
2) I have to add a caveat that we test with Oracle JDK 8. OpenJDK 8 will probably work (knock on wood), but it simply is not something we have tested with yet.

**Comment by denis-yuen** [comment]
@brainstorm  Oh, for the second bit. You can try something like this (avoids the dockstore warning about root, you'll need to substitute your location for the dockstore script). You should also mount a settings file to avoid the prompt for setting up an account, but hope that helps. 
```
 docker run -it -e "DOCKSTORE_ROOT=true" -v /home/dyuen/dockstore/dockstore-client/target/dockstore:/dockstore openjdk:8 /dockstore tool launch
Downloading Dockstore to /root/.dockstore/self-installs/dockstore-client-1.0.1.jar now...
```

**Comment by brainstorm** [comment]
Thanks @denis-yuen for the tips, unfortunately I'm still running into some issues:

```
$ docker run -it -e "DOCKSTORE_ROOT=true" -v $HOME/.dockstore:/root/.dockstore -v $HOME/bin/dockstore:/bin/dockstore openjdk:8 dockstore tool launch --entry Dockstore.cwl --local-entry --json test1.json
java.lang.RuntimeException: Failed to get content of entry file.
```

Then I tried adding the missing path bits, but since it's running on the java container, it doesn't find the appropriate context (i.e `cwltool`):

```
[rvalls@node08 CGP-Somatic-Docker]$ docker run -it -e "DOCKSTORE_ROOT=true" -v `pwd`:/root/CGP-Somatic-Docker -v $HOME/.dockstore:/root/.dockstore -v $HOME/bin/dockstore:/bin/dockstore openjdk:8 dockstore tool launch --entry /root/CGP-Somatic-Docker/Dockstore.cwl --local-entry --json /root/CGP-Somatic-Docker/test1.json
org.apache.commons.exec.ExecuteException: Execution failed (Exit value: -559038737. Caused by java.io.IOException: Cannot run program "cwltool" (in directory "."): error=2, No such file or directory)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:205)
        at java.lang.Thread.run(Thread.java:745)
Caused by: java.io.IOException: Cannot run program "cwltool" (in directory "."): error=2, No such file or directory
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1048)
        at java.lang.Runtime.exec(Runtime.java:620)
        at org.apache.commons.exec.launcher.Java13CommandLauncher.exec(Java13CommandLauncher.java:61)
        at org.apache.commons.exec.DefaultExecutor.launch(DefaultExecutor.java:279)
        at org.apache.commons.exec.DefaultExecutor.executeInternal(DefaultExecutor.java:336)
        at org.apache.commons.exec.DefaultExecutor.access$200(DefaultExecutor.java:48)
        at org.apache.commons.exec.DefaultExecutor$1.run(DefaultExecutor.java:200)
        ... 1 more
Caused by: java.io.IOException: error=2, No such file or directory
        at java.lang.UNIXProcess.forkAndExec(Native Method)
        at java.lang.UNIXProcess.<init>(UNIXProcess.java:248)
        at java.lang.ProcessImpl.start(ProcessImpl.java:134)
        at java.lang.ProcessBuilder.start(ProcessBuilder.java:1029)
        ... 7 more
java.lang.RuntimeException: problems running command: cwltool --non-strict --print-pre /root/CGP-Somatic-Docker/Dockstore.cwl
```

I'm afraid I've to backpedal a bit on this and see if there are easier ways... @denis-yuen did you manage to run the whole CGP pipeline this way?

**Comment by denis-yuen** [comment]
Hi,
No, ironically, we haven't actually run the dockstore command-line itself inside a Docker container. 

Rather, the normal flow of things is on a particular host, Docker and Java 8 are installed, then cwltool. When you run the dockstore command-line, it does a bit of file provisioning, then calls cwltool, which starts a Docker container (CGP-Somatic-Docker) in your case, and then finishes up when the container stops. 
(We've run through Somatic Docker many times in this fashion) 

These two pages of the tutorial describe this:
https://dockstore.org/docs/getting-started-with-docker
https://dockstore.org/docs/getting-started-with-cwl

Note that the dockstore command-line runs on the host and that's where (Oracle) Java 1.8 is important. That's why I thought you were either trying to a) try out the dockstore command-line with OpenJDK installed on the host when running on hosts that cannot install 1.8 or b)  run the dockstore command-line in a docker container to work around this.
