### ISSUE TITLE
Display placeholder for "verified"

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#470]
### Desired behaviour

The GA4GH endpoints currently have the (not hooked up) fields 
```
    "verified": false,
    "verified-source": "string",
    "signed": false,
```
 for each tool and version of each tool. 

For the PCAWG group, as a stopgap, let's display this information if it exists and the dockstore team can manually populate these fields for tools that we verified ourselves. 

attn @briandoconnor

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/pull/479

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/108

**Comment by agduncan94** [comment]
We still have to hook up the GA4GH endpoints, so we can't close this yet.

**Comment by denis-yuen** [comment]
Looks like the root verified and verified-source are not hooked up properly after verified by version

**Comment by denis-yuen** [comment]
Functional on staging.dockstore.org
