### ISSUE TITLE
It seems like user object is not reloaded in the UI unless you logout and log back in

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#472]
If you are logged in and change isAdmin to true, this won't reflect what the UI thinks, though in the DB you are an admin.

**Comment by agduncan94** [comment]
This also seems to be the case for using the CLI, I think we have to refresh the user or maybe clear the cache (userDAO.clearCache())

**Comment by denis-yuen** [comment]
@agduncan94 
The cache is probably the issue or at least one of the caches. 
Note that in addition to the ORM cache above, there's also a caching authenticator built into DropWizard http://www.dropwizard.io/1.0.0/docs/manual/auth.html#caching which probably isn't aware of the role change.

**Comment by denis-yuen** [comment]
UI1
