### ISSUE TITLE
Dockstore.org documentation issues

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#476]
I'm working through the dockstore documentation will post any findings as I go. 

First off, on the very first page (https://dockstore.org/docs/getting-started), under Tool Development Environment it says "When going through the onboarding wizard, our various dependencies were introduced. "
This made no sense to me until I checked the github repo and saw a link to https://dockstore.org/onboarding in the README. It would be helpful is this was listed (and linked) as a step after 'sign up' and before 'Tool Development'

**Comment by Jeltje** [comment]
https://dockstore.org/onboarding, under Part 3, point 4, link to docker's website is broken. Should probably be https://docs.docker.com/engine/installation/linux/ubuntulinux

**Comment by Jeltje** [comment]
https://dockstore.org/docs/getting-started, under Tool Development Environment: dockstore version is listed as `0.4-beta.5`. My download lists `1.0.1`

**Comment by Jeltje** [comment]
Nitpicky point: 
https://dockstore.org/docs/getting-started-with-cwl
In the image below the text `the description is actually parsed and displayed in the Dockstore page.`, at the very bottom it shows the description line `See the BAMStats website for more information`, just like in the CWL example. 
However, the word `BAMStats` is listed in blue, as if it's a link. How can it be a link? There's no link text in the CWL description.

Does this mean we CAN put a link in the description? If so, how?

**Comment by Jeltje** [comment]
Same page
`Notice a few things, first, the bam_input: matches with bam_input in the sample parameterization JSON.`

No JSON has been described yet.

**Comment by Jeltje** [comment]
What I'm missing in the `getting started with docker` tutorial is an example of how to call a container from the command line. This is the way docker is normally used, and it would also explain the parametrization JSON later on: what you're doing is creating the command line needed to run the container. 

The way it's written now, it looks like you must log on to the container to get it to do anything, which is confusing later on.

**Comment by denis-yuen** [comment]
re: the link
In https://dockstore.org/docs/getting-started-with-cwl the example shows this cwl snippet 
```
description: |
    ![build_status](https://quay.io/repository/collaboratory/dockstore-tool-bamstats/status)
    A Docker container for the BAMStats command. See the [BAMStats](http://bamstats.sourceforge.net/) website for more information.
```
I do not think that CWL specifies a format for the description, it just says human-readable text. 
We display it as Markdown though, which is why the link is rendered.

**Comment by Jeltje** [comment]
Good to know! 

I also just noticed I went by the simplified description text right above the figure, instead of that at the top of the full cwl example. So I didn't notice there was a link.

**Comment by Jeltje** [comment]
Minor inconsistency:
https://dockstore.org/docs/getting-started-with-cwl
The text mentions `CancerCollaboratory / dockstore-tool-bamstats`. This matches the figure _below_ the text, but not the one above it (`collaboratory/dockstore-tool-bamstats`).

**Comment by Jeltje** [comment]
![buildtrigger](https://cloud.githubusercontent.com/assets/5482232/20188572/16b7e9b2-a72e-11e6-84da-cd964642b85a.png)
Under `Please select the credentials`, do I select None or Robot Account? It's not mentioned in the documentation.

**Comment by denis-yuen** [comment]
@Jeltje I think that would be None (By way of explanation, I think Robot accounts are how quay.io handles private repositories which we don't really handle)

**Comment by Jeltje** [comment]
https://dockstore.org/docs/getting-started-with-dockstore
Typo `upon completetion`

**Comment by Jeltje** [comment]
https://dockstore.org/docs/getting-started-with-dockstore
Starts with a description of how to link the account after login. Since I'm reading this _on the dockstore website_, there's a good chance I'm already logged in. In fact, because I needed the onboarding wizard in an earlier step, my Quay.io account was already linked.

To get my freshly minted Quay.io containter linked, I had to go to My Tools and, then add tool.

It would be helpful to have this info in the documentation, maybe at the end of https://dockstore.org/docs/getting-started-with-cwl ?

**Comment by Jeltje** [comment]
https://dockstore.org/docs/getting-started-with-dockstore
typo `Words encapsulated in parentheses denotes` should be `denote`. Also I would lose `encapsulated`, but that's me.

**Comment by Jeltje** [comment]
`Detailed information and links for each tool is` - `are`

**Comment by Jeltje** [comment]
`To publish a tool, press the yellow 'Register' button in the top-right corner`
Yellow button says Publish, not Register.

Also, in my case the publish button is grayed (or rather blued) out. It's not clear why I'm not allowed to publish my tool.

**Comment by Jeltje** [comment]
`image registry path and the toolname uniquely distinguishes` should be `distinguish`
or possibly
`the combination of image registry path and toolname uniquely distinguishes`

**Comment by denis-yuen** [comment]
re: parenthesis. Sorry, we simplified out the toolnames in parenthesis, but didn't update this doc.

**Comment by denis-yuen** [comment]
Also, we need to better describe the quay.io trigger creation process

**Comment by Jeltje** [comment]
Minor issue: Text layout at https://dockstore.org/docs/about looks weird. As if copy/pasted with line breaks.

**Comment by Jeltje** [comment]
You're probably aware of this one, but 
https://dockstore.org/docs/workflows
has a 
`<!-- insert a good example here --> `

**Comment by Jeltje** [comment]
Same page, typy: `patterm`

**Comment by Jeltje** [comment]
`describe your workflow as either a CWL workflow (...)`  This link currently points to http://www.commonwl.org/draft-3/Workflow.html, should probably be updated to http://www.commonwl.org/v1.0/Workflow.html

**Comment by Jeltje** [comment]
Confusing: https://dockstore.org/docs/getting-started-with-cwl, in the examples
mixes v1.0 terminology (`doc`) with draft-3 terms (`description`)

Can you actually use them both? And if not, should the `description` at the top of the CWL file also be `doc`?:

```
class: CommandLineTool
id: "BAMStats"
label: "BAMStats tool"
cwlVersion: v1.0
description: "A Docker container for ..."
```

**Comment by denis-yuen** [comment]
I think description was renamed to doc. As far as Dockstore is concerned, you can use both and I believe that the tool will still launch since we use `--non-strict`. That said, doc is correct and we should definitely fix that documentation.

**Comment by denis-yuen** [comment]
Thanks @Jeltje !

( Updates verified on staging.dockstore.org. )
