### ISSUE TITLE
Give users ability to check if descriptor is valid

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#482]
I just found this on the WDL website. https://software.broadinstitute.org/wdl/userguide/validation
They have a jar file that you can call to validate WDL.

This would be pretty useful for someone creating a wdl workflow/tool, and may be a useful dev option for the CLI. Something like dockstore tool validate --wdl <path-to-wdl>

**Comment by denis-yuen** [comment]
Looks interesting https://github.com/broadinstitute/wdltool

I don't see it at https://artifactory.broadinstitute.org/artifactory/libs-release/org/broadinstitute/ though

**Comment by agduncan94** [comment]
Seems like we could also use wdltool to get inputs and parse.

**Comment by denis-yuen** [comment]
Redun
