### ISSUE TITLE
Can't use arrow functions with grunt uglify

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#498]
It seems that at the time of creation of this issue, grunt uglify js does not support arrow functions. Arrow functions are very nice and can make code cleaner/easier to read.

Here is an example of how we could use arrow functions, though these can probably be cleaned up even more.
https://gist.github.com/agduncan94/233a1a7f799addfc4bd2aa8846b8d197

**Comment by denis-yuen** [comment]
Won't be an issue post Angular (2)
