### ISSUE TITLE
1.1 release issues on staging

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#502]
### Expected behaviour

Migration succeeds but dirtybit (both tag and workflowversion) and verified are null rather than false, messing up display of the home page for workflows and tools

### Actual behaviour

Successful migration and startup

**Comment by denis-yuen** [comment]
Noticed the following warning on `bower update`
```
bower qtip2#^2.2.0                       invalid-meta The "main" field has to contain only 1 file per filetype; found multiple .js files: ["./jquery.qtip.js","./basic/jquery.qtip.js"]
```

**Comment by denis-yuen** [comment]
We'll need a new issue to track the ambiguous nature of having the same organization and repo in multiple locations

**Comment by denis-yuen** [comment]
Documentation in onboarding wizard needs to reflect our new cwltool version

**Comment by agduncan94** [comment]
I am going to use this one comment to track UI issues I find.
* Onboarding wizard -> step 3 "Sign up for an account on Gitlab" link is incorrect

**Comment by denis-yuen** [comment]
We need a new issue (post release) to add https://github.com/ga4gh/tool-registry-validator to one of our build paths (probably the coverage testing path) to validate that we always pass ga4gh validation (we do, right now).

**Comment by agduncan94** [comment]
We should add to the documentation, probably in the FAQ, discussing some of the weird assumptions CWL tool has. Things like what cwltool uses for tmpdir, working dir, and how it sets most things to read only.

**Comment by agduncan94** [comment]
Add tag in the tool versions tab for manual tools does not work.

**Comment by denis-yuen** [comment]
`  A Test Parameter File associated with this Docker container could not be found.` should probably be `  A Test Parameter File associated with this tool version could not be found.`

**Comment by denis-yuen** [comment]
Spacing in CLI is inconsistent
```
  label            :  updates labels for an individual Tool

  test_parameter            :  updates test parameter files for a version of a Tool

  convert          :  utilities that allow you to convert file types

```

**Comment by denis-yuen** [comment]
Error message could be better, like 'Tag <tag name> is not available to be verified'
```
$ dockstore tool verify --entry quay.io/pancancer/pcawg-sanger-cgp-workflow --version developed --verified-source 'Mr. T'
java.util.NoSuchElementException: No value present
```

**Comment by denis-yuen** [comment]
Release complete
