### ISSUE TITLE
Make documentation easier to navigate

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#504]
Currently the navigation in the documentation isn't the best. Here are some possible ways I can think to improve it. 
* Floating table of contents (https://afeld.github.io/bootstrap-toc/) like seen on the Bootstrap site
* Jump/return to top button at the bottom of a page
* Links to individual headers of a page (https://github.com/ga4gh/dockstore/issues/494)

**Comment by denis-yuen** [comment]
A table of contents would be nice. The markdown documentation may make this interesting.

**Comment by agduncan94** [comment]
It seems that the table of contents plugin listed above creates the links based on header elements (h1,h2,h3, etc), however we are using markup so it won't work. We would have to switch to HTML to support the TOC.

**Comment by denis-yuen** [comment]
Checked into develop as https://github.com/ga4gh/dockstore-ui/pull/129

**Comment by denis-yuen** [comment]
Looks good on staging.dockstore.org. 
Table of contents and documentation anchors seem to work well.
