### ISSUE TITLE
Test, fix, document outcome of duplicate workflows

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#508]
It is possible that our implication that workflow names are generated from organisations and workflow names could create duplicate entities if a repo and org are named the same in two different source code repositories. 

Test and then document:
- how we tie break when more than one are published
- if it is possible to publish two of the same
- a possible solution

**Comment by garyluu** [comment]
Looks like if there's the name of the repo and organization is the same, dockstore will not let you create the workflow.  However, providing the optional workflow name will allow the workflow to be created.  So the naming appears to be <organization>/<repo>/<optional workflow name>.  As long as that's unique, it can be created.
