### ISSUE TITLE
Prepare Cypress as a skeleton project with a few good examples of tests

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#512]
### Desired behaviour

A test framework based a work term report and https://github.com/ga4gh/dockstore-ui/tree/test_cypress_travis with a few examples of how to code up tests. 
Tests should be properly reflected on coveralls.io and the dockstore primer properly documenting how to add new tests.

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore-ui/pull/115
