### ISSUE TITLE
Unreliable test for Gitlab

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#516]
The test for Gitlab seems to fail a lot. There is not much output 

```
Tests run: 29, Failures: 1, Errors: 0, Skipped: 0, Time elapsed: 404.681 sec <<< FAILURE! - in io.dockstore.client.cli.GeneralWorkflowET
testManualPublishGitlab(io.dockstore.client.cli.GeneralWorkflowET)  Time elapsed: 0.947 sec  <<< FAILURE!
java.lang.AssertionError: Unexpected call of System.exit(6).
```

```
Failed tests: 
  GeneralWorkflowET.testManualPublishGitlab Unexpected call of System.exit(6).

Tests run: 158, Failures: 1, Errors: 0, Skipped: 2
```

Change the test so that it will wait and retry on failure to hopefully reduce how often we get a false positive failure. 

(do an exponential back-off or similar) https://docs.aws.amazon.com/general/latest/gr/api-retries.html

**Comment by agduncan94** [comment]
Saw this with testDockerhubGitlabManualRegistrationDuplicates too.
