### ISSUE TITLE
Merge Accounts and Tokens pages into a dashboard/profile view

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#517]
From a user perspective, it makes sense to have a dashboard/profile page (similar to accounts) where they can get an overview of their account, and also edit/update their information. Things like tokens should be displayed in this new page, where the user can view them and remove them.

It doesn't really make sense for tokens to be so accessible, since they are not likely to be seen much by the user.

We could also set this up to be like a github profile (though not public) where users can see an overview of their entries and maybe some useful statistics.

**Comment by denis-yuen** [comment]
This seems mostly done except for the overview and statistics may make it into a redesigned home page
