### ISSUE TITLE
Site doesn't look that nice on mobile

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#519]
We should improve the UI so that it is nicer on mobile. This should be just a matter of better utilizing the bootstrap column classes (http://getbootstrap.com/css/#grid)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-462)
┆Issue Type: Story
┆Issue Number: DOCK-462

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/issues/206

**Comment by agduncan94** [comment]
Random thoughts to clean up the UI:
-navbar should collapse when screen is small enough
-vertical tabs when viewing a tool or workflow take up way too much space
-some documentation for tools/workflows (images) will spill over outside of their area (ex. [h3abionet/h3agatk](https://dockstore.org/workflows/h3abionet%2Fh3agatk)

**Comment by SolomonShorser-OICR** [comment]
:+1:

**Comment by agduncan94** [comment]
The new release has fixed a lot of the issues, the only main issue I notice is that some images in the documentation for tools/workflows still spill out.

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/issues/1771

**Comment by denis-yuen** [comment]
Re-open for new UI if applicable

**Comment by SolomonShorser-OICR** [comment]
:+1: 
Looks much better now.
