### ISSUE TITLE
Use dockerize in UI travis script 

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#523]
We should use dockerize for the UI travis.yml script instead of sleeping 10 seconds.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-464)
┆Issue Type: Story
┆Issue Number: DOCK-464

**Comment by denis-yuen** [comment]
https://github.com/dockstore/dockstore-ui2/blob/develop/scripts/wait-for.sh
