### ISSUE TITLE
File provisioning should be pluggable

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#524]
### Desired behaviour

Currently, we support the protocols that commons vfs2 support + Synpase, + icgc Storage, GNOS. However, we should really make this system pluggable in order to allow different institutions to add their own file transfer protocol.

**Comment by denis-yuen** [comment]
Specification in progress https://wiki.oicr.on.ca/display/SOFTENG/Dockstore+Pluggable+File+Provisioning+Specification

**Comment by keiranmraine** [comment]
Once you have a base structure for the plugin I'd be interested in trying to add [iRODS](https://irods.org/) support as we use it internally.

**Comment by denis-yuen** [comment]
Provided at https://github.com/ga4gh/dockstore/tree/develop/dockstore-file-plugin-parent
