### ISSUE TITLE
Typo in mail to link on the info tab

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#529]
### Expected behaviour

Mail to link should open an email with a correct email address

### Actual behaviour

Opens up an email with `mailto:<actual email address>` rather than `<actual email address`

Heads up thanks to @larsgt

**Comment by denis-yuen** [comment]
Ok, didn't realize that this was not a typo. 
1) We should strip "mailto" on refresh to ensure our database is consistent
2) Migration script should clean up existing mailto
3) For now, UI should strip it if it encounters mailto as a prefix

**Comment by agduncan94** [comment]
https://github.com/ga4gh/dockstore/pull/536
