### ISSUE TITLE
Hovering over In affiliation with images should change to a coloured version

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#535]
See https://dcc.icgc.org/ as an example (OICR logo in bottom right of the page)

**Comment by denis-yuen** [comment]
Find the original coloured (and high-resolution images) at https://github.com/ga4gh/dockstore-ui/tree/develop/app/images In particular, there is https://github.com/ga4gh/dockstore-ui/tree/develop/app/images/high-res

**Comment by denis-yuen** [comment]
Checked into develop https://github.com/ga4gh/dockstore-ui/pull/129

**Comment by denis-yuen** [comment]
Functional on staging.dockstore.org
