### ISSUE TITLE
GUI usability - ability to blank WDL when n/a, indicate default branch

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#542]
### Desired behaviour

1. The Info tab description stays blank until a version is selected, we could use an indication that a default version needs to be selected first before populating this (and other fields in the into tab)
2. Cannot blank the (default?) WDL path when adding a default branch

[chat.txt](https://github.com/ga4gh/dockstore/files/649272/chat.txt)

This is on 1.1 release of Dockstore

**Comment by keiranmraine** [comment]
Also, when switching between the inner tabs of 'Files' the correct version is only selected on first opened tab.  If you then click along Descriptor, test files the version changes, and persists back to 'Dockerfile'.

e.g. dockstore-cgpmap has 1.0.2 selected as current version, but it switches back to 1.0.0

https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap

**Comment by garyluu** [comment]
Check that blanking one of WDL or CWL works correctly both in the "Add Tool" dialogue and the Info tab for defaults.

**Comment by denis-yuen** [comment]
Update:
1) We're unifying version selection across files, launch with, and info which should be more clear and simpler (i.e. you only select version once rather than having dropdowns in various places)
2) Blanking one of cwl or wdl works for "Add Tool". However, this change was not carried through to "Add Version Tag" making it inconsistent
3) The current implemention is kind of annoying in that you need to hit "refresh" when switching the default branch to change the default info display even if the information is already in the DB

**Comment by denis-yuen** [comment]
Working in staging.dockstore.org
