### ISSUE TITLE
Launch with will sometimes show undefined for --descriptor

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#543]
This can be seen in the tools launch with section. Changing the version will fix the issue.
ex.
https://dockstore.org/containers/quay.io/collaboratory/dockstore-tool-bedtools-genomecov

**Comment by agduncan94** [comment]
The launch with CWL tool also doesn't show. I think this is because the descriptor is null (It shouldn't be)

**Comment by denis-yuen** [comment]
Looks fixed on https://staging.dockstore.org/containers/quay.io/collaboratory/dockstore-tool-bedtools-genomecov at least
