### ISSUE TITLE
Use ~/.s3cfg for non AWS S3

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#548]
## Feature Request 

The documentation only shows AWS style configuration for S3 upload/download and doesn't appear to accept other methods.

### Desired behaviour

It would be desirable to use the [`~/.s3cfg`](http://s3tools.org/kb/item14.htm) supported by tools like `s3cmd`.

```
[default]
access_key = XXXXXXXXXXXXXXXXXXX
encrypt = False
host_base = radosgw.XXX.XX.XX
host_bucket = %(bucket)s.radosgw.XXX.XX.XX
progress_meter = False
secret_key = XXXXXXXXXXXXXXXXXXXXXXXXXXXX
use_https = True
```

### Actual behaviour

```
com.amazonaws.AmazonClientException: Unable to load AWS credentials from any provider in the chain
```

### Steps to reproduce the behaviour 

Use a non-AWS S3 implementation with a `~/.s3cfg` instead of `~/.aws/config` and `~/.aws/credentials`

### Environment (Browser or OS and Dockstore version)

Dockstore 1.1 CLI.

**Comment by denis-yuen** [comment]
@keiranmraine could you link to a document that lists some of the features/advantages of this configuration format as opposed to the standard AWS config? (Maybe more precisely, what behaviour in the client or specifically s3cmd are you interested in?)

Note to self: this is probably related to #524 , we should allow file provisioning to accept plug-ins, perhaps an optional s3cmd plugin might be the right way to go here

**Comment by keiranmraine** [comment]
I guess it could be a documentation thing, but s3cmd will work with AWS S3 or other variants using this method.  I don't think the same is true for the `.aws/config` approach.

It's one less config file to worry about as I'm assuming people won't be wanting to spawn AWS instances from a dockstore run.

If in the short term it's possible to configure a non-AWS S3 using the AWS method that's fine, I was under the impression you couldn't change the authentication method though.

Currently working round this by presenting S3 as a filesystem for uploads:

```
$ s3fs /radosgwtest -o passwd_file=s3fs.cfg -o url=http://radosgwtest.....ac.uk -o use_path_request_style -o bucket=test_bucket
```

**Comment by denis-yuen** [comment]
Ok, poked around a bit. 
We currently support an alternative S3 endpoint, you can have a Dockstore config file that looks like the bottom of
```
token: dummy
server-url: https://www.dockstore.org:8443
use-cache = true
cache-dir = /media/large_volume/dockstore_cache

[s3]
endpoint =  https://object.cancercollaboratory.org:9080
```
And this does work when talking to our collaboratory S3 api, so you can upload to a location other than the official AWS S3 endpoints.

However, we don't support changing authentication type and it doesn't look like the AWS S3 SDK that we rely upon does either. So I think more custom configuration would probably mean that we should implement  a pluggable provision system with s3cmd as a good example. 

Note to self: it looks like s3cmd supports a wealth of configuration that isn't normally present in the aws cli/java sdk http://s3tools.org/kb/item14.htm

**Comment by keiranmraine** [comment]
@denis-yuen , which dockstore config file does the above go into?  I'll see if this works.  The alternate auth type seemed to be required to get `s3fs`working.

**Comment by denis-yuen** [comment]
It looks like you can tell the AWS SDK to point to a different endpoint, you would put the above `[S3]` section into `~/.dockstore/config`. However, we do not support an alternate authentication type, it might even be possible that the AWS SDK doesn't support alternatives since AWS doesn't really use that.

**Comment by denis-yuen** [comment]
Note to self: Implementation of s3cmd pluggin related to #524

**Comment by keiranmraine** [comment]
FYI, this works but fails after the file is downloaded...

I set the endpoint as you indicated, put my ceph-S3 credentials into `~/.aws/credentials` and ran a test.

```
16:24:14.327 [main] INFO  io.dockstore.common.FileProvisioning - found custom S3 endpoint, setting to https://cog.sanger.ac.uk
[##################################################] 100%
16:24:30.453 [main] INFO  io.github.collaboratory.LauncherCWL - DOWNLOADED FILE: LOCAL: insilico_21.bam URL: s3://MapTest/insilico_21.bam
16:24:30.571 [main] INFO  io.dockstore.common.FileProvisioning - found custom S3 endpoint, setting to https://cog.sanger.ac.uk
com.amazonaws.services.s3.model.AmazonS3Exception: null (Service: Amazon S3; Status Code: 404; Error Code: NoSuchKey; Request ID: tx00000000000000000ac17-0058862e3e-50570c-default), S3 Extended Request ID: 50570c-default-default
	at com.amazonaws.http.AmazonHttpClient.handleErrorResponse(AmazonHttpClient.java:1389)
	at com.amazonaws.http.AmazonHttpClient.executeOneRequest(AmazonHttpClient.java:902)
	at com.amazonaws.http.AmazonHttpClient.executeHelper(AmazonHttpClient.java:607)
	at com.amazonaws.http.AmazonHttpClient.doExecute(AmazonHttpClient.java:376)
	at com.amazonaws.http.AmazonHttpClient.executeWithTimer(AmazonHttpClient.java:338)
	at com.amazonaws.http.AmazonHttpClient.execute(AmazonHttpClient.java:287)
	at com.amazonaws.services.s3.AmazonS3Client.invoke(AmazonS3Client.java:3826)
	at com.amazonaws.services.s3.AmazonS3Client.getObject(AmazonS3Client.java:1143)
	at io.dockstore.common.FileProvisioning.downloadFromS3(FileProvisioning.java:125)
	at io.dockstore.common.FileProvisioning.provisionInputFile(FileProvisioning.java:242)
	at io.github.collaboratory.LauncherCWL.copyIndividualFile(LauncherCWL.java:722)
	at io.github.collaboratory.LauncherCWL.doProcessFile(LauncherCWL.java:702)
	at io.github.collaboratory.LauncherCWL.pullFilesHelper(LauncherCWL.java:659)
	at io.github.collaboratory.LauncherCWL.pullFiles(LauncherCWL.java:586)
	at io.github.collaboratory.LauncherCWL.run(LauncherCWL.java:185)
	at io.dockstore.client.cli.nested.AbstractEntryClient.handleCWLLaunch(AbstractEntryClient.java:1028)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launchCwl(AbstractEntryClient.java:968)
	at io.dockstore.client.cli.nested.AbstractEntryClient.checkEntryFile(AbstractEntryClient.java:857)
	at io.dockstore.client.cli.nested.AbstractEntryClient.launch(AbstractEntryClient.java:930)
	at io.dockstore.client.cli.nested.AbstractEntryClient.processEntryCommands(AbstractEntryClient.java:247)
	at io.dockstore.client.cli.Client.run(Client.java:704)
	at io.dockstore.client.cli.Client.main(Client.java:796)

```

But the file exists and md5 matched
```
$ s3cmd get s3://MapTest/insilico_21.bam
download: 's3://MapTest/insilico_21.bam' -> './insilico_21.bam' (486828427 bytes in 5.6 seconds, 83.57 MB/s)
$ md5sum insilico_21.bam 
12554316412b03524913455ea1134ef9  insilico_21.bam
$ md5sum datastore/launcher-1ce35420-6f26-4563-8f77-9b9494eac025/inputs/348906ec-3200-4030-a09c-f8a33cd4e9c8/insilico_21.bam
12554316412b03524913455ea1134ef9  datastore/launcher-1ce35420-6f26-4563-8f77-9b9494eac025/inputs/348906ec-3200-4030-a09c-f8a33cd4e9c8/insilico_21.bam
```

**Comment by denis-yuen** [comment]
@keiranmraine If I understand correctly, it sounds like s3://MapTest/insilico_21.bam downloaded correctly, but the next file it attempted to download from S3 failed, perhaps due to an incorrect path (or for some APIs, an authentication error manifests as a file not found to avoid not exposing information).
 
You should be able to get more details on what the next file is by running with `dockstore --debug`

**Comment by keiranmraine** [comment]
@denis-yuen , all is well.  There are secondary files for the BAM, the error message could do with indicating which file it is trying to pull as the output I provided was from a `--debug` output.

So this all works provided you put the endpoint in `~/.dockstore/config` in my case no port:

```
[s3]
endpoint = https://XXX.sanger.ac.uk
```

and add include the tokens in the `~/.aws/credentials`

```
[default]
aws_access_key_id = XXXXXX
aws_secret_access_key = XXXXXX
```

**Comment by denis-yuen** [comment]
@garyluu  I think the remaining task to finish this one off it to get your s3cmd plugin deployed on artifacts.oicr.on.ca
