### ISSUE TITLE
Clean up of Gruntfile

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#549]
There seems to be some relics from when we used protractor and karma within the Gruntfile and the ./test directory. Also the Grunt file has a bit of commented out code and code that I'm not totally sure if it is used anymore.

We should clean up the Gruntfile (and other related files) and document the purpose of the different tasks that grunt uses (ex. grunt vs grunt serve vs grunt test).

**Comment by denis-yuen** [comment]
Going to be obsolete with angular2
