### ISSUE TITLE
Improve documentation on multiple tool maintainers on a team

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#550]
I can't see the ability to add other users as maintainers of a tool.

Ideally we want to be able to manage these as a team rather than as individuals.

Thanks

**Comment by denis-yuen** [comment]
@keiranmraine 

For tools registered on quay.io, we automatically allow users from the same organization (on quay.io) the ability to manage tools together. (With the caveat that a user does not initially see the tools in their organization until they refresh)

For tools registered on Docker Hub, we don't have any facility to retrieve organizational information so this feature does not exist yet.

**Comment by keiranmraine** [comment]
Great thanks,

**Comment by denis-yuen** [comment]
This is a good thing to test on staging and to document our current behaviour with multiple users in an organization with both tools and workflows

**Comment by denis-yuen** [comment]
I think https://docs.dockstore.org/faq/#how-do-i-add-other-users-as-maintainers-of-a-tool was added for this.
