### ISSUE TITLE
Override image version (dockstore tool)

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#551]
## Feature Request 
The auto docs give a command like:

```
dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap:1.0.4 --json Dockstore.json
```

If I'm testing a hotfix, I don't want to have to link the branch into dockstore, update the Dockerfile and the Dockstore.cwl.

### Desired behaviour
The `--entry` on the command line should be used as the source of the cwl and base repository, but add an option of `--alt_ver` to point it to another version of the image, e.g.

```
dockstore tool launch --entry quay.io/wtsicgp/dockstore-cgpmap:1.0.4 --alt_ver hotfix_1.0.5 --json Dockstore.json
```

At present I believe the only way to get round this is to pre-stage the docker image and retag it.

**Comment by denis-yuen** [comment]
Hmmm, the way that we currently tackle this is to use local CWL files. 
i.e. 
```
dockstore tool launch --entry Dockstore.cwl --local-entry --json Dockstore.json
```
with Dockstore.cwl configured to point at `hotfix_1.0.5` in your case if that is the correct tag for the image on quay.io. `Latest` might work as well

I think the above would be reasonable, although it should be clearly noted that we're essentially overriding the image that is recorded in the CWL file (`1.0.4`) in this case with `hotfix_1.0.5`,

**Comment by keiranmraine** [comment]
Ah this makes sense, I was confused as I changed the entry to point at hotfix_1.0.5  and it still picked up the 1.0.4 version (at least I think that's what I did last week).

Does it by any chance fall back to the last linked version of the Dockstore.cwl if it can't find the specified version?

**Comment by denis-yuen** [comment]
Kinda.

If you point dockstore at a version that doesn't exist, it should fail. 
However, note that depending on how you have your quay.io repo is setup, you probably have a `latest` tag that can bounce around different tags. You can get this version by either accessing `quay.io/wtsicgp/dockstore-cgpmap:latest` or `quay.io/wtsicgp/dockstore-cgpmap` (a la docker).


But in your case, I would guess that what happened is that you created a version `hotfix_1.0.5 ` but the actual cwl document in that branch still pointed to `1.0.4` and that was what got executed unexpectedly.

**Comment by denis-yuen** [comment]
It seems like using the local Dockstore.cwl should suffice for this use-case. Re-open is this is incorrect
