### ISSUE TITLE
Deploy Let's Encrypt

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#558]
### Desired behaviour

Deploy and move to a free SSL provider https://letsencrypt.org/ in the Fall
[Certbot_LincolnLabPresentation_20170125-2-formatted-for-PPT.pptx](https://github.com/ga4gh/dockstore/files/767561/Certbot_LincolnLabPresentation_20170125-2-formatted-for-PPT.pptx)

**Comment by denis-yuen** [comment]
@SolomonShorser-OICR  Can you link your lab meeting talk here so I have it for reference? (Doesn't matter if its an internal link)

**Comment by SolomonShorser-OICR** [comment]
I just emailed it to you.

**Comment by denis-yuen** [comment]
:shallow_pan_of_food:

**Comment by denis-yuen** [comment]
These docs will be useful
https://github.com/dropwizard/dropwizard/releases/tag/v1.1.0
https://nbsoftsolutions.com/blog/dropwizard-1-1-and-lets-encrypt-with-no-downtime

**Comment by denis-yuen** [comment]
Helpful articles 
https://nbsoftsolutions.com/blog/dropwizard-1-1-and-lets-encrypt-with-no-downtime
https://www.digitalocean.com/community/tutorials/how-to-secure-nginx-with-let-s-encrypt-on-ubuntu-16-04

**Comment by denis-yuen** [comment]
http://www.automationlogic.com/using-lets-encrypt-and-docker-for-automatic-ssl/

**Comment by denis-yuen** [comment]
https://github.com/dockstore/compose_setup updated with support for https

**Comment by denis-yuen** [comment]
Deployed on staging.dockstore.org, awaiting dockstore.org

**Comment by denis-yuen** [comment]
Functional on dockstore.org with documentation at https://github.com/dockstore/compose_setup
