### ISSUE TITLE
OpenJDK 10

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#561]
### Desired behaviour

We should start replacing Oracle JDK 8 with OpenJDK 10. 
This will affect local builds and Travis-CI. 

Partial dependency on Cromwell , how well does this work with 10?)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-169)
┆Issue Type: Story
┆Issue Number: DOCK-169

**Comment by garyluu** [comment]
Didn't really look into it much, but tooltester/jenkins didn't seem to work with OpenJDK 10 without changes

**Comment by denis-yuen** [comment]
I definitely expect changes for these open-ended tasks :)

**Comment by NatalieEO** [comment]
duplicate of ga4gh/dockstore#2320
