### ISSUE TITLE
Dockstore doesn't provision correctly for workflows

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#563]
## Bug Report

I'm having trouble using `secondaryFiles` in a workflow when using dockstore but not when using the cwl-runner from cwltool (1.0.20161114152756).
When I use dockstore, the bam.bai file does not get hardlinked to the input dir.
My `mutect.cwl` file contains this:
```
  input_normal:
    type: File
    inputBinding:
      position: 2
      prefix: --input_file:normal
    secondaryFiles:
      - .bai
```                

This works when run it with `dockstore tool runner`. However, when I put it in a workflow the `.bai` file doesn't get hardlinked and the tool fails. Oddly, when I run the same workflow with cwl-runner, the file _is_ present in the proper directory (the cwl-runner then dies on wrongly mounting the output from a previous step but that's a different issue). 

Links: Tool [mutect.cwl](http://hgwdev.cse.ucsc.edu/~jeltje/toil/mutect.cwl) and [json](http://hgwdev.cse.ucsc.edu/~jeltje/toil/tool.json); Workflow [cwl] (http://hgwdev.cse.ucsc.edu/~jeltje/toil/workflow.cwl) and [json](http://hgwdev.cse.ucsc.edu/~jeltje/toil/workflow.json)

Commands and logs (working runs were killed when it was clear mutect started properly):
`cwl-runner /mnt/mutect.cwl --json tool.json` [log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/cr_working_tool.log) **works**
`cwl-runner /mnt/workflow.cwl --json workflow.json` [log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/cr_working_workflow.log) **mounts bam.bai files** (then fails on something else)
`dockstore tool launch --entry /mnt/mutect.cwl --local-entry --json tool.json` [log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/ds_working_tool.log) **works**
`dockstore workflow launch --entry /mnt/workflow.cwl --local-entry --json` workflow.json [log](http://hgwdev.cse.ucsc.edu/~jeltje/toil/ds_fail_workflow.log), [log with cwl-runner --debug](http://hgwdev.cse.ucsc.edu/~jeltje/toil/ds_fail_workflow_wdebug.log)

### Environment (Browser or OS and Dockstore version)
Ubuntu 16.04
dockstore 1.1

**Comment by denis-yuen** [comment]
Hi, looks like an issue with file provisioning with work-flows.

**Comment by Jeltje** [comment]
This is still an issue.

**Comment by denis-yuen** [comment]
Finally had a chance to look at this. 

The short story is that we seem to have misunderstood how CWL specifies input files for workflows. 
The code only considers input files specified in the "root" CWL when running a workflow. But this workflow and one other on the GA4GH-DREAM project basically add additional files via secondary files or other ways inside the nested tools. 
Note to self: This will take some work on our side and is outside the scope of a hotfix

**Comment by denis-yuen** [comment]
We ended up doing this as a hotfix with 1.3 taking too long for the scope of the dream challenge. 

This should be functional in 1.2.10 as per #865
