### ISSUE TITLE
tool convert dies on missing output

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#564]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Feature Request 

When there is no `output:` feature in the cwl file, `dockstore tool convert cwl2json` dies. 

### Desired behaviour
Throw an error that says `Missing output feature in cwl file`
### Actual behaviour
`java.lang.NullPointerException`

### Environment (Browser or OS and Dockstore version)

`Dockstore 1.1`

**Comment by denis-yuen** [comment]
Similar to #570  
Create a Junit + better error message for this one as well.

**Comment by denis-yuen** [comment]
Looks good now on staging.dockstore.org 
```
$ dockstore tool convert cwl2json --cwl Dockstore.cwl 
problems running command: cwltool --non-strict --validate Dockstore.cwl
stderr for command:
        /usr/local/bin/cwltool 1.0.20170217172322
        Resolved 'Dockstore.cwl' to 'file:///home/dyuen/dockstore_tools/dockstore-tool-bamstats/Dockstore.cwl'
        Tool definition failed validation:
        Dockstore.cwl:3:1: Object `Dockstore.cwl` is not valid because
                             tried `CommandLineTool` but
                               missing required field `outputs`
```
Thanks @k-cao
