### ISSUE TITLE
ngdocs document

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#572]
### Desired behaviour
ngdocs document created by grunt-ngdocs should be viewable on github but not on production

**Comment by denis-yuen** [comment]
To elaborate, we can probably use github pages ( https://pages.github.com/ ) to store this documentation rather than serving it ourselves from the productive site. We just need to decide when and how it gets built and uploaded

**Comment by denis-yuen** [comment]
Now available at https://ga4gh.github.io/dockstore-ui/#/api
