### ISSUE TITLE
Test Param File not showing descriptor type

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#585]
## Bug Report

Selecting the latest version of the 'Test Parameter File' results in the 'Descriptor Type' field becoming blank (possible follow on from #584)

### Expected behaviour

Should be able to select cwl/wdl in dd-menu (depending on which is available).

### Actual behaviour

v1.0.0 of dockstore-cgpmap shows the correct `cwl` descriptor type in the dd-menu:

![screen shot 2017-02-02 at 09 19 40](https://cloud.githubusercontent.com/assets/3740323/22543524/c12fd620-e928-11e6-86ab-f7a965bc9734.png)

Switching to v1.0.3 (manually created due to #584) the dd-menu is blank:

![screen shot 2017-02-02 at 09 20 41](https://cloud.githubusercontent.com/assets/3740323/22543554/e7adc2d0-e928-11e6-9098-4c4337c9878d.png)

**Comment by denis-yuen** [comment]
Looks better, but not complete on 
```
DockstoreUI - 1.2-alpha.3
DockstoreApi - 1.2.0-beta.0 
```

When selecting Test Parameter Files on https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap

You can now select 1.0.8 and it will select CWL correctly. 
However, the display is initially blank and says "  A Test Parameter File associated with this Docker container could not be found. " which is incorrect

**Comment by denis-yuen** [comment]
@garyluu  looks like this can still occur. 
Go to https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap
Select 1.0.6 of the Dockerfile, click through to Descriptor Files and then to Test Parameter Files. 
You will see `A Test Parameter File associated with this Docker container could not be found. ` and the container version is set to a blank value rather then one of 1.0.8 or 2.0.1 as expected.

**Comment by denis-yuen** [comment]
Going back to the OP, this seems better now. 
https://staging.dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap displays a test parameter file for 1.0.8 (which does have a test param file) and a filled in cwl value for the type. For 1.0.6 (which lacks the test parameter file), the file becomes blank but the warning is better. Closing this tentatively for now
