### ISSUE TITLE
Output Provisioning for large files very slow

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#586]
## Feature Request 

While working around #580  writing files to tmp and then uploading with s3cmd adds considerable time to a process due to dockstore copying files out of datastore to the 'final' location before they are available.  68 GB file adds ~2.5 hours to process.  Copy seems remarkably slow under java.

### Desired behaviour

Option for fast copy without progress meters in `FileProvisioning.copyFromInputStreamToOutputStream`?

Possible that a larger value than `Util.DEFAULT_COPY_BUFFER_SIZE` (1k by the look of it) may help but copying to memory is always going to make it slower.

```java
private void copy(String in, String out) throws Exception {
    FileChannel fin = new FileInputStream(in).getChannel();
    FileChannel fout = new FileOutputStream(out).getChannel();
 
    fout.transferFrom(fin, 0, new File(in).length());
 
    fin.close();
    fout.close();
}
```

### Steps to reproduce the behaviour 

Anything that copies a large file into the output locations.

### Environment (Browser or OS and Dockstore version)

Dockstore Client 1.1.2

**Comment by denis-yuen** [comment]
Sounds like a good thing to tune/look into.

**Comment by denis-yuen** [comment]
Should be functional on staging.dockstore.org (1.2.0 beta)
