### ISSUE TITLE
Junit Tests: Unable to check system log if tested methods have exited

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#595]
## Bug Report
A number of junit tests have an assert statement after the tested method have exited.
```
thisMethodExits();
assertTrue("output should include an error message and exit",
                systemOutRule.getLog().contains("exit..."));
```

 These assert statements have no effect. Use exit.checkAssertionAfterwards as shown here: https://stefanbirkner.github.io/system-rules/#ExpectedSystemExit

Use systemOutRule or systemErrRule like so:
```
exit.checkAssertionAfterwards(new Assertion() {
      public void checkAssertion() {
            assertEquals("exit ...", systemOutRule.getLog());
      }
});
```
### Environment (Browser or OS and Dockstore version)
Dockstore 1.1.2

**Comment by denis-yuen** [comment]
I believe this is complete, thanks @garyluu
