### ISSUE TITLE
UI: jump to last settings, not default settings

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#600]
This is for the dockstore UI, but I don't have privileges to start a ticket there, it seems.

### Desired behaviour
Jump back to the page I started on, not to my default page.

### Details
When I want to add a new tool, my options are listed on the left hand side. By default, my quay.io/jeltje tools are shown. Below that are the two other organizations I'm a member of, opengenomics and ucsc_cgl. To see their tools, I have to click on them.

After I have changed a file path on one of these tools (the cwl file location, for example), the page refreshes... and shows me the default setting again (quay.io/jeltje). So I have to close that, open the organization, and start again. This is fine when you have to add a few tools, but I have a whole list and it's getting tedious.

This is a really minor nuisance, but still.

**Comment by denis-yuen** [comment]
Still present in 
```
DockstoreUI - 1.2-alpha.3
DockstoreApi - 1.2.0-beta.0
```

**Comment by denis-yuen** [comment]
Demoed previously, thanks!
