### ISSUE TITLE
add support for GCS (similar to what exists for S3)

### ISSUE THREAD

**Issue by smrgit** [ga4gh/dockstore#601]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Feature Request 
in reading the Dockstore paper the other day, I saw mention of support for input and output files coming from and going to S3 -- I'd like to request similar support for Google Cloud Storage (GCS)

### Steps to reproduce the behaviour 
(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)
Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-56)
┆Issue Type: Story
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-56

**Comment by garyluu** [comment]
@smrgit Public data available on GCS such as "http://storage.googleapis.com/uspto-pair/applications/05900002.zip" already works without a file provisioning plugin.  For private data, is there a preferred method of authentication that you want to be supported?

**Comment by smrgit** [comment]
@garyluu -- that's great to know thanks -- for data requiring credentials, maybe using the same [approach that htslib recently implemented](https://github.com/samtools/htslib/pull/446)  would make sense?

**Comment by jbingham** [comment]
The best approach to auth would be to support service account credentials, as I think htslib did. Service accounts are the recommended way, according to Google security experts. 

As a convenience so users can get started easily, it's good to also support user account credentials, though it's advisable to alert users to the caveats and provide documentation. The recommendation is that if you use user credentials, you should do so from your own cloud project, which no other users have access to, or from your own computer, which no other users have access to.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The GCS plugin is working but needs some cleanup and tests to be written.

[https://github.com/dockstore/gs-plugin/tree/feature/issue-601-gs-plugin](https://github.com/dockstore/gs-plugin/tree/feature/issue-601-gs-plugin)

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

Unit tests implemented

PR [https://github.com/dockstore/gs-plugin/pull/1](https://github.com/dockstore/gs-plugin/pull/1) submitted and under review.

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

PR accepted and merged

**Comment by cricketsloan** [comment]
➤ Walt Shands commented:

The plugin support service account credentials. The USER just needs to point the environment variable GOOGLE_APPLICATION_CREDENTIALS to the file with the service account key before using the Dockstore command line. A link to Google instructions for setting this up is provided in the GCS plugin READ.ME

**Comment by wshands** [comment]
This ticket needs to be verified.

**Comment by cricketsloan** [comment]
➤ Charles Overbeck commented:

Verified by using the workflow at https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:1.32.0?tab=files ( https://staging.dockstore.org/workflows/github.com/DataBiosphere/topmed-workflows/UM_aligner_wdl:1.32.0?tab=files ).

Downloaded the test parameter JSON file from that same workflow. That file has https URLs; I changed them to to gs urls by changing https to gs and removing storage.googleapis.com ( http://storage.googleapis.com ). For example,  https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/input_files/NWD176325.25rea ( https://storage.googleapis.com/topmed_workflow_testing/topmed_aligner/input_files/NWD176325.25rea )ds.cram becomes gs://topmed_workflow_testing/topmed_aligner/input_files/NWD176325.25reads.cram.

Tested against staging with 1.6.0-beta.4.

Did notice an issue downloading plugins while testing, but it is unrelated to this fix. Logged it as https://github.com/ga4gh/dockstore/issues/2261 ( https://github.com/ga4gh/dockstore/issues/2261 )

**Comment by Ldcabansay** [comment]
There's a notable download speed discrepancy between gs and https paths, gs is about 2-3x slower. #2268
