### ISSUE TITLE
Improve documentation on test JSON and add default json path

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#607]
### Desired behaviour

https://dockstore.org/docs/getting-started-with-dockstore references and screenshots how to register test JSON for manually created tools, but it only references it in the text for quick registration. 
Improve this documentation to be more clear and explicit about how to register test JSON since it is confusing. (This may have been improved by the private repo work by @agduncan94  already)

Double-check that this page is properly headered and linkable with the new develop TOC system. 

Encountered by @Jeltje https://gitter.im/ga4gh/dockstore?at=58b77849f1a33b62756a7a91

### Environment (Browser or OS and Dockstore version)

1.1.6 website

**Comment by Jeltje** [comment]
I would add that I'd expect an upload feature under the Files tab. Maybe, similar to the `cwl` and `wdl` file formats, the system could look for a specific `json` file (say Dockstore.json) in the repo and serve that as default?

**Comment by denis-yuen** [comment]
@Jeltje that makes sense actually, the web service currently allows for you to register multiple test json, but we should probably automatically look for one test json at a default at least, that wouldn't be too expensive in terms of rate limit

**Comment by denis-yuen** [comment]
Food for thought, running through the 1.3 tutorials. 
It gave a me a double-take, when I added the test json. 
I may have been tired, but I added `/test.json` and pressed save. I was able to return to the version which made me think I had saved it, but I actually need to hit the `+` button for it to actually be added.

**Comment by agduncan94** [comment]
I noticed that too today, was going to create a ticket that we should redesign the adding and subtracting of test json files.

**Comment by denis-yuen** [comment]
This looks much more intuitive on staging.dockstore.org. 
We're not doing upload (yet, anyway), but we did add the ability to add a default
