### ISSUE TITLE
Use only GA4GH methods instead of /containers and /workflows

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#623]
## Feature Request
Have front end use only methods from https://dockstore.org:8443/static/swagger-ui/index.html#/GA4GH

Currently, we use:
https://dockstore.org:8443/static/swagger-ui/index.html#/containers
https://dockstore.org:8443/static/swagger-ui/index.html#/workflows

### Desired behaviour
Have all the same functionalities as the ones currently on https://dockstore.org/

### Environment (Browser or OS and Dockstore version)
DockstoreUI - 1.1.6
DockstoreApi - 1.1.5

**Comment by denis-yuen** [comment]
Add to #1731
