### ISSUE TITLE
Deregister Workflows

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#624]
## Feature Request 
Have a de-register button with confirmation for workflows on the UI

### Desired behaviour
Similar to de-registering a tool on the UI (confirmation is currently in develop, but not master)

### Environment (Browser or OS and Dockstore version)
DockstoreUI - 1.1.6
DockstoreApi - 1.1.5

**Comment by denis-yuen** [comment]
Still required

**Comment by agduncan94** [comment]
Would this be something like adding the workflow to a blacklist? And then just ignoring these on refresh?

**Comment by agduncan94** [comment]
Right now if a workflow if hosted or manual, you can delete it. If it isn't you cannot delete it, however you can stub it. Deleting it would simply delete it until the org it is in is refresh either individually or as refresh all. Restub will set it back to its original settings as a stub, with no associated versions or files. I think this is good enough.
