### ISSUE TITLE
Default Version Indicator

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#628]
## Feature Request 

Tools/Workflows should indicate what the default branch/version is on the info tab.

### Desired behaviour

Currently there's no good indicator showing what the default branch/version is.  Also applies to CLI too.

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.1.6
DockstoreApi - 1.1.5

**Comment by denis-yuen** [comment]
This one is weird. 
Tools is lacking the feature. 
Workflows has it, but you can select the default from "Workflows" as opposed to "My Workflows"

**Comment by garyluu** [comment]
It's been removed from Workflows in a recent pull request.  Not sure if there's any obvious indicator which one is the default branch for either of them yet.

**Comment by denis-yuen** [comment]
Let's show a disabled radio button for "Tools" and "Workflows" (for all users) and enable it in "My Tools" and "My Workflows" for selection.

**Comment by garyluu** [comment]
I like how this is assigned to Jennifer

**Comment by denis-yuen** [comment]
Indicator is present but it is hard to tell what the indicator is actually indicating.
Add tooltips to the headers and the indicator itself like in "My Tools" and "My Workflows" explaining the situation.

**Comment by garyluu** [comment]
I've just added a toolip to the radio button indicator on the public page.  Can you clarify what the header is?

**Comment by denis-yuen** [comment]
For tools, you would want to explain that this is a Docker tag, that a Docker tag uniquely describes a version of a tool, an indicator describes the default version of a tool and that determines what displays in to the info and launch-with. You might need to link to documentation like with the verified documentation. 

For workflows, you'll want to explain the same with the change that a workflow version is identified by git reference only rather than a docker tag.

**Comment by denis-yuen** [comment]
(Note that the verified documentation link doesn't seem to work, perhaps a merge conflict)

**Comment by garyluu** [comment]
Clicking the verified icon explains in more details what 'verified' is in both mytools and tools. but clicking the default branch radio button is suppose to set the default version.  Where do you want the link to the documentation for default version?

**Comment by denis-yuen** [comment]
Maybe link in the tooltip for the radio button or in the header? We'll have to take a look and see which looks better/is more intuitive.

**Comment by denis-yuen** [comment]
While you're at it, could you also similarly link the private icon to https://staging.dockstore.org/docs/public_private_tools ? thanks

**Comment by denis-yuen** [comment]
FYI, missed this earlier, but the tooltip is not clear and might not be a sentence. 
https://github.com/dockstore/dockstore-ui2/blob/develop/src/app/shared/versions.ts#L31

**Comment by garyluu** [comment]
The tooltip is displayed as "Set as default branch.  The default branch uniquely identifies the branch of a tool/workflow.   Determines what is displayed in the Info tab (Description, Launch With, etc)."

On hover: 
- It tells you what clicking it does - "Set as default branch."  
- It briefly describes what the default branch is - "The default branch uniquely identifies the branch of a tool/workflow"
- It briefly describes how that affects the users -"Determines what is displayed in the Info Tab (Description, Launch With, etc).  

Seems clear enough for me, feel free to provide suggestions on what else should be included.  Third one may not seem like a sentence because it's in passive voice and could be changed to an active sentence or merged with the 2nd sentence if needed.

**Comment by denis-yuen** [comment]
1. Tooltip cut off in Tools and Workflows
2. Put yourself in the shoes of a user with a separate tooltip for end-users vs workflow/tool developer
3. Possibility: Write a longer description and just link to it in the FAQ

**Comment by denis-yuen** [comment]
Looks good for now, following up with issue as indicated
