### ISSUE TITLE
Support embedded Dockerfile in CWL

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#63]
See https://groups.google.com/forum/#!topic/common-workflow-language/NhZv8eGjNnE

This is not slated for a particular milestone but more of an idea for the future.  If people embedded Dockerfiles in CWL it would help keep them in sync.  Also, Dockstore could have a mode that would setup and build the Docker image from this CWL-embedded Dockerfile.

**Comment by denis-yuen** [comment]
Duplicates #52
