### ISSUE TITLE
Misleading Route for Documentation

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#632]
## Bug Report

Currently, navigating to https://dockstore.org/docs gives the user a page displaying 403 Forbidden error instead of the main documentation page which seems to share the same path

### Expected behaviour

Show main documentation page

### Actual behaviour

Shows 403 Forbidden Page

### Steps to reproduce the behaviour 

Directly type: https://dockstore.org/docs (make sure to clear cache)

### Environment (Dockstore version)
DockstoreUI - 1.1.6
DockstoreApi - 1.1.5

**Comment by denis-yuen** [comment]
Sill present as of  1.2-alpha.3 
Might be nginx configuration

**Comment by denis-yuen** [comment]
This is due to an interaction between nginx and angular js 
https://stackoverflow.com/questions/28359714/nginx-403-error-on-specific-angular-route 
But should go away in the next version

**Comment by denis-yuen** [comment]
https://github.com/ga4gh/dockstore/issues/815 is the workaround from the linked issue

**Comment by denis-yuen** [comment]
Works now in https://staging.dockstore.org/docs
