### ISSUE TITLE
Sorting by Table Column Not Working

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#634]
## Bug Report
Sorting by columns does not work for browse tools on the home page

### Expected behaviour
Table to be sorted by column

### Actual behaviour
Preview does not change when sorting

### Steps to reproduce the behaviour
Go to https://dockstore.org/ and click on the arrows besides name and author

### Environment (Dockstore version)
DockstoreUI - 1.1.6
DockstoreApi - 1.1.5

**Comment by denis-yuen** [comment]
Functional as of 1.2-alpha.3 on staging.dockstore.org
Thanks @k-cao
