### ISSUE TITLE
Easy way to share or switch to the published listing for a tool from "My Tools"

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#636]
### Desired behaviour

Idea from @SolomonShorser-OICR 
Right now, you need to switch to "tools" and then search for a tool which is not intuitive.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-476)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Issue Number: DOCK-476

**Comment by SolomonShorser-OICR** [comment]
:+1:

**Comment by agduncan94** [comment]
Could this be something like a "View public workflow/tool" button? Not sure of the best place to put it. Could go with the publish/refresh buttons, or could be in the info tab depending on how important it is.

**Comment by denis-yuen** [comment]
Exists with DockstoreAPI - 1.6.0-beta.0DockstoreUI - 2.3.0-beta.0
