### ISSUE TITLE
Bulk import of CWL from "official" sources

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#64]
Related to:
- https://github.com/common-workflow-language/common-workflow-language/issues/170
- https://github.com/ga4gh/dockstore/issues/34

There has been a request from Andrey to take CWL from the official CWL repo and auto-import them into Dockstore.

**Comment by victoroicr** [comment]
The specific repo to look at is https://github.com/common-workflow-language/workflows
