### ISSUE TITLE
Test new endpoints for organization

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#643]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Feature Request
Have automated tests for new endpoints about organization

### Desired behaviour
Test new endpoints (ex. organization)

### Environment (Browser or OS and Dockstore version)
DockstoreApi - 1.1.5

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-477)
┆Issue Type: Story
┆Issue Number: DOCK-477

**Comment by denis-yuen** [comment]
This should be more specific and refer to the json-ld endpoints

**Comment by denis-yuen** [comment]
Think this is superceded
