### ISSUE TITLE
Parameter file endpoint not working as expected

### ISSUE THREAD

**Issue by k-cao** [ga4gh/dockstore#649]
## Bug Report
GET containers/{containerId}/testParameterFiles requires all of its parameters, even the optional ones, to be filled before it can behave as expected

#### No Parameters
Return an array of tags with only their test parameter files.

#### Parameter 'tag' only
Return the specified tag's test parameter files

#### Parameter 'descriptorType' only
Return a list of tags with only their test parameter files, all of the specified descriptorType

#### Both Parameters
Return an array of json objects each describing a test parameter file of the specified descriptorType and belonging to the specified tag

#### No Parameters, Parameter 'tag' only
Error

#### Parameter 'descriptorType' only
Empty array

#### Both Parameters
Same as expected

#### No Parameters
https://staging.dockstore.org:8443/containers/1522/testParameterFiles

#### Parameter 'tag' only
https://staging.dockstore.org:8443/containers/1522/testParameterFiles?tag=master

#### Parameter 'descriptorType' only
https://staging.dockstore.org:8443/containers/1522/testParameterFiles?descriptorType=cwl

### Environment (Browser or OS and Dockstore version)
DockstoreApi - 1.1.5

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-478)
┆Issue Type: Story
┆Issue Number: DOCK-478

**Comment by denis-yuen** [comment]
@k-cao 
Verified, but do experiment under a few conditions to narrow this down
Give some indication as to whether this works in the normal case, with only WDL test json, with only CWL test json, all files present, etc. Thanks

**Comment by denis-yuen** [comment]
Superceded
