### ISSUE TITLE
DAG tab hidden

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#653]
### Expected behaviour

DAG tab in workflows should never be hidden

### Actual behaviour

DAG tab is sometimes hidden

### Steps to reproduce the behaviour 

Start with full screen, keep making the window horizontally shorter.  The DAG tab will be hidden at some point.

**Comment by garyluu** [comment]
This issue causes non-fullscreen or low res cypress tests to fail.

**Comment by denis-yuen** [comment]
@garyluu  FYI, either fill in the environment and instructions or leave them off.

**Comment by garyluu** [comment]
I believe this should be fixed.
