### ISSUE TITLE
Dockstore command line auto-update check

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#66]
It would be nice for `--version` to check the current version of the Dockstore CLI/library:

```
boconnor@odm-boconnor ~$ dockstore --version
Dockstore version 0.2.0
You are running the latest version...
```
and

```
boconnor@odm-boconnor ~$ dockstore --version
Dockstore version 0.2.0
The latest version is 0.3.0, please upgrade by going to <URL>...
```

Would be even more awesome to have a `--upgrade` option that downloads the latest CLI and gives directions on where to put it/chmod it.

**Comment by agduncan94** [comment]
The functionality has been added in the referenced feature branch.
