### ISSUE TITLE
Test out gitlab support on staging.dockstore.org

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#669]
A placeholder for some testing work, let's test out gitlab support on staging.dockstore.org
(both source and docker image)

**Comment by garyluu** [comment]
Automatic refresh of a GitLab source code repo with quay.io image adds the tool to Dockstore.  However, it seems that the source files aren't added to the tag.

**Comment by garyluu** [comment]
Looks like the tag isn't being automatically added, but once the tag and git reference is manually added, the files get correctly displayed.

**Comment by denis-yuen** [comment]
I was able to add descriptors from gitlab and docker images from gitlab.
