### ISSUE TITLE
Manual image doesn't link to Dockerfile/Dockstore.cwl correctly

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#67]
![image](https://cloud.githubusercontent.com/assets/1730584/11790881/1e870a14-a26c-11e5-8d3f-7af740630e53.png)

This image shows the "latest" tag was used to attempt to pull the Dockerfile but the actual git branch was "master"

![image](https://cloud.githubusercontent.com/assets/1730584/11790900/418936b8-a26c-11e5-82fb-41ec78a70068.png)

**Comment by briandoconnor** [comment]
So it looks like "latest" (tag from Dockerhub) is used when the git repo "master" should be used for the Dockerfile and Dockstore.cwl.

**Comment by briandoconnor** [comment]
Vincent said it's not that the incorrect git branch is being used.  It's another problem that he's investigating.  It looks like a manually registered DockerHub+GitHub image does not work... the versions are always "Valid=NO" and the Dockerfile and Descriptor cannot be displayed.

**Comment by victoroicr** [comment]
Fixed
