### ISSUE TITLE
/users/starredTools/  non-deterministic order

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#672]
### Expected behaviour
Response from /users/starredTools/ should be consistent.  Tools returned should be in the same order every time.

### Actual behaviour
Tools returned from /users/starredTools/ are not returned in the same order every time.

### Steps to reproduce the behaviour 
Star a bunch of tools/workflows.  Go to starred tools/workflows page.  Note the order of the tools/workflows displayed.  Refresh the page.  The tools/workflows are now in a different order.

**Comment by denis-yuen** [comment]
This looks fixed on staging.dockstore.org
