### ISSUE TITLE
GitLab API V4

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#679]
### Desired behaviour
We should use GitLab API V4 because GitLab API V3 will be phased out.
Since GitLab 9.0, API V4 is the preferred version to be used.
V3 will remain working until at least GitLab 9.3.  It is currently GitLab 9.1

**Comment by denis-yuen** [comment]
Develop uses https://github.com/timols/java-gitlab-api which uses v4. 
Hotfix branch uses v3 which is now broken.
