### ISSUE TITLE
Error messages without bitbucket token

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#682]
### Desired behaviour
Tools using public bitbucket repos should function normally.  Files can be added and then displayed in the files tab after refresh.

**Comment by denis-yuen** [comment]
FYI, this probably won't work for consistency with GitHub. 
We usually use a user's own oauth token to talk to GitHub/Bitbucket. If we don't have one for a user, public access has a low rate limit, so we just don't allow this. Instead, as mentioned on Slack, a user shouldn't be able to add a Bitbucket-based tool without a token (show an appropriate error message).
