### ISSUE TITLE
Adding same test file

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#683]
### Expected behaviour
Test file that is already added should not be added again.

### Actual behaviour
Test file of the same path/name can still be added

### Steps to reproduce the behaviour 
Create a tool manually in the UI, create new tag, add two files with the same name.

**Comment by denis-yuen** [comment]
This seems to still be broken. I can add two /test.json for `quay.io/dockstore-testing/dockstore-tool-md5sum`. While they don't both display in Files which is good, I can see two of the same file when editing the version (instead, we should display a red warning and disable saving like when adding a CWL file that doesn't end in CWL)

**Comment by garyluu** [comment]
I believe we agreed it was fine to move it to dockstore-ui2 only

**Comment by denis-yuen** [comment]
@garyluu  Ah, this issue needs to be updated then.

**Comment by garyluu** [comment]
In UI2, form still allows you to "Add" the same test file.  However, upon editing the tag again, the duplicate file will disappear.  So it seems it's partially fixed.

**Comment by denis-yuen** [comment]
Thanks for the update. That is better. 
However, I think its reasonable for the GUI to check for this since it should have the information for what test paths already exist in order to reject an update.

**Comment by coverbeck** [comment]
This is fixed, but see my comment on [#728](https://github.com/ga4gh/dockstore/issues/728). I think this fix just makes that issue obvious, so I will close this one, but mentioning it just in case.

**Comment by denis-yuen** [comment]
Thanks!
