### ISSUE TITLE
Excessive API calls for tag creation

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#684]
### Expected behaviour
Test Parameter Files should be updated only once per tag created.

### Actual behaviour
While typing in the "Version Tag" field, an API call is made to get the test parameter file of that unfinished Version Tag name (ex. l, la, lat, late, lates, latest) even though it does not exist yet.

### Steps to reproduce the behaviour 
Have a tool in manual mode.  Add tag, start typing into the "Version Tag" field and watch the network API calls.  

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.1.6

**Comment by denis-yuen** [comment]
Thanks
