### ISSUE TITLE
Test Parameter File Not Updating Upon Tag Creation

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#685]
### Expected behaviour
When creating a new tag with a test parameter file, the file should immediately show up in the files tab. 

### Actual behaviour
When creating a new tag with a test parameter file, the file does not immediately show up in the files tab unless refreshed.  

### Steps to reproduce the behaviour 
- Add tag
- Put a test parameter file
- Save changes
- Go to files tab -> test parameter files
- File is not present

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.1.6

**Comment by denis-yuen** [comment]
Thanks
