### ISSUE TITLE
Gravatar/github image is low res and inconsistent

### ISSUE THREAD

**Issue by travisgithuboicr** [ga4gh/dockstore#687]
### Expected behaviour
Image on accounts page should always stay the same between refreshes
Image on stargazers page is not low res.

### Actual behaviour
Image changes from gravatar to github image upon sync with github
Image on stargazers page is low res.

### Steps to reproduce the behaviour 
- Have a gravatar image and github image
- Go to your accounts page 
- Sync with GitHub
The image has changed
- Star a tool/workflow
- Go to stargazers page of that tool/workflow
The image is low res

**Comment by denis-yuen** [comment]
Looks high-res now
