### ISSUE TITLE
De-Register Button not Obvious

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#69]
So it's actually really hard to tell that you click on the "Registered" button in order to de-register the tool.  I think you need a better toggle or other button that makes it clear you should click it to register/de-register the tool:

![image](https://cloud.githubusercontent.com/assets/1730584/11792738/9a17513a-a275-11e5-8de4-de958bc8ddf6.png)

**Comment by briandoconnor** [comment]
Maybe "Register" and "De-Register" for the labels?

**Comment by briandoconnor** [comment]
I'll let you choose between deregister and unregister: http://english.stackexchange.com/questions/25931/unregister-vs-deregister

**Comment by denis-yuen** [comment]
I do think that we need to be consistent, we use "publish" and "register" somewhat interchangeably

**Comment by oicr-vchung** [comment]
Changed the labels to use these semantics (for now):

* Publish/Unpublish: Make a container (<sup>i.e.</sup> image) visible/not visible in the public listing
* Register/Deregister: Add (manually, through a form) or Delete a container (<sup>i.e.</sup> image)
