### ISSUE TITLE
Starred workflows/tools can run off the box or get arranged weirdly

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#692]
### Expected behaviour

Workflow urls do not run off, boxes are arranged in a more normal left to right, top to bottom manner
The same applies for tools

### Actual behaviour

![screenshot from 2017-04-25 16-17-26](https://cloud.githubusercontent.com/assets/1730679/25405906/dae78b9a-29d2-11e7-9f2e-e92afc505cef.png)
![screenshot from 2017-04-25 16-19-16](https://cloud.githubusercontent.com/assets/1730679/25405946/02f80ba0-29d3-11e7-966c-60cb303d86e9.png)

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.1
DockstoreApi - 1.2.0

**Comment by denis-yuen** [comment]
@JWKaiqi  review and close if no longer an issue

**Comment by JWKaiqi** [comment]
No longer an issue in UI2
