### ISSUE TITLE
review tutorial

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#695]
### Expected behaviour

The official Dockstore tutorials should result in automated tools (except for the section that specifically addresses manual tools). 

### Actual behaviour

Somehow, users are occasionally ending up with manual tools. This may be a miscommunication or similar. 
ex:
```
ok, quick hits:
1. I can’t speak for @tom, but when I created the two `helloworld` tools, I followed the tutorial pretty much point-by-point; for some reason, both still showed up as “Manual” rather than automated, even though the auto-build trigger is working fine on the quay.io side.
```

**Comment by garyluu** [comment]
Going to put all minor issues with the tutorial in this issue.

**Comment by garyluu** [comment]
1.  https://dockstore.org/docs/getting-started should say "Dockstore is powered by Quay.io, Docker Hub, and GitLab for storing Docker images"

**Comment by garyluu** [comment]
2.  Kind of strange how Dockstore is being referred it as "the Dockstore" and simply "Dockstore"

**Comment by denis-yuen** [comment]
Kinda like how you can refer to Batman as "the Batman" ;)

**Comment by garyluu** [comment]
https://dockstore.org/docs/getting-started-with-dockstore#-linking-github-bitbucket-gitlab-and-quay-io-linking-services-   says  "]onboarding wizard."

**Comment by garyluu** [comment]
I don't think the tool will be registered if the image has not been built yet.

**Comment by garyluu** [comment]
In https://dockstore.org/docs/getting-started-with-dockstore#-register-your-tool-in-dockstore-register-your-tool-in-dockstore-

Instead of "When we discover both of these, we create an unregistered entry in the interface below."  Maybe it's supposed to be "unpublished entry"?

**Comment by denis-yuen** [comment]
re 1) IIRC, we don't actually support GitLab as a Docker image repo, but you can give it a try

**Comment by garyluu** [comment]
Similar to Docker Hub, we can manually add tools with GitLab.  However, the tool will not be automatically picked-up.

**Comment by garyluu** [comment]
Yellow 'Publish' button is not yellow in the screenshot

**Comment by garyluu** [comment]
"at least one valid tag. In order to be valid, a tag has to:

    be automated from a GitHub, Bitbucket, or GitLab reference".  Kind of misleading.  Sounds like a manual tool can't be valid.
