### ISSUE TITLE
Unable to add tools directly

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#696]
### Expected behaviour

A user should be able to login directly and add tools without a full refresh and without any tools using build triggers

### Actual behaviour

It looks like a 500 error results sometime during this process. On the DB side, it looks like the registry becomes undefined in this case. Will need to investigate under what situation this occurs

### Steps to reproduce the behaviour 

![](https://files.gitter.im/ga4gh/dockstore/QA8i/image.png)

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.1
DockstoreApi - 1.2.1

**Comment by denis-yuen** [comment]
FYI @garyluu, since you're already looking at it. Let's go with your idea and see if there's an across-the-board way of getting more info on the exceptions. We've seen individual 500s in the past get more info passed back, I don't know if there's a more comprehensive way of doing it

**Comment by garyluu** [comment]
I can't seem to reproduce this error.  Here's a series of steps I've tried:

1. Forked the github repo
2. Created a quay.io repo
3. Create github push build trigger on quay
4. Add tool
5. Select different image registry tags in the dropdown menu.

The Docker Registry Path's placeholder should not be present upon page load or image registry tag changes.  Perhaps javascript was blocked?

**Comment by denis-yuen** [comment]
I believe that this was due to the DB constraint issues
