### ISSUE TITLE
dockstore old release warning should be on STDERR

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#699]
When I run an older version of dockstore, I get the warning
```
Current version : 1.1.2
Latest version : 1.2.0
You do not have the most recent stable release of Dockstore.
Please upgrade with the following command:
   dockstore --upgrade
```
This goes to STDOUT
As a result, it's now in my CWL files because I run like so `dockstore tool cwl --entry quay.io/ucsc_cgl/dockstore_tool_adtex > adtex.cwl`
Took me a while to find the problem!

### Desired behaviour
Print this warning to STDERR

**Comment by denis-yuen** [comment]
Thanks for the heads-up!

**Comment by denis-yuen** [comment]
@garyluu  This is partially fixed. 
While the version info is redirected, we can still end-up with the following 
```
e$ cat adtex.cwl 
Downloading Dockstore to /home/dyuen/.dockstore/self-installs/dockstore-client-1.2.2.jar now...
file:////home/dyuen/.m2/repository/io/dockstore/dockstore-client/1.2.2/dockstore-client-1.2.2-shaded.jar
#!/usr/bin/env cwl-runner

class: CommandLineTool
id: "ADTEx"
label: "ADTEx workflow"
cwlVersion: v1.0
...

Make sure that downloading messages do not make it into the CWL file either. 
```

**Comment by denis-yuen** [comment]
Looks good now, this will only really work for versions going forward from 1.2.3 though
