### ISSUE TITLE
Implement display of GUI version

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#702]
### Desired behaviour

This old UI displays the version of the UI on the footer and links to an appropriate tag on GitHub
Implement this in the new UI. Note that this was implemented in Grunt before and this should be hooked into the "ng" series of commands somehow

**Comment by denis-yuen** [comment]
Note in the current version, we link to the commit always, but display a tag if its available. 
Ideally, we would link to the actual tag if we have a tag checked out and a commit if not.

**Comment by denis-yuen** [comment]
Note that the API version isn't displayed either. Note that this part is easier since the webservice returns its own version from the metadata endpoint.

**Comment by denis-yuen** [comment]
Correction: looks like the display of the web service version is functional already, only the UI version is needed.

**Comment by garyluu** [comment]
http://stackoverflow.com/questions/42155115/how-to-include-git-revision-into-angular-cli-application
