### ISSUE TITLE
Tool not refreshed upon tag creation

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#707]
### Expected behaviour
Upon tag creation, tool should be refreshed so that the new tag will be displayed and the file contents will be retrieved from source code repository and then visible in the files tab.

### Actual behaviour
Upon tag creation, tool is not refreshed.  There is no indication that the tag was created.

### Steps to reproduce the behaviour 

- Manually add a tool with a GitHub repo and GitLab registry (it will be in manual mode)
- Add tag with valid descriptor, dockerfile, test parameter file
The new tag does not immediately appear and the tool is not refreshed.

### Environment (Browser or OS and Dockstore version)

Firefox
UI and API 1.2.1

┆Issue is synchronized with this [Jira Bug](https://ucsc-cgl.atlassian.net/browse/DOCK-481)
┆Issue Type: Bug
┆Sprint: Seabright Sprint 6 Ferry
┆Issue Number: DOCK-481

**Comment by keiranmraine** [comment]
This looks similar to what I encountered in #584.  The difference is that I linked in a release branch for testing which it tagged as manual and subsequently all new tags aren't picked up unless I de/re-register the tool.  I end up doing them all manually due to this.

**Comment by denis-yuen** [comment]
@garyluu 
Let's take a look at this. I looks like between this and the previous bug, there are a few problems in play:
1) New tags aren't being picked up in some circumstance even with automated builds
2) Tools in manual mode are having issues when adding new tags (as described in the bug report above)
3) Tools in automated mode are being flipped to manual mode when they should not be

You may be able to experiment with https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwgs and https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpwxs on staging. The former seems to be working properly, the lattter is not

**Comment by denis-yuen** [comment]
@keiranmraine  For the time being, I flipped quay.io/wtsicgp/dockstore-cgpwxs into automated mode. After refreshing, it picked up two new versions 2.0.5 and 2.0.6 although I left the default version at 2.0.4. 

@garyluu  When you look into this, the old database state will still be present on staging for your experiments

**Comment by garyluu** [comment]
For the specific issue I posted, it somehow got fixed between API version 1.2.1 and develop.  May possibly have just been a GitLab issue.

**Comment by NatalieEO** [comment]
@garyluu The tag does automatically get added now and the tool is refreshed. However, while it's loading the form puts the first two fields in red and says they cannot be empty. Not sure if new bug with this fix, or just a separate issue when you add a tag to any tool.

**Comment by garyluu** [comment]
Tossed the fix in https://github.com/dockstore/dockstore-ui2/pull/591/commits/c64f36db550dd88e0c6738150e0f367bb366cd22
