### ISSUE TITLE
When I edit a Version Tag it should be auto-sync'd

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#71]
![image](https://cloud.githubusercontent.com/assets/1730584/11793555/46d24494-a27a-11e5-9c72-56fe271914fe.png)

When I added a Git reference (it was missing) this version tag stayed "value=NO" until I did a resync.  Is it possible to resync whenever you make changes to version tags and save them?  Trigger the resync when "save changes" is clicked?

**Comment by oicr-vchung** [comment]
Duplicate of #83.
