### ISSUE TITLE
Adding new variants of tools - launch-with commands seem broken

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#716]
### Expected behaviour

Launch-with commands should work properly when you add a tool based on another tool. In other words, if the same quay.io image + github Descriptor pair has more than one entry in Dockstore

### Actual behaviour

The launch-with commands (convert, launch, cwltool, and consonance) seem broken when looking at tools that are alternates for a pair of quay.io/github. In other words, if you add a tool with a new toolname based on an existing automated tool, the commands reflect the original tool, not the new tool. 

FYI @keiranmraine

### Environment (Browser or OS and Dockstore version)
DockstoreUI - 1.2.2
DockstoreApi - 1.2.1

**Comment by agduncan94** [comment]
This does not seem to be an issue anymore. I have tried convert, launch, and CWL tool and they all work. I only have consonance left. Gary said that he thinks he fixed this issue at some point and that seems to be the case.
