### ISSUE TITLE
Download-able Files in files tab

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#720]
### Desired behaviour
All files in the files tab should be downloadable.  This includes Dockerfiles, CWL descriptor files, and test parameter files.  There should be an icon or a link that initiates the download.

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1

**Comment by denis-yuen** [comment]
Duplicates #1422
