### ISSUE TITLE
Tool Details Escapes Bootstrap Container

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#723]
### Expected behaviour
Perform steps, the versions info should look "normal"

### Actual behaviour
Perform steps, the versions info breaks out of the tab headers and goes under the side bar possibly because the tags are too long.  In addition to the tags being long, the column is even longer than it needed to be.

### Steps to reproduce the behaviour 
1. Go to https://dockstore.org/containers/quay.io/ucsc_cgl/rnaseq-cgl-pipeline
2. Click the "Versions" tab

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1 
DockstoreUI2 - As of https://github.com/dockstore/dockstore-ui2/commit/3faab0055a0291bcd796b1fbcc532c2c38d9ba43

**Comment by denis-yuen** [comment]
Still present in staging.dockstore.org

**Comment by denis-yuen** [comment]
Result is a scrollable cut-off center which I suppose is better than the alternative.
