### ISSUE TITLE
Register GA4GH-DREAM workflows and get them into a verified state

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#725]
Review workflows for GA4GH-DREAM and try them out (in prep for getting them registered and verified on Dockstore)

This is a follow-up to #726 and should result in all workflows from this challenge being available on Dockstore

**Comment by garyluu** [comment]
For https://dockstore.org/containers/quay.io/ga4gh-dream/dockstore-tool-synapse-get, only 1.6.2 has test parameter files.  Test with test_id.cwl.json works.

**Comment by garyluu** [comment]
Test with test_query.cwl.json is successful.

**Comment by garyluu** [comment]
test_tablequery.cwl.json is empty, so unsuccessful

**Comment by garyluu** [comment]
For https://dockstore.org/workflows/briandoconnor/dockstore-workflow-md5sum, it is unsuccessful because input files are not found.  The synapse-get tool using the previous dockstore's 3 test files do not place files expected by this md5sum workflow.  However, using synapse's md5sum_get.cwl.json and then this md5sum workflow works.

**Comment by denis-yuen** [comment]
This is essentially a dependency for running tool tester now
