### ISSUE TITLE
GA4GH-DREAM Challenge: Test out the md5sum workflow

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#726]
For the first workflow, test out md5sum which is already registered. And hit verify if successful

* Just like the first phase of the challenge, do create  document that explains how to run these tools via Dockstore like https://www.synapse.org/#!Synapse:syn8080249/wiki/412566 so that others can run the same tools and workflows
* May want to investigate how to optimize this procedure if any steps or input.json optimziations can results in a shorter procedure
* md5sum should be published as a result of this work (if it not already) and should be easy for anyone to run if encountering it on Dockstore for the first time

**Comment by denis-yuen** [comment]
Completed this in a review of GA4GH-DREAM work
