### ISSUE TITLE
Can't edit tag with unusual tag name

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#728]
### Expected behaviour
Tag editor should be able to edit tags named 1.0.3.dev--2 for a tool

### Actual behaviour
"Save Changes" is disabled because 1.0.3.dev--2 does not match the regular expression /^[a-zA-Z0-9]+([-_\.][a-zA-Z0-9]+)*$/i
Additionally, there is no message in the form to notify the regular expression is invalid.

### Steps to reproduce the behaviour 
- Create a tool
- Create a tag with the name 1.0.3.dev--2
- Try to edit the tag and save changes

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.2
DockstoreApi - 1.2.1

**Comment by denis-yuen** [comment]
Workaround:
use a tag name that matches the regular expression

Long-term: we should probably get a hotfix for this

**Comment by denis-yuen** [comment]
@agduncan94  I think this might be a duplicate since you're already on the case

**Comment by coverbeck** [comment]
I am able to edit the tag.

But I notice if you click Add Tag and save, then click Add Tag again, the CWL and WDL test files are duplicated when the dialog starts up.

![image](https://user-images.githubusercontent.com/1049340/34276355-f0090fa4-e655-11e7-9d27-31d1a73cb7e1.png)

**Comment by agduncan94** [comment]
Seems like we might not be clearing the form fully after saving.

**Comment by agduncan94** [comment]
Closing this and opening a new issue for the issue Charles found.

**Comment by denis-yuen** [comment]
This seems resolved in staging.dockstore.org
