### ISSUE TITLE
Testing Settings in CWL

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#73]
Explore the best way to include testing settings/files/call to tool in the CWL.  This way we can automate the testing of the tools

**Comment by briandoconnor** [comment]
@denis-yuen I think this will become increasingly important as various execution platforms (SevenBridges etc) want to test and validate tools/workflows on Dockstore.  I think we need a UI tab for "Test Data" and each entry is a Dockstore.json sample parameterization that can be run with the workflow.  What do you think?

**Comment by denis-yuen** [comment]
It could make sense. Presumably we would do the same drill as descriptors or Dockerfiles in that we would have to allow navigation between tags.
We would also have to model the json file (files?) in some way so that we know to cache them on refresh.

**Comment by denis-yuen** [comment]
Implemented in 1.1
