### ISSUE TITLE
Ensure the hello_world workflow is working

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#730]
Ensure and document:

1. dockstore tool launch --entry quay.io/ga4gh-dream/dockstore-tool-synapse-get --json hello_world_get.cwl.json sucessfully runs
- Perhaps move the hello_world_get.cwl.json to Dockstore from Synapse.
2. The output files are in datastore/launcher*/outputs/
- Perhaps move these output files to the original directory
3. dockstore tool launch --entry quay.io/ga4gh-dream/dockstore-tool-helloworld --json hello_world.cwl.json successfully runs
4. The output files are in datastore/launcher*/outputs/
- Perhaps move these output files to the original directory
5. dockstore tool launch --entry quay.io/ga4gh-dream/dockstore-tool-helloworld-checker --json hello_world_checker.cwl.json successfully runs 
6. dockstore tool launch --entry quay.io/ga4gh-dream/dockstore-tool-synapse-submit --json

**Comment by denis-yuen** [comment]
This looks complete
