### ISSUE TITLE
Dockstore documentation on "Releasing on GitHub" mismatched the tags

### ISSUE THREAD

**Issue by JWKaiqi** [ga4gh/dockstore#731]
Link: https://dockstore.org/docs/getting-started-with-cwl, and search for "Releasing on GitHub".

Note that the release tag 1.25-3 doesn't match with the release tag in the image, which is 1.25-6.

**Comment by denis-yuen** [comment]
Worked through new tutorial covering new quay.io interface at  staging.dockstore.org
Noticed some preexisting issues at  #798
