### ISSUE TITLE
Read json parameters from http

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#736]
### Desired behaviour

As a silly workaround, I have a script that downloads a parameter file over http. 
https://github.com/dockstore/batch_wrapper/blob/master/test.sh to run a Dockstore tool with a remote parameter file in one command (due to escaping issues). 

This feature should be added to the Dockstore CLI

**Comment by garyluu** [comment]
Works with:
 `./dockstore tool launch --entry quay.io/briandoconnor/dockstore-tool-md5sum:1.0.4 --json https://raw.githubusercontent.com/briandoconnor/dockstore-tool-md5sum/master/test.json`
and
`./dockstore workflow launch --entry github.com/briandoconnor/dockstore-workflow-md5sum:1.0.0 --json https://raw.githubusercontent.com/garyluu/dockstore-workflow-md5sum/develop/md5sum.cwl.json`
