### ISSUE TITLE
Test parameter file should fill based on last version

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#738]
## Feature Request

When adding a new version to a tool you have to manually set set the location of the 'Test Parameter Files' each time.

### Desired behaviour

If a test parameter file is defined on the last 'default branch' it should be copied to the new version if found to exists in same location of repository.  If the path is no longer valid warn user that it is no longer mapped.

### Environment (Browser or OS and Dockstore version)

UI 1.2.2

**Comment by garyluu** [comment]
I've actually started working on this feature already.  On my working build, I can set a default test CWL/WDL test parameter file path (similar to default CWL descriptor path) for each tool.  All new versions/tags upon refresh will automatically add that path to its list of test parameter files.

**Comment by denis-yuen** [comment]
see also #607 
It should be possible to set a default path akin to the default cwl path and default wdl path. After that, any additional test json defined can be merged as in the OP

**Comment by denis-yuen** [comment]
@garyluu  FYI, update this ticket

**Comment by garyluu** [comment]
Still in the process of testing the updated web service.  For new tools that are added via refresh all tools, currently "/test.json" is added as the defaultTestParameterFile for the tool as well as all its versions/tags.  I'm also currently updating UI2 to allow editing of the default test parameter file paths.  However, editing the default test parameter file path in a manual mode tool will not propagate the change to all its versions.  New tags/versions that are manually added will autofill with the default test parameter file path though.

**Comment by denis-yuen** [comment]
Related to #745 testing
