### ISSUE TITLE
Migrate Launch-With and Sidebar

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#744]
### Desired behaviour

This ticket covers finishing off the launch-with UI instructions and the remainder of the sidebar (add this, , sharing, source repositories, docker pull)

**Comment by denis-yuen** [comment]
Please migrate the DNAStack launch-with functionality as well
https://github.com/ga4gh/dockstore-ui/pull/174

**Comment by JWKaiqi** [comment]
The only thing left on this ticket is to try on a real server, sharing through services that would really check the URL

**Comment by JWKaiqi** [comment]
See #784 for follow-up
