### ISSUE TITLE
Migrate Add Tools, Refresh, and Publish

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#746]
### Desired behaviour

This covers migration of the Add Tools button, the "+" button per organization, refresh all tools, and publishing. A stretch goal that can be tackled as a bonus would be #210

**Comment by denis-yuen** [comment]
@garyluu  review this for completeness

**Comment by JWKaiqi** [comment]
Per organization "+" is left

**Comment by denis-yuen** [comment]
I believe that this has been demoed
