### ISSUE TITLE
Tabs on container page not clickable

### ISSUE THREAD

**Issue by adamnovak** [ga4gh/dockstore#75]
When you hover over the tabs on the container pages ("Info", "Labels", "Versions" and do on on, say, [this page](https://www.dockstore.org/containers/quay.io/briandoconnor/dockstore-workflow-pcawg-bwa-alignment)), the tab's box turns purple as soon as you hover over it, but only the actual text is clickable.

I spent a good few seconds wondering why the tabs weren't coming up when I clicked on them, until I worked out that, contrary to the visual feedback I was receiving, the box around the text wasn't actually clickable.

Please make the boxes themselves clickable, or make only the text provide feedback on mouseover.

**Comment by adamnovak** [comment]
This is rightly an issue on ga4gh/dockstore-ui, but that project doesn't have issue tracking.

**Comment by denis-yuen** [comment]
Took a brief look at this. Normal bootstrap tabs do not seem to display this behaviour (see https://angular-ui.github.io/bootstrap/ ). This seems to stem from an interaction between  bootstrap-sass-official and ```.nav > li > a {
  position: initial;
  display: initial;
  padding: initial;
}``` in ds-style-fix.scss

To investigate further.

**Comment by agduncan94** [comment]
Fixed in branch release 1.1
