### ISSUE TITLE
Free-text search

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#752]
### Desired behaviour

This is a placeholder for tackling free text search. 
This will give the search UI the ability to search descriptions and metadata using free-text search. This should allow for things like boolean queries and fuzzy searches.

**Comment by JWKaiqi** [comment]
Ability to search descriptions looks good, I think we're done barring the bug discovered during the demo. Next step will be to provide a way of searching the whole descriptor, see  https://dockstore.org/workflows/Barski-lab/biowardrobe_chipseq_se for a good example of a workflow that contains a lot of metadata.

**Comment by denis-yuen** [comment]
Demoed in general, break out individual bugs into their own tasks
