### ISSUE TITLE
Dockstore Primer updates

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#758]
### Desired behaviour

Place-holder for updating our Dockstore primer with information on ui2 and any search dependencies.

**Comment by denis-yuen** [comment]
Assigning this for @JWKaiqi  's final week. This will involve updating the the primer ( https://wiki.oicr.on.ca/display/SEQWARE/Dockstore+Primer ) and readme.md ( https://github.com/ga4gh/dockstore/blob/develop/README.md ) with documentation

Updates include
1) How to install + use kibana to support the tag clouds page (and where the tag clouds page is)
2) Updates for using and developing with ui2 including the build tool (angular-cli)
3) the best resources for learning angular 2
4) updating the search demo instructions

**Comment by denis-yuen** [comment]
@garyluu  adding you to this ticket since you'll want to double-check sure that Jennifer's last week of work is properly handed off and works in your hands

**Comment by denis-yuen** [comment]
@agduncan94  
To finish this off, please update the Dockstore primer as you encounter inconsistencies or holes during your re-orientation

**Comment by agduncan94** [comment]
I've added some documentation for how to setup dockstore with UI2 in the wiki primer.
