### ISSUE TITLE
Read-only DB messaging

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#760]
### Expected behaviour

A postgres database in read-only mode should pass messages back to the UI properly. 

### Actual behaviour

After setting read-only mode (http://longwayaround.org.uk/notes/read-only-postgres-database/), the UI just displays `[HTTP 500] Internal Server Error: [object Object]` on operations. In the web service log we can see messages like `ERROR: cannot execute INSERT in a read-only transaction` or `ERROR: cannot execute UPDATE in a read-only transaction` which would be more descriptive. 

### Environment (Browser or OS and Dockstore version)
DockstoreUI - 1.2.3
DockstoreApi - 1.2.3

**Comment by denis-yuen** [comment]
This is a more general issue, 500 errors in general should pass back more of the underlying information

**Comment by denis-yuen** [comment]
Webservice now reports some useful info. 
Looks like the UI doesn't report 500 errors though.

Reproduce by setting the DB to read-only after you have a good database setup with a login and tools visible. Then try to add labels or publish/unpublish. You will see failing requests, but no UI message indicating a failure of any kind. 

Working on #760

**Comment by agduncan94** [comment]
When I set the database to read only, the running webservice is still able to read and write. If I stop the webservice and try restarting it, then I get an error when I try to start it up since it seems like the webservice tries to write to the database during startup.

**Comment by denis-yuen** [comment]
Huh, I wonder if this is a side-effect ofusing hbm2ddl validate, what's the error message on start-up?

**Comment by denis-yuen** [comment]
Was able to test by just disabling index creation on start-up temporarily. 
Added a few more error conditions caught and displayed by the ui2

https://github.com/ga4gh/dockstore/pull/1090
https://github.com/dockstore/dockstore-ui2/
