### ISSUE TITLE
Pop-up info box in DAG diagram hides parts of the DAG diagram.

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#762]
### Minor UI issue

The when looking at the DAG for a workflow, if the user hovers their mouse over a node then a pop-up info box appears and hides most of the relevant content around it. See screenshot below.

It would be nice if there was a way to have the info in that pop-up box appear somewhere else, maybe in a fixed-size/location box off to the side that is not actually in the graph region?

![dockstore-dag-pop-up-infobox](https://cloud.githubusercontent.com/assets/10213802/26744195/e9ac8cd6-47b2-11e7-8920-cd3cddba159d.png)

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-488)
┆Issue Type: Story
┆Issue Number: DOCK-488

**Comment by denis-yuen** [comment]
It's transparent now at least
