### ISSUE TITLE
/containers/{containerId}/testParameterFiles swagger

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#764]
### Desired behaviour
/containers/{containerId}/testParameterFiles should have descriptorType listed as a required dropdown menu in swagger since it fails otherwise.  This applies to both put and delete.

**Comment by denis-yuen** [comment]
FYI @garyluu  as a part of your current work

**Comment by denis-yuen** [comment]
Working on staging.dockstore.org
