### ISSUE TITLE
Tag information displayed does not update upon saved changes

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#765]
### Expected behaviour
After modifying a tool's tag and saving changes, web service should be invoked to grab the new tool tag information.

### Actual behaviour
After modifying a tool's tag and saving changes, web service is not invoked.  The tag editor appears to have the changes applied but it may not be the case.  

### Steps to reproduce the behaviour 
- Have a registered tool in my tools
- Modify its tag
- Save changes
- Modify the tag back to the original but do not save changes (to fake modify)
- Press close instead
- Revisit the tag after clicking on other tools, other tags, etc

The tag that was modified does not show its changes.

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.3
DockstoreApi - 1.2.3

**Comment by denis-yuen** [comment]
No longer a thing on staging
