### ISSUE TITLE
Expose validation errors

### ISSUE THREAD

**Issue by buchanae** [ga4gh/dockstore#766]
## Feature Request 

I have a few invalid workflows, but I don't know why they're invalid. It would be useful if validation errors were clearly reported in the UI.

### Desired behaviour

Easy access to validation errors. Also, mark invalid workflows very clearly. It took me a few minutes to realize what was wrong.

### Environment (Browser or OS and Dockstore version)

Dockstore UI and API = version 1.2.3

These are the invalid workflows:
smc-rna-challenge/uhrigs-9609508/uhrigs-9609508
 smc-rna-challenge/uhrigs-9609502/uhrigs-9609502 
 smc-rna-challenge/uhrigs-8645625/uhrigs-8645625 
 smc-rna-challenge/uhrigs-8645601/uhrigs-8645601 
 smc-rna-challenge/uhrigs-8645203/uhrigs-8645203 
 smc-rna-challenge/uhrigs-8396553/uhrigs-8396553 
 smc-rna-challenge/rbierman-9608942/rbierman-9608942 
 smc-rna-challenge/rbierman-9608941/rbierman-9608941 

These all have something in common: they were designed in Seven Bridges and require rabix to run them. So if they're not easily supported, I'll understand.

┆Issue is synchronized with this [Jira Story](https://ucsc-cgl.atlassian.net/browse/DOCK-489)
┆Issue Type: Story
┆Fix Versions: Dockstore 1.6
┆Sprint: Seabright Sprint 5 Electric
┆Issue Number: DOCK-489

**Comment by denis-yuen** [comment]
Definitely a good idea

Note to implementer, see also #696 which has a similar issue with errors not being exposed in the UI

**Comment by denis-yuen** [comment]
This is also relevant for addition of hosted workflows which we validate in a few ways

**Comment by denis-yuen** [comment]
Requirements for a solution:
* when refreshing single workflows or editing single hosted workflows
  * include existing checks across CWL, WDL, Nextflow
  * with addition of #1734  and #1445 we might be able to do more sophisticated validation
* when refreshing multiple workflows in an organization (or globally)
  * should not abort refresh on workflows with invalid workflows, instead should continue on but ...
* UI
  * should show allow users to open up workflows with invalid versions and find out why they are invalid
  * will require storage of validation errors per version

**Comment by denis-yuen** [comment]
Looks more legit now. You will get validation messages that look like this kind of thing 
![screenshot from 2019-03-04 13-32-24](https://user-images.githubusercontent.com/1730679/53754463-01e58380-3e82-11e9-8459-4bb7b87b80dc.png)

The issue with Seven Bridges specifically is tracked separately in #1060
