### ISSUE TITLE
Update Validation Messages

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#767]
### Desired behaviour
Lots of validation messages need to be added to UI2.  Currently, there are only a 8 fields with a set of validation messages.

**Comment by denis-yuen** [comment]
Note to self: see what has validation and close if not applicable

**Comment by denis-yuen** [comment]
Notes: 
1) Dockerfile validation message not quite right, says "Invalid Dockerfile Path format. Dockerfile Path must begin with '/' and end with '/Dockerfile'. " but "/test.Dockerfile" and "/Dockerfile.test" are accepted as they should be. 
2) WDL Test Parameter File(s) has no message
3) Workflow path and label validation warnings use big red warnings, the other valdiations just use black text on the regular background. Seems inconsistent.

**Comment by coverbeck** [comment]
I tried 3 dialogs -- let me know if there are more I should test.

## Add Tag

```A Tag Name may only consist of alphanumeric characters and internal hyphens, periods and underscores.```
1. The label for the control is `Version Tag`, not `Tag Name`.
2. The word `and` is in there twice; I suggest `A Tag Name may only consist of alphanumeric characters, internal hyphens, periods and underscores.`

```Invalid Git Reference format. An Git Reference path may only consist of alphanumeric characters, '-' and '_', with interior '/' and '.' separators.```

1. Should be `A Git Reference...`.

```Invalid Descriptor Path format. Descriptor Path must begin with '/' and end with '*.cwl', '*.yml', or'*.yaml'.```

1. No space after `or` in `or'*.yaml`
2. I would lean towards not having the asterisks, although I can see why you do, to indicate something must go before the `.cwl`. 

## Register Tool

```The namespace and name of the image repository, separated by a '/'. Use '_' for an empty namespace. Currently, only Quay.io and Docker Hub are supported third-party platforms.```

1. Is this correct? The dropdown also shows Gitlab and Amazon ECR, but the error message doesn't mention them. If it's correct, I suppose makes sense, although what am I supposed to do with the other two choices in the dropdown?; if we support all 4, then I don't think that should be part of the message at all.

* No validation for Docker registry path and tool name

## Register Workflow

```Source Code Repository Path is too short. (Min. 3 characters.) The namespace and name of the Git repository, separated by a '/'. Currently, only GitHub, Bitbucket and GitLab are supported third-party platforms.```

1. Similar to my previous comment, I don't think you should have `Currently, only GitHub, Bitbucket and GitLab are supported third-party platforms.` -- that's informational, not an error, and the dropdown already indicates what platforms are supported.

**Comment by denis-yuen** [comment]
Looks much improved
