### ISSUE TITLE
Dockstore did not find Dockstore.cwl file from GitHub

### ISSUE THREAD

**Issue by Welliton309** [ga4gh/dockstore#768]
## Bug Report

I am trying to manually add the [Rqc software](https://bioconductor.org/packages/release/bioc/html/Rqc.html) on Dockstore.
I created a public [GitHub repository](https://github.com/labbcb/dockstore-rqc) that provides the `Dockerfile` and `Dockstore.cwl` files.
I used [Docker Hub](https://hub.docker.com/r/welliton/rqc/) to build a Docker image.

### Expected behaviour

Info fields (such as Author) filled with data from [Dockstore.cwl](https://github.com/labbcb/dockstore-rqc/blob/master/Dockstore.cwl#L15).
Tool ready to Publish on system.

### Actual behaviour

The UI gave me the error message "No description associated with this tool." (see figure below).

![dockstore_error](https://user-images.githubusercontent.com/645272/26942339-0e548c24-4c58-11e7-99fa-0fb0d6782fa2.PNG)

### Steps to reproduce the behaviour 

I filled the "Registry Tool" form with the information showed by the figure below.

![dockstore_add_rqc](https://user-images.githubusercontent.com/645272/26942361-23cb7aa4-4c58-11e7-9370-e7e5d2f9809f.PNG)

### Environment (Browser or OS and Dockstore version)

Google Chrome version 59.0.3071.86 64 bits.
Windows 10.

**Comment by denis-yuen** [comment]
Hi
I don't see any obvious errors comparing with https://dockstore.org/containers/registry.hub.docker.com/francescof/pcawg_delly_workflow

Do you see the CWL descriptors in the "Files" tab?

**Comment by Welliton309** [comment]
The "Files" tab does not show any information for "Dockerfile" and "Description files".

![dockstore_files](https://user-images.githubusercontent.com/645272/26948051-687ad132-4c6b-11e7-9cc4-7ebe308bc14d.PNG)

**Comment by denis-yuen** [comment]
Ah, I think I know what's going on. 

Since this is a manually added tool from Docker Hub, go to versions and hit "Add Tag".
You will need to fill in the version tag (the version number on Docker Hub) and the git reference (the version number on GitHub). After you hit Add Tag. it should fill out the description and author fields.

**Comment by Welliton309** [comment]
It worked, thank you!
I created a tag in GitHub. The DockerHub automatically created Docker image for the tag.
https://dockstore.org/containers/registry.hub.docker.com/welliton/rqc

**Comment by denis-yuen** [comment]
Looks good!
