### ISSUE TITLE
TagEditor's Dockerfile folder and extension

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#772]
### Expected behaviour
Dockerfile's form validation error message to be correct.

### Actual behaviour
Dockerfile's form validation error message is not clear/correct.  A pattern like:
/test/Dockerfile.test should be allowed but it is not

### Steps to reproduce the behaviour 
- Go to tool tag editor
- Edit a tag's Dockerfile to be /test/Dockerfile.test
- Observe the error that appears.

### Environment (Browser or OS and Dockstore version)
UI2

**Comment by denis-yuen** [comment]
FYI, this is actually reversed. 
`/test/test.Dockerfile` should be allowed, not `/test/Dockerfile.test`

**Comment by denis-yuen** [comment]
NVM, duplicate of #823
