### ISSUE TITLE
Tag Editor's Descriptor Extension

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#773]
### Expected behaviour
Descriptor form validation error to show the correct descriptor extensions pattern allowed.  See UI2 for the correct descriptor error messages/pattern

### Actual behaviour
Descriptor form validation errors shows the wrong descriptor extensions for CWL and WDL.  

### Steps to reproduce the behaviour 
- Go to tag editor
- Edit a tag to have wrong CWL and WDL descriptors
- Observe the error message that appears.

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.3-1-gd39f3b2
DockstoreApi - 1.2.3

**Comment by denis-yuen** [comment]
Seems obsolete
