### ISSUE TITLE
Tag Editor Test Parameter Files Typo

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#774]
### Expected behaviour
Tag editor's form validation error message for test parameter files to be grammatically corrected

### Actual behaviour
Upon incorrect pattern, it displays: 
"Invalid Test parameter file format. Test parameter file path must begin with '/' and end with end with '*.json', '*.yml', or '*.yaml'. "

### Steps to reproduce the behaviour 
- Go to tag editor by edit
- Try adding /test
- Observe the error message that appears

### Environment (Browser or OS and Dockstore version)

DockstoreUI - 1.2.3-1-gd39f3b2
DockstoreApi - 1.2.3

**Comment by JWKaiqi** [comment]
Keep an eye out for this when editing is added to Workflow versions

**Comment by denis-yuen** [comment]
Merging with #1012
