### ISSUE TITLE
Setting of CWL test file not taking

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#777]
## Bug Report

Setting a CWL test parameter file appears to work in the version edit dialog but on accessing through files the content is not displayed.  Leaving 'My Tools,  returning and opening the edit dialog shows the CWL test file as not defined.

### Expected behaviour

Should retain the path and show content of file in 'Files' -> 'Test Parameter Files'

### Actual behaviour

Loss of path or failure to save in persistent state.

### Steps to reproduce the behaviour

Add a CWL test parameter file to a project where not defined, exit 'My Tools' and try to view in general are.  Returning to 'My Tools' results in the CWL json file path no being shown on return.

**Comment by denis-yuen** [comment]
I think I've encountered this, the dialog box doesn't ensure that the path you selected for test json is real. So you can save a path to a file that doesn't exist. This can be tricky because the file both has to exist and has to exist in the specific branch or tag associated with that version.

**Comment by keiranmraine** [comment]
The path definitely exists in the tag.  Extracted `/examples/bamtofastq.json` from the repo URL:

https://github.com/cancerit/dockstore-biobambam2/blob/1.0.0/examples/bamtofastq.json

If you add it, exit the dialog, let it refresh and go back in to the same 'edit' dialog it is still held.  But if you leave the 'My Tools' area and then go back it is cleared.

It's this tool: https://dockstore.org/containers/quay.io/wtsicgp/dockstore-biobambam2/bamtofastq

**Comment by denis-yuen** [comment]
Hi,
You're right, I've confirmed that this is indeed an issue with this tool. 
The web-service seems to be rejecting the json file path although it does exist. 
We'll look into this further.

**Comment by garyluu** [comment]
The descriptor is '/cwls/bamtofastq.cwl'.  Dockstore is setting the working directory as 'cwls'.  Even though the test parameter file is set as '/examples/bamtofastq.json', Dockstore is looking for it in GitHub as 'cwls/examples/bamtofastq.json'

Some solutions:
- Move the JSON so it is 'cwls/examples/bamtofastq.json'
- Modify Dockstore web service to ignore the concept of working directory
- Modify Dockstore web service to search in both locations (with working directory, then fall back to absolute)
- Modify Docsktore web service to search in the working directory if the test json does not have "/" as the prefix.  Search absolute path when it does have "/".  This also requires the Dockstore-UI form validation to change.

**Comment by denis-yuen** [comment]
I suspect whats going here is that paths get resolved to the working directory inside CWL files and WDL files. For example when you import files, it sounds like some of this code was re-used directly for test parameter files that doesn't make too much sense. 

I think the last option makes the most sense. Search the working directory for the descriptor when there is no `/` and the absolute path when it does. It would also be nice to display the resolved path in some way. i.e. "The path we're going to look in for this relative path is relative to /cwl based on your descriptor" but more succinctly

**Comment by denis-yuen** [comment]
FYI, the last solution in the above list was been implemented for the back-end. 
I think it also makes sense to display the resolved path in way or make an info button that says both absolute and relative paths can work.

**Comment by denis-yuen** [comment]
Confirmed on staging.dockstore.org 
( https://staging.dockstore.org/containers/quay.io/denis_yuen/dockstore-biobambam2 for now )
