### ISSUE TITLE
Browse by organisation should be sorted

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#779]
## Feature Request

The link https://dockstore.org/organizations isn't sorted

### Desired behaviour

Sorted list so easier to scan

**Comment by denis-yuen** [comment]
@JWKaiqi  I think this can be taken into your design for organizational search

**Comment by JWKaiqi** [comment]
This should be sorted in ui2, but we do need to implement links to searches

**Comment by denis-yuen** [comment]
Demoed previously
