### ISSUE TITLE
Container Version drop down under the Files|Dockerfile and Descriptor Files tab seems to update very slowly

### ISSUE THREAD

**Issue by wshands** [ga4gh/dockstore#788]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Bug Report
The correct version for the tool quay.io/ucsc_cgl/rnaseq-cgl-pipeline  '3.3.4-1.12.3' selected in the Versions tab the Container Version drop down under the Files|Dockerfile and Descriptor Files tab seems to update very slowly

![screen shot 2017-06-26 at 11 28 04 am](https://user-images.githubusercontent.com/3650921/27554218-93726c4c-5a62-11e7-97a3-cd585d7eb21b.png)

![screen shot 2017-06-26 at 1 29 22 pm](https://user-images.githubusercontent.com/3650921/27559210-90b3a4b4-5a74-11e7-8754-85a4ba87a76b.png)

### Expected behaviour
The Container Version drop down would hold all the verified versions of the tool within a second or two of selecting the Dockerfile or Descriptor File tab

### Actual behaviour
The Container Version drop down at first holds only master, latest and an older version of the tool, then after a minute or so updates to include all the versions; perhaps it could be speeded up?

### Steps to reproduce the behaviour 

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

### Environment (Browser or OS and Dockstore version)

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website)

**Comment by denis-yuen** [comment]
This seems fixed in 1.3.0 although we still need #992 for an optimal experience
