### ISSUE TITLE
Output provisioning silently fails if json badly constructed.

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#789]
## Bug Report

Using [dockstore-cgpmap](https://dockstore.org/containers/quay.io/wtsicgp/dockstore-cgpmap) as an example.

If the output location parameters are badly defined the cwltool and dockstore both complete successfully.

E.g. Expected output mapping:

```json
{
  ...
  "out_bam": {
    "path": "/tmp/mapped.bam",
    "class": "File"
  },
  ...
}
```

Bad output mapping

```json
{
  ...
  "out_bam": "/tmp/mapped.bam",
  ...
}
```

### Expected behaviour

Should error

### Actual behaviour

Data is written to cwl output folder (`datastore/launcher-2e89a1d4-febb-43ca-afc6-7f4a1415968d/outputs/`) but not provisioned out.  No errors are thrown to indicate failure to capture the files.

### Steps to reproduce the behaviour 

Use the default json but change the output params to be plain paths instead of objects:

```json
{
  "reference": {
    "path": "ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/core_ref_GRCh37d5.tar.gz",
    "class": "File"
  },
  "bwa_idx": {
    "path": "ftp://ftp.sanger.ac.uk/pub/cancer/dockstore/human/bwa_idx_GRCh37d5.tar.gz",
    "class": "File"
  },
  "bams_in": [
    {"class": "File",
      "path": "ftp://ngs.sanger.ac.uk/production/cancer/dockstore/cgpmap/insilico_21.bam"}
  ],
  "cram": false,
  "sample": "test",
  "out_bam": "/tmp/mapped.bam",
  "out_bai": "/tmp/mapped.bam.bai",
  "out_bas": "/tmp/mapped.bam.bas",
  "out_md5": "/tmp/mapped.bam.md5",
  "out_met": "/tmp/mapped.bam.met",
  "out_maptime": "/tmp/mapped.bam.maptime",
}
```

Output:

```
$ dockstore tool --debug launch --entry quay.io/wtsicgp/dockstore-cgpmap:2.0.3 --json run.json
...
	Workflow end: Tue Jun 27 10:50:54 UTC 2017
	[job temp2977869313535061161.cwl] completed success
	Final process status is success

Saving copy of cwltool stdout to: /tmp/wr_cmd/cwd/./datastore/launcher-2e89a1d4-febb-43ca-afc6-7f4a1415968d/outputs/cwltool.stdout.txt
Saving copy of cwltool stderr to: /tmp/wr_cmd/cwd/./datastore/launcher-2e89a1d4-febb-43ca-afc6-7f4a1415968d/outputs/cwltool.stderr.txt

$ echo $?
0
```

### Environment (Browser or OS and Dockstore version)
Dockstore 1.2.3

**Comment by denis-yuen** [comment]
@keiranmraine  FYI, I think this request partially conflicts with some of the GA4GH-DREAM workflows which basically expect to work like cwltool, dumping files into the current working directory.

I think I'm going to change this to display a big warning if an output location is not found and provision by default to the current working directory ala cwltool. Hopefully that works for your use-case.

**Comment by denis-yuen** [comment]
As an update, 1.2.4 behaves in the following manner
```
$ cat test-missing.json
{
    "input_file": {
        "class": "File",
        "path": "md5sum.input"
    }
}
$ cat test-malformed.json
{
  "input_file": {
        "class": "File",
        "path": "md5sum.input"
    },
    "output_file": "/tmp/md5sum.txt"
}
$ dockstore tool launch --entry  quay.io/briandoconnor/dockstore-tool-md5sum    --json test-malformed.json | grep WARNING
WARNING: Output malformed for "output_file" provisioning by default to working directory
```
