### ISSUE TITLE
Publish vs. Register... pick a term and be consistent in CLI and Web

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#79]

**Comment by agduncan94** [comment]
These are the definitions we will use for each term:
Register - add container to Dockstore
Publish - make a registered container public (visible to all users)

**Comment by agduncan94** [comment]
The isregistered and ispublic columns of the tool table don't seem to mean what we think they would mean.  ispublic refers to if a repo is public on quay, and is registered is used to see if a container is published on Dockstore (using definition of publish mentioned in my above comment).

I believe the isregistered can be removed completely, and ispublic replaced with ispublished. This will prevent future confusion between how we store tools and the way quay stores repos.

ispublished will just determine if the tool is published.  If a tool is registered on the site then it will be in the DB anyways, so it is a redundant field.

**Comment by denis-yuen** [comment]
I think we're consistent with this nomenclature now, in user-facing interfaces, if not totally in code.
