### ISSUE TITLE
File staging changes filenames

### ISSUE THREAD

**Issue by keiranmraine** [ga4gh/dockstore#791]
## Bug Report

File names presented within CWL may not match those of source file.

### Expected behaviour

Filenames with no unusual characters should not be modified.

### Actual behaviour

Filenames like `COLO-829.bam` are changed to `COLO829.bam`

### Steps to reproduce the behaviour 

Use a file with a hyphen as an input, `ls -l datastore/launcher-*/inputs/*/`

Confirmed occurs on local files and s3cmd plugin.

### Environment (Browser or OS and Dockstore version)

Dockstore: 1.2.3
Ubuntu: Trusty

**Comment by denis-yuen** [comment]
This looks like a misunderstanding that crept in. 
We were sanitizing filenames when this should be done for individual file provisioning plugins when they can't handle particular file names, not across the board.

**Comment by denis-yuen** [comment]
Fixed in 1.2.4 and available on staging.dockstore.org
