### ISSUE TITLE
Incorrect detection of tools

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#800]
### Expected behaviour

Go to https://dockstore.org/workflows/ENCODE-DCC/pipeline-container/encode-mapping and see a list of tool that it uses just like https://dockstore.org/workflows/BD2KGenomics/dockstore_workflow_cnv

### Actual behaviour

Go to https://dockstore.org/workflows/ENCODE-DCC/pipeline-container/encode-mapping 
The Tools tab displays no tools. However, the individual tools are registered on Dockstore, for example https://dockstore.org/containers/quay.io/gabdank/mapping

I've also verified that this is some issue relating to the web service not returning the correct tools to display to the UI

### Environment (Browser or OS and Dockstore version)

1.2.3

**Comment by agduncan94** [comment]
This is likely do to us not parsing hints correctly. This is fixed in develop but is not on staging yet. Also the workflow referenced is now at https://dockstore.org/workflows/github.com/ENCODE-DCC/pipeline-container/encode-mapping-cwl

**Comment by agduncan94** [comment]
I tested this on devleop and the issue is dealt with.
![screenshot from 2018-04-16 09-35-32](https://user-images.githubusercontent.com/6331159/38812168-8b687526-4159-11e8-8462-016f1f2b534e.png)

**Comment by denis-yuen** [comment]
This seems better now on staging.dockstore.org
