### ISSUE TITLE
Search Ideas

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#813]
### Desired behaviour
Some search ideas:
- Break link between UI values and elastic search value
- Linkable searches (be able to have a URL that links to the search results/query)
- Scoring function (scoring function to determine the order of entries displayed after search query)
- Autocomplete (auto-complete certain fields like tags or entries)
- Tag cloud (for labels, entries, etc...)
- Different types of sorting (for example, sort authors alphabetically vs frequency)
- Sorting categories altogether (should verified and verified source be grouped together or even nested)
* hint that categories can be expanded or collapsed
*mock up, what would an advanced search for text look like
  * Google Advanced search as an example, I think we need either a fuzzy search and search in "quotes"

**Comment by denis-yuen** [comment]
Most of these are now complete including automcomplete, tag cloud, advanced search, and expanding/collapsing categories.
