### ISSUE TITLE
Branches deleted from github still appear in dockstore UI

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#816]
## Bug Report
I deleted a branch from my repository (https://github.com/ICGC-TCGA-PanCancer/OxoG-Dockstore-Tools) but the branch still appears valid in dockstore.

### Expected behaviour

When a branch is deleted from github, should be able to click the "Refresh" button and then after the refresh process completes, the branch that was deleted should no longer be shown in dockstore.

### Actual behaviour

The branch is still visible, as if it were still there in github.

### Steps to reproduce the behaviour 

1. Create a workflow.
2. Create some branches with changes - verify that after you Refresh in dockstore, the changes are in dockstore.
3. Delete some of the branches in github
4. Refresh the workflow in dockstore.
5. Check to see if the branches still appear in dockstore.

### Environment (Browser or OS and Dockstore version)

Ubuntu 16.04 using Vivaldi browser.

**Comment by denis-yuen** [comment]
Working in staging.dockstore.org for workflows at least
