### ISSUE TITLE
Discourse custom title and body

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#818]
## Feature Request 
Discourse upgrade

### Desired behaviour
Modify the title and body of new topics created by Discourse.  To modify the title, some options to consider are:
- Serve the pages with the correct topic title in the html title tag (without modifying it afterward with JS/TS).  This may involve either server side rendering or some clever use of Angular JS or another library.  Whether the title is correct can be tested using Nokogiri locally.
- Extend Dockstore web service to have an RSS/Atom feed which allows Discourse to crawl Dockstore for info.
- Extend Dockstore web service by using the Discourse API to create topics for each tool/workflow with a non-existing topic ID and then passing that ID back to the dockstore-ui(2) client's embedded Discourse

**Comment by denis-yuen** [comment]
Hi @garyluu 
Make sure to include links to the various Discourse docker repo,  the relevant Discourse crawler code, and short gist or similar of a Ruby script for local testing so that we have somewhere good to start when picking this back up.

**Comment by garyluu** [comment]
See this link for how to create a topic post with the API:  http://docs.discourse.org/#tag/Topics%2Fpaths%2F~1posts%2Fpost   

See this link for how to run discourse locally: https://github.com/discourse/discourse/blob/master/docs/VAGRANT.md

Run the following script or similar using 'ruby <script>.rb' to test what Nokogiri sees:

```
require 'open-uri'
require 'nokogiri'
doc = Nokogiri::HTML(open("http://localhost:9000/containers/quay.io/A2/a"))
if doc
  title = doc.at('title')
  puts title
end
```



```

**Comment by denis-yuen** [comment]
This looks like we'll need to go the route of pre-creating threads via the API. 
Basically this means 
1) Create threads on Discourse when publishing a tool or workflow
2) Store the topic id in the webservice
3) Replace Disqus with Discourse by pulling back topics based on the topic id

**Comment by denis-yuen** [comment]
We ended up testing RSS which serves to work pretty well as an alternative to crawling dockstore.org for content or pre-creating threads. 

Last step seems to be step 4) of https://meta.discourse.org/t/embedding-discourse-comments-via-javascript/31963

**Comment by denis-yuen** [comment]
Bumping up priority since we actually aren't replacing disqus in UI2, we haven't implemented disqus in ui2 all together

**Comment by agduncan94** [comment]
The comments have been added to the individual tool/workflow pages. Old discuss comments still need to be transferred.

**Comment by denis-yuen** [comment]
Looks functional in staging.dockstore.org

Old disqus comments have been imported using some scripting a while back to https://discuss.dockstore.org/t/dockstore-disqus-experimental-import/22/13 but its all messed up due to the issue with Disqus not really tracking which link is associated with each comment. There's not too many comments, so we should be able to divvy them up and manually move the comments to the right tool in ui2 after the main release of code.
