### ISSUE TITLE
ui2 elastic search, verified filter is showing both verified and non-verified entries.  

### ISSUE THREAD

**Issue by JWKaiqi** [ga4gh/dockstore#821]
For instance:
![issue1](https://user-images.githubusercontent.com/13563753/28126644-0f7ccb7e-66f8-11e7-947a-56eb685ba912.jpg)

Either update the elastic search query or the web-service to resolve this problem.

**Comment by JWKaiqi** [comment]
Still present during demo

**Comment by denis-yuen** [comment]
Demonstrated fixed in demo
