### ISSUE TITLE
Allow docker file with name other than Dockerfile

### ISSUE THREAD

**Issue by wshands** [ga4gh/dockstore#823]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Feature Request 
I build Docker images and push them to Quay.io. The Dockerfiles are constructed from a template by a script as it builds the images so the 'Dockerfile' is not present on Github. The Dockstore UI will not allow me to save the path to the dockerfile.template in the Edit Version Tag dialog because it wants a file named 'Dockerfile' to exist in the Github repository. I suppose the only reason the Dockerfile is needed in my case is to display it in the Files | Dockerfile window. 
### Desired behaviour
I would like to enter a file name other than 'Dockerfile' for the Dockerfile edit box in the Edit Version Tag dialog or leave it out altogether. 

![image](https://user-images.githubusercontent.com/3650921/28128934-3ed2121a-66e6-11e7-993a-b2fa94581b15.png)

**Comment by denis-yuen** [comment]
Related to #772 

Leaving it out altogether would be less than desirable, part of the philosophy of Dockstore is that users should have some idea how a Docker image was created, even if that isn't perfect. 

A different pattern should be fine, we can allow
`/*/Dockerfile.*` and `/*/*.Dockerfile`

**Comment by denis-yuen** [comment]
Looks like this works on staging.dockstore.org
