### ISSUE TITLE
"Entry not found" dockstore tool error 

### ISSUE THREAD

**Issue by nathankw** [ga4gh/dockstore#824]
Thanks for submitting your feedback to Dockstore. 
Please fill in the appropriate section depending on whether you want to submit a feature request or a bug report. 

## Bug Report
I've been following along the dockstore tutorial and am trying to make a docstore tool for a fork of dockstore-tool-bamstats as mentioned in the tutorial. Executing the dockstore clientcommand to generate a JSON template (which I copied from my dockerstore tool from the UI) always returns the exception "Entry not found". 

dockstore tool convert entry2json --entry registry.hub.docker.com/nathankw/dockstore-tool-bamstats:develop > Dockstore.json
io.swagger.client.ApiException: Entry not found

### Actual behaviour
io.swagger.client.ApiException: Entry not found

### Steps to reproduce the behaviour 
Fork dockstore-tool-bamstats. 
Create new release in GitHub web interface with the tag 11.1 (random tag name). 
Create automated build in Docker Hub. In the build settings, set the following fields:
  Type -> Branch
  Name -> develop
  Dockerfile Location -> /
  Docker Tag Name -> develop

Now register tool on Dockstore: I set "Source Code Repository" to GitHub with the value nathankw/dockstore-tool-bamstats. I set "Image Repository" to "Docker Hub" with the same value "nathankw/dockstore-tool-bamstats". I then added a tag in my Dockstore tool and set  "Version Tag" to "develop" and "Git Reference" to "develop". I can see that it found the Dockerfile and CWL file, and the Info tab pulls up all the values. 

(Attach tool/workflow documents or links where applicable to help us reproduce your issue)

Docker Hub repository: nathankw/dockstore-tool-bamstats. I didn't make my dockstore tool public, but let me know if should so you can see it. 

### Environment (Browser or OS and Dockstore version)
The version of dockstore client is 1.2.3

Describe your operating system (relevant for CLI and launcher) or your web browser (name and version, relevant for the Dockstore website) 

I'm running on Mac OS X Yosemite. .

**Comment by nathankw** [comment]
![version_tab](https://user-images.githubusercontent.com/6232664/28133668-94fda1ea-66f5-11e7-848b-6a6cec044da2.png)
![info_tab](https://user-images.githubusercontent.com/6232664/28133667-94f5cce0-66f5-11e7-854e-ce22d67c38e1.png)

**Comment by nathankw** [comment]
![dhub_tags](https://user-images.githubusercontent.com/6232664/28133964-6aa9756c-66f6-11e7-9f7d-49a71525146d.png)
![dhub_build_settings](https://user-images.githubusercontent.com/6232664/28133965-6aaa1c92-66f6-11e7-9a5c-7f993a80048f.png)

**Comment by denis-yuen** [comment]
Hi, 
Try again after publishing/making the tool public. 
That particular command won't actually work unless the tool is public, we should probably make that more clear

**Comment by nathankw** [comment]
I see, thanks!
