### ISSUE TITLE
Advanced indexing 

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#828]
### Desired behaviour

This will come in two parts

1) Benchmarking. What happens when we have  1000, 10,000, 100,000 tools and workflows with users constantly changing things? How long will it take to do a full-reindex? 

This will probably need a data generation utility to simulate lots of tools and workflows. Maybe even load (such as many users changing things).

2) Depending on whether we decide to re-generate on a set schedule (every 10 mintues? every hour?) or do batched updates (accumulate a certain number of changes?), we need to ensure that the index updates on all user operations that can affect content. Label adding/removal, publish/unpublish, changing paths, setting defaults, etc.  Add an Elastic Manager class that can keep track of requests for updates being made and update only the documents that need updating rather than all documents

**Comment by garyluu** [comment]
1.  I was doing: create, refresh, reindex, and add labels for each tool from 1 tool to 1000 tools.  The first reindex takes 929 ms, the next reindex takes 592 ms, then 230 ms.  Aside from 1 outlier, it appears the full re-indexing is trending down (for some reason) as the number of tools increased.  I have a chart to illustrate these timings

**Comment by denis-yuen** [comment]
Note: a potentially incomplete list of operations which will need inform the index about changes
1. Label editing 
2. Refresh (both individual tools and workflows or across the board)
3. Editing default versions
4. Adding new test json 
5. Changing file paths

Note that this can be done in the actual operations, or potentially done by looking at DB timestamps

**Comment by denis-yuen** [comment]
So on staging. it should be possible to run both the hotfix 1.2.7 as the "default" webstie (using 443) and run a version of develop (1.3) on a different set of ports. The other possibility is just run 1.3 on CancerCollaboratory

**Comment by denis-yuen** [comment]
Seems to basically function and update on tool + workflow publish, unpublish + labels for staging.dockstore.org. 
Will break out smaller issues into their own tickets.
