### ISSUE TITLE
Make obvious copyright notice for ui

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#833]
### Desired behaviour

Our GitHub repos are marked with the Apache V2 license, but the compiled and published UI is not. Add a notice of this in a reasonable location.

**Comment by agduncan94** [comment]
How exactly do we want this? We have some sort of icon/text in the footer linking to the copyright on github?

**Comment by denis-yuen** [comment]
Yeah, some small unobstrusive link to the license for the UI and/or WS license like https://github.com/ga4gh/dockstore/blob/1.2.10/LICENSE

**Comment by denis-yuen** [comment]
On staging.dockstore.org
