### ISSUE TITLE
Workflow file provisioning fails

### ISSUE THREAD

**Issue by Jeltje** [ga4gh/dockstore#835]
## Bug Report
This is for the GA4GH Dream Challenge workflow [bcbio_NA12878-chr20](https://github.com/ga4gh/dockstore/files/1163534/main-NA12878-platinum-chr20.cwl.txt), which runs fine with `cwltool=1.0.20170217172322`
[bcbio.json](https://github.com/ga4gh/dockstore/files/1163535/bcbio.json.txt)

### Expected behaviour
Stage files in `/datastore` directory so that they can be retrieved

### Actual behaviour
File gets hardlinked to `()/datastore/launcher-ef66914e-b880-4d56-b1dc-9432d92afd49/inputs/f7e25976-8b3b-4460-929c-787d64ed8015/hg38.fa.fai`
but that's not where the runner looks when it's trying to run:
`No such file or directory: '()/datastore/launcher-ef66914e-b880-4d56-b1dc-9432d92afd49/biodata/collections/hg38/seq/hg38.fa.fai`
[dockstore3.err.txt](https://github.com/ga4gh/dockstore/files/1163546/dockstore3.err.txt)
[dockstore3.log.txt](https://github.com/ga4gh/dockstore/files/1163547/dockstore3.log.txt)

The reason appears to be that the workflow's JSON specifically states the location of `secondaryFiles`:
```
            "class": "File",
            "path": "biodata/collections/hg38/seq/hg38.fa",
            "secondaryFiles": [
                {
                    "class": "File",
                    "path": "biodata/collections/hg38/seq/hg38.fa.fai"
                },
                {
                    "class": "File",
                    "path": "biodata/collections/hg38/seq/hg38.dict"
                }
            ]
```
Dockstore apparently sees this as a reason to go look for secondaryFiles not in the same directory as the primaryFile.

To verify this, I removed this secondaryFile section from the input JSON - there are many more so I expected this to lead to a similar issue with another file. 
[my.json.txt](https://github.com/ga4gh/dockstore/files/1163539/my.json.txt)
But no, this time it dies with 

`No such file or directory: '(...)/datastore/launcher-63977c42-f73d-4d3f-bff1-fc8d04b80c2f/biodata/giab/na12878/NA12878-platinum-chr20.bam'`
This is a regular (not secondary) file, and this time it's nowhere to be found in `launcher-63977c42-f73d-4d3f-bff1-fc8d04b80c2f/inputs`

[dockstore4.err.txt](https://github.com/ga4gh/dockstore/files/1163544/dockstore4.err.txt)
[dockstore4.log.txt](https://github.com/ga4gh/dockstore/files/1163545/dockstore4.log.txt)

### Steps to reproduce the behaviour 

`dockstore workflow launch --local-entry main-NA12878-platinum-chr20.cwl --json my.json`

### Environment (Browser or OS and Dockstore version)

`Dockstore 1.2.4` - while writing this I noticed there has been an upgrade, so I did a quick test with `1.2.5` and found the same issues.

**Comment by denis-yuen** [comment]
Interesting, I ran into this, didn't have a chance to look deeply had thought that this was #563 
Thanks for the additional info

**Comment by denis-yuen** [comment]
bcbio is now functional with Dockstore 1.2.10 as per https://www.synapse.org/#!Synapse:syn10876714
