### ISSUE TITLE
User controls on Workflows page

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#836]
## Feature Request 
Due to #729 , there are a large amount of stubs in the "My Workflows" page.  Currently, it is much easier to find our own workflows in the normal workflows page.

### Desired behaviour
Due to the above, it would be nice to have the user control (Publish, Refresh, etc) on the Workflows page too.

**Comment by denis-yuen** [comment]
This seems like a work around, if it is easier to find workflows in Workflows than "My Workflows" then we should improve "My Workflows" in the first place to make it more useful.

**Comment by JWKaiqi** [comment]
Add a mode (maybe even by default) to show only published workflows in ""My Workflows". Experiment with a few options like this (show published, or show published and refreshed) or just hide stubs and see what it looks like

**Comment by denis-yuen** [comment]
Addressed by #1094
