### ISSUE TITLE
Permalinks to search results

### ISSUE THREAD

**Issue by JWKaiqi** [ga4gh/dockstore#839]
### Desired behaviour

When clicking different facets in the search page, the URL should change and be shareable to other people. Long term, may even want to create short URLs, but in first phase, let's make them linkable. 
URLs to do not necessarily need to be human-readable.

**Comment by denis-yuen** [comment]
1. Use a query parameter to store the filter settings, doesn't have to be completely human-readable as shown on google maps or the icgc portal
2. Use a URL shortener to distribute simpler URLs for sharing in papers and other news

**Comment by agduncan94** [comment]
This has been completed, though the URL shortener has not been implemented. Is this something we want still?

**Comment by denis-yuen** [comment]
I believe so, at least as an option. It can be split out into a separate ticket for tracking purposes though.

**Comment by agduncan94** [comment]
Made a new issue for URL shortening.
