### ISSUE TITLE
Advanced Elasticsearch Fixes

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#851]
### Expected behaviour
Upper case and symbols should be able to be entered into the advanced search and regular search field

### Actual behaviour
Upper case and symbols do not work when entered into advanced search and regular search field.  No results are returned.  Current workaround is to convert everything to lower case and not use symbols when entering into those fields.

### Environment (Browser or OS and Dockstore version)
UI2

**Comment by denis-yuen** [comment]
Implemented in https://github.com/dockstore/dockstore-ui2/pull/70
