### ISSUE TITLE
Swagger API on UI2 is using localhost

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#852]
### Expected behaviour
Swagger API should be using Dockstore.API_URI

### Actual behaviour
Swagger API on UI2 is using localhost

### Environment (Browser or OS and Dockstore version)

UI2

**Comment by garyluu** [comment]
I just fixed this in feature/swaggerFix

**Comment by denis-yuen** [comment]
Looks fixed as of 2.0.0-alpha.0 at least
