### ISSUE TITLE
Fix enableProd() in search page (console error)

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#853]
### Desired behaviour
When Elasticsearch results are being loaded, there should be an indicator showing that it is loading.

### Expected behaviour
enableProd() should not be in the search component ts file

### Actual behaviour
enableProd() is in the search component ts file

### Environment (Browser or OS and Dockstore version)

UI2

**Comment by denis-yuen** [comment]
@garyluu please elaborate, this is kind of confusing since its a feature request and a bug report?

**Comment by garyluu** [comment]
I think this includes two parts.  The indicator for the elastic search loading should be a feature.  However, there is a bug with enableProd() which is likely what causes it to load slowly.

**Comment by denis-yuen** [comment]
Note, first section is complete. Second section remains and needs significant work.

**Comment by denis-yuen** [comment]
Looks good now on staging.dockstore.org
