### ISSUE TITLE
TRS validation service

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#858]
### Desired behaviour

Tool Registry Schema validation service. We need one of these, may be able to reuse code from 
#814 or #376 

A rudimentary badge might be useful as well (i.e. something like https://github.com/swagger-api/validator-badge )

**Comment by denis-yuen** [comment]
This can be our first project using protocol buffers first? Depending on time available. 
Look at https://github.com/ckaznocha/protoc-gen-lint too

**Comment by denis-yuen** [comment]
Ping @mdmiller53 whomay be able to take a look to see if our protocol buffers translation is sane

**Comment by denis-yuen** [comment]
See https://wiki.oicr.on.ca/display/SOFTENG/Compliance+Test+Service+and+Registry+of+Registries for a writeup on the tasks needed for this project

**Comment by denis-yuen** [comment]
Some useful experience for the the swagger conversion process https://github.com/ga4gh/task-execution-schemas/pull/97

**Comment by denis-yuen** [comment]
An interesting implementation that just came up
https://github.com/brucehoff/ga4gh-to-synapse

**Comment by denis-yuen** [comment]
Awaiting review and merge
Documentation improvements
* link to build.sh
* fix relative paths
* link to page with example temporary location of ga4gh validator (will be replaced based on feedback)

**Comment by garyluu** [comment]
Pull request updated.

**Comment by denis-yuen** [comment]
Considered deployed thanks to @garyluu 
https://ga4gh.github.io/tool-registry-service-schemas/
