### ISSUE TITLE
Include information about Registrant(s)

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#86]
![image](https://cloud.githubusercontent.com/assets/1730584/11906004/9eacafcc-a597-11e5-8f99-83b769ea0fed.png)

I think we need another box here that has the registrant (or multiple people if multiple people have "published" this Docker image and we record this) for this image.

This will be helpful when the CWL lacks authorship information.  Otherwise you won't know who to contact about the particular image.

**Comment by denis-yuen** [comment]
This is one idea, when authorship information cannot be harvested from CWL, we can at least display user contact information for the user that published the tool

**Comment by denis-yuen** [comment]
Implemented for private docker registries
