### ISSUE TITLE
File format search

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#864]
### Desired behaviour

This is a large feature that covers a few different code-bases and should be broken up into smaller tickets for each item as one starts working on them

To implement this, we will need the following:
1. All verified workflows should have file formats added ala https://github.com/common-workflow-language/user_guide/pull/12 when it is published or https://dockstore.org/docs/best-practices#metadata-and-authorship in the meantime
(It may be helpful to test out rabix compatibility while we have these "open" ) 
2. The web service should explicitly pull out file formats for tools and workflows similar to how we highlight authors and present a set of input and output formats
3. The search UI should expose these formats as a new facet (presenting friendly names rather than the raw EDAM numeric identifiers)
4. :beers:

**Comment by agduncan94** [comment]
I tried following the docs at https://docs.dockstore.org/docs/publisher-tutorials/best-practices/ and adding a file format to the input of a tool. When I refresh the tool, refresh the index through swagger, and then load the search page there is no facet with file format :cry:

**Comment by denis-yuen** [comment]
@agduncan94 to my superficial recollection, no. 
Can you tell where the breakage is occurring? (i.e. does the file format make it into the DB, if so, does the value make it into the search index, etc.)

**Comment by agduncan94** [comment]
The value does make it into the database, it does not seem to make it into the search index.

**Comment by denis-yuen** [comment]
Currently testing on staging:

Works with: 
Docker Hub tool with Descriptor from github

Does not work with: 
Hosted tool 
Hosted workflow
Workflow from GitHub

**Comment by denis-yuen** [comment]
Improvements in #1674

**Comment by agduncan94** [comment]
Fixed.
