### ISSUE TITLE
Delete Tag

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#874]
### Expected behaviour
Delete Tag should work for manual mode tools

### Actual behaviour
Delete Tag is visible in automated tools.  Delete tag does not work.

**Comment by garyluu** [comment]
Update:

Delete tag works with feature/bugFixes branch.  However, due to the use of swagger codegen, it requires modifications to the webservice.  The webservice is returning status 200 with no entity.  The generated swagger client expects all non-204 responses to contain something.  Currently my webservice is modified to be `return Response.noContent().build();`  instead of `return Response.ok().build();`

Another solution is to return the current tags.

**Comment by denis-yuen** [comment]
The steps listed here make sense to me.

**Comment by denis-yuen** [comment]
Please link to PR

**Comment by denis-yuen** [comment]
In the console log, the web service responses will cause errors. 
Take a look for invalid responses and fix them

**Comment by garyluu** [comment]
Pull request that included the delete token fix is https://github.com/ga4gh/dockstore/pull/914
Pull request that included the delete tag fix is https://github.com/ga4gh/dockstore/pull/909

Still probably some others need checking/changes.

**Comment by denis-yuen** [comment]
Works on staging.dockstore.org
