### ISSUE TITLE
Git Tags with a 'v' prefix are not recognized

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#876]
### Expected behaviour
GitHub tags with a 'v' prefix should be handled correctly (source files can be viewed on Dockstore)

### Actual behaviour
GitHub tags with a 'v' prefix are completely ignored by Dockstore egit library.  Files are not displayed.

### Steps to reproduce the behaviour 
- Have a GitHub repository with a valid Dockerfile in a tag called 'v0.0.1'
- Create a manual tool with that GitHub repository
- Manually add a version using 'v0.0.1' as the Git Reference
- Refresh tool
Observe how the Dockerfile is not viewable in the files tab

**Comment by denis-yuen** [comment]
Seems a bit like https://github.com/ga4gh/dockstore/issues/776

**Comment by denis-yuen** [comment]
Tried to duplicate, could not. 
Try with your fork of the fusion repo, otherwise, close.

**Comment by garyluu** [comment]
Tried to reproduce again, could not do so.
