### ISSUE TITLE
Miscellaneous UI2 bugs

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#877]
This contains a list of small bugs in the UI2 that should eventually get fixed.  This issue tracks it.

## Bug Report
1. ~Workflow page cuts off DAG tab and parts of the table when window is shrunken (fixed but now sidebar is too small and sharing icons escape from container)~ 
1. ~Footer Icons collapse too early (when the window is slightly shrunk)~ 
1. ~mytools and myworkflows add entry based on an organization is protruding outside accordions~
1. ~Docker pull column text fields can't be clicked inside~ broken out
-this seems to be because of datatables, and other fields like author can't be selected either, but name can
-in search things are highlight able, but not in tools/workflows pages
5. ~Using Dockstore, Adding to Dockstore, About Dockstore not centered~
6. ~Invalid API calls should redirect similar to UI1~
7. ~Test parameter files in version/tag editor modal and should be editable and form validated~ broken out
8.  ~/Admin-search should be renamed.~
9. ~< delay this to after 1.3> Paramfiles component is not refactored yet.~ broken out
10.  ~Missing the following tests:~
- ~page component (no idea)~
- ~listentry (wait until settled)~
- ~login service (no idea).~
- ~dag component (cytoscape library causing issues)~
12. ~Refresh all workflows/tools is missing indicator, alert bar with spinning icon~
13. ~Private tools not indicated in search tools/workflows.~ 
14. ~IDs should be added to all tabs for better testing.~ broken out
15. ~< delay this till after 1.3> Tool and workflow component should use the tool and workflow models, currently they contain additional properties.~ broken out
16. ~Workflow tabs are completely missing from until selected.  Tool tabs are simply hidden.  Keep it consistent.~ broken out
18. ~Use fixed version for npm versions~
19. ~script modifications:~
      - ~Filename extension~
      - ~A #! header~
      - ~set -u, set -x, set -o~
    ~For more explanation http://kvz.io/blog/2013/11/21/bash-best-practices/~
20.  ~Fix src/app/container/error.service.spec.ts errorObj to be grammatically correct~
21. ~< delay this to 1.4> Move dockstore.model.ts to the environment.ts and environment.prod.ts~
22. ~Remove the swagger inject header script.  It is no longer needed, but the configuration.apiKey needs to grab the token from the auth service.~
23. ~View Version Tag for workflows shows incorrect tooltip from test parameter files.  Add file is not hidden in public.~
24. ~Remove default version selector from public page~
25. ~Adding a valid descriptor and test parameter file at the same time and then refreshing causes the test parameter file addition to fail without warning.  Apparently this happens in UI1 too (except UI1's UI seems to indicate it succeeded but the file doesn't appear in the files tab because it actually failed)~

**Comment by denis-yuen** [comment]
:+1: to tool and workflow refresh indicator

**Comment by denis-yuen** [comment]
Don't display useless dropdowns when there are no versions
![screenshot from 2017-09-26 13-59-29](https://user-images.githubusercontent.com/1730679/30875962-1d1d6e80-a2c3-11e7-9015-f9795de7463b.png)

This applies to the tabs of Files and DAG

**Comment by denis-yuen** [comment]
Restub introduces a new button convention. Note that Publish and Refresh are buttons with background. Restub is in brackets and there's a edit button in blue to the right. 
Restub should use one of the two

![screenshot from 2017-09-26 14-06-38](https://user-images.githubusercontent.com/1730679/30876249-fc46d15a-a2c3-11e7-8ab3-92e668e9610b.png)

**Comment by denis-yuen** [comment]
Adding a WDL workflow by editing "Workflow Path"from CWL to WDL hangs the GUI with the spinning icon.

**Comment by denis-yuen** [comment]
Selecting a version of a tool or workflow provides no feedback that it succeeded

**Comment by denis-yuen** [comment]
ts-node is listed as a development dependency, but is required by "prebuild" which seems to be necessary across the board at least according to the readme

**Comment by agduncan94** [comment]
The icon used on the list workflows page is not the right one, it should be green.

**Comment by denis-yuen** [comment]
search text field is cut off
![screenshot from 2017-10-02 15-45-22](https://user-images.githubusercontent.com/1730679/31096034-dbf77a02-a788-11e7-83b1-a298a5393d1e.png)

**Comment by denis-yuen** [comment]
When going to a permalink, the screen briefly flashes "Sorry, no matches for [x]" before showing the real set of results

**Comment by denis-yuen** [comment]
"+" button is cut off 

![screenshot from 2017-10-02 16-02-53](https://user-images.githubusercontent.com/1730679/31096827-4588de8c-a78b-11e7-91cb-4eb1ce14df22.png)

**Comment by denis-yuen** [comment]
When performing a search with a search term, clicking into a result and coming back seems to clear all searches but the search is still applied. 

Expected:
Should see search options still selected

**Comment by denis-yuen** [comment]
As discussed, the verified checkmark in ui2 is in an odd location. 
In tools and workflows, it is displayed beside author. In dockstore.org (1.2.10) it is displayed in from of the workflow or tool name, which makes more sense.

**Comment by agduncan94** [comment]
Since the workflow table doesn't have the docker pull column, the rows are shorter than the ones for tools. They should be a consistent size.

**Comment by agduncan94** [comment]
On home page, the tabs for browse tools and browse workflows have icons. They should switch to the purple/unselected icon when they are not selected.

**Comment by denis-yuen** [comment]
![screenshot from 2017-10-11 16-21-47](https://user-images.githubusercontent.com/1730679/31464898-60147a24-aea0-11e7-938e-24a92ae3f85d.png)

Spacing between DockstoreAPI, Dockstore UI, and the copyright notice are too big making the footer too big

**Comment by denis-yuen** [comment]
The "Add Tag" button is visible for tools hat are in "Fully Automated" mode unlike 1.2.10. 
Hide it for non-manual tools.

**Comment by denis-yuen** [comment]
1. Go to https://staging.dockstore.org/
2. Under Browse Tools go to "pcawg-bwa-mem-workflow"
3. Switch Launch With to "cwl"
4. Click on "Run locally with cwltool"
5. Click back.
6. The page will fail to load with a few webpack errors 

![screenshot from 2017-10-12 17-20-24](https://user-images.githubusercontent.com/1730679/31519849-c3e13480-af71-11e7-849a-3badb06186a5.png)

**Comment by denis-yuen** [comment]
Tool description displays for the wrong version. 

https://staging.dockstore.org/containers/quay.io%2Fdenis_yuen%2Fdockstore-tool-imports

Displays a description for https://staging.dockstore.org:8443/containers/218/cwl?tag=yaml_descriptor not  https://staging.dockstore.org:8443/containers/218/cwl?tag=master as one would expect.

**Comment by denis-yuen** [comment]
FYI, this is a reminder to all that this is closed to new issues.

**Comment by denis-yuen** [comment]
Looks clear with remaining tasks broken out or cleared tasks working on staging.dockstore.org
