### ISSUE TITLE
Default branch with Docker Hub tool does not work

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#878]
### Expected behaviour
dockstore tool cwl --entry registry.hub.docker.com/ucsctreehouse/fusion > dockstore.cwl should work

### Actual behaviour
dockstore tool cwl --entry registry.hub.docker.com/ucsctreehouse/fusion > dockstore.cwl should work
Invalid tag
io.swagger.client.ApiException: Invalid version.

### Steps to reproduce the behaviour 
Have a dockerhub tool, select a default branch, run the above command without specifying a tag
The command does not work.

**Comment by denis-yuen** [comment]
good catch

**Comment by denis-yuen** [comment]
Wasn't able to duplicate with `registry.hub.docker.com/ucsctreehouse/fusion` was able to duplicate with 
 `quay.io/ucsc_cgl/protect`. This might actually be the double-dash problem in disguise

**Comment by denis-yuen** [comment]
Actually, the webservice is not checking that valid default versions are being submitted which is the root of the problem. Reclassifying

**Comment by denis-yuen** [comment]
Investigate why the UI marks the git reference as opposed to the Docker tag
