### ISSUE TITLE
When there are more than 200 results we should indicate this to the user

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#882]
## Feature Request 
Indicate to user when there are more results than returned.

### Desired behaviour
When a user searches for something and there are over 200 results, indicate to the user that their search 
-returned over 200 results
-only is showing 200 results
-should be filtered down to return more relevant results

**Comment by denis-yuen** [comment]
Currently on 
https://staging.dockstore.org/search
The message shows by default which is ok, but should probably be special cased. i.e. The notice is probably not necessary when there no search being applied at all

**Comment by agduncan94** [comment]
I can change it so that it only shows it if a filter is set.

**Comment by denis-yuen** [comment]
Looks like this has been fixed
