### ISSUE TITLE
Update front page search

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#886]
## Feature Request 
Redo the search on the front page to use elastic search.

### Desired behaviour
Currently the search on the front page only searches the small subset of tools and workflows on the front page. Instead we should probably add a search box to the top nav bar, which will redirect to the search page.

**Comment by agduncan94** [comment]
Instead of a search box I have added a search link in the navbar, which links to the search page.

**Comment by agduncan94** [comment]
Making it so that when you search on the front page and press enter, you will be redirected to the search page with the search results for the given keyword from the front page.

**Comment by denis-yuen** [comment]
Works on internal staging
