### ISSUE TITLE
Home page tool and workflows subset could be changed to something like Top Tools/Workflows

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#887]
## Feature Request 
Better presentation on the home page for discovering popular tools.

### Desired behaviour
The list of tools and workflows on the home page should be changed to something similar to "Discover Tools/Workflows", and maybe would show highlighted entries (done by us) or entries with the highest rating.

**Comment by denis-yuen** [comment]
Working on specification for this
