### ISSUE TITLE
Should clean up the login page

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#890]
## Feature Request 
We should have a nicer login page. Currently it is just a box that says sign in and has a GitHub button.

### Desired behaviour
Here is an [example sign in](http://cbsnews3.cbsistatic.com/hub/i/r/2015/11/02/cdd999c4-151c-4b98-a90a-42c0f710a464/thumbnail/620x350/a0054f0953fdf0527ad82ca4b90385c6/etsy-sign-in-screenshot.png). We should do something similar. Perhaps even use a GitHub logo.

**Comment by denis-yuen** [comment]
On staging.dockstore.org
