### ISSUE TITLE
Confirmation on actions

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#892]
## Feature Request 
We used to have notifications on things like copying to clipboard. Perhaps we should add these again for certain actions. I am not sure if these were removed on purpose, but I do think they might help improve usability. Feedback for the user is always good.

### Desired behaviour
On actions such as copying to clipboard, publishing tool/workflow, etc there should be a notification confirming to the user that the action has been completed.

**Comment by denis-yuen** [comment]
Clipboard is affected by copy of docker pull and copy of file contents
