### ISSUE TITLE
Custom loading screen

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#893]
## Feature Request 
Currently Angular 4 by default shows the word loading... in the top left corner during loading screens. We can change this so that it is a custom loading screen, and it seems fairly straightforward to do.

Here is a simple [example](https://alligator.io/angular/custom-loading-screen/)
### Desired behaviour
Have a pretty loading screen for angular 4

**Comment by denis-yuen** [comment]
See also #463
