### ISSUE TITLE
Fixing search links to use angular routes

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#897]
Clicking on the search link will use typical href to open, which completely reloads the page. This will ensure that no search query or filter is applied, so that the user can start searching from scratch. The problem is that this is slower than the Angular approach of doing things, which uses routes to reload only part of the page (no loading page). This would make the app feel like a single page application, which is nice.

To change the links to the search page to angular routes, we would have to ensure that the search forms to be in the same state as if you reloaded the page from scratch (no filters or terms applied).

**Comment by agduncan94** [comment]
"When performing a search with a search term, clicking into a result and coming back seems to clear all searches but the search is still applied.

Expected:
Should see search options still selected"
-Denis

**Comment by denis-yuen** [comment]
This is working on dockstore.org
