### ISSUE TITLE
Wrong client error message

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#905]
### Expected behaviour
./dockstore tool launch biowardrobe_chipseq_se_checker.cwl
dockstore needs to be on PATH for certain commands to work (like --upgrade)
dockstore: missing required flag --entry or --local-entry

### Actual behaviour
./dockstore tool launch biowardrobe_chipseq_se_checker.cwl
dockstore needs to be on PATH for certain commands to work (like --upgrade)
dockstore: missing required flag --entry

### Steps to reproduce the behaviour 
./dockstore tool launch biowardrobe_chipseq_se_checker.cwl

**Comment by denis-yuen** [comment]
Still present
```
$ dockstore tool launch Dockstore.cwl
dockstore: missing required flag --entry
$ dockstore --version
Dockstore version 1.3.0-beta.0
The latest stable version is 1.2.10
You are currently on the latest unstable version. If you wish to upgrade to the latest stable version, please use the following command:
   dockstore --upgrade-stable
```

**Comment by denis-yuen** [comment]
Works with 1.3.0-beta.1
