### ISSUE TITLE
Ensure special characters don't break the search

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#916]
### Expected behaviour
Searching for special characters shouldn't break the search in any way.
### Actual behaviour
Not sure, needs to be tested to see what problems we have.

**Comment by agduncan94** [comment]
I tried some special characters from [here](https://en.wikipedia.org/wiki/List_of_Unicode_characters) and they don't seem to break anything. There will be an alert that the supplied text did not match anything.

When you look at the shareable link, it will have the escaped versions of the characters, and won't return any results since they don't match anything.

**Comment by denis-yuen** [comment]
Looks good
