### ISSUE TITLE
Use URL shortener for permalinks

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#924]
Update permalink to use URL shorteners.
#839

**Comment by agduncan94** [comment]
For this are we thinking of using something like [bitly](https://bitly.com/) or would this just be a matter of compressing the query parameters when we display the permalink and uncompressing them when a user goes to a permalink?

**Comment by denis-yuen** [comment]
I think the former would make more sense

**Comment by denis-yuen** [comment]
I think I'll delay this to 1.4 if you haven't started actually

**Comment by denis-yuen** [comment]
Functional after adding to compose_setup
