### ISSUE TITLE
Dockstore-UI2 and webservice login desync

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#928]
### Expected behavior
The "logged in" state should consist of two things (at least the 2nd one):
1. The browser must have the dockstore token
2. The dockstore token must be valid (User object retrieved from dockstore webservice)
### Actual behaviour
The "logged in" state purely consists of the browser dockstore token regardless of whether or not the token is valid.  In effect, even when the user is not properly logged in, my-tools and my-workflow page is visible and can be clicked.  The navbar looks like the user is logged in but is missing things like the username.

### Steps to reproduce the behaviour 
Use your browser of choice' developer tools to add an invalid ng2-ui-auth_token into the local storage.  The site now believes the user is logged in.

### Environment (Browser or OS and Dockstore version)
UI2

**Comment by denis-yuen** [comment]
Somewhat inside baseball if it needs developer tools to re-create
