### ISSUE TITLE
Add a nice link from ui1 to ui2

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#933]
### Desired behaviour

Add a nice looking link from ui1 to ui2 that can be toggled on and off in the config. 
Turn it on and test it using the docker-compose setup setup.

**Comment by garyluu** [comment]
Dockstore UI2 to UI1 apparently

**Comment by denis-yuen** [comment]
Looks like a faulty merge conflict?

**Comment by denis-yuen** [comment]
Present
