### ISSUE TITLE
Long user names cause layout/alignment issues in UI

### ISSUE THREAD

**Issue by SolomonShorser-OICR** [ga4gh/dockstore#94]
Long user names cause a weird problem where the username is on one side of the screen, but when you click on it, the drop-down for the user appears on the *other* side of the screen.

![dockstore_ui_issue_with_long_user_names](https://cloud.githubusercontent.com/assets/10213802/12096961/e7893e20-b2e6-11e5-8e24-03f1fa8cdbb0.png)

**Comment by agduncan94** [comment]
If a user name is > 10 characters long, a substring of it will be displayed with an ellipsis.
