### ISSUE TITLE
Tool description displays for the wrong version.

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#950]
## Bug Report

Go to
https://staging.dockstore.org/containers/quay.io%2Fdenis_yuen%2Fdockstore-tool-imports

Displays a description for https://staging.dockstore.org:8443/containers/218/cwl?tag=yaml_descriptor not https://staging.dockstore.org:8443/containers/218/cwl?tag=master as one would expect.

Broken out from #877

**Comment by agduncan94** [comment]
Just to clarify, the webservice should be grabbing tool info from master if no default is specified?

**Comment by agduncan94** [comment]
Can't duplicate.
