### ISSUE TITLE
Change Tooltester and dockstoresaver to use aws tool

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#955]
Cancercollaboratory currently does not support s3cmd.  We should switch to aws cli

### Desired behaviour
Change dockstoresaver and tooltester to use AWS CLI

**Comment by denis-yuen** [comment]
To be specific, dockstoresaver should use the Java SDK https://aws.amazon.com/sdk-for-java/. 
Tooltester can use the CLI.

**Comment by garyluu** [comment]
Looks like the dockstoresaver uses the AmazonS3Client java library.  Curious why it failed.

**Comment by garyluu** [comment]
Also, tooltester now uses the AWS CLI
