### ISSUE TITLE
Add loading messages or pagination to Tools, Workflows, and Search

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#958]
## Bug Report

Encountered by @briandoconnor  in Orlando, on a very slow connection, it looks like search might not load properly and times out. 

![pasted_image_at_2017_10_16_04_00_pm](https://user-images.githubusercontent.com/1730679/31633398-4123bf84-b28e-11e7-8873-78af28121059.png)

Simulate a slow connection or try a variety of mobile devices on different connections.

**Comment by briandoconnor** [comment]
![image](https://user-images.githubusercontent.com/1730584/31634475-b9c92106-b291-11e7-82a5-61c90eeef888.png)

Notice the length of time the page takes to load and the size (in MB) of data the page pulls.  On a degraded/slow connection this is very noticeable.  Seems strange the returns would be MB in size!?

**Comment by denis-yuen** [comment]
@agduncan94 @garyluu 
Part of it actually makes sense, we haven't implemented pagination properly yet. 
The stranger issue is that it's making that call four times. 

We can lower the default limit of tools+workflows from 200 to 50, which will help a bit. Thanks for the heads-up.

**Comment by garyluu** [comment]
My local one has 3 small 2 large requests.  Staging looks like it has 4 large, 2 small requests.

**Comment by denis-yuen** [comment]
From discussion:
https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-source-filtering.html should cut down on what's being returned enough actually without changing limits

**Comment by agduncan94** [comment]
We could implement [pagination with elastic search](https://www.elastic.co/guide/en/elasticsearch/reference/current/search-request-from-size.html) as it pretty straightforward. Datatables pagination is a bit weird anyways. This also will help with permalinks referencing a specific page in the search.

**Comment by denis-yuen** [comment]
Ideas: search looks more usable on a mobile connection at least at home and downloads about as much as the main landing page. 

Take a look and see what else breaks if you browse to dockstore with a weak connection. Either simulate a slow connection using Linux utilities or just use the laptop in the elevator lobby or the OICR bridge as examples.

**Comment by denis-yuen** [comment]
Can use https://developers.google.com/web/tools/chrome-devtools/network-performance/reference#throttling to simulate slow speeds.

Looks like Dockstore needs at least "Fast 3G" to be sane
