### ISSUE TITLE
Manual spot checks

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#961]
1. Tutorials in the getting started 
2. Adding tools and workflows manually, modifying their versions
3. Refresh in a few scenarios
4. Labelling (add, remove labels)
5. CLI file provisioning with plugins (try S3 and synapse, icgc storage)
6. DNA Stack launch with

**Comment by denis-yuen** [comment]
Recheck DNA stack on production

**Comment by garyluu** [comment]
DNA stack looks fine for production
