### ISSUE TITLE
Paramfiles component refactor

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#963]
### Desired behaviour
Currently there are 3 paramfiles.component.ts:
- src/app/container/paramfiles/paramfiles.component.ts
- src/app/paramfiles/paramfiles.component.ts
- src/app/workflow/paramfiles/paramfiles.component.ts

Several oddities:
- The middle file is imported into the paramfile modules and the module is imported into container and workflow components but aren't actually used
- ParamfilesComponent 1 and 3 extends FileSelector which extends DescriptorSelector which extends VersionSelector.  This should be made simpler.  One component, 3 descriptors, no reactTo functions and OnChange functions.

**Comment by denis-yuen** [comment]
See also #1036
