### ISSUE TITLE
Use Models and types to improve code quality

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#965]
### Desired behaviour
- All functions should have a return type

**Comment by denis-yuen** [comment]
After the first two are complete, are there jslint config or something that can be used to enforce these?

**Comment by garyluu** [comment]
Enforce the first one using:
```
"typedef": [
  true,
  "call-signature",
  "property-declaration"
]
```

Currently 461 lint errors with it...fun

**Comment by denis-yuen** [comment]
Linking to be done during #1731
