### ISSUE TITLE
DAG repeating itself

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#967]
## Bug Report
Navigating to the DAG tab, leaving to another tab, then going back to the DAG tab will make the dag info duplication
### Expected behaviour
There should only be one instance of the DAG info
### Actual behaviour
There are multiple instances of the DAG info
### Steps to reproduce the behaviour 
1. Go to https://staging.dockstore.org/workflows/NCI-GDC/gdc-dnaseq-cwl/GDC_DNASeq
1. Go to DAG tab
1. Click on another tab
1. Go back to DAG tab

**Comment by agduncan94** [comment]
This seems to be only for those workflows without dags

**Comment by denis-yuen** [comment]
This may be a general pattern, noticed description or other elements glitching and repeating once one error occurs.

**Comment by garyluu** [comment]
Looks fixed.

**Comment by garyluu** [comment]
May have been part of https://github.com/dockstore/dockstore-ui2/pull/107 where all tabs were similarly broken.

**Comment by denis-yuen** [comment]
Looks fixed on staging.dockstore.org
