### ISSUE TITLE
Utilize environment.ts and environment.prod.ts

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#968]
### Desired behaviour
Currently we use the dockstore.model.ts.  It requires modifications and is not .gitignore'd .   Angular provides environments for this use case, we should take advantage of it.  See https://github.com/dockstore/dockstore-ui2/commits/feature/issue-933 for an example.

**Comment by denis-yuen** [comment]
Note to implementor, make corresponding changes to https://github.com/dockstore/compose_setup

**Comment by denis-yuen** [comment]
Introduced with https://github.com/dockstore/dockstore-ui2/pull/261
