### ISSUE TITLE
Wipe out console errors in ui2 during regular browsing

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#971]
### Expected behaviour
There should be no console errors on mytools page

### Actual behaviour
There is ExpressionChangedAfterItHasBeenCheckedError in  MyToolsComponent.html:53
### Steps to reproduce the behaviour 
Go to mytools page, have tools

**Comment by denis-yuen** [comment]
A bit specific with the line number and all.

**Comment by denis-yuen** [comment]
This seems better now
