### ISSUE TITLE
Refresh all tools/workflows not returning all tools/workflows

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#977]
### Expected behaviour
Refresh all tools/workflows endpoint should return all current tools/workflows

### Actual behaviour
It only returns what it refreshed.

### Steps to reproduce the behaviour 
Have bunch of tools, remove your tokens, refresh all.
Now it shows you have no tools but you actually do have it in the database.

**Comment by denis-yuen** [comment]
It should also say that you have no tokens and what to do about it (link your accounts).

**Comment by garyluu** [comment]
Seperate issue in my opinion

**Comment by agduncan94** [comment]
@garyluu This seems like it can be closed.

**Comment by denis-yuen** [comment]
I think I've still seen this behavior actually. 
Not sure if that's the reason, but starting from a clean Dockstore, I refresh all tools and nothing happens on success unless I browse away and come back or reload

**Comment by agduncan94** [comment]
@denis-yuen Though those seem like they might be related, I think they are different issues. The issue here was that refreshing an org for example only returned the tools/workflows that were refreshed. I do see the case you mentioned happening locally, though I wonder if that is a UI issue and not a webservice issue. In which case I think it makes sense to make a new issue for that.

**Comment by garyluu** [comment]
![selection_021](https://user-images.githubusercontent.com/24548904/38701337-8eb39e36-3e6b-11e8-9d72-ca58f30aa92c.png)

**Comment by agduncan94** [comment]
The issue seems to be that the tools are not associated with the user until after the refresh, so when we return all of a users tools it returns the ones before the refresh I think. I think it is some state issue.

**Comment by garyluu** [comment]
Still not working for me
![image](https://user-images.githubusercontent.com/24548904/41253831-8e52d922-6d8f-11e8-9c61-dfa2d3410143.png)

**Comment by agduncan94** [comment]
Wouldn't the fix be in develop and not the hotfix?

**Comment by denis-yuen** [comment]
It looks like it. I think the move on Apr 23 was incorrect.

**Comment by garyluu** [comment]
Moving it to the other column then

**Comment by garyluu** [comment]
Appears to work with develop once #1541 is bypassed
