### ISSUE TITLE
Rework documentation to release separately from UI

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#980]
### Desired behaviour

Right now, changing release notes and other blog content requires updating the UI. 
Change it so that this content is seamlessly provided via GitHub Pages, Wordpress, etc. so that this content can be updated with re-releasing the UI.

**Comment by denis-yuen** [comment]
Let's create a few demos with the above systems.

**Comment by agduncan94** [comment]
Is this for all documentation? Or just release notes/blog posts?

**Comment by denis-yuen** [comment]
Ideally, this would be for anything under the table of contents for https://dockstore.org/docs
The FAQ, the news, and tutorials would be the most likely to change, but ideally everything in there would do into this system. Only the quick start / wizard portions of the tutorial with generated version numbers would have to start in UI2 although ideally, the chosen solution would support variables as well. 

Some things to consider actually  (along with the usuals like cost and ease of use)
1) Source controlled documentation (allows us to track changes)
2) Table of contents (quickly skip between documentation sections)
3) Header links (allows for links to subsections of docs)
4) Variables (allows us to quickly change things that change often like version numbers) 
5) Branched docs (allow a staging environment to point at an alternate version of docs)

Feel free to bat around any other considerations

**Comment by agduncan94** [comment]
This has been completed, the only things left to do are
* to deal with existing links to the site by redirecting to a page that says "docs have moved to ..."
* to change the current link to the docs on dockstore to the new docs.dockstore.org page

**Comment by denis-yuen** [comment]
Works on staging.dockstore.org
