### ISSUE TITLE
Individual refresh of entry does not properly populate the path column, across the board refresh does

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#99]
This is in the case of manually added containers. 

Procedure to replicate:

1.  dockstore manual_publish  --registry quay.io --namespace pypi --name arbitrary3 --git-url git@github.com:funky-user/test2.git --git-reference refs/head/master`
2. Check DB record (path is empty)
3. Call /containers/{containerId}/refresh
4. Check DB record (should remain the same in terms of path)
5. Call `dockstore refresh`
6. Check DB record (should be populated now)

**Comment by agduncan94** [comment]
I have made a fix for this in the branch [implement_individual_refresh_for_IT](https://github.com/ga4gh/dockstore/compare/feature/implement_individual_refresh_for_IT) by calling a manual refresh when a manually added container is added via the command line.  This occurs in the manualPublish function found [here](https://github.com/ga4gh/dockstore/blob/2fb871485bf45e9da89afb3526d2cf14ddc2b0d6/dockstore-client/src/main/java/io/dockstore/client/cli/Client.java)

**Comment by agduncan94** [comment]
I realized that the fix I made will only ensure that manually added containers from the command line have their path set, not any added in the UI.  To fix this I set the path in the registerManual API call.
