### ISSUE TITLE
Need improved docs in Dockstore Primer

### ISSUE THREAD

**Issue by denis-yuen** [ga4gh/dockstore#990]
### Desired behaviour

This can extend the wiki for now, but probably needs to be moved out later. 
```
Notes for new docs:
1. Add notes on flag to open a browser to the correct URL
2. Fix comments on bitbucket
3. Run through everything again to make sure this is consistent
4. Add a link to the run locally.
5. Add screenshots for the Running Locally section
6. Running locally should be copied and made consistent with UI2 out of the box. Make sure ports are correct
7. Let's get instructions for production/staging over https with the correct ports.
8. To save some copy-paste, you can create a good table that shows the differences in the authorization callback URLs between ui1, ui2 locally, and ui2 in staging/production
```

**Comment by denis-yuen** [comment]
![screenshot from 2017-10-24 17-51-07](https://user-images.githubusercontent.com/1730679/31970211-3e7dcab0-b8e5-11e7-8950-7bd9c55e8c2e.png)
![screenshot from 2017-10-24 17-51-02](https://user-images.githubusercontent.com/1730679/31970213-3e8fca6c-b8e5-11e7-9f24-3d20d957cd1d.png)
![screenshot from 2017-10-24 17-51-20](https://user-images.githubusercontent.com/1730679/31970214-3e9c2d34-b8e5-11e7-9360-17f339711f68.png)
![screenshot from 2017-10-24 17-51-24](https://user-images.githubusercontent.com/1730679/31970215-3ea742d2-b8e5-11e7-98a8-b4fa49bd85b7.png)

FYI, some screenshots to get you on your way. Document how to get to these pages though

**Comment by denis-yuen** [comment]
FYI, a few things I noticed while doing a review to link to this from the compose setup. 
1. The flow is a bit odd with the third party integrations being the first thing we mention about the webservice. I think there needs to be a bit of explanation of what the web service is and what integrations are necessary to accomplish what. 
2. The screenshots for the integrations are much after the description of where to use them in the various settings files
3. A few broken links
4. In general, the primer seems ok as a reference if you know exactly what you're looking for. It doesn't do a good job of explaining what things are, why you need to know about them, and how each section relates to the one before it.

**Comment by garyluu** [comment]
1. Starting from "Building and Running Dockstore-UI2",  The first thing that's mentioned is to go to the github README to see what to do to set things up.  Third party integrations is one of the last things mentioned.

2. Made a reference to them from the running locally section.  It should've been easily spotted if following from the UI2 section.

3. Fixed the link directing to UI2 readme.

**Comment by garyluu** [comment]
Reordered the primer a bit.

**Comment by denis-yuen** [comment]
The diff from before and after the changes looks like https://wiki.oicr.on.ca/pages/diffpagesbyversion.action?pageId=66945738&selectedPageVersions=139&selectedPageVersions=100

**Comment by denis-yuen** [comment]
Looks sufficiently better for the purposes of this, but I think the testing section needs an update after I finish with IDE settings and some production settings. Following this up
