### ISSUE TITLE
Files tab should select the appropriate select option

### ISSUE THREAD

**Issue by agduncan94** [ga4gh/dockstore#992]
The select tab does not always properly select a specific version. We should ensure that the first non-empty version (or valid default version) is set.

**Comment by denis-yuen** [comment]
Other related issues:
* odd extended dropdown size
* ensure default selction is working 
* #249

**Comment by agduncan94** [comment]
See dockstore/dockstore-ui2#152

**Comment by denis-yuen** [comment]
Made superfluous by new versioned design
