### ISSUE TITLE
downloadcliclient.component.html markdown

### ISSUE THREAD

**Issue by garyluu** [ga4gh/dockstore#994]
### Desired behaviour
downloadcliclient.component.html contains alot of html tags when it can be greatly simplified if it uses as much markdown as possible.  Simply put `<markdown></markdown>`  Going forward, it should be easier to update and read.

**Comment by denis-yuen** [comment]
It's a good idea although last I tried, the problem is that weird things happened when I tried to use variables inside the markdown.

**Comment by garyluu** [comment]
Should be possible, even if it isn't, there's always the option of converting the parts of the variables that don't use markdown.  feature/issue-994 for sample
