### ISSUE TITLE
Remove repos when Quay.io source is deleted

### ISSUE THREAD

**Issue by briandoconnor** [ga4gh/dockstore#999]
## Feature Request 

Cleanup of deleted repos

### Desired behaviour

When a quay.org repo is deleted the corresponding registration on Dockstore should be removed upon refresh (or refresh of all tools)

This will be really helpful when creating a bunch of quay.io repos for testing or training purposes.  Most folks will want to clean them up after finishing the tutorial and will delete the corresponding Quay.io and Github repos.  Yet these stick around currently in Dockstore (not published but visible in the My Tools/My Workflows section).

**Comment by denis-yuen** [comment]
The implementation should distinguish between a quay.io repo having been deleted and the service simply being unavailable or the user being rate limited. 

Alternatively, we can just not restrict the delete function to manual tools. It might be useful for users to delete their tools and workflows to reset them if they somehow get in a bad state anyways.

**Comment by denis-yuen** [comment]
This seems to now exist as part of https://github.com/ga4gh/dockstore/issues/1779
